{"sections":[],"deprecationSummary":[{"inlineContent":[{"text":"Use stripeID (defined in STPSourceProtocol)","type":"text"}],"type":"paragraph"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cardId","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpcard\/cardid"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcard\/cardid"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/cardId"},"metadata":{"platforms":[],"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"cardId","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","title":"cardId","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cardId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPCard(py)cardId"},"abstract":[{"type":"text","text":"The Stripe ID for the card."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard","url":"\/documentation\/stripepayments\/stpcard","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCard"}],"title":"STPCard","type":"topic","abstract":[{"text":"Representation of a user’s credit card details that have been tokenized with","type":"text"},{"text":" ","type":"text"},{"text":"the Stripe API","type":"text"}],"navigatorTitle":[{"text":"STPCard","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/cardId":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/cardId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"deprecated":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cardId"}],"type":"topic","abstract":[{"type":"text","text":"The Stripe ID for the card."}],"url":"\/documentation\/stripepayments\/stpcard\/cardid","title":"cardId"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":[],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"cardId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"cardId","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"cardId","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/title","op":"replace","value":"STPCard"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/fragments","value":[{"kind":"identifier","text":"STPCard"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPCard"}]},{"value":"cardId","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1cardId\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1cardId\/fragments","op":"replace","value":[{"text":"cardId","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}