{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/funding(from:)"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcard\/funding(from:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcard\/funding(from:)"]}],"kind":"symbol","abstract":[{"type":"text","text":"This parses a string representing a card’s funding type into the appropriate"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPCardFundingType"},{"type":"text","text":" enum value,"},{"type":"text","text":" "},{"type":"text","text":"i.e. "},{"type":"codeVoice","code":"STPCard.funding(from string:\"prepaid\") == .prepaid"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(fundingFromString:) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"funding"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"string"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"STPCardFundingType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType","preciseIdentifier":"c:@M@StripePayments@E@STPCardFundingType"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"string","content":[{"type":"paragraph","inlineContent":[{"text":"A string representing the card’s funding type as returned from","type":"text"},{"text":" ","type":"text"},{"text":"the Stripe API","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"An enum value mapped to that string. If the string is unrecognized,"},{"type":"text","text":" "},{"type":"text","text":"returns "},{"code":"STPCardFundingTypeOther","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]}],"metadata":{"symbolKind":"method","role":"symbol","title":"funding(from:)","roleHeading":"Type Method","externalID":"c:@M@StripePayments@objc(cs)STPCard(cm)fundingFromString:","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"funding"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"STPCardFundingType","preciseIdentifier":"c:@M@StripePayments@E@STPCardFundingType"}],"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fundingFromString:"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType","kind":"symbol","abstract":[{"text":"The various funding sources for a payment card.","type":"text"}],"title":"STPCardFundingType","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpcardfundingtype","navigatorTitle":[{"kind":"identifier","text":"STPCardFundingType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFundingType"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard","title":"STPCard","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCard","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"STPCard","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpcard","abstract":[{"text":"Representation of a user’s credit card details that have been tokenized with","type":"text"},{"text":" ","type":"text"},{"text":"the Stripe API","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/funding(from:)":{"url":"\/documentation\/stripepayments\/stpcard\/funding(from:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/funding(from:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"funding"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardFundingType","kind":"typeIdentifier","text":"STPCardFundingType"}],"abstract":[{"type":"text","text":"This parses a string representing a card’s funding type into the appropriate"},{"type":"text","text":" "},{"code":"STPCardFundingType","type":"codeVoice"},{"type":"text","text":" enum value,"},{"type":"text","text":" "},{"type":"text","text":"i.e. "},{"code":"STPCard.funding(from string:\"prepaid\") == .prepaid","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","title":"funding(from:)","kind":"symbol","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fundingFromString:"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"fundingFromString:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fundingFromString:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardFundingType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType","preciseIdentifier":"c:@M@StripePayments@E@STPCardFundingType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"fundingFromString:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"string","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A string representing the card’s funding type as returned from"},{"type":"text","text":" "},{"type":"text","text":"the Stripe API"}],"type":"paragraph"}],"name":"string"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"An enum value mapped to that string. If the string is unrecognized,","type":"text"},{"text":" ","type":"text"},{"text":"returns ","type":"text"},{"code":"STPCardFundingTypeOther","type":"codeVoice"},{"text":".","type":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"STPCardFundingType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/title"},{"value":[{"kind":"identifier","text":"STPCardFundingType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/fragments"},{"value":[{"kind":"identifier","text":"STPCardFundingType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/navigatorTitle"},{"value":"STPCard","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/title"},{"value":[{"kind":"identifier","text":"STPCard"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/fragments"},{"value":[{"kind":"identifier","text":"STPCard"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/navigatorTitle"},{"value":"fundingFromString:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1funding(from:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fundingFromString:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1funding(from:)\/fragments"}]}]}