{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/init(id:brand:last4:expMonth:expYear:funding:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcard\/init(id:brand:last4:expmonth:expyear:funding:)"]},{"paths":["\/documentation\/stripepayments\/stpcard\/init(id:brand:last4:expmonth:expyear:funding:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Create an STPCard from a Stripe API response."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithID:brand:last4:expMonth:expYear:funding:) ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"cardID","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"brand","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCardBrand","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"kind":"text","text":", "},{"kind":"externalParam","text":"last4"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"expMonth","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"expYear","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"funding"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardFundingType","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType","text":"STPCardFundingType"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"cardID","content":[{"inlineContent":[{"text":"The Stripe ID of the card, e.g. ","type":"text"},{"code":"card_185iQx4JYtv6MPZKfcuXwkOx","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The brand of the card (e.g. “Visa”. To obtain this enum value"},{"type":"text","text":" "},{"type":"text","text":"from a string, use "},{"code":"STPCardBrand.brand(from string:string)","type":"codeVoice"},{"type":"text","text":";"}],"type":"paragraph"}],"name":"brand"},{"name":"last4","content":[{"inlineContent":[{"text":"The last 4 digits of the card, e.g. 4242","type":"text"}],"type":"paragraph"}]},{"name":"expMonth","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The card’s expiration month, 1-indexed (i.e. 1 = January)"}]}]},{"content":[{"inlineContent":[{"text":"The card’s expiration year","type":"text"}],"type":"paragraph"}],"name":"expYear"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The card’s funding type (credit, debit, or prepaid). To obtain","type":"text"},{"text":" ","type":"text"},{"text":"this enum value from a string, use ","type":"text"},{"type":"codeVoice","code":"STPCardBrand.funding(from string:)"},{"text":".","type":"text"}]}],"name":"funding"}]}],"deprecationSummary":[{"inlineContent":[{"text":"You cannot directly instantiate an STPCard. You should only use one that has been returned from an STPAPIClient callback.","type":"text"}],"type":"paragraph"}],"metadata":{"title":"init(id:brand:last4:expMonth:expYear:funding:)","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithID:brand:last4:expMonth:expYear:funding:","kind":"identifier"}],"symbolKind":"init","externalID":"c:@M@StripePayments@objc(cs)STPCard(im)initWithID:brand:last4:expMonth:expYear:funding:","platforms":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"brand"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","kind":"typeIdentifier","text":"STPCardBrand"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"last4"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"expMonth","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"expYear","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"funding","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCardFundingType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardFundingType"},{"text":")","kind":"text"}],"modules":[{"name":"StripePayments"}],"role":"symbol"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCardBrand"}],"abstract":[{"text":"The various card brands to which a payment card can belong.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","navigatorTitle":[{"kind":"identifier","text":"STPCardBrand"}],"title":"STPCardBrand","url":"\/documentation\/stripepayments\/stpcardbrand","role":"symbol","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard":{"url":"\/documentation\/stripepayments\/stpcard","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCard","kind":"identifier"}],"title":"STPCard","navigatorTitle":[{"kind":"identifier","text":"STPCard"}],"abstract":[{"text":"Representation of a user’s credit card details that have been tokenized with","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the Stripe API"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType":{"title":"STPCardFundingType","abstract":[{"type":"text","text":"The various funding sources for a payment card."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType","type":"topic","url":"\/documentation\/stripepayments\/stpcardfundingtype","navigatorTitle":[{"text":"STPCardFundingType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFundingType"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/init(id:brand:last4:expMonth:expYear:funding:)":{"title":"init(id:brand:last4:expMonth:expYear:funding:)","abstract":[{"type":"text","text":"Create an STPCard from a Stripe API response."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/init(id:brand:last4:expMonth:expYear:funding:)","type":"topic","url":"\/documentation\/stripepayments\/stpcard\/init(id:brand:last4:expmonth:expyear:funding:)","navigatorTitle":[{"text":"initWithID:brand:last4:expMonth:expYear:funding:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"brand"},{"text":": ","kind":"text"},{"text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"last4"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"expMonth","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"expYear"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"funding"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardFundingType","kind":"typeIdentifier","text":"STPCardFundingType"},{"text":")","kind":"text"}],"deprecated":true}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"replace","value":[]},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithID:brand:last4:expMonth:expYear:funding:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithID:brand:last4:expMonth:expYear:funding:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithID:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cardID"},{"text":" ","kind":"text"},{"text":"brand:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand"},{"kind":"text","text":") "},{"text":"brand","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"last4:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"last4"},{"kind":"text","text":" "},{"kind":"identifier","text":"expMonth:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"expMonth"},{"text":" ","kind":"text"},{"kind":"identifier","text":"expYear:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"expYear","kind":"internalParam"},{"kind":"text","text":" "},{"text":"funding:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardFundingType","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType","preciseIdentifier":"c:@M@StripePayments@E@STPCardFundingType"},{"text":") ","kind":"text"},{"text":"funding","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"cardID","content":[{"type":"paragraph","inlineContent":[{"text":"The Stripe ID of the card, e.g. ","type":"text"},{"code":"card_185iQx4JYtv6MPZKfcuXwkOx","type":"codeVoice"}]}]},{"content":[{"inlineContent":[{"text":"The brand of the card (e.g. “Visa”. To obtain this enum value","type":"text"},{"type":"text","text":" "},{"text":"from a string, use ","type":"text"},{"code":"STPCardBrand.brand(from string:string)","type":"codeVoice"},{"text":";","type":"text"}],"type":"paragraph"}],"name":"brand"},{"content":[{"inlineContent":[{"type":"text","text":"The last 4 digits of the card, e.g. 4242"}],"type":"paragraph"}],"name":"last4"},{"name":"expMonth","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The card’s expiration month, 1-indexed (i.e. 1 = January)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The card’s expiration year"}]}],"name":"expYear"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The card’s funding type (credit, debit, or prepaid). To obtain"},{"text":" ","type":"text"},{"text":"this enum value from a string, use ","type":"text"},{"type":"codeVoice","code":"STPCardBrand.funding(from string:)"},{"type":"text","text":"."}]}],"name":"funding"}],"kind":"parameters"},"op":"replace"},{"value":{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"text":"An STPCard instance populated with the provided values.","type":"text"}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"add"},{"value":"STPCardBrand","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/fragments","value":[{"kind":"identifier","text":"STPCardBrand"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/navigatorTitle","value":[{"text":"STPCardBrand","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/title","value":"STPCard"},{"op":"replace","value":[{"text":"STPCard","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/fragments"},{"value":[{"kind":"identifier","text":"STPCard"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/title","op":"replace","value":"STPCardFundingType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/fragments","value":[{"kind":"identifier","text":"STPCardFundingType"}]},{"value":[{"kind":"identifier","text":"STPCardFundingType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1init(id:brand:last4:expMonth:expYear:funding:)\/title","value":"initWithID:brand:last4:expMonth:expYear:funding:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1init(id:brand:last4:expMonth:expYear:funding:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithID:brand:last4:expMonth:expYear:funding:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}