{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/string(from:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"stringFromBrand:"}],"roleHeading":"Type Method","title":"string(from:)","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPCard(cm)stringFromBrand:","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"string"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","kind":"typeIdentifier","text":"STPCardBrand"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(stringFromBrand:) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"string","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"brand","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The brand you want to convert to a string","type":"text"}],"type":"paragraph"}],"name":"brand"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"A string representing the brand, suitable for displaying to a user.","type":"text"}]}]}],"abstract":[{"text":"Returns a string representation for the provided card brand;","type":"text"},{"text":" ","type":"text"},{"text":"i.e. ","type":"text"},{"code":"STPCard.string(from brand: .visa) == \"Visa\"","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpcard\/string(from:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcard\/string(from:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","type":"topic","url":"\/documentation\/stripepayments\/stpcardbrand","abstract":[{"type":"text","text":"The various card brands to which a payment card can belong."}],"navigatorTitle":[{"text":"STPCardBrand","kind":"identifier"}],"kind":"symbol","title":"STPCardBrand","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardBrand","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/string(from:)":{"navigatorTitle":[{"kind":"identifier","text":"stringFromBrand:"}],"kind":"symbol","title":"string(from:)","abstract":[{"text":"Returns a string representation for the provided card brand;","type":"text"},{"text":" ","type":"text"},{"text":"i.e. ","type":"text"},{"code":"STPCard.string(from brand: .visa) == \"Visa\"","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/string(from:)","type":"topic","url":"\/documentation\/stripepayments\/stpcard\/string(from:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"string"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","kind":"typeIdentifier","text":"STPCardBrand"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard":{"type":"topic","url":"\/documentation\/stripepayments\/stpcard","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCard","kind":"identifier"}],"title":"STPCard","abstract":[{"text":"Representation of a user’s credit card details that have been tokenized with","type":"text"},{"text":" ","type":"text"},{"text":"the Stripe API","type":"text"}],"navigatorTitle":[{"text":"STPCard","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"stringFromBrand:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringFromBrand:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"stringFromBrand:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand"},{"text":") ","kind":"text"},{"text":"brand","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"brand","content":[{"type":"paragraph","inlineContent":[{"text":"The brand you want to convert to a string","type":"text"}]}]}]}},{"value":{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"A string representing the brand, suitable for displaying to a user.","type":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"STPCardBrand","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/title"},{"value":[{"text":"STPCardBrand","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/fragments"},{"value":[{"text":"STPCardBrand","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/navigatorTitle"},{"value":"stringFromBrand:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1string(from:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringFromBrand:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1string(from:)\/fragments"},{"value":"STPCard","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/title"},{"value":[{"text":"STPCard","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/fragments"},{"value":[{"kind":"identifier","text":"STPCard"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/navigatorTitle"}]}]}