{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copy","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"zone"},{"text":": ","kind":"text"},{"text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV","kind":"typeIdentifier"},{"text":"? = nil) -> ","kind":"text"},{"kind":"keyword","text":"Any"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/copy(with:)"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/NSCopying-Implementations"]]},"metadata":{"title":"copy(with:)","externalID":"c:@CM@StripePayments@objc(cs)STPAddress(im)copyWithZone:","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"copy"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"extendedModule":"StripePayments","modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/stripepayments\/stpaddress\/copy(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpaddress\/copy(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":":nodoc:","type":"text"}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","kind":"symbol","title":"STPAddress","url":"\/documentation\/stripepayments\/stpaddress","abstract":[{"text":"STPAddress Contains an address as represented by the Stripe API.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPAddress","kind":"identifier"}],"navigatorTitle":[{"text":"STPAddress","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/copy(with:)":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/copy(with:)","type":"topic","url":"\/documentation\/stripepayments\/stpaddress\/copy(with:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"copy","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSZone","kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"}],"abstract":[{"text":":nodoc:","type":"text"}],"title":"copy(with:)","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/NSCopying-Implementations":{"title":"NSCopying Implementations","role":"collectionGroup","url":"\/documentation\/stripepayments\/stpaddress\/nscopying-implementations","kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/NSCopying-Implementations"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"copyWithZone:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"copyWithZone:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@_NSZone","text":"_NSZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"zone"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPAddress","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPAddress"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/navigatorTitle","value":[{"text":"STPAddress","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1copy(with:)\/title","value":"copyWithZone:"},{"value":[{"kind":"text","text":"- "},{"text":"copyWithZone:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1copy(with:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}