{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/init(paymentMethodBillingDetails:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentMethodBillingDetails"},{"kind":"text","text":" "},{"kind":"internalParam","text":"billingDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The STPPaymentMethodBillingDetails instance you want to populate the STPAddress from."}]}],"name":"billingDetails"}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"A new STPAddress instance with data copied from the passed in billing details."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentMethodBillingDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails"},{"kind":"text","text":")"}],"title":"init(paymentMethodBillingDetails:)","externalID":"c:@M@StripePayments@objc(cs)STPAddress(im)initWithPaymentMethodBillingDetails:","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"initWithPaymentMethodBillingDetails:","kind":"identifier"}],"roleHeading":"Initializer","role":"symbol","symbolKind":"init"},"kind":"symbol","abstract":[{"text":"Initializes a new STPAddress with data from STPPaymentMethodBillingDetails.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpaddress\/init(paymentmethodbillingdetails:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpaddress\/init(paymentmethodbillingdetails:)"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","abstract":[{"type":"text","text":"STPAddress Contains an address as represented by the Stripe API."}],"type":"topic","url":"\/documentation\/stripepayments\/stpaddress","navigatorTitle":[{"kind":"identifier","text":"STPAddress"}],"title":"STPAddress","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddress"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/init(paymentMethodBillingDetails:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/init(paymentMethodBillingDetails:)","kind":"symbol","type":"topic","title":"init(paymentMethodBillingDetails:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentMethodBillingDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPaymentMethodBillingDetails:"}],"url":"\/documentation\/stripepayments\/stpaddress\/init(paymentmethodbillingdetails:)","abstract":[{"text":"Initializes a new STPAddress with data from STPPaymentMethodBillingDetails.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","title":"STPPaymentMethodBillingDetails","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails","navigatorTitle":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Billing information associated with a "},{"type":"codeVoice","code":"STPPaymentMethod"},{"type":"text","text":" that may be used or required by particular types of payment methods."}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithPaymentMethodBillingDetails:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPaymentMethodBillingDetails:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPaymentMethodBillingDetails:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"billingDetails"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"billingDetails","content":[{"inlineContent":[{"type":"text","text":"The STPPaymentMethodBillingDetails instance you want to populate the STPAddress from."}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new STPAddress instance with data copied from the passed in billing details."}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/title","value":"STPAddress"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/fragments","value":[{"kind":"identifier","text":"STPAddress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/navigatorTitle","value":[{"kind":"identifier","text":"STPAddress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1init(paymentMethodBillingDetails:)\/title","value":"initWithPaymentMethodBillingDetails:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1init(paymentMethodBillingDetails:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPaymentMethodBillingDetails:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title","value":"STPPaymentMethodBillingDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}