{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress"]]},"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPAddress(im)initWithCNContact:","role":"symbol","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCNContact:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cnContact","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CNContact","kind":"typeIdentifier","text":"CNContact"},{"kind":"text","text":")"}],"symbolKind":"init","roleHeading":"Initializer","title":"init(cnContact:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithCNContact:) ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"cnContact","kind":"externalParam"},{"kind":"text","text":" "},{"text":"contact","kind":"internalParam"},{"kind":"text","text":": "},{"text":"CNContact","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CNContact"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"contact","content":[{"inlineContent":[{"type":"text","text":"The CNContact you want to populate the STPAddress from."}],"type":"paragraph"}]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Initializes a new STPAddress with a contact from the Contacts framework.","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/init(cnContact:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpaddress\/init(cncontact:)"]},{"paths":["\/documentation\/stripepayments\/stpaddress\/init(cncontact:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/init(cnContact:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"cnContact","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CNContact","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CNContact"},{"kind":"text","text":")"}],"role":"symbol","title":"init(cnContact:)","navigatorTitle":[{"kind":"identifier","text":"initWithCNContact:"}],"type":"topic","url":"\/documentation\/stripepayments\/stpaddress\/init(cncontact:)","abstract":[{"text":"Initializes a new STPAddress with a contact from the Contacts framework.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/init(cnContact:)","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPAddress","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpaddress","title":"STPAddress","navigatorTitle":[{"text":"STPAddress","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"STPAddress Contains an address as represented by the Stripe API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","role":"collection","title":"StripePayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithCNContact:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCNContact:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithCNContact:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CNContact","kind":"typeIdentifier","text":"CNContact"},{"text":" *) ","kind":"text"},{"text":"contact","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"contact","content":[{"inlineContent":[{"type":"text","text":"The CNContact you want to populate the STPAddress from."}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"text":"A new STPAddress instance with data copied from the passed in contact.","type":"text"}],"type":"paragraph"}],"kind":"content"},"op":"add"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1init(cnContact:)\/title","value":"initWithCNContact:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithCNContact:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1init(cnContact:)\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/title","op":"replace","value":"STPAddress"},{"value":[{"kind":"identifier","text":"STPAddress"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/navigatorTitle","value":[{"text":"STPAddress","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}