{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(initWithPKContact:) "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"pkContact","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"contact"},{"kind":"text","text":": "},{"text":"PKContact","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKContact"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"contact","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The PassKit contact you want to populate the STPAddress from."}]}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpaddress\/init(pkcontact:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpaddress\/init(pkcontact:)"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress"]]},"metadata":{"role":"symbol","navigatorTitle":[{"text":"initWithPKContact:","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPAddress(im)initWithPKContact:","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pkContact"},{"text":": ","kind":"text"},{"text":"PKContact","preciseIdentifier":"c:objc(cs)PKContact","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"StripePayments"}],"symbolKind":"init","title":"init(pkContact:)"},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/init(pkContact:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes a new STPAddress with data from an PassKit contact."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/init(pkContact:)":{"abstract":[{"type":"text","text":"Initializes a new STPAddress with data from an PassKit contact."}],"kind":"symbol","role":"symbol","title":"init(pkContact:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/init(pkContact:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pkContact"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKContact","preciseIdentifier":"c:objc(cs)PKContact"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithPKContact:","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpaddress\/init(pkcontact:)","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAddress","kind":"identifier"}],"role":"symbol","title":"STPAddress","abstract":[{"type":"text","text":"STPAddress Contains an address as represented by the Stripe API."}],"url":"\/documentation\/stripepayments\/stpaddress","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","navigatorTitle":[{"text":"STPAddress","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithPKContact:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPKContact:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPKContact:"},{"text":"(","kind":"text"},{"text":"PKContact","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKContact"},{"text":" *) ","kind":"text"},{"text":"contact","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The PassKit contact you want to populate the STPAddress from.","type":"text"}]}],"name":"contact"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"A new STPAddress instance with data copied from the passed in contact.","type":"text"}],"type":"paragraph"}]},"op":"add","path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1init(pkContact:)\/title","value":"initWithPKContact:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1init(pkContact:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPKContact:"}],"op":"replace"},{"value":"STPAddress","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPAddress"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/fragments","op":"replace"},{"op":"replace","value":[{"text":"STPAddress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/navigatorTitle"}]}]}