{"metadata":{"role":"collectionGroup","modules":[{"name":"StripePayments"}],"roleHeading":"API Collection","title":"NSCopying Implementations"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/NSCopying-Implementations"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/copy(with:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpaddress\/nscopying-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpaddress\/nscopying-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAddress","kind":"identifier"}],"role":"symbol","title":"STPAddress","abstract":[{"type":"text","text":"STPAddress Contains an address as represented by the Stripe API."}],"url":"\/documentation\/stripepayments\/stpaddress","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","navigatorTitle":[{"text":"STPAddress","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/copy(with:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/copy(with:)","title":"copy(with:)","kind":"symbol","type":"topic","abstract":[{"text":":nodoc:","type":"text"}],"navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpaddress\/copy(with:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"NSZone","kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"text":"Any","kind":"keyword"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/copy(with:)"],"title":"Instance Methods","generated":true}],"path":"\/topicSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":"STPAddress","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/fragments","value":[{"text":"STPAddress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/navigatorTitle","value":[{"kind":"identifier","text":"STPAddress"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1copy(with:)\/title","value":"copyWithZone:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1copy(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}],"op":"replace"}]}]}