{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(PKContactValue) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pkContactValue","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKContact","text":"PKContact","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"A new PassKit contact with data copied from this STPAddress instance."}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/pkContactValue()","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pkContactValue","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"PKContact","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKContact"}],"modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@StripePayments@objc(cs)STPAddress(im)PKContactValue","navigatorTitle":[{"kind":"identifier","text":"PKContactValue"}],"title":"pkContactValue()"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress"]]},"abstract":[{"type":"text","text":"Generates a PassKit contact representation of this STPAddress."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpaddress\/pkcontactvalue()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpaddress\/pkcontactvalue()"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/pkContactValue()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pkContactValue","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"PKContact","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKContact"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/pkContactValue()","role":"symbol","navigatorTitle":[{"text":"PKContactValue","kind":"identifier"}],"abstract":[{"type":"text","text":"Generates a PassKit contact representation of this STPAddress."}],"title":"pkContactValue()","url":"\/documentation\/stripepayments\/stpaddress\/pkcontactvalue()","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","type":"topic","role":"symbol","kind":"symbol","title":"STPAddress","navigatorTitle":[{"kind":"identifier","text":"STPAddress"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddress"}],"abstract":[{"type":"text","text":"STPAddress Contains an address as represented by the Stripe API."}],"url":"\/documentation\/stripepayments\/stpaddress"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"PKContactValue"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"PKContactValue","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"PKContact","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKContact"},{"text":" *) ","kind":"text"},{"text":"PKContactValue","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"A new PassKit contact with data copied from this STPAddress instance."}],"type":"paragraph"}]}},{"value":"PKContactValue","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1pkContactValue()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"PKContactValue"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1pkContactValue()\/fragments"},{"value":"STPAddress","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/title"},{"value":[{"text":"STPAddress","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/fragments"},{"value":[{"text":"STPAddress","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/navigatorTitle"}]}]}