{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"},{"text":"() -> [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@CM@StripePayments@objc(cs)STPAddress(cm)propertyNamesToFormFieldNamesMapping","title":"propertyNamesToFormFieldNamesMapping()","modules":[{"name":"StripePayments"}],"symbolKind":"method","extendedModule":"StripePayments","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]","kind":"text"}],"roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/propertyNamesToFormFieldNamesMapping()"},"abstract":[{"type":"text","text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called "},{"code":"expMonth","type":"codeVoice"},{"text":", but the Stripe API expects a field called ","type":"text"},{"code":"exp_month","type":"codeVoice"},{"text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/STPFormEncodable-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpaddress\/propertynamestoformfieldnamesmapping()"]},{"paths":["\/documentation\/stripepayments\/stpaddress\/propertynamestoformfieldnamesmapping()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/STPFormEncodable-Implementations":{"title":"STPFormEncodable Implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/STPFormEncodable-Implementations","url":"\/documentation\/stripepayments\/stpaddress\/stpformencodable-implementations","kind":"article","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/propertyNamesToFormFieldNamesMapping()":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"title":"propertyNamesToFormFieldNamesMapping()","url":"\/documentation\/stripepayments\/stpaddress\/propertynamestoformfieldnamesmapping()","kind":"symbol","abstract":[{"text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called ","type":"text"},{"type":"codeVoice","code":"expMonth"},{"text":", but the Stripe API expects a field called ","type":"text"},{"type":"codeVoice","code":"exp_month"},{"type":"text","text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/propertyNamesToFormFieldNamesMapping()"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress":{"role":"symbol","abstract":[{"text":"STPAddress Contains an address as represented by the Stripe API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAddress"}],"kind":"symbol","title":"STPAddress","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPAddress"}],"url":"\/documentation\/stripepayments\/stpaddress"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"propertyNamesToFormFieldNamesMapping","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","value":"propertyNamesToFormFieldNamesMapping","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1propertyNamesToFormFieldNamesMapping()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1propertyNamesToFormFieldNamesMapping()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}]},{"value":"STPAddress","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/fragments","op":"replace","value":[{"text":"STPAddress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/navigatorTitle","value":[{"kind":"identifier","text":"STPAddress"}],"op":"replace"}]}]}