{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(shippingInfoForChargeWithAddress:shippingMethod:) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingInfoForCharge"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"address"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"shippingMethod"},{"kind":"text","text":" "},{"kind":"internalParam","text":"method"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKShippingMethod","text":"PKShippingMethod"},{"kind":"text","text":"?) -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The user’s shipping address. If nil, this method will return nil."}],"type":"paragraph"}],"name":"address"},{"content":[{"inlineContent":[{"type":"text","text":"The user’s selected shipping method. May be nil."}],"type":"paragraph"}],"name":"method"}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"content":[{"inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Api#Create_charge-Shipping"}],"type":"paragraph"}],"type":"aside","style":"note","name":"See Also"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"shippingInfoForChargeWithAddress:shippingMethod:"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPAddress(cm)shippingInfoForChargeWithAddress:shippingMethod:","title":"shippingInfoForCharge(with:shippingMethod:)","symbolKind":"method","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingInfoForCharge"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"shippingMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKShippingMethod","text":"PKShippingMethod"},{"kind":"text","text":"?) -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}]},"kind":"symbol","abstract":[{"type":"text","text":"When creating a charge on your backend, you can attach shipping information"},{"type":"text","text":" "},{"type":"text","text":"to prevent fraud on a physical good. You can use this method to turn your user’s"},{"type":"text","text":" "},{"type":"text","text":"shipping address and selected shipping method into a hash suitable for attaching"},{"type":"text","text":" "},{"type":"text","text":"to a charge. You should pass this to your backend, and use it as the "},{"type":"codeVoice","code":"shipping"},{"type":"text","text":" "},{"type":"text","text":"parameter when creating a charge."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpaddress\/shippinginfoforcharge(with:shippingmethod:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpaddress\/shippinginfoforcharge(with:shippingmethod:)"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/shippingInfoForCharge(with:shippingMethod:)","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/shippingInfoForCharge(with:shippingMethod:)":{"abstract":[{"type":"text","text":"When creating a charge on your backend, you can attach shipping information"},{"type":"text","text":" "},{"type":"text","text":"to prevent fraud on a physical good. You can use this method to turn your user’s"},{"type":"text","text":" "},{"type":"text","text":"shipping address and selected shipping method into a hash suitable for attaching"},{"type":"text","text":" "},{"type":"text","text":"to a charge. You should pass this to your backend, and use it as the "},{"type":"codeVoice","code":"shipping"},{"type":"text","text":" "},{"type":"text","text":"parameter when creating a charge."}],"role":"symbol","kind":"symbol","title":"shippingInfoForCharge(with:shippingMethod:)","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"shippingInfoForChargeWithAddress:shippingMethod:"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingInfoForCharge"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"shippingMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKShippingMethod","preciseIdentifier":"c:objc(cs)PKShippingMethod"},{"kind":"text","text":"?) -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"url":"\/documentation\/stripepayments\/stpaddress\/shippinginfoforcharge(with:shippingmethod:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/shippingInfoForCharge(with:shippingMethod:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","kind":"symbol","title":"StripePayments","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","abstract":[{"text":"STPAddress Contains an address as represented by the Stripe API.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddress"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPAddress"}],"title":"STPAddress","url":"\/documentation\/stripepayments\/stpaddress","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"shippingInfoForChargeWithAddress:shippingMethod:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"shippingInfoForChargeWithAddress:shippingMethod:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"shippingInfoForChargeWithAddress:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"address","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"shippingMethod:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKShippingMethod","text":"PKShippingMethod","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"method","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"name":"address","content":[{"type":"paragraph","inlineContent":[{"text":"The user’s shipping address. If nil, this method will return nil.","type":"text"}]}]},{"name":"method","content":[{"type":"paragraph","inlineContent":[{"text":"The user’s selected shipping method. May be nil.","type":"text"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"shippingInfoForChargeWithAddress:shippingMethod:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1shippingInfoForCharge(with:shippingMethod:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"shippingInfoForChargeWithAddress:shippingMethod:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1shippingInfoForCharge(with:shippingMethod:)\/fragments","op":"replace"},{"value":"STPAddress","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPAddress"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPAddress"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}