{"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/decodedObject(fromAPIResponse:)"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/STPAPIResponseDecodable-Implementations","interfaceLanguage":"swift"},"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress"]]},"metadata":{"modules":[{"name":"StripePayments"}],"role":"collectionGroup","roleHeading":"API Collection","title":"STPAPIResponseDecodable Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpaddress\/stpapiresponsedecodable-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpaddress\/stpapiresponsedecodable-implementations"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPAddress","kind":"identifier"}],"abstract":[{"type":"text","text":"STPAddress Contains an address as represented by the Stripe API."}],"url":"\/documentation\/stripepayments\/stpaddress","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","type":"topic","navigatorTitle":[{"text":"STPAddress","kind":"identifier"}],"kind":"symbol","title":"STPAddress","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/decodedObject(fromAPIResponse:)":{"url":"\/documentation\/stripepayments\/stpaddress\/decodedobject(fromapiresponse:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromAPIResponse"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/decodedObject(fromAPIResponse:)","abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"an "},{"type":"codeVoice","code":"NSDictionary"},{"text":") into an instance of the class.","type":"text"}],"role":"symbol","title":"decodedObject(fromAPIResponse:)","kind":"symbol","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/decodedObject(fromAPIResponse:)"],"generated":true,"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":"STPAddress","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/fragments","value":[{"text":"STPAddress","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/navigatorTitle","value":[{"kind":"identifier","text":"STPAddress"}],"op":"replace"},{"value":"decodedObjectFromAPIResponse:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1decodedObject(fromAPIResponse:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1decodedObject(fromAPIResponse:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]}]}]}