{"topicSections":[{"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/rootObjectName()"],"generated":true,"title":"Type Methods"}],"metadata":{"role":"collectionGroup","modules":[{"name":"StripePayments"}],"title":"STPFormEncodable Implementations","roleHeading":"API Collection"},"variants":[{"paths":["\/documentation\/stripepayments\/stpaddress\/stpformencodable-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpaddress\/stpformencodable-implementations"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/STPFormEncodable-Implementations","interfaceLanguage":"swift"},"kind":"article","sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress":{"navigatorTitle":[{"text":"STPAddress","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","type":"topic","abstract":[{"text":"STPAddress Contains an address as represented by the Stripe API.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAddress"}],"url":"\/documentation\/stripepayments\/stpaddress","title":"STPAddress"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/propertyNamesToFormFieldNamesMapping()":{"abstract":[{"type":"text","text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called "},{"type":"codeVoice","code":"expMonth"},{"type":"text","text":", but the Stripe API expects a field called "},{"code":"exp_month","type":"codeVoice"},{"type":"text","text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)"}],"url":"\/documentation\/stripepayments\/stpaddress\/propertynamestoformfieldnamesmapping()","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"kind":"text","text":"() -> ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}],"title":"propertyNamesToFormFieldNamesMapping()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/propertyNamesToFormFieldNamesMapping()","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/rootObjectName()":{"navigatorTitle":[{"text":"rootObjectName","kind":"identifier"}],"abstract":[{"type":"text","text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by "},{"code":"propertyNamesToFormFieldNamesMapping","type":"codeVoice"},{"text":" below.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/rootObjectName()","url":"\/documentation\/stripepayments\/stpaddress\/rootobjectname()","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rootObjectName"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"title":"rootObjectName()"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/rootObjectName()"],"anchor":"Type-Methods","generated":true,"title":"Type Methods"}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/title","value":"STPAddress"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPAddress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/navigatorTitle","value":[{"kind":"identifier","text":"STPAddress"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1propertyNamesToFormFieldNamesMapping()\/title","op":"replace","value":"propertyNamesToFormFieldNamesMapping"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1propertyNamesToFormFieldNamesMapping()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1rootObjectName()\/title","value":"rootObjectName"},{"value":[{"text":"+ ","kind":"text"},{"text":"rootObjectName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1rootObjectName()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}