{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(confirmSetupIntentWithParams:authenticationContext:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmSetupIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams","text":"STPSetupIntentConfirmParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"authenticationContext","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","text":"STPAuthenticationContext","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:14StripePayments49STPPaymentHandlerActionSetupIntentCompletionBlocka","text":"STPPaymentHandlerActionSetupIntentCompletionBlock","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionSetupIntentCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The params used to confirm the SetupIntent. Note that this method overrides the value of "},{"code":"setupIntentConfirmParams.useStripeSDK","type":"codeVoice"},{"type":"text","text":" to "},{"code":"@YES","type":"codeVoice"},{"type":"text","text":"."}]}],"name":"params"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The authentication context used to authenticate the SetupIntent."}]}],"name":"authenticationContext"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion block called when this method is finished."}]}],"name":"completion"}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"name":"Note","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"If the status returned is "},{"code":"STPPaymentHandlerActionStatus.succeeded","type":"codeVoice"},{"type":"text","text":", the SetupIntent status will always be "},{"code":"STPSetupIntentStatus.succeeded","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmSetupIntent(params:authenticationContext:completion:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler"]]},"abstract":[{"type":"text","text":"Confirms the SetupIntent using the provided parameters and handles any next actions required to authenticate the SetupIntent."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymenthandler\/confirmsetupintent(params:authenticationcontext:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymenthandler\/confirmsetupintent(params:authenticationcontext:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","symbolKind":"method","modules":[{"name":"StripePayments"}],"roleHeading":"Instance Method","externalID":"c:@M@StripePayments@objc(cs)STPPaymentHandler(im)confirmSetupIntentWithParams:authenticationContext:completion:","title":"confirmSetupIntent(params:authenticationContext:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmSetupIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams","text":"STPSetupIntentConfirmParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","text":"STPAuthenticationContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments49STPPaymentHandlerActionSetupIntentCompletionBlocka","text":"STPPaymentHandlerActionSetupIntentCompletionBlock"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"confirmSetupIntentWithParams:authenticationContext:completion:"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAuthenticationContext"}],"navigatorTitle":[{"kind":"identifier","text":"STPAuthenticationContext"}],"type":"topic","url":"\/documentation\/stripepayments\/stpauthenticationcontext","abstract":[{"type":"codeVoice","code":"STPAuthenticationContext"},{"type":"text","text":" provides information required to present authentication challenges"},{"type":"text","text":" "},{"type":"text","text":"to a user."}],"title":"STPAuthenticationContext","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler":{"title":"STPPaymentHandler","abstract":[{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" is a utility class that confirms PaymentIntents\/SetupIntents and handles any authentication required, such as 3DS1\/3DS2 for Strong Customer Authentication."},{"type":"text","text":" "},{"type":"text","text":"It can present authentication UI on top of your app or redirect users out of your app (to e.g. their banking app)."}],"url":"\/documentation\/stripepayments\/stppaymenthandler","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandler"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandler"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams","title":"STPSetupIntentConfirmParams","abstract":[{"text":"An object representing parameters to confirm a SetupIntent object.","type":"text"},{"text":" ","type":"text"},{"text":"For example, you would confirm a SetupIntent when a customer hits the “Save” button on a payment method management view in your app.","type":"text"},{"text":" ","type":"text"},{"text":"If the selected payment method does not require any additional steps from the customer, the SetupIntent’s status will transition to ","type":"text"},{"type":"codeVoice","code":"STPSetupIntentStatusSucceeded"},{"text":".  Otherwise, it will transition to ","type":"text"},{"type":"codeVoice","code":"STPSetupIntentStatusRequiresAction"},{"text":", and suggest additional actions via ","type":"text"},{"type":"codeVoice","code":"nextAction"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Instead of passing this to "},{"type":"codeVoice","code":"STPAPIClient.confirmSetupIntent(...)"},{"type":"text","text":" directly, we recommend using "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" to handle any additional steps for you."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionSetupIntentCompletionBlock":{"url":"\/documentation\/stripepayments\/stppaymenthandleractionsetupintentcompletionblock","abstract":[{"type":"text","text":"Completion block typedef for use in "},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" methods for Setup Intents."}],"navigatorTitle":[{"text":"STPPaymentHandlerActionSetupIntentCompletionBlock","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionSetupIntentCompletionBlock","kind":"symbol","title":"STPPaymentHandlerActionSetupIntentCompletionBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerActionSetupIntentCompletionBlock","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"navigatorTitle":[{"text":"STPSetupIntent","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsetupintent","abstract":[{"text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","role":"symbol","title":"STPSetupIntent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntent","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionStatus":{"role":"symbol","title":"STPPaymentHandlerActionStatus","kind":"symbol","abstract":[{"type":"codeVoice","code":"STPPaymentHandlerActionStatus"},{"type":"text","text":" represents the possible outcomes of requesting an action by "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":". An action could be confirming and\/or handling the next action for a PaymentIntent."}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymenthandleractionstatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus","navigatorTitle":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/confirmSetupIntent(params:authenticationContext:completion:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmSetupIntent(params:authenticationContext:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmSetupIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPSetupIntentConfirmParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams"},{"text":", ","kind":"text"},{"text":"authenticationContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPAuthenticationContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentHandlerActionSetupIntentCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments49STPPaymentHandlerActionSetupIntentCompletionBlocka"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"confirmSetupIntentWithParams:authenticationContext:completion:","kind":"identifier"}],"kind":"symbol","title":"confirmSetupIntent(params:authenticationContext:completion:)","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandler\/confirmsetupintent(params:authenticationcontext:completion:)","abstract":[{"type":"text","text":"Confirms the SetupIntent using the provided parameters and handles any next actions required to authenticate the SetupIntent."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"confirmSetupIntentWithParams:authenticationContext:completion:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"confirmSetupIntentWithParams:authenticationContext:completion:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"confirmSetupIntentWithParams:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","text":"STPSetupIntentConfirmParams","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"params","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"authenticationContext:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<STPAuthenticationContext>","preciseIdentifier":"c:Qo@M@StripePayments@objc(pl)STPAuthenticationContext","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"authenticationContext","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerActionStatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus"},{"kind":"text","text":" "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent","text":"STPSetupIntent"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The params used to confirm the SetupIntent. Note that this method overrides the value of "},{"type":"codeVoice","code":"setupIntentConfirmParams.useStripeSDK"},{"type":"text","text":" to "},{"type":"codeVoice","code":"@YES"},{"type":"text","text":"."}]}],"name":"params"},{"content":[{"inlineContent":[{"text":"The authentication context used to authenticate the SetupIntent.","type":"text"}],"type":"paragraph"}],"name":"authenticationContext"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion block called when this method is finished."}]}],"name":"completion"}]}},{"value":"STPAuthenticationContext","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/title"},{"value":[{"text":"STPAuthenticationContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/fragments"},{"value":[{"kind":"identifier","text":"STPAuthenticationContext"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/navigatorTitle"},{"value":"STPPaymentHandler","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/title"},{"value":[{"text":"STPPaymentHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/fragments"},{"value":[{"text":"STPPaymentHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/navigatorTitle"},{"value":"STPSetupIntentConfirmParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/title"},{"value":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/fragments"},{"value":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/navigatorTitle"},{"value":"STPSetupIntent","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title"},{"value":[{"kind":"identifier","text":"STPSetupIntent"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments"},{"value":[{"kind":"identifier","text":"STPSetupIntent"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle"},{"value":"STPPaymentHandlerActionStatus","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/title"},{"value":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/fragments"},{"value":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/navigatorTitle"},{"value":"confirmSetupIntentWithParams:authenticationContext:completion:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1confirmSetupIntent(params:authenticationContext:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"confirmSetupIntentWithParams:authenticationContext:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1confirmSetupIntent(params:authenticationContext:completion:)\/fragments"}]}]}