{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(confirmPayment:withAuthenticationContext:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"paymentParams","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams","preciseIdentifier":"s:14StripePayments22STPPaymentIntentParamsa"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"authenticationContext","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"STPAuthenticationContext","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"platforms":[{"unavailable":false,"deprecated":true,"beta":false,"renamed":"confirmPaymentIntent(params:authenticationContext:completion:)"}],"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"confirmPayment:withAuthenticationContext:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPPaymentIntentParams","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments22STPPaymentIntentParamsa"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPAuthenticationContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka"},{"text":")","kind":"text"}],"role":"symbol","extendedModule":"StripePayments","title":"confirmPayment(_:with:completion:)","roleHeading":"Instance Method","externalID":"c:@CM@StripePayments@objc(cs)STPPaymentHandler(im)confirmPayment:withAuthenticationContext:completion:","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler\/confirmpayment(_:with:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler\/confirmpayment(_:with:completion:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmPayment(_:with:completion:)","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler":{"url":"\/documentation\/stripepayments\/stppaymenthandler","abstract":[{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" is a utility class that confirms PaymentIntents\/SetupIntents and handles any authentication required, such as 3DS1\/3DS2 for Strong Customer Authentication.","type":"text"},{"text":" ","type":"text"},{"text":"It can present authentication UI on top of your app or redirect users out of your app (to e.g. their banking app).","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandler"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandler"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler","title":"STPPaymentHandler","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/confirmPayment(_:with:completion:)":{"url":"\/documentation\/stripepayments\/stppaymenthandler\/confirmpayment(_:with:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPPaymentIntentParams","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments22STPPaymentIntentParamsa"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPAuthenticationContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"confirmPayment:withAuthenticationContext:completion:","kind":"identifier"}],"deprecated":true,"abstract":[],"title":"confirmPayment(_:with:completion:)","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmPayment(_:with:completion:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext":{"url":"\/documentation\/stripepayments\/stpauthenticationcontext","abstract":[{"code":"STPAuthenticationContext","type":"codeVoice"},{"text":" provides information required to present authentication challenges","type":"text"},{"text":" ","type":"text"},{"text":"to a user.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAuthenticationContext"}],"navigatorTitle":[{"kind":"identifier","text":"STPAuthenticationContext"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","title":"STPAuthenticationContext","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"STPPaymentIntentParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentintentparams","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentParams","kind":"identifier"}],"kind":"symbol","title":"STPPaymentIntentParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionPaymentIntentCompletionBlock":{"title":"STPPaymentHandlerActionPaymentIntentCompletionBlock","navigatorTitle":[{"text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandleractionpaymentintentcompletionblock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionPaymentIntentCompletionBlock","abstract":[{"text":"Completion block typedef for use in ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" methods for Payment Intents.","type":"text"}],"type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams","abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"type":"text","text":" "},{"type":"text","text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it."},{"type":"text","text":" "},{"type":"text","text":"That PaymentMethod or Source can either be:"}],"kind":"symbol","title":"STPPaymentIntentConfirmParams","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"role":"symbol","kind":"symbol","title":"STPPaymentIntent","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntent","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentIntent","kind":"identifier"}],"abstract":[{"text":"A PaymentIntent tracks the process of collecting a payment from your customer.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionStatus":{"role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandleractionstatus","title":"STPPaymentHandlerActionStatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"STPPaymentHandlerActionStatus"},{"text":" represents the possible outcomes of requesting an action by ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"text":". An action could be confirming and\/or handling the next action for a PaymentIntent.","type":"text"}],"navigatorTitle":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"beta":false,"deprecated":true}],"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"confirmPayment:withAuthenticationContext:completion:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"confirmPayment:withAuthenticationContext:completion:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"confirmPayment:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams","text":"STPPaymentIntentConfirmParams"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentParams"},{"kind":"text","text":" "},{"kind":"identifier","text":"withAuthenticationContext:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<STPAuthenticationContext>","preciseIdentifier":"c:Qo@M@StripePayments@objc(pl)STPAuthenticationContext"},{"kind":"text","text":") "},{"kind":"internalParam","text":"authenticationContext"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^)("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPPaymentHandlerActionStatus","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"STPPaymentIntent","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentHandler","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandler"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/fragments"},{"op":"replace","value":[{"text":"STPPaymentHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/navigatorTitle"},{"op":"replace","value":"confirmPayment:withAuthenticationContext:completion:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1confirmPayment(_:with:completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"confirmPayment:withAuthenticationContext:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1confirmPayment(_:with:completion:)\/fragments"},{"op":"replace","value":"STPAuthenticationContext","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/title"},{"op":"replace","value":[{"text":"STPAuthenticationContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPAuthenticationContext"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/navigatorTitle"},{"op":"replace","value":"STPPaymentIntentConfirmParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/title"},{"op":"replace","value":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/fragments"},{"op":"replace","value":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/navigatorTitle"},{"op":"replace","value":"STPPaymentIntent","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title"},{"op":"replace","value":[{"text":"STPPaymentIntent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntent"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle"},{"op":"replace","value":"STPPaymentHandlerActionStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/fragments"},{"op":"replace","value":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/navigatorTitle"}]}]}