{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confirmPayment"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withParams"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentParams","text":"STPPaymentIntentParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"authenticationContext"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","text":"STPAuthenticationContext","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionPaymentIntentCompletionBlock","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"metadata":{"title":"confirmPayment(withParams:authenticationContext:completion:)","modules":[{"name":"StripePayments"}],"platforms":[],"roleHeading":"Instance Method","externalID":"s:14StripePayments17STPPaymentHandlerC14confirmPayment10withParams21authenticationContext10completionyAA0c6IntentH0C_AA017STPAuthenticationJ0_pyAA0cD12ActionStatusO_AA0cL0CSgSo7NSErrorCSgtctF","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"confirmPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withParams","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentParams","text":"STPPaymentIntentParams"},{"kind":"text","text":", "},{"text":"authenticationContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPAuthenticationContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"method","role":"symbol"},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use confirmPayment(_:with:completion:) instead"}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler\/confirmpayment(withparams:authenticationcontext:completion:)"]}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmPayment(withParams:authenticationContext:completion:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams":{"url":"\/documentation\/stripepayments\/stppaymentintentparams","role":"symbol","title":"STPPaymentIntentParams","navigatorTitle":[{"text":"STPPaymentIntentParams","kind":"identifier"}],"abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"text":" ","type":"text"},{"type":"text","text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it."},{"text":" ","type":"text"},{"text":"That PaymentMethod or Source can either be:","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentIntentParams"}],"type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/confirmPayment(withParams:authenticationContext:completion:)":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmPayment(withParams:authenticationContext:completion:)","url":"\/documentation\/stripepayments\/stppaymenthandler\/confirmpayment(withparams:authenticationcontext:completion:)","deprecated":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"confirmPayment","kind":"identifier"},{"kind":"text","text":"("},{"text":"withParams","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentIntentParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationContext"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPAuthenticationContext","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"text":":nodoc:","type":"text"}],"title":"confirmPayment(withParams:authenticationContext:completion:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext":{"abstract":[{"code":"STPAuthenticationContext","type":"codeVoice"},{"text":" provides information required to present authentication challenges","type":"text"},{"text":" ","type":"text"},{"text":"to a user.","type":"text"}],"title":"STPAuthenticationContext","url":"\/documentation\/stripepayments\/stpauthenticationcontext","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAuthenticationContext"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPAuthenticationContext"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionPaymentIntentCompletionBlock":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymenthandleractionpaymentintentcompletionblock","title":"STPPaymentHandlerActionPaymentIntentCompletionBlock","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock"}],"abstract":[{"type":"text","text":"Completion block typedef for use in "},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" methods for Payment Intents.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionPaymentIntentCompletionBlock"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler":{"role":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandler","title":"STPPaymentHandler","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler","kind":"symbol","abstract":[{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" is a utility class that confirms PaymentIntents\/SetupIntents and handles any authentication required, such as 3DS1\/3DS2 for Strong Customer Authentication."},{"text":" ","type":"text"},{"text":"It can present authentication UI on top of your app or redirect users out of your app (to e.g. their banking app).","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentHandler"}],"navigatorTitle":[{"text":"STPPaymentHandler","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPPaymentIntentParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentIntentParams","kind":"identifier"}]},{"value":"STPAuthenticationContext","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/fragments","value":[{"text":"STPAuthenticationContext","kind":"identifier"}]},{"value":[{"text":"STPAuthenticationContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/title","value":"STPPaymentHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandler"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/navigatorTitle","value":[{"text":"STPPaymentHandler","kind":"identifier"}],"op":"replace"}]}]}