{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(confirmSetupIntent:withAuthenticationContext:completion:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmSetupIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"setupIntentConfirmParams"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams","text":"STPSetupIntentConfirmParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"authenticationContext"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","text":"STPAuthenticationContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionSetupIntentCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments49STPPaymentHandlerActionSetupIntentCompletionBlocka","text":"STPPaymentHandlerActionSetupIntentCompletionBlock"},{"kind":"text","text":")"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmSetupIntent(_:with:completion:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler\/confirmsetupintent(_:with:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler\/confirmsetupintent(_:with:completion:)"]}],"metadata":{"role":"symbol","roleHeading":"Instance Method","extendedModule":"StripePayments","modules":[{"name":"StripePayments"}],"title":"confirmSetupIntent(_:with:completion:)","symbolKind":"method","externalID":"c:@CM@StripePayments@objc(cs)STPPaymentHandler(im)confirmSetupIntent:withAuthenticationContext:completion:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmSetupIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPSetupIntentConfirmParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPAuthenticationContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentHandlerActionSetupIntentCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments49STPPaymentHandlerActionSetupIntentCompletionBlocka"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"confirmSetupIntent:withAuthenticationContext:completion:","kind":"identifier"}],"platforms":[]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/confirmSetupIntent(_:with:completion:)":{"type":"topic","title":"confirmSetupIntent(_:with:completion:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmSetupIntent(_:with:completion:)","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmSetupIntent:withAuthenticationContext:completion:"}],"abstract":[],"url":"\/documentation\/stripepayments\/stppaymenthandler\/confirmsetupintent(_:with:completion:)","deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmSetupIntent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams","text":"STPSetupIntentConfirmParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","text":"STPAuthenticationContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments49STPPaymentHandlerActionSetupIntentCompletionBlocka","text":"STPPaymentHandlerActionSetupIntentCompletionBlock"},{"kind":"text","text":")"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler":{"type":"topic","abstract":[{"type":"codeVoice","code":"STPPaymentHandler"},{"text":" is a utility class that confirms PaymentIntents\/SetupIntents and handles any authentication required, such as 3DS1\/3DS2 for Strong Customer Authentication.","type":"text"},{"text":" ","type":"text"},{"text":"It can present authentication UI on top of your app or redirect users out of your app (to e.g. their banking app).","type":"text"}],"title":"STPPaymentHandler","role":"symbol","navigatorTitle":[{"text":"STPPaymentHandler","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandler","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler","url":"\/documentation\/stripepayments\/stppaymenthandler","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext":{"type":"topic","abstract":[{"type":"codeVoice","code":"STPAuthenticationContext"},{"text":" provides information required to present authentication challenges","type":"text"},{"text":" ","type":"text"},{"text":"to a user.","type":"text"}],"title":"STPAuthenticationContext","role":"symbol","navigatorTitle":[{"text":"STPAuthenticationContext","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAuthenticationContext","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","url":"\/documentation\/stripepayments\/stpauthenticationcontext","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionSetupIntentCompletionBlock":{"type":"topic","title":"STPPaymentHandlerActionSetupIntentCompletionBlock","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionSetupIntentCompletionBlock","navigatorTitle":[{"text":"STPPaymentHandlerActionSetupIntentCompletionBlock","kind":"identifier"}],"abstract":[{"text":"Completion block typedef for use in ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" methods for Setup Intents.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymenthandleractionsetupintentcompletionblock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerActionSetupIntentCompletionBlock","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"type":"topic","title":"STPSetupIntent","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","navigatorTitle":[{"text":"STPSetupIntent","kind":"identifier"}],"abstract":[{"type":"text","text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments."}],"url":"\/documentation\/stripepayments\/stpsetupintent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntent","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionStatus":{"type":"topic","abstract":[{"type":"codeVoice","code":"STPPaymentHandlerActionStatus"},{"text":" represents the possible outcomes of requesting an action by ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"text":". An action could be confirming and\/or handling the next action for a PaymentIntent.","type":"text"}],"title":"STPPaymentHandlerActionStatus","role":"symbol","navigatorTitle":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus","url":"\/documentation\/stripepayments\/stppaymenthandleractionstatus","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams":{"title":"STPSetupIntentConfirmParams","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","navigatorTitle":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"abstract":[{"type":"text","text":"An object representing parameters to confirm a SetupIntent object."},{"type":"text","text":" "},{"type":"text","text":"For example, you would confirm a SetupIntent when a customer hits the “Save” button on a payment method management view in your app."},{"type":"text","text":" "},{"type":"text","text":"If the selected payment method does not require any additional steps from the customer, the SetupIntent’s status will transition to "},{"type":"codeVoice","code":"STPSetupIntentStatusSucceeded"},{"type":"text","text":".  Otherwise, it will transition to "},{"type":"codeVoice","code":"STPSetupIntentStatusRequiresAction"},{"type":"text","text":", and suggest additional actions via "},{"type":"codeVoice","code":"nextAction"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Instead of passing this to "},{"type":"codeVoice","code":"STPAPIClient.confirmSetupIntent(...)"},{"type":"text","text":" directly, we recommend using "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" to handle any additional steps for you."}],"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentConfirmParams","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[],"path":"\/metadata\/platforms","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"confirmSetupIntent:withAuthenticationContext:completion:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"confirmSetupIntent:withAuthenticationContext:completion:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"confirmSetupIntent:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPSetupIntentConfirmParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams"},{"text":" *) ","kind":"text"},{"text":"setupIntentConfirmParams","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withAuthenticationContext:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<STPAuthenticationContext>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@StripePayments@objc(pl)STPAuthenticationContext"},{"text":") ","kind":"text"},{"text":"authenticationContext","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^)(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerActionStatus","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"STPSetupIntent","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent"},{"text":" *","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" *","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"confirmSetupIntent:withAuthenticationContext:completion:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1confirmSetupIntent(_:with:completion:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"confirmSetupIntent:withAuthenticationContext:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1confirmSetupIntent(_:with:completion:)\/fragments","op":"replace"},{"value":"STPPaymentHandler","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/title","op":"replace"},{"value":[{"text":"STPPaymentHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/fragments","op":"replace"},{"value":[{"text":"STPPaymentHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/navigatorTitle","op":"replace"},{"value":"STPAuthenticationContext","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/title","op":"replace"},{"value":[{"text":"STPAuthenticationContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/fragments","op":"replace"},{"value":[{"text":"STPAuthenticationContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/navigatorTitle","op":"replace"},{"value":"STPSetupIntent","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title","op":"replace"},{"value":[{"text":"STPSetupIntent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments","op":"replace"},{"value":[{"text":"STPSetupIntent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle","op":"replace"},{"value":"STPPaymentHandlerActionStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/title","op":"replace"},{"value":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/fragments","op":"replace"},{"value":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/navigatorTitle","op":"replace"},{"value":"STPSetupIntentConfirmParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/title","op":"replace"},{"value":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/fragments","op":"replace"},{"value":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/navigatorTitle","op":"replace"}]}]}