{"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentConfirmParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"authenticationContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPAuthenticationContext","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"confirmPaymentIntentWithParams:authenticationContext:completion:","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentHandler(im)confirmPaymentIntentWithParams:authenticationContext:completion:","symbolKind":"method","role":"symbol","title":"confirmPaymentIntent(params:authenticationContext:completion:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Confirms the PaymentIntent using the provided ","type":"text"},{"code":"params","type":"codeVoice"},{"text":" and handles any next actions required to authenticate the PaymentIntent.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler\/confirmpaymentintent(params:authenticationcontext:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler\/confirmpaymentintent(params:authenticationcontext:completion:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmPaymentIntent(params:authenticationContext:completion:)"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(confirmPaymentIntentWithParams:authenticationContext:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentConfirmParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams"},{"text":", ","kind":"text"},{"text":"authenticationContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPAuthenticationContext","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionPaymentIntentCompletionBlock"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The params used to confirm the PaymentIntent. Note that this method overrides the value of ","type":"text"},{"code":"paymentParams.useStripeSDK","type":"codeVoice"},{"text":" to ","type":"text"},{"code":"@YES","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"params"},{"content":[{"inlineContent":[{"text":"The authentication context used to authenticate the payment.","type":"text"}],"type":"paragraph"}],"name":"authenticationContext"},{"content":[{"inlineContent":[{"text":"The completion block.","type":"text"}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"content":[{"inlineContent":[{"text":"If the status returned is ","type":"text"},{"code":"STPPaymentHandlerActionStatus.succeeded","type":"codeVoice"},{"text":", the PaymentIntent status is not necessarily ","type":"text"},{"code":"STPPaymentIntentStatus.succeeded","type":"codeVoice"},{"text":" (e.g. some bank payment methods take days before money moves and the PaymentIntent succeeds).","type":"text"}],"type":"paragraph"}],"style":"note","name":"Note","type":"aside"}],"kind":"content"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","type":"topic","title":"STPAuthenticationContext","abstract":[{"type":"codeVoice","code":"STPAuthenticationContext"},{"text":" provides information required to present authentication challenges","type":"text"},{"text":" ","type":"text"},{"text":"to a user.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAuthenticationContext","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpauthenticationcontext","navigatorTitle":[{"text":"STPAuthenticationContext","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionPaymentIntentCompletionBlock":{"abstract":[{"type":"text","text":"Completion block typedef for use in "},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" methods for Payment Intents."}],"role":"symbol","title":"STPPaymentHandlerActionPaymentIntentCompletionBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandleractionpaymentintentcompletionblock","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionPaymentIntentCompletionBlock"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"url":"\/documentation\/stripepayments\/stppaymentintent","kind":"symbol","abstract":[{"type":"text","text":"A PaymentIntent tracks the process of collecting a payment from your customer."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntent"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntent"}],"type":"topic","title":"STPPaymentIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams":{"url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams","abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"type":"text","text":" "},{"type":"text","text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it."},{"type":"text","text":" "},{"type":"text","text":"That PaymentMethod or Source can either be:"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"type":"topic","title":"STPPaymentIntentConfirmParams","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/confirmPaymentIntent(params:authenticationContext:completion:)":{"navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmPaymentIntentWithParams:authenticationContext:completion:"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmPaymentIntent(params:authenticationContext:completion:)","abstract":[{"text":"Confirms the PaymentIntent using the provided ","type":"text"},{"code":"params","type":"codeVoice"},{"text":" and handles any next actions required to authenticate the PaymentIntent.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmPaymentIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams","text":"STPPaymentIntentConfirmParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","text":"STPAuthenticationContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock"},{"kind":"text","text":")"}],"url":"\/documentation\/stripepayments\/stppaymenthandler\/confirmpaymentintent(params:authenticationcontext:completion:)","title":"confirmPaymentIntent(params:authenticationContext:completion:)","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler":{"navigatorTitle":[{"text":"STPPaymentHandler","kind":"identifier"}],"abstract":[{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" is a utility class that confirms PaymentIntents\/SetupIntents and handles any authentication required, such as 3DS1\/3DS2 for Strong Customer Authentication.","type":"text"},{"text":" ","type":"text"},{"text":"It can present authentication UI on top of your app or redirect users out of your app (to e.g. their banking app).","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler","url":"\/documentation\/stripepayments\/stppaymenthandler","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandler","kind":"identifier"}],"title":"STPPaymentHandler"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionStatus":{"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus","title":"STPPaymentHandlerActionStatus","abstract":[{"type":"codeVoice","code":"STPPaymentHandlerActionStatus"},{"type":"text","text":" represents the possible outcomes of requesting an action by "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":". An action could be confirming and\/or handling the next action for a PaymentIntent."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}],"url":"\/documentation\/stripepayments\/stppaymenthandleractionstatus","navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"confirmPaymentIntentWithParams:authenticationContext:completion:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"confirmPaymentIntentWithParams:authenticationContext:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"confirmPaymentIntentWithParams:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams","text":"STPPaymentIntentConfirmParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams"},{"text":" *) ","kind":"text"},{"text":"params","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"authenticationContext:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@StripePayments@objc(pl)STPAuthenticationContext","text":"id<STPAuthenticationContext>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"authenticationContext","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus","text":"STPPaymentHandlerActionStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","text":"STPPaymentIntent","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent"},{"text":" *","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" *","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"params","content":[{"type":"paragraph","inlineContent":[{"text":"The params used to confirm the PaymentIntent. Note that this method overrides the value of ","type":"text"},{"type":"codeVoice","code":"paymentParams.useStripeSDK"},{"text":" to ","type":"text"},{"type":"codeVoice","code":"@YES"},{"text":".","type":"text"}]}]},{"name":"authenticationContext","content":[{"type":"paragraph","inlineContent":[{"text":"The authentication context used to authenticate the payment.","type":"text"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"The completion block.","type":"text"}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"STPAuthenticationContext","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/title"},{"value":[{"text":"STPAuthenticationContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/fragments"},{"value":[{"text":"STPAuthenticationContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/navigatorTitle"},{"value":"STPPaymentIntent","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title"},{"value":[{"text":"STPPaymentIntent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments"},{"value":[{"text":"STPPaymentIntent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle"},{"value":"STPPaymentIntentConfirmParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/title"},{"value":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/fragments"},{"value":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/navigatorTitle"},{"value":"confirmPaymentIntentWithParams:authenticationContext:completion:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1confirmPaymentIntent(params:authenticationContext:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"confirmPaymentIntentWithParams:authenticationContext:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1confirmPaymentIntent(params:authenticationContext:completion:)\/fragments"},{"value":"STPPaymentHandler","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/title"},{"value":[{"text":"STPPaymentHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/fragments"},{"value":[{"text":"STPPaymentHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/navigatorTitle"},{"value":"STPPaymentHandlerActionStatus","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/title"},{"value":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/fragments"},{"value":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/navigatorTitle"}]}]}