{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleNextAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentIntentClientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","text":"STPAuthenticationContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus","text":"STPPaymentHandlerActionStatus"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","text":"STPPaymentIntent"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":"?)"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"paymentIntentClientSecret","content":[{"inlineContent":[{"type":"text","text":"The client secret of the PaymentIntent to handle next actions for."}],"type":"paragraph"}]},{"name":"authenticationContext","content":[{"inlineContent":[{"type":"text","text":"The authentication context used to authenticate the payment."}],"type":"paragraph"}]},{"name":"returnURL","content":[{"inlineContent":[{"type":"text","text":"An optional URL to redirect your customer back to after they authenticate or cancel in a webview. This should match the returnURL you specified during PaymentIntent confirmation."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":""}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Handles any "},{"type":"codeVoice","code":"nextAction"},{"type":"text","text":" required to authenticate the PaymentIntent."},{"type":"text","text":" "},{"type":"text","text":"Call this method if you are using server-side confirmation."}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleNextAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentIntentClientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","text":"STPAuthenticationContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus","text":"STPPaymentHandlerActionStatus"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","text":"STPPaymentIntent"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":"?)"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"StripePayments"}],"title":"handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:)","externalID":"s:14StripePayments17STPPaymentHandlerC16handleNextAction25paymentIntentClientSecret21authenticationContext9returnURLAA0cdG6StatusO_AA0cI0CSgSo7NSErrorCSgtSS_AA017STPAuthenticationM0_pSSSgtYaF"},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(paymentintentclientsecret:authenticationcontext:returnurl:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext":{"type":"topic","abstract":[{"type":"codeVoice","code":"STPAuthenticationContext"},{"text":" provides information required to present authentication challenges","type":"text"},{"text":" ","type":"text"},{"text":"to a user.","type":"text"}],"title":"STPAuthenticationContext","role":"symbol","navigatorTitle":[{"text":"STPAuthenticationContext","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAuthenticationContext","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","url":"\/documentation\/stripepayments\/stpauthenticationcontext","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"url":"\/documentation\/stripepayments\/stppaymentintent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"A PaymentIntent tracks the process of collecting a payment from your customer.","type":"text"}],"navigatorTitle":[{"text":"STPPaymentIntent","kind":"identifier"}],"title":"STPPaymentIntent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntent","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionStatus":{"type":"topic","abstract":[{"type":"codeVoice","code":"STPPaymentHandlerActionStatus"},{"text":" represents the possible outcomes of requesting an action by ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"text":". An action could be confirming and\/or handling the next action for a PaymentIntent.","type":"text"}],"title":"STPPaymentHandlerActionStatus","role":"symbol","navigatorTitle":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus","url":"\/documentation\/stripepayments\/stppaymenthandleractionstatus","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:)":{"url":"\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(paymentintentclientsecret:authenticationcontext:returnurl:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:)","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Handles any "},{"type":"codeVoice","code":"nextAction"},{"type":"text","text":" required to authenticate the PaymentIntent."},{"type":"text","text":" "},{"type":"text","text":"Call this method if you are using server-side confirmation."}],"title":"handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleNextAction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"paymentIntentClientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"authenticationContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPAuthenticationContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> (","kind":"text"},{"text":"STPPaymentHandlerActionStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus"},{"text":", ","kind":"text"},{"text":"STPPaymentIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent"},{"text":"?, ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":"?)","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler":{"type":"topic","abstract":[{"type":"codeVoice","code":"STPPaymentHandler"},{"text":" is a utility class that confirms PaymentIntents\/SetupIntents and handles any authentication required, such as 3DS1\/3DS2 for Strong Customer Authentication.","type":"text"},{"text":" ","type":"text"},{"text":"It can present authentication UI on top of your app or redirect users out of your app (to e.g. their banking app).","type":"text"}],"title":"STPPaymentHandler","role":"symbol","navigatorTitle":[{"text":"STPPaymentHandler","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandler","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler","url":"\/documentation\/stripepayments\/stppaymenthandler","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"STPAuthenticationContext","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPAuthenticationContext"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPAuthenticationContext"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/navigatorTitle"},{"op":"replace","value":"STPPaymentIntent","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntent"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntent"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle"},{"op":"replace","value":"STPPaymentHandlerActionStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/navigatorTitle"},{"op":"replace","value":"STPPaymentHandler","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandler"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandler"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}