{"sections":[],"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"handleNextActionForPayment:withAuthenticationContext:returnURL:completion:"}],"symbolKind":"method","platforms":[{"unavailable":false,"beta":false,"deprecated":true,"renamed":"handleNextAction(paymentIntentClientSecret:authenticationContext:completion:)"}],"extendedModule":"StripePayments","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleNextAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPayment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","text":"STPAuthenticationContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock"},{"kind":"text","text":")"}],"externalID":"c:@CM@StripePayments@objc(cs)STPPaymentHandler(im)handleNextActionForPayment:withAuthenticationContext:returnURL:completion:","title":"handleNextAction(forPayment:with:returnURL:completion:)","roleHeading":"Instance Method","modules":[{"name":"StripePayments"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(forPayment:with:returnURL:completion:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(handleNextActionForPayment:withAuthenticationContext:returnURL:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleNextAction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forPayment","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"paymentIntentClientSecret","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"authenticationContext","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","text":"STPAuthenticationContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionPaymentIntentCompletionBlock","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(forpayment:with:returnurl:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(forpayment:with:returnurl:completion:)"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext":{"url":"\/documentation\/stripepayments\/stpauthenticationcontext","type":"topic","abstract":[{"type":"codeVoice","code":"STPAuthenticationContext"},{"text":" provides information required to present authentication challenges","type":"text"},{"text":" ","type":"text"},{"text":"to a user.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"STPAuthenticationContext","kind":"identifier"}],"title":"STPAuthenticationContext","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAuthenticationContext","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionPaymentIntentCompletionBlock":{"title":"STPPaymentHandlerActionPaymentIntentCompletionBlock","url":"\/documentation\/stripepayments\/stppaymenthandleractionpaymentintentcompletionblock","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Completion block typedef for use in ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" methods for Payment Intents.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"abstract":[{"text":"A PaymentIntent tracks the process of collecting a payment from your customer.","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintent","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntent"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntent"}],"title":"STPPaymentIntent","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/handleNextAction(forPayment:with:returnURL:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleNextAction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forPayment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPAuthenticationContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"handleNextActionForPayment:withAuthenticationContext:returnURL:completion:","kind":"identifier"}],"title":"handleNextAction(forPayment:with:returnURL:completion:)","abstract":[],"url":"\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(forpayment:with:returnurl:completion:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(forPayment:with:returnURL:completion:)","type":"topic","deprecated":true,"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler":{"abstract":[{"type":"codeVoice","code":"STPPaymentHandler"},{"text":" is a utility class that confirms PaymentIntents\/SetupIntents and handles any authentication required, such as 3DS1\/3DS2 for Strong Customer Authentication.","type":"text"},{"text":" ","type":"text"},{"text":"It can present authentication UI on top of your app or redirect users out of your app (to e.g. their banking app).","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler","url":"\/documentation\/stripepayments\/stppaymenthandler","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandler"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandler"}],"title":"STPPaymentHandler"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionStatus":{"kind":"symbol","title":"STPPaymentHandlerActionStatus","type":"topic","role":"symbol","abstract":[{"code":"STPPaymentHandlerActionStatus","type":"codeVoice"},{"type":"text","text":" represents the possible outcomes of requesting an action by "},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":". An action could be confirming and\/or handling the next action for a PaymentIntent."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}],"url":"\/documentation\/stripepayments\/stppaymenthandleractionstatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"deprecated":true,"unavailable":false,"beta":false}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"handleNextActionForPayment:withAuthenticationContext:returnURL:completion:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"handleNextActionForPayment:withAuthenticationContext:returnURL:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"handleNextActionForPayment:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentIntentClientSecret"},{"kind":"text","text":" "},{"kind":"identifier","text":"withAuthenticationContext:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@StripePayments@objc(pl)STPAuthenticationContext","kind":"typeIdentifier","text":"id<STPAuthenticationContext>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"authenticationContext"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnURL:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"returnURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^)("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus","kind":"typeIdentifier","text":"STPPaymentHandlerActionStatus"},{"kind":"text","text":" "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","kind":"typeIdentifier","text":"STPPaymentIntent"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/title","value":"STPAuthenticationContext","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/fragments","value":[{"kind":"identifier","text":"STPAuthenticationContext"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/navigatorTitle","value":[{"text":"STPAuthenticationContext","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title","value":"STPPaymentIntent","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntent"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntent"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1handleNextAction(forPayment:with:returnURL:completion:)\/title","value":"handleNextActionForPayment:withAuthenticationContext:returnURL:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1handleNextAction(forPayment:with:returnURL:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"handleNextActionForPayment:withAuthenticationContext:returnURL:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/title","value":"STPPaymentHandler","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/fragments","value":[{"text":"STPPaymentHandler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/navigatorTitle","value":[{"text":"STPPaymentHandler","kind":"identifier"}],"op":"replace"},{"value":"STPPaymentHandlerActionStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/navigatorTitle","op":"replace"}]}]}