{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(handleNextActionForSetupIntent:withAuthenticationContext:returnURL:completion:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleNextAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSetupIntent"},{"kind":"text","text":" "},{"kind":"internalParam","text":"setupIntentClientSecret"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"authenticationContext"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","kind":"typeIdentifier","text":"STPAuthenticationContext","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"preciseIdentifier":"s:14StripePayments49STPPaymentHandlerActionSetupIntentCompletionBlocka","kind":"typeIdentifier","text":"STPPaymentHandlerActionSetupIntentCompletionBlock","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionSetupIntentCompletionBlock"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"sections":[],"metadata":{"externalID":"c:@CM@StripePayments@objc(cs)STPPaymentHandler(im)handleNextActionForSetupIntent:withAuthenticationContext:returnURL:completion:","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"handleNextActionForSetupIntent:withAuthenticationContext:returnURL:completion:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","platforms":[],"symbolKind":"method","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleNextAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSetupIntent"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","kind":"typeIdentifier","text":"STPAuthenticationContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments49STPPaymentHandlerActionSetupIntentCompletionBlocka","text":"STPPaymentHandlerActionSetupIntentCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"extendedModule":"StripePayments","title":"handleNextAction(forSetupIntent:with:returnURL:completion:)"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(forsetupintent:with:returnurl:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(forsetupintent:with:returnurl:completion:)"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(forSetupIntent:with:returnURL:completion:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionStatus":{"type":"topic","kind":"symbol","abstract":[{"code":"STPPaymentHandlerActionStatus","type":"codeVoice"},{"text":" represents the possible outcomes of requesting an action by ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":". An action could be confirming and\/or handling the next action for a PaymentIntent."}],"role":"symbol","navigatorTitle":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymenthandleractionstatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus","title":"STPPaymentHandlerActionStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext":{"url":"\/documentation\/stripepayments\/stpauthenticationcontext","abstract":[{"type":"codeVoice","code":"STPAuthenticationContext"},{"type":"text","text":" provides information required to present authentication challenges"},{"type":"text","text":" "},{"type":"text","text":"to a user."}],"navigatorTitle":[{"kind":"identifier","text":"STPAuthenticationContext"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAuthenticationContext"}],"type":"topic","title":"STPAuthenticationContext"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler":{"kind":"symbol","abstract":[{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" is a utility class that confirms PaymentIntents\/SetupIntents and handles any authentication required, such as 3DS1\/3DS2 for Strong Customer Authentication.","type":"text"},{"text":" ","type":"text"},{"text":"It can present authentication UI on top of your app or redirect users out of your app (to e.g. their banking app).","type":"text"}],"role":"symbol","title":"STPPaymentHandler","url":"\/documentation\/stripepayments\/stppaymenthandler","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandler","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentHandler","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionSetupIntentCompletionBlock":{"kind":"symbol","abstract":[{"text":"Completion block typedef for use in ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" methods for Setup Intents.","type":"text"}],"role":"symbol","title":"STPPaymentHandlerActionSetupIntentCompletionBlock","url":"\/documentation\/stripepayments\/stppaymenthandleractionsetupintentcompletionblock","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionSetupIntentCompletionBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerActionSetupIntentCompletionBlock","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentHandlerActionSetupIntentCompletionBlock","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"title":"STPSetupIntent","abstract":[{"text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntent","kind":"identifier"}],"navigatorTitle":[{"text":"STPSetupIntent","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","url":"\/documentation\/stripepayments\/stpsetupintent","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/handleNextAction(forSetupIntent:with:returnURL:completion:)":{"title":"handleNextAction(forSetupIntent:with:returnURL:completion:)","abstract":[],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"handleNextActionForSetupIntent:withAuthenticationContext:returnURL:completion:","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(forSetupIntent:with:returnURL:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleNextAction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forSetupIntent","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","text":"STPAuthenticationContext","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments49STPPaymentHandlerActionSetupIntentCompletionBlocka","text":"STPPaymentHandlerActionSetupIntentCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"deprecated":true,"type":"topic","url":"\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(forsetupintent:with:returnurl:completion:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[],"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"handleNextActionForSetupIntent:withAuthenticationContext:returnURL:completion:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleNextActionForSetupIntent:withAuthenticationContext:returnURL:completion:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"handleNextActionForSetupIntent:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"setupIntentClientSecret"},{"kind":"text","text":" "},{"kind":"identifier","text":"withAuthenticationContext:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@StripePayments@objc(pl)STPAuthenticationContext","kind":"typeIdentifier","text":"id<STPAuthenticationContext>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"authenticationContext"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnURL:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"returnURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^)("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus","text":"STPPaymentHandlerActionStatus"},{"kind":"text","text":" "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"text":"STPSetupIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent"},{"kind":"text","text":" *"},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" *"},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentHandlerActionStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/fragments"},{"value":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/navigatorTitle"},{"value":"STPAuthenticationContext","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPAuthenticationContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/navigatorTitle","value":[{"kind":"identifier","text":"STPAuthenticationContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/title","value":"STPPaymentHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title","value":"STPSetupIntent"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments","value":[{"kind":"identifier","text":"STPSetupIntent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle","value":[{"kind":"identifier","text":"STPSetupIntent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1handleNextAction(forSetupIntent:with:returnURL:completion:)\/title","value":"handleNextActionForSetupIntent:withAuthenticationContext:returnURL:completion:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1handleNextAction(forSetupIntent:with:returnURL:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleNextActionForSetupIntent:withAuthenticationContext:returnURL:completion:"}]}]}]}