{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(setupintentclientsecret:authenticationcontext:returnurl:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(setupintentclientsecret:authenticationcontext:returnurl:completion:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(handleNextActionForSetupIntent:authenticationContext:returnURL:completion:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleNextAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"setupIntentClientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","text":"STPAuthenticationContext","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments49STPPaymentHandlerActionSetupIntentCompletionBlocka","text":"STPPaymentHandlerActionSetupIntentCompletionBlock","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionSetupIntentCompletionBlock"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The client secret of the SetupIntent to handle next actions for."}],"type":"paragraph"}],"name":"setupIntentClientSecret"},{"content":[{"inlineContent":[{"text":"The authentication context used to authenticate the SetupIntent.","type":"text"}],"type":"paragraph"}],"name":"authenticationContext"},{"content":[{"type":"paragraph","inlineContent":[{"text":"An optional URL to redirect your customer back to after they authenticate or cancel in a webview. This should match the returnURL you specified during SetupIntent confirmation.","type":"text"}]}],"name":"returnURL"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion block. If the status returned is "},{"type":"codeVoice","code":"STPPaymentHandlerActionStatusSucceeded"},{"type":"text","text":", the SetupIntent status will always be  STPSetupIntentStatusSucceeded."}]}],"name":"completion"}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleNextAction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"setupIntentClientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"authenticationContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPAuthenticationContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentHandlerActionSetupIntentCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments49STPPaymentHandlerActionSetupIntentCompletionBlocka"},{"text":")","kind":"text"}],"title":"handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:completion:)","externalID":"c:@M@StripePayments@objc(cs)STPPaymentHandler(im)handleNextActionForSetupIntent:authenticationContext:returnURL:completion:","navigatorTitle":[{"text":"handleNextActionForSetupIntent:authenticationContext:returnURL:completion:","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:completion:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","abstract":[{"text":"Handles any ","type":"text"},{"code":"nextAction","type":"codeVoice"},{"text":" required to authenticate the SetupIntent.","type":"text"},{"text":" ","type":"text"},{"text":"Call this method if you are confirming the SetupIntent on your backend and get a status of requires_action.","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:completion:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:completion:)","role":"symbol","title":"handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleNextAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"setupIntentClientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","text":"STPAuthenticationContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments49STPPaymentHandlerActionSetupIntentCompletionBlocka","text":"STPPaymentHandlerActionSetupIntentCompletionBlock"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"handleNextActionForSetupIntent:authenticationContext:returnURL:completion:"}],"type":"topic","kind":"symbol","abstract":[{"text":"Handles any ","type":"text"},{"code":"nextAction","type":"codeVoice"},{"text":" required to authenticate the SetupIntent.","type":"text"},{"text":" ","type":"text"},{"text":"Call this method if you are confirming the SetupIntent on your backend and get a status of requires_action.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(setupintentclientsecret:authenticationcontext:returnurl:completion:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandler"}],"role":"symbol","abstract":[{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" is a utility class that confirms PaymentIntents\/SetupIntents and handles any authentication required, such as 3DS1\/3DS2 for Strong Customer Authentication."},{"type":"text","text":" "},{"type":"text","text":"It can present authentication UI on top of your app or redirect users out of your app (to e.g. their banking app)."}],"url":"\/documentation\/stripepayments\/stppaymenthandler","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandler"}],"title":"STPPaymentHandler"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionStatus":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandleractionstatus","title":"STPPaymentHandlerActionStatus","abstract":[{"code":"STPPaymentHandlerActionStatus","type":"codeVoice"},{"text":" represents the possible outcomes of requesting an action by ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":". An action could be confirming and\/or handling the next action for a PaymentIntent.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionSetupIntentCompletionBlock":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerActionSetupIntentCompletionBlock"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandleractionsetupintentcompletionblock","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionSetupIntentCompletionBlock","abstract":[{"text":"Completion block typedef for use in ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"text":" methods for Setup Intents.","type":"text"}],"title":"STPPaymentHandlerActionSetupIntentCompletionBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandlerActionSetupIntentCompletionBlock"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintent","abstract":[{"type":"text","text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments."}],"title":"STPSetupIntent","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntent","kind":"identifier"}],"navigatorTitle":[{"text":"STPSetupIntent","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","type":"topic","navigatorTitle":[{"text":"STPAuthenticationContext","kind":"identifier"}],"abstract":[{"code":"STPAuthenticationContext","type":"codeVoice"},{"type":"text","text":" provides information required to present authentication challenges"},{"type":"text","text":" "},{"type":"text","text":"to a user."}],"title":"STPAuthenticationContext","role":"symbol","url":"\/documentation\/stripepayments\/stpauthenticationcontext","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAuthenticationContext","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"handleNextActionForSetupIntent:authenticationContext:returnURL:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleNextActionForSetupIntent:authenticationContext:returnURL:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"handleNextActionForSetupIntent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"setupIntentClientSecret"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationContext:"},{"kind":"text","text":"("},{"text":"id<STPAuthenticationContext>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@StripePayments@objc(pl)STPAuthenticationContext"},{"text":") ","kind":"text"},{"text":"authenticationContext","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"returnURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^)("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"STPPaymentHandlerActionStatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus"},{"kind":"text","text":" "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"STPSetupIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The client secret of the SetupIntent to handle next actions for."}]}],"name":"setupIntentClientSecret"},{"content":[{"inlineContent":[{"type":"text","text":"The authentication context used to authenticate the SetupIntent."}],"type":"paragraph"}],"name":"authenticationContext"},{"content":[{"inlineContent":[{"type":"text","text":"An optional URL to redirect your customer back to after they authenticate or cancel in a webview. This should match the returnURL you specified during SetupIntent confirmation."}],"type":"paragraph"}],"name":"returnURL"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion block. If the status returned is "},{"type":"codeVoice","code":"STPPaymentHandlerActionStatusSucceeded"},{"type":"text","text":", the SetupIntent status will always be  STPSetupIntentStatusSucceeded."}]}],"name":"completion"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:completion:)\/title","value":"handleNextActionForSetupIntent:authenticationContext:returnURL:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleNextActionForSetupIntent:authenticationContext:returnURL:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/title","value":"STPPaymentHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/navigatorTitle","value":[{"text":"STPPaymentHandler","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/title","value":"STPPaymentHandlerActionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/fragments","value":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title","value":"STPSetupIntent"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments","value":[{"kind":"identifier","text":"STPSetupIntent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle","value":[{"text":"STPSetupIntent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/title","value":"STPAuthenticationContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/fragments","value":[{"text":"STPAuthenticationContext","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/navigatorTitle","value":[{"text":"STPAuthenticationContext","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}