{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"StripePayments"}],"title":"handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleNextAction","kind":"identifier"},{"kind":"text","text":"("},{"text":"setupIntentClientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"authenticationContext","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","text":"STPAuthenticationContext","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?) "},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> ("},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus","text":"STPPaymentHandlerActionStatus","kind":"typeIdentifier"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent","text":"STPSetupIntent","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?)"}],"externalID":"s:14StripePayments17STPPaymentHandlerC16handleNextAction23setupIntentClientSecret21authenticationContext9returnURLAA0cdG6StatusO_AA08STPSetupI0CSgs5Error_pSgtSS_AA017STPAuthenticationM0_pSSSgtYaF","role":"symbol","roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"handleNextAction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"setupIntentClientSecret","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"authenticationContext","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","kind":"typeIdentifier","text":"STPAuthenticationContext","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"kind":"text","text":", "},{"text":"returnURL","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" -> (","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus","kind":"typeIdentifier","text":"STPPaymentHandlerActionStatus","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"STPSetupIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"languages":["swift"]}]},{"parameters":[{"name":"setupIntentClientSecret","content":[{"type":"paragraph","inlineContent":[{"text":"The client secret of the SetupIntent to handle next actions for.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The authentication context used to authenticate the SetupIntent.","type":"text"}]}],"name":"authenticationContext"},{"content":[{"type":"paragraph","inlineContent":[{"text":"An optional URL to redirect your customer back to after they authenticate or cancel in a webview. This should match the returnURL you specified during SetupIntent confirmation.","type":"text"}]}],"name":"returnURL"}],"kind":"parameters"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(setupintentclientsecret:authenticationcontext:returnurl:)"]}],"abstract":[{"type":"text","text":"Handles any "},{"code":"nextAction","type":"codeVoice"},{"type":"text","text":" required to authenticate the SetupIntent."},{"type":"text","text":" "},{"text":"Call this method if you are confirming the SetupIntent on your backend and get a status of requires_action.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:)"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:)":{"url":"\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(setupintentclientsecret:authenticationcontext:returnurl:)","abstract":[{"text":"Handles any ","type":"text"},{"type":"codeVoice","code":"nextAction"},{"text":" required to authenticate the SetupIntent.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Call this method if you are confirming the SetupIntent on your backend and get a status of requires_action."}],"title":"handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleNextAction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"setupIntentClientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationContext"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","text":"STPAuthenticationContext","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> (","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus","kind":"typeIdentifier","text":"STPPaymentHandlerActionStatus"},{"text":", ","kind":"text"},{"text":"STPSetupIntent","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionStatus":{"title":"STPPaymentHandlerActionStatus","url":"\/documentation\/stripepayments\/stppaymenthandleractionstatus","abstract":[{"code":"STPPaymentHandlerActionStatus","type":"codeVoice"},{"text":" represents the possible outcomes of requesting an action by ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"text":". An action could be confirming and\/or handling the next action for a PaymentIntent.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}],"role":"symbol","navigatorTitle":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandler"}],"title":"STPPaymentHandler","abstract":[{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" is a utility class that confirms PaymentIntents\/SetupIntents and handles any authentication required, such as 3DS1\/3DS2 for Strong Customer Authentication."},{"text":" ","type":"text"},{"type":"text","text":"It can present authentication UI on top of your app or redirect users out of your app (to e.g. their banking app)."}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymenthandler","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentHandler","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","abstract":[{"text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPSetupIntent","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsetupintent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntent"}],"title":"STPSetupIntent","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext":{"navigatorTitle":[{"kind":"identifier","text":"STPAuthenticationContext"}],"title":"STPAuthenticationContext","abstract":[{"code":"STPAuthenticationContext","type":"codeVoice"},{"type":"text","text":" provides information required to present authentication challenges"},{"type":"text","text":" "},{"text":"to a user.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stpauthenticationcontext","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"STPAuthenticationContext","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPPaymentHandlerActionStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/fragments","value":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}]},{"op":"replace","value":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/navigatorTitle"},{"value":"STPPaymentHandler","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/title","op":"replace"},{"op":"replace","value":[{"text":"STPPaymentHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title","op":"replace","value":"STPSetupIntent"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments","op":"replace","value":[{"text":"STPSetupIntent","kind":"identifier"}]},{"value":[{"text":"STPSetupIntent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle"},{"value":"STPAuthenticationContext","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/title"},{"op":"replace","value":[{"text":"STPAuthenticationContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/fragments"},{"value":[{"text":"STPAuthenticationContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/navigatorTitle"}]}]}