{"metadata":{"title":"handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:completion:)","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"handleNextAction","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"paymentIntentClientSecret"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"authenticationContext","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","text":"STPAuthenticationContext","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"returnURL","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"handleNextActionForPaymentIntent:authenticationContext:returnURL:completion:","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentHandler(im)handleNextActionForPaymentIntent:authenticationContext:returnURL:completion:","role":"symbol"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:completion:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(paymentintentclientsecret:authenticationcontext:returnurl:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(paymentintentclientsecret:authenticationcontext:returnurl:completion:)"]}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Handles any ","type":"text"},{"code":"nextAction","type":"codeVoice"},{"type":"text","text":" required to authenticate the PaymentIntent."},{"text":" ","type":"text"},{"type":"text","text":"Call this method if you are using server-side confirmation."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(handleNextActionForPaymentIntent:authenticationContext:returnURL:completion:) "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleNextAction","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"paymentIntentClientSecret"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"authenticationContext","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","text":"STPAuthenticationContext","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionPaymentIntentCompletionBlock","preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"paymentIntentClientSecret","content":[{"type":"paragraph","inlineContent":[{"text":"The client secret of the PaymentIntent to handle next actions for.","type":"text"}]}]},{"name":"authenticationContext","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The authentication context used to authenticate the payment."}]}]},{"name":"returnURL","content":[{"inlineContent":[{"text":"An optional URL to redirect your customer back to after they authenticate or cancel in a webview. This should match the returnURL you specified during PaymentIntent confirmation.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion block. If the status returned is "},{"code":"STPPaymentHandlerActionStatusSucceeded","type":"codeVoice"},{"type":"text","text":", the PaymentIntent status is not necessarily STPPaymentIntentStatusSucceeded (e.g. some bank payment methods take days before the PaymentIntent succeeds)."}]}],"name":"completion"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntent"}],"title":"STPPaymentIntent","abstract":[{"text":"A PaymentIntent tracks the process of collecting a payment from your customer.","type":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentintent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentIntent","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext":{"navigatorTitle":[{"text":"STPAuthenticationContext","kind":"identifier"}],"type":"topic","abstract":[{"code":"STPAuthenticationContext","type":"codeVoice"},{"type":"text","text":" provides information required to present authentication challenges"},{"text":" ","type":"text"},{"text":"to a user.","type":"text"}],"title":"STPAuthenticationContext","kind":"symbol","url":"\/documentation\/stripepayments\/stpauthenticationcontext","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPAuthenticationContext","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionPaymentIntentCompletionBlock":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionPaymentIntentCompletionBlock","navigatorTitle":[{"text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"identifier"}],"title":"STPPaymentHandlerActionPaymentIntentCompletionBlock","abstract":[{"text":"Completion block typedef for use in ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" methods for Payment Intents."}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandleractionpaymentintentcompletionblock","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionStatus":{"navigatorTitle":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"type":"topic","abstract":[{"type":"codeVoice","code":"STPPaymentHandlerActionStatus"},{"type":"text","text":" represents the possible outcomes of requesting an action by "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":". An action could be confirming and\/or handling the next action for a PaymentIntent."}],"title":"STPPaymentHandlerActionStatus","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandleractionstatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:completion:)":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:completion:)","navigatorTitle":[{"text":"handleNextActionForPaymentIntent:authenticationContext:returnURL:completion:","kind":"identifier"}],"title":"handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:completion:)","abstract":[{"type":"text","text":"Handles any "},{"code":"nextAction","type":"codeVoice"},{"type":"text","text":" required to authenticate the PaymentIntent."},{"type":"text","text":" "},{"type":"text","text":"Call this method if you are using server-side confirmation."}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(paymentintentclientsecret:authenticationcontext:returnurl:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"handleNextAction","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"paymentIntentClientSecret"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"authenticationContext","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","text":"STPAuthenticationContext","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler":{"navigatorTitle":[{"text":"STPPaymentHandler","kind":"identifier"}],"type":"topic","abstract":[{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" is a utility class that confirms PaymentIntents\/SetupIntents and handles any authentication required, such as 3DS1\/3DS2 for Strong Customer Authentication.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It can present authentication UI on top of your app or redirect users out of your app (to e.g. their banking app)."}],"title":"STPPaymentHandler","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandler","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentHandler"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"handleNextActionForPaymentIntent:authenticationContext:returnURL:completion:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"handleNextActionForPaymentIntent:authenticationContext:returnURL:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"handleNextActionForPaymentIntent:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"paymentIntentClientSecret"},{"kind":"text","text":" "},{"text":"authenticationContext:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@StripePayments@objc(pl)STPAuthenticationContext","text":"id<STPAuthenticationContext>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"authenticationContext","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"returnURL:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"returnURL","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus","text":"STPPaymentHandlerActionStatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","text":"STPPaymentIntent"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"paymentIntentClientSecret","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The client secret of the PaymentIntent to handle next actions for."}]}]},{"name":"authenticationContext","content":[{"inlineContent":[{"type":"text","text":"The authentication context used to authenticate the payment."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"An optional URL to redirect your customer back to after they authenticate or cancel in a webview. This should match the returnURL you specified during PaymentIntent confirmation."}],"type":"paragraph"}],"name":"returnURL"},{"content":[{"inlineContent":[{"text":"The completion block. If the status returned is ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandlerActionStatusSucceeded"},{"type":"text","text":", the PaymentIntent status is not necessarily STPPaymentIntentStatusSucceeded (e.g. some bank payment methods take days before the PaymentIntent succeeds)."}],"type":"paragraph"}],"name":"completion"}]}},{"value":"STPPaymentIntent","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntent"}]},{"value":[{"kind":"identifier","text":"STPPaymentIntent"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/title","value":"STPAuthenticationContext","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/fragments","value":[{"text":"STPAuthenticationContext","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"STPAuthenticationContext"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/navigatorTitle"},{"op":"replace","value":"STPPaymentHandlerActionStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/title"},{"value":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/fragments"},{"value":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:completion:)\/title","value":"handleNextActionForPaymentIntent:authenticationContext:returnURL:completion:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"handleNextActionForPaymentIntent:authenticationContext:returnURL:completion:","kind":"identifier"}],"op":"replace"},{"value":"STPPaymentHandler","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/fragments","value":[{"text":"STPPaymentHandler","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentHandler","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}