{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/safariViewControllerDidFinish(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":":nodoc:"}],"metadata":{"navigatorTitle":[{"text":"safariViewControllerDidFinish:","kind":"identifier"}],"role":"symbol","externalID":"c:@CM@StripePayments@objc(cs)STPPaymentHandler(im)safariViewControllerDidFinish:","extendedModule":"StripePayments","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"safariViewControllerDidFinish","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SFSafariViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SFSafariViewController"},{"text":")","kind":"text"}],"modules":[{"name":"StripePayments"}],"title":"safariViewControllerDidFinish(_:)","symbolKind":"method","roleHeading":"Instance Method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"safariViewControllerDidFinish","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SFSafariViewController","text":"SFSafariViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymenthandler\/safariviewcontrollerdidfinish(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymenthandler\/safariviewcontrollerdidfinish(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler":{"title":"STPPaymentHandler","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandler","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymenthandler","navigatorTitle":[{"text":"STPPaymentHandler","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" is a utility class that confirms PaymentIntents\/SetupIntents and handles any authentication required, such as 3DS1\/3DS2 for Strong Customer Authentication."},{"type":"text","text":" "},{"type":"text","text":"It can present authentication UI on top of your app or redirect users out of your app (to e.g. their banking app)."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/safariViewControllerDidFinish(_:)":{"title":"safariViewControllerDidFinish(_:)","url":"\/documentation\/stripepayments\/stppaymenthandler\/safariviewcontrollerdidfinish(_:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/safariViewControllerDidFinish(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"safariViewControllerDidFinish:"}],"abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"safariViewControllerDidFinish"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)SFSafariViewController","kind":"typeIdentifier","text":"SFSafariViewController"},{"kind":"text","text":")"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"safariViewControllerDidFinish:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"safariViewControllerDidFinish:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"safariViewControllerDidFinish:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SFSafariViewController","text":"SFSafariViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/title","op":"replace","value":"STPPaymentHandler"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandler"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandler"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1safariViewControllerDidFinish(_:)\/title","op":"replace","value":"safariViewControllerDidFinish:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1safariViewControllerDidFinish(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"safariViewControllerDidFinish:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}