{"topicSections":[{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/safariViewControllerDidFinish(_:)"],"title":"Instance Methods"}],"kind":"article","metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"SFSafariViewControllerDelegate Implementations","modules":[{"name":"StripePayments"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymenthandler\/sfsafariviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler\/sfsafariviewcontrollerdelegate-implementations"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/SFSafariViewControllerDelegate-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandler","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentHandler","kind":"identifier"}],"abstract":[{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" is a utility class that confirms PaymentIntents\/SetupIntents and handles any authentication required, such as 3DS1\/3DS2 for Strong Customer Authentication."},{"text":" ","type":"text"},{"type":"text","text":"It can present authentication UI on top of your app or redirect users out of your app (to e.g. their banking app)."}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandler"}],"title":"STPPaymentHandler","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/safariViewControllerDidFinish(_:)":{"url":"\/documentation\/stripepayments\/stppaymenthandler\/safariviewcontrollerdidfinish(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"safariViewControllerDidFinish","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SFSafariViewController","text":"SFSafariViewController"},{"text":")","kind":"text"}],"abstract":[{"text":":nodoc:","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"safariViewControllerDidFinish:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/safariViewControllerDidFinish(_:)","role":"symbol","title":"safariViewControllerDidFinish(_:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/safariViewControllerDidFinish(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":"STPPaymentHandler","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/title"},{"op":"replace","value":[{"text":"STPPaymentHandler","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentHandler"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1safariViewControllerDidFinish(_:)\/title","value":"safariViewControllerDidFinish:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"safariViewControllerDidFinish:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1safariViewControllerDidFinish(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}