{"abstract":[{"text":"The globally shared instance of ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"text":".","type":"text"}],"sections":[],"metadata":{"title":"shared()","externalID":"c:@M@StripePayments@objc(cs)STPPaymentHandler(cm)shared","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentHandler","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentHandler"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Type Method","navigatorTitle":[{"text":"shared","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"text":"() -> ","kind":"text"},{"text":"STPPaymentHandler","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentHandler"}],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler\/shared()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler\/shared()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/shared()"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/shared()":{"url":"\/documentation\/stripepayments\/stppaymenthandler\/shared()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"STPPaymentHandler","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentHandler"}],"title":"shared()","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shared"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/shared()","abstract":[{"text":"The globally shared instance of ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":"."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler":{"role":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandler","title":"STPPaymentHandler","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler","kind":"symbol","abstract":[{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" is a utility class that confirms PaymentIntents\/SetupIntents and handles any authentication required, such as 3DS1\/3DS2 for Strong Customer Authentication."},{"text":" ","type":"text"},{"text":"It can present authentication UI on top of your app or redirect users out of your app (to e.g. their banking app).","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentHandler"}],"navigatorTitle":[{"text":"STPPaymentHandler","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"shared","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"shared"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"STPPaymentHandler","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentHandler"},{"text":" *) ","kind":"text"},{"text":"shared","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1shared()\/title","op":"replace","value":"shared"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1shared()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"shared"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/title","value":"STPPaymentHandler"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/fragments","value":[{"text":"STPPaymentHandler","kind":"identifier"}],"op":"replace"},{"value":[{"text":"STPPaymentHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/navigatorTitle"}]}]}