{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/threeDSCustomizationSettings","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler"]]},"abstract":[{"type":"text","text":"Customizable settings to use when performing 3DS2 authentication."},{"type":"text","text":" "},{"text":"Note: Configure this before calling any methods.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"STPThreeDSCustomizationSettings()"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"threeDSCustomizationSettings","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSCustomizationSettings","kind":"typeIdentifier","text":"STPThreeDSCustomizationSettings","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymenthandler\/threedscustomizationsettings"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler\/threedscustomizationsettings"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"threeDSCustomizationSettings"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPThreeDSCustomizationSettings","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSCustomizationSettings"}],"title":"threeDSCustomizationSettings","externalID":"c:@M@StripePayments@objc(cs)STPPaymentHandler(py)threeDSCustomizationSettings","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"threeDSCustomizationSettings","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property"},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandler"}],"role":"symbol","title":"STPPaymentHandler","abstract":[{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" is a utility class that confirms PaymentIntents\/SetupIntents and handles any authentication required, such as 3DS1\/3DS2 for Strong Customer Authentication."},{"text":" ","type":"text"},{"type":"text","text":"It can present authentication UI on top of your app or redirect users out of your app (to e.g. their banking app)."}],"url":"\/documentation\/stripepayments\/stppaymenthandler","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler","navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandler"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/threeDSCustomizationSettings":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"threeDSCustomizationSettings"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSCustomizationSettings","kind":"typeIdentifier","text":"STPThreeDSCustomizationSettings"}],"abstract":[{"type":"text","text":"Customizable settings to use when performing 3DS2 authentication."},{"type":"text","text":" "},{"type":"text","text":"Note: Configure this before calling any methods."},{"type":"text","text":" "},{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"STPThreeDSCustomizationSettings()"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/threeDSCustomizationSettings","url":"\/documentation\/stripepayments\/stppaymenthandler\/threedscustomizationsettings","kind":"symbol","navigatorTitle":[{"text":"threeDSCustomizationSettings","kind":"identifier"}],"type":"topic","title":"threeDSCustomizationSettings"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationSettings":{"url":"\/documentation\/stripepayments\/stpthreedscustomizationsettings","kind":"symbol","role":"symbol","type":"topic","title":"STPThreeDSCustomizationSettings","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPThreeDSCustomizationSettings"}],"navigatorTitle":[{"text":"STPThreeDSCustomizationSettings","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"STPThreeDSCustomizationSettings"},{"text":" provides customization options for 3DS2 authentication flows in your app.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"threeDSCustomizationSettings","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"threeDSCustomizationSettings","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSCustomizationSettings","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings","text":"STPThreeDSCustomizationSettings"},{"kind":"text","text":" * "},{"text":"threeDSCustomizationSettings","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPPaymentHandler","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandler"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentHandler"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1threeDSCustomizationSettings\/title","value":"threeDSCustomizationSettings"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1threeDSCustomizationSettings\/fragments","value":[{"text":"threeDSCustomizationSettings","kind":"identifier"}],"op":"replace"},{"value":"STPThreeDSCustomizationSettings","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings\/fragments","value":[{"kind":"identifier","text":"STPThreeDSCustomizationSettings"}]},{"value":[{"text":"STPThreeDSCustomizationSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings\/navigatorTitle"}]}]}