{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/SwiftUICore\/View\/paymentConfirmationSheet(isConfirmingPayment:paymentIntentParams:onCompletion:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/swiftuicore\/view\/paymentconfirmationsheet(isconfirmingpayment:paymentintentparams:oncompletion:)"]}],"metadata":{"role":"symbol","symbolKind":"method","externalID":"s:7SwiftUI4ViewP14StripePaymentsE24paymentConfirmationSheet19isConfirmingPayment0F12IntentParams12onCompletionQrAA7BindingVySbG_AD010STPPaymentl7ConfirmM0CyAD0Q19HandlerActionStatusO_AD0qL0CSgSo7NSErrorCSgtctF","modules":[{"relatedModules":["SwiftUICore"],"name":"StripePayments"}],"extendedModule":"SwiftUICore","roleHeading":"Instance Method","title":"paymentConfirmationSheet(isConfirmingPayment:paymentIntentParams:onCompletion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentConfirmationSheet"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isConfirmingPayment"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI7BindingV","kind":"typeIdentifier","text":"Binding"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"paymentIntentParams"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams","kind":"typeIdentifier","text":"STPPaymentIntentConfirmParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onCompletion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka","kind":"typeIdentifier","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier","text":"View"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/SwiftUICore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/SwiftUICore\/View"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentConfirmationSheet"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isConfirmingPayment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"paymentIntentParams"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams","text":"STPPaymentIntentConfirmParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onCompletion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"},{"kind":"text","text":"\n"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A binding to whether the payment is being confirmed. This will present a sheet if needed. It will be updated to "},{"code":"false","type":"codeVoice"},{"type":"text","text":" after performing the payment confirmation."}],"type":"paragraph"}],"name":"isConfirmingPayment"},{"content":[{"inlineContent":[{"text":"A PaymentIntentParams to confirm.","type":"text"}],"type":"paragraph"}],"name":"paymentIntentParams"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Called with the result of the payment after the payment confirmation is done and the sheet (if any) is dismissed.","type":"text"}]}],"name":"onCompletion"}],"kind":"parameters"}],"sections":[],"abstract":[{"type":"text","text":"Confirm the payment, presenting a sheet for the user to confirm their payment if needed."}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/SwiftUICore/View/paymentConfirmationSheet(isConfirmingPayment:paymentIntentParams:onCompletion:)":{"role":"symbol","title":"paymentConfirmationSheet(isConfirmingPayment:paymentIntentParams:onCompletion:)","abstract":[{"text":"Confirm the payment, presenting a sheet for the user to confirm their payment if needed.","type":"text"}],"url":"\/documentation\/stripepayments\/swiftuicore\/view\/paymentconfirmationsheet(isconfirmingpayment:paymentintentparams:oncompletion:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/SwiftUICore\/View\/paymentConfirmationSheet(isConfirmingPayment:paymentIntentParams:onCompletion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentConfirmationSheet","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isConfirmingPayment","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"paymentIntentParams","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams","text":"STPPaymentIntentConfirmParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onCompletion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/SwiftUICore":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/SwiftUICore","abstract":[],"title":"SwiftUICore","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments\/swiftuicore"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/SwiftUICore/View":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"View"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/SwiftUICore\/View","title":"View","kind":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"role":"symbol","url":"\/documentation\/stripepayments\/swiftuicore\/view"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams":{"abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"type":"text","text":" "},{"type":"text","text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it."},{"type":"text","text":" "},{"type":"text","text":"That PaymentMethod or Source can either be:"}],"title":"STPPaymentIntentConfirmParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionPaymentIntentCompletionBlock":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Completion block typedef for use in "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" methods for Payment Intents."}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock"}],"url":"\/documentation\/stripepayments\/stppaymenthandleractionpaymentintentcompletionblock","title":"STPPaymentHandlerActionPaymentIntentCompletionBlock","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionPaymentIntentCompletionBlock"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/title","op":"replace","value":"STPPaymentIntentConfirmParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/fragments","op":"replace","value":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}