{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupIntentConfirmationSheet"},{"text":"(","kind":"text"},{"text":"isConfirmingSetupIntent","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Binding","preciseIdentifier":"s:7SwiftUI7BindingV"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":">, "},{"text":"setupIntentParams","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","text":"STPSetupIntentConfirmParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onCompletion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionSetupIntentCompletionBlock","preciseIdentifier":"s:14StripePayments49STPPaymentHandlerActionSetupIntentCompletionBlocka","kind":"typeIdentifier","text":"STPPaymentHandlerActionSetupIntentCompletionBlock"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"},{"kind":"text","text":"\n"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A binding to whether the SetupIntent is being confirmed. This will present a sheet if needed. It will be updated to ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":" after performing the SetupIntent confirmation."}]}],"name":"isConfirmingSetupIntent"},{"name":"onCompletion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Called with the result of the SetupIntent confirmation after the confirmation is done and the sheet (if any) is dismissed."}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/SwiftUICore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/SwiftUICore\/View"]]},"metadata":{"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"StripePayments","relatedModules":["SwiftUICore"]}],"extendedModule":"SwiftUICore","externalID":"s:7SwiftUI4ViewP14StripePaymentsE28setupIntentConfirmationSheet017isConfirmingSetupG00fG6Params12onCompletionQrAA7BindingVySbG_AD08STPSetupg7ConfirmM0CyAD29STPPaymentHandlerActionStatusO_AD0qG0CSgSo7NSErrorCSgtctF","title":"setupIntentConfirmationSheet(isConfirmingSetupIntent:setupIntentParams:onCompletion:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupIntentConfirmationSheet"},{"kind":"text","text":"("},{"text":"isConfirmingSetupIntent","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":">, ","kind":"text"},{"text":"setupIntentParams","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams","kind":"typeIdentifier","text":"STPSetupIntentConfirmParams"},{"text":", ","kind":"text"},{"text":"onCompletion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14StripePayments49STPPaymentHandlerActionSetupIntentCompletionBlocka","kind":"typeIdentifier","text":"STPPaymentHandlerActionSetupIntentCompletionBlock"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/SwiftUICore\/View\/setupIntentConfirmationSheet(isConfirmingSetupIntent:setupIntentParams:onCompletion:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/swiftuicore\/view\/setupintentconfirmationsheet(isconfirmingsetupintent:setupintentparams:oncompletion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Confirm the SetupIntent, presenting a sheet for the user to confirm if needed.","type":"text"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/SwiftUICore/View":{"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/SwiftUICore\/View","url":"\/documentation\/stripepayments\/swiftuicore\/view","navigatorTitle":[{"kind":"identifier","text":"View"}],"abstract":[],"type":"topic","title":"View","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"abstract":[{"type":"text","text":"An object representing parameters to confirm a SetupIntent object."},{"type":"text","text":" "},{"text":"For example, you would confirm a SetupIntent when a customer hits the “Save” button on a payment method management view in your app.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the selected payment method does not require any additional steps from the customer, the SetupIntent’s status will transition to "},{"type":"codeVoice","code":"STPSetupIntentStatusSucceeded"},{"type":"text","text":".  Otherwise, it will transition to "},{"code":"STPSetupIntentStatusRequiresAction","type":"codeVoice"},{"text":", and suggest additional actions via ","type":"text"},{"code":"nextAction","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Instead of passing this to "},{"type":"codeVoice","code":"STPAPIClient.confirmSetupIntent(...)"},{"type":"text","text":" directly, we recommend using "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" to handle any additional steps for you."}],"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams","title":"STPSetupIntentConfirmParams","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/SwiftUICore/View/setupIntentConfirmationSheet(isConfirmingSetupIntent:setupIntentParams:onCompletion:)":{"abstract":[{"text":"Confirm the SetupIntent, presenting a sheet for the user to confirm if needed.","type":"text"}],"url":"\/documentation\/stripepayments\/swiftuicore\/view\/setupintentconfirmationsheet(isconfirmingsetupintent:setupintentparams:oncompletion:)","title":"setupIntentConfirmationSheet(isConfirmingSetupIntent:setupIntentParams:onCompletion:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setupIntentConfirmationSheet","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isConfirmingSetupIntent"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI7BindingV","kind":"typeIdentifier","text":"Binding"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":">, "},{"text":"setupIntentParams","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams","kind":"typeIdentifier","text":"STPSetupIntentConfirmParams"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onCompletion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments49STPPaymentHandlerActionSetupIntentCompletionBlocka","text":"STPPaymentHandlerActionSetupIntentCompletionBlock"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/SwiftUICore\/View\/setupIntentConfirmationSheet(isConfirmingSetupIntent:setupIntentParams:onCompletion:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/SwiftUICore":{"type":"topic","abstract":[],"kind":"symbol","role":"collection","title":"SwiftUICore","url":"\/documentation\/stripepayments\/swiftuicore","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/SwiftUICore"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionSetupIntentCompletionBlock":{"type":"topic","abstract":[{"type":"text","text":"Completion block typedef for use in "},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" methods for Setup Intents.","type":"text"}],"navigatorTitle":[{"text":"STPPaymentHandlerActionSetupIntentCompletionBlock","kind":"identifier"}],"kind":"symbol","title":"STPPaymentHandlerActionSetupIntentCompletionBlock","url":"\/documentation\/stripepayments\/stppaymenthandleractionsetupintentcompletionblock","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionSetupIntentCompletionBlock","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentHandlerActionSetupIntentCompletionBlock"}]}},"variantOverrides":[{"patch":[{"value":"STPSetupIntentConfirmParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/fragments"},{"value":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}