{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentactiontype\/customstringconvertible-implementations"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"StripePayments"}],"title":"CustomStringConvertible Implementations"},"kind":"article","topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/description"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/CustomStringConvertible-Implementations","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentActionType":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentActionType","kind":"identifier"}],"title":"STPPaymentIntentActionType","navigatorTitle":[{"text":"STPPaymentIntentActionType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentintentactiontype","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Types of Actions from a "},{"code":"STPPaymentIntent","type":"codeVoice"},{"text":", when the payment intent","type":"text"},{"text":" ","type":"text"},{"text":"status is ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntentStatusRequiresAction"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentActionType/description":{"title":"description","url":"\/documentation\/stripepayments\/stppaymentintentactiontype\/description","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/description","type":"topic","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentActionType\/title","value":"STPPaymentIntentActionType"},{"value":[{"kind":"identifier","text":"STPPaymentIntentActionType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentActionType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentActionType\/navigatorTitle","value":[{"text":"STPPaymentIntentActionType","kind":"identifier"}],"op":"replace"}]}]}