{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentactiontype\/redirecttourl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentactiontype\/redirecttourl"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType"]]},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/redirectToURL","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@StripePayments@E@STPPaymentIntentActionType@STPPaymentIntentActionTypeRedirectToURL","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"redirectToURL","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"role":"symbol","platforms":[{"message":"Use STPIntentActionType instead","unavailable":false,"deprecated":true,"beta":false,"renamed":"STPIntentActionType.redirectToURL"}],"navigatorTitle":[{"text":"STPPaymentIntentActionTypeRedirectToURL","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","title":"STPPaymentIntentActionType.redirectToURL"},"kind":"symbol","abstract":[{"type":"text","text":"The payment intent needs to be authorized by the user. We provide"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPRedirectContext"},{"type":"text","text":" to handle the url redirections necessary."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"redirectToURL","kind":"identifier"}]}],"kind":"declarations"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use STPIntentActionType instead"}],"type":"paragraph"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentActionType":{"kind":"symbol","title":"STPPaymentIntentActionType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType","type":"topic","abstract":[{"type":"text","text":"Types of Actions from a "},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":", when the payment intent"},{"type":"text","text":" "},{"type":"text","text":"status is "},{"type":"codeVoice","code":"STPPaymentIntentStatusRequiresAction"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentActionType"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentActionType"}],"url":"\/documentation\/stripepayments\/stppaymentintentactiontype"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentActionType/redirectToURL":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The payment intent needs to be authorized by the user. We provide"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPRedirectContext"},{"type":"text","text":" to handle the url redirections necessary."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/redirectToURL","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"redirectToURL"}],"deprecated":true,"url":"\/documentation\/stripepayments\/stppaymentintentactiontype\/redirecttourl","title":"STPPaymentIntentActionType.redirectToURL","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentActionTypeRedirectToURL"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentIntentActionTypeRedirectToURL"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentActionTypeRedirectToURL"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"STPPaymentIntentActionTypeRedirectToURL"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/deprecationSummary","value":[]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentActionType\/title","value":"STPPaymentIntentActionType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentActionType\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentActionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentActionType\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntentActionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentActionType~1redirectToURL\/title","value":"STPPaymentIntentActionTypeRedirectToURL"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentActionType~1redirectToURL\/fragments","value":[{"text":"STPPaymentIntentActionTypeRedirectToURL","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}