{"metadata":{"modules":[{"name":"StripePayments"}],"title":"STPPaymentIntentActionType.unknown","externalID":"c:@M@StripePayments@E@STPPaymentIntentActionType@STPPaymentIntentActionTypeUnknown","role":"symbol","roleHeading":"Case","platforms":[],"navigatorTitle":[{"text":"STPPaymentIntentActionTypeUnknown","kind":"identifier"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}]},"abstract":[{"type":"text","text":"This is an unknown action, that’s been added since the SDK"},{"type":"text","text":" "},{"type":"text","text":"was last updated."},{"type":"text","text":" "},{"type":"text","text":"Update your SDK, or use the "},{"type":"codeVoice","code":"nextAction.allResponseFields"},{"type":"text","text":" "},{"type":"text","text":"for custom handling."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType"]]},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use STPIntentActionType instead"}],"type":"paragraph"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentactiontype\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentactiontype\/unknown"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/unknown","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentActionType/unknown":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/unknown","abstract":[{"type":"text","text":"This is an unknown action, that’s been added since the SDK"},{"type":"text","text":" "},{"type":"text","text":"was last updated."},{"type":"text","text":" "},{"type":"text","text":"Update your SDK, or use the "},{"type":"codeVoice","code":"nextAction.allResponseFields"},{"type":"text","text":" "},{"type":"text","text":"for custom handling."}],"role":"symbol","title":"STPPaymentIntentActionType.unknown","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentintentactiontype\/unknown","navigatorTitle":[{"text":"STPPaymentIntentActionTypeUnknown","kind":"identifier"}],"type":"topic","deprecated":true,"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentActionType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentActionType"}],"abstract":[{"type":"text","text":"Types of Actions from a "},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":", when the payment intent"},{"type":"text","text":" "},{"type":"text","text":"status is "},{"type":"codeVoice","code":"STPPaymentIntentStatusRequiresAction"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentActionType"}],"title":"STPPaymentIntentActionType","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType","url":"\/documentation\/stripepayments\/stppaymentintentactiontype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"STPPaymentIntentActionTypeUnknown","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPPaymentIntentActionTypeUnknown","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"STPPaymentIntentActionTypeUnknown","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/deprecationSummary","value":[],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentActionType~1unknown\/title","value":"STPPaymentIntentActionTypeUnknown","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentActionType~1unknown\/fragments","value":[{"text":"STPPaymentIntentActionTypeUnknown","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentActionType\/title","value":"STPPaymentIntentActionType","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentActionType\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentActionType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentActionType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentActionType"}]}]}]}