{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions"]]},"sections":[],"abstract":[{"type":"text","text":"Initializer for "},{"type":"codeVoice","code":"STPConfirmUSBankAccountOptions"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconfirmusbankaccountoptions\/init(setupfutureusage:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconfirmusbankaccountoptions\/init(setupfutureusage:)"]}],"metadata":{"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"setupFutureUsage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage","text":"STPPaymentIntentSetupFutureUsage"},{"kind":"text","text":")"}],"title":"init(setupFutureUsage:)","navigatorTitle":[{"kind":"identifier","text":"initWithSetupFutureUsage:"}],"modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"init","externalID":"c:@M@StripePayments@objc(cs)STPConfirmUSBankAccountOptions(im)initWithSetupFutureUsage:"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions\/init(setupFutureUsage:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"setupFutureUsage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentSetupFutureUsage","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Indicates that you intend to make future payments with this payment method.","type":"text"}]}],"name":"setupFutureUsage"}],"kind":"parameters"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmUSBankAccountOptions":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmUSBankAccountOptions","kind":"identifier"}],"navigatorTitle":[{"text":"STPConfirmUSBankAccountOptions","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"STPConfirmUSBankAccountOptions","abstract":[{"text":"Options for US Bank Account Payment Methods during PaymentIntent or SetupIntent confirmation","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions","url":"\/documentation\/stripepayments\/stpconfirmusbankaccountoptions","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmUSBankAccountOptions/init(setupFutureUsage:)":{"abstract":[{"type":"text","text":"Initializer for "},{"type":"codeVoice","code":"STPConfirmUSBankAccountOptions"}],"title":"init(setupFutureUsage:)","role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmusbankaccountoptions\/init(setupfutureusage:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions\/init(setupFutureUsage:)","navigatorTitle":[{"kind":"identifier","text":"initWithSetupFutureUsage:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"setupFutureUsage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage","kind":"typeIdentifier","text":"STPPaymentIntentSetupFutureUsage"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage":{"title":"STPPaymentIntentSetupFutureUsage","abstract":[{"type":"text","text":"Indicates how you intend to use the payment method that your customer provides after the current payment completes."},{"type":"text","text":" "},{"type":"text","text":"If applicable, additional authentication may be performed to comply with regional legislation or network rules required to enable the usage of the same payment method for additional payments."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsage"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsage"}],"url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithSetupFutureUsage:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithSetupFutureUsage:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSetupFutureUsage:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage","text":"STPPaymentIntentSetupFutureUsage"},{"kind":"text","text":") "},{"kind":"internalParam","text":"setupFutureUsage"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"Indicates that you intend to make future payments with this payment method.","type":"text"}],"type":"paragraph"}],"name":"setupFutureUsage"}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions\/title","value":"STPConfirmUSBankAccountOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions\/fragments","value":[{"text":"STPConfirmUSBankAccountOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions\/navigatorTitle","value":[{"text":"STPConfirmUSBankAccountOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions~1init(setupFutureUsage:)\/title","value":"initWithSetupFutureUsage:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions~1init(setupFutureUsage:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSetupFutureUsage:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/title","value":"STPPaymentIntentSetupFutureUsage","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/fragments","value":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/navigatorTitle","value":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"op":"replace"}]}]}