{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions\/setupFutureUsage","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions"]]},"metadata":{"role":"symbol","modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","title":"setupFutureUsage","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupFutureUsage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage","text":"STPPaymentIntentSetupFutureUsage","kind":"typeIdentifier"}],"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPConfirmUSBankAccountOptions(py)setupFutureUsage","navigatorTitle":[{"kind":"identifier","text":"setupFutureUsage"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupFutureUsage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage","text":"STPPaymentIntentSetupFutureUsage","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If setup_future_usage is already set, you may only update the value from on_session to off_session."}]}],"kind":"content"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconfirmusbankaccountoptions\/setupfutureusage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconfirmusbankaccountoptions\/setupfutureusage"]}],"abstract":[{"type":"text","text":"Indicates that you intend to make future payments with this payment method."},{"type":"text","text":" "},{"type":"text","text":"Providing this parameter will attach the payment method to the PaymentIntent’s Customer, if present, after the Intent is confirmed and any required actions from the user are complete. If no Customer was provided, the payment method can still be attached to a Customer after the transaction completes."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage":{"type":"topic","abstract":[{"type":"text","text":"Indicates how you intend to use the payment method that your customer provides after the current payment completes."},{"type":"text","text":" "},{"type":"text","text":"If applicable, additional authentication may be performed to comply with regional legislation or network rules required to enable the usage of the same payment method for additional payments."}],"title":"STPPaymentIntentSetupFutureUsage","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsage"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsage"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage","url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmUSBankAccountOptions":{"title":"STPConfirmUSBankAccountOptions","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions","navigatorTitle":[{"text":"STPConfirmUSBankAccountOptions","kind":"identifier"}],"abstract":[{"text":"Options for US Bank Account Payment Methods during PaymentIntent or SetupIntent confirmation","type":"text"}],"url":"\/documentation\/stripepayments\/stpconfirmusbankaccountoptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmUSBankAccountOptions","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmUSBankAccountOptions/setupFutureUsage":{"type":"topic","title":"setupFutureUsage","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions\/setupFutureUsage","navigatorTitle":[{"text":"setupFutureUsage","kind":"identifier"}],"abstract":[{"text":"Indicates that you intend to make future payments with this payment method.","type":"text"},{"text":" ","type":"text"},{"text":"Providing this parameter will attach the payment method to the PaymentIntent’s Customer, if present, after the Intent is confirmed and any required actions from the user are complete. If no Customer was provided, the payment method can still be attached to a Customer after the transaction completes.","type":"text"}],"url":"\/documentation\/stripepayments\/stpconfirmusbankaccountoptions\/setupfutureusage","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupFutureUsage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentSetupFutureUsage","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"setupFutureUsage","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"setupFutureUsage","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentSetupFutureUsage","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"setupFutureUsage","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPPaymentIntentSetupFutureUsage","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/title"},{"value":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/fragments"},{"value":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/navigatorTitle"},{"value":"STPConfirmUSBankAccountOptions","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions\/title"},{"value":[{"text":"STPConfirmUSBankAccountOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions\/fragments"},{"value":[{"text":"STPConfirmUSBankAccountOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions\/navigatorTitle"},{"value":"setupFutureUsage","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions~1setupFutureUsage\/title"},{"value":[{"text":"setupFutureUsage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions~1setupFutureUsage\/fragments"}]}]}