{"identifier":{"url":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/apiClient","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apiClient"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPAPIClient","text":"STPAPIClient","kind":"typeIdentifier"}],"languages":["swift"]}]}],"abstract":[{"text":"The API Client to use to make requests.","type":"text"},{"type":"text","text":" "},{"text":"Defaults to ","type":"text"},{"code":"STPAPIClient.shared","type":"codeVoice"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext"]]},"variants":[{"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/apiclient"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/apiclient"]}],"metadata":{"modules":[{"name":"StripeApplePay"}],"role":"symbol","title":"apiClient","externalID":"c:@M@StripeApplePay@objc(cs)STPApplePayContext(py)apiClient","navigatorTitle":[{"text":"apiClient","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"apiClient","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","kind":"typeIdentifier"}]},"sections":[],"references":{"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/apiClient":{"role":"symbol","navigatorTitle":[{"text":"apiClient","kind":"identifier"}],"type":"topic","abstract":[{"text":"The API Client to use to make requests.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to ","type":"text"},{"code":"STPAPIClient.shared","type":"codeVoice"}],"title":"apiClient","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/apiClient","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/apiclient","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"apiClient","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","text":"STPAPIClient","kind":"typeIdentifier"}]},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay":{"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","type":"topic","kind":"symbol","url":"\/documentation\/stripeapplepay","abstract":[{"type":"text","text":"StripeApplePay is a lightweight Apple Pay SDK intended for building App Clips or other size-constrained apps."}],"role":"collection","title":"StripeApplePay"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext":{"url":"\/documentation\/stripeapplepay\/stpapplepaycontext","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPApplePayContext","kind":"identifier"}],"title":"STPApplePayContext","navigatorTitle":[{"kind":"identifier","text":"STPApplePayContext"}],"abstract":[{"text":"A helper class that implements Apple Pay.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Usage looks like this:"}]},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPAPIClient":{"abstract":[{"text":"A client for making connections to the Stripe API.","type":"text"}],"type":"topic","url":"\/documentation\/stripeapplepay\/stpapiclient","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPAPIClient","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAPIClient"}],"title":"STPAPIClient","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"apiClient"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"apiClient"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPAPIClient","text":"STPAPIClient","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"apiClient","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1apiClient\/title","value":"apiClient","op":"replace"},{"value":[{"text":"apiClient","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1apiClient\/fragments"},{"value":"STPApplePayContext","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/title","op":"replace"},{"value":[{"text":"STPApplePayContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPApplePayContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}