{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dismiss"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPVoidBlock","preciseIdentifier":"s:14StripeApplePay12STPVoidBlocka"},{"kind":"text","text":"?)"}],"role":"symbol","title":"dismiss(completion:)","roleHeading":"Instance Method","externalID":"c:@M@StripeApplePay@objc(cs)STPApplePayContext(im)dismissWithCompletion:","symbolKind":"method","navigatorTitle":[{"text":"dismissWithCompletion:","kind":"identifier"}],"modules":[{"name":"StripeApplePay"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/dismiss(completion:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(dismissWithCompletion:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripeApplePay12STPVoidBlocka","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPVoidBlock","text":"STPVoidBlock"},{"text":"? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Called after the Apple Pay sheet is dismissed."}]}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"content":[{"inlineContent":[{"text":"Does not call the ","type":"text"},{"type":"codeVoice","code":"applePayContext:didCompleteWithStatus:"},{"text":" delegate method.","type":"text"}],"type":"paragraph"}],"name":"Note","style":"note","type":"aside"},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"You must create a new instance of ApplePayContext after using this method."}],"type":"paragraph"}],"name":"Note","style":"note"}]}],"abstract":[{"text":"Dismisses the Apple Pay sheet.","type":"text"}],"variants":[{"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/dismiss(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/dismiss(completion:)"]}],"sections":[],"references":{"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/dismiss(completion:)":{"abstract":[{"type":"text","text":"Dismisses the Apple Pay sheet."}],"role":"symbol","type":"topic","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/dismiss(completion:)","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/dismiss(completion:)","title":"dismiss(completion:)","navigatorTitle":[{"kind":"identifier","text":"dismissWithCompletion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPVoidBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripeApplePay12STPVoidBlocka"},{"kind":"text","text":"?)"}],"kind":"symbol"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext":{"navigatorTitle":[{"text":"STPApplePayContext","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPApplePayContext"}],"url":"\/documentation\/stripeapplepay\/stpapplepaycontext","title":"STPApplePayContext","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A helper class that implements Apple Pay."},{"type":"text","text":" "},{"text":"Usage looks like this:","type":"text"}]},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay":{"kind":"symbol","abstract":[{"text":"StripeApplePay is a lightweight Apple Pay SDK intended for building App Clips or other size-constrained apps.","type":"text"}],"title":"StripeApplePay","type":"topic","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","url":"\/documentation\/stripeapplepay","role":"collection"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPVoidBlock":{"abstract":[{"text":"An empty block, called with no arguments, returning nothing.","type":"text"}],"url":"\/documentation\/stripeapplepay\/stpvoidblock","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"STPVoidBlock","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"STPVoidBlock","kind":"identifier"}],"title":"STPVoidBlock","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPVoidBlock"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"dismissWithCompletion:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissWithCompletion:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"dismissWithCompletion:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")()) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Called after the Apple Pay sheet is dismissed."}]}],"name":"completion"}]}},{"value":"dismissWithCompletion:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1dismiss(completion:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1dismiss(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"dismissWithCompletion:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"STPApplePayContext","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/title"},{"value":[{"kind":"identifier","text":"STPApplePayContext"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/navigatorTitle","value":[{"text":"STPApplePayContext","kind":"identifier"}],"op":"replace"}]}]}