{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/init(paymentrequest:delegate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/init(paymentrequest:delegate:)"]}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"paymentRequest","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PKPaymentRequest","preciseIdentifier":"c:objc(cs)PKPaymentRequest","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"_stpinternal_STPApplePayContextDelegateBase","preciseIdentifier":"c:@M@StripeApplePay@objc(pl)_stpinternal_STPApplePayContextDelegateBase","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"externalID":"c:@M@StripeApplePay@objc(cs)STPApplePayContext(im)initWithPaymentRequest:delegate:","modules":[{"name":"StripeApplePay"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPaymentRequest:delegate:"}],"title":"init(paymentRequest:delegate:)","symbolKind":"init","role":"symbol","roleHeading":"Initializer"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(initWithPaymentRequest:delegate:) "},{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"paymentRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKPaymentRequest","preciseIdentifier":"c:objc(cs)PKPaymentRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"_stpinternal_STPApplePayContextDelegateBase","preciseIdentifier":"c:@M@StripeApplePay@objc(pl)_stpinternal_STPApplePayContextDelegateBase"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"content":[{"inlineContent":[{"type":"text","text":"This may return nil if the request is invalid e.g. the user is restricted by parental controls, or can’t make payments on any of the request’s supported networks"}],"type":"paragraph"}],"style":"note","name":"Note","type":"aside"},{"content":[{"type":"paragraph","inlineContent":[{"text":"If using Swift, using ApplePayContextDelegate is recommended over STPApplePayContextDelegate.","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Parameters:"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"paymentRequest:      The payment request to use with Apple Pay.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"delegate:                    The delegate.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]}]}],"style":"note","name":"Note","type":"aside"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/init(paymentRequest:delegate:)"},"abstract":[{"text":"Initializes this class.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/init(paymentRequest:delegate:)":{"kind":"symbol","navigatorTitle":[{"text":"initWithPaymentRequest:delegate:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/init(paymentRequest:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"paymentRequest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKPaymentRequest","preciseIdentifier":"c:objc(cs)PKPaymentRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"_stpinternal_STPApplePayContextDelegateBase","preciseIdentifier":"c:@M@StripeApplePay@objc(pl)_stpinternal_STPApplePayContextDelegateBase"},{"kind":"text","text":"?)"}],"type":"topic","title":"init(paymentRequest:delegate:)","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/init(paymentrequest:delegate:)","abstract":[{"text":"Initializes this class.","type":"text"}]},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay":{"role":"collection","abstract":[{"type":"text","text":"StripeApplePay is a lightweight Apple Pay SDK intended for building App Clips or other size-constrained apps."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","url":"\/documentation\/stripeapplepay","title":"StripeApplePay","type":"topic"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext":{"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPApplePayContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPApplePayContext","kind":"identifier"}],"title":"STPApplePayContext","abstract":[{"text":"A helper class that implements Apple Pay.","type":"text"},{"text":" ","type":"text"},{"text":"Usage looks like this:","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/stripeapplepay\/stpapplepaycontext"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithPaymentRequest:delegate:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPaymentRequest:delegate:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPaymentRequest:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKPaymentRequest","preciseIdentifier":"c:objc(cs)PKPaymentRequest"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentRequest"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate:"},{"kind":"text","text":"("},{"text":"id<_stpinternal_STPApplePayContextDelegateBase>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@StripeApplePay@objc(pl)_stpinternal_STPApplePayContextDelegateBase"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1init(paymentRequest:delegate:)\/title","value":"initWithPaymentRequest:delegate:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1init(paymentRequest:delegate:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithPaymentRequest:delegate:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/title","value":"STPApplePayContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/fragments","value":[{"text":"STPApplePayContext","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/navigatorTitle","value":[{"kind":"identifier","text":"STPApplePayContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}