{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationController(_:didSelectShippingMethod:handler:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentAuthorizationController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PKPaymentAuthorizationController","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSelectShippingMethod","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"shippingMethod","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PKShippingMethod","preciseIdentifier":"c:objc(cs)PKShippingMethod","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"handler","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"PKPaymentRequestShippingMethodUpdate","preciseIdentifier":"c:objc(cs)PKPaymentRequestShippingMethodUpdate","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"PKPaymentAuthorizationControllerDelegate.paymentAuthorizationController(_:didSelectShippingMethod:handler:)"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentauthorizationcontroller(_:didselectshippingmethod:handler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentauthorizationcontroller(_:didselectshippingmethod:handler:)"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@M@StripeApplePay@objc(cs)STPApplePayContext(im)paymentAuthorizationController:didSelectShippingMethod:handler:","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","title":"paymentAuthorizationController(_:didSelectShippingMethod:handler:)","navigatorTitle":[{"kind":"identifier","text":"paymentAuthorizationController:didSelectShippingMethod:handler:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentAuthorizationController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKPaymentAuthorizationController","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectShippingMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKShippingMethod","preciseIdentifier":"c:objc(cs)PKShippingMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"PKPaymentRequestShippingMethodUpdate","preciseIdentifier":"c:objc(cs)PKPaymentRequestShippingMethodUpdate"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"modules":[{"name":"StripeApplePay"}]},"sections":[],"references":{"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext":{"url":"\/documentation\/stripeapplepay\/stpapplepaycontext","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPApplePayContext"}],"navigatorTitle":[{"kind":"identifier","text":"STPApplePayContext"}],"title":"STPApplePayContext","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext","abstract":[{"type":"text","text":"A helper class that implements Apple Pay."},{"type":"text","text":" "},{"type":"text","text":"Usage looks like this:"}],"type":"topic"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay":{"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","role":"collection","abstract":[{"text":"StripeApplePay is a lightweight Apple Pay SDK intended for building App Clips or other size-constrained apps.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripeapplepay","title":"StripeApplePay"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/paymentAuthorizationController(_:didSelectShippingMethod:handler:)":{"title":"paymentAuthorizationController(_:didSelectShippingMethod:handler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentAuthorizationController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PKPaymentAuthorizationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController"},{"text":", ","kind":"text"},{"text":"didSelectShippingMethod","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PKShippingMethod","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKShippingMethod"},{"text":", ","kind":"text"},{"text":"handler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"PKPaymentRequestShippingMethodUpdate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentRequestShippingMethodUpdate"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"navigatorTitle":[{"text":"paymentAuthorizationController:didSelectShippingMethod:handler:","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentauthorizationcontroller(_:didselectshippingmethod:handler:)","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationController(_:didSelectShippingMethod:handler:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"paymentAuthorizationController:didSelectShippingMethod:handler:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"paymentAuthorizationController:didSelectShippingMethod:handler:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"paymentAuthorizationController:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController","kind":"typeIdentifier","text":"PKPaymentAuthorizationController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectShippingMethod:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)PKShippingMethod","kind":"typeIdentifier","text":"PKShippingMethod"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"shippingMethod"},{"kind":"text","text":" "},{"kind":"identifier","text":"handler:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^)("},{"preciseIdentifier":"c:objc(cs)PKPaymentRequestShippingMethodUpdate","kind":"typeIdentifier","text":"PKPaymentRequestShippingMethodUpdate"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/title","value":"STPApplePayContext","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/fragments","value":[{"text":"STPApplePayContext","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/navigatorTitle","value":[{"kind":"identifier","text":"STPApplePayContext"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1paymentAuthorizationController(_:didSelectShippingMethod:handler:)\/title","value":"paymentAuthorizationController:didSelectShippingMethod:handler:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1paymentAuthorizationController(_:didSelectShippingMethod:handler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentAuthorizationController:didSelectShippingMethod:handler:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}