{"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(paymentAuthorizationController:didAuthorizePayment:handler:) "},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentAuthorizationController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController","kind":"typeIdentifier","text":"PKPaymentAuthorizationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didAuthorizePayment"},{"text":" ","kind":"text"},{"text":"payment","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)PKPayment","kind":"typeIdentifier","text":"PKPayment"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"handler"},{"kind":"text","text":" "},{"text":"completion","kind":"internalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"PKPaymentAuthorizationResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationResult"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentauthorizationcontroller(_:didauthorizepayment:handler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentauthorizationcontroller(_:didauthorizepayment:handler:)"]}],"abstract":[{"text":":nodoc:","type":"text"}],"metadata":{"navigatorTitle":[{"text":"paymentAuthorizationController:didAuthorizePayment:handler:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"paymentAuthorizationController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKPaymentAuthorizationController","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController"},{"kind":"text","text":", "},{"text":"didAuthorizePayment","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PKPayment","preciseIdentifier":"c:objc(cs)PKPayment","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"handler","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationResult","text":"PKPaymentAuthorizationResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"modules":[{"name":"StripeApplePay"}],"title":"paymentAuthorizationController(_:didAuthorizePayment:handler:)","externalID":"c:@M@StripeApplePay@objc(cs)STPApplePayContext(im)paymentAuthorizationController:didAuthorizePayment:handler:","symbolKind":"method","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationController(_:didAuthorizePayment:handler:)"},"references":{"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext","role":"symbol","url":"\/documentation\/stripeapplepay\/stpapplepaycontext","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPApplePayContext","kind":"identifier"}],"type":"topic","title":"STPApplePayContext","abstract":[{"text":"A helper class that implements Apple Pay.","type":"text"},{"text":" ","type":"text"},{"text":"Usage looks like this:","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPApplePayContext"}]},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/paymentAuthorizationController(_:didAuthorizePayment:handler:)":{"title":"paymentAuthorizationController(_:didAuthorizePayment:handler:)","abstract":[{"type":"text","text":":nodoc:"}],"type":"topic","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentauthorizationcontroller(_:didauthorizepayment:handler:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"paymentAuthorizationController","kind":"identifier"},{"kind":"text","text":"("},{"text":"PKPaymentAuthorizationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController"},{"kind":"text","text":", "},{"text":"didAuthorizePayment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PKPayment","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPayment"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": ("},{"text":"PKPaymentAuthorizationResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationResult"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationController(_:didAuthorizePayment:handler:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentAuthorizationController:didAuthorizePayment:handler:"}]},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay":{"type":"topic","url":"\/documentation\/stripeapplepay","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","abstract":[{"text":"StripeApplePay is a lightweight Apple Pay SDK intended for building App Clips or other size-constrained apps.","type":"text"}],"role":"collection","kind":"symbol","title":"StripeApplePay"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"paymentAuthorizationController:didAuthorizePayment:handler:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"paymentAuthorizationController:didAuthorizePayment:handler:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"paymentAuthorizationController:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKPaymentAuthorizationController","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didAuthorizePayment:"},{"kind":"text","text":"("},{"text":"PKPayment","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPayment"},{"text":" *) ","kind":"text"},{"text":"payment","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"handler:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"text":"PKPaymentAuthorizationResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationResult"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/title","value":"STPApplePayContext","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/fragments","value":[{"kind":"identifier","text":"STPApplePayContext"}]},{"value":[{"text":"STPApplePayContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1paymentAuthorizationController(_:didAuthorizePayment:handler:)\/title","value":"paymentAuthorizationController:didAuthorizePayment:handler:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentAuthorizationController:didAuthorizePayment:handler:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1paymentAuthorizationController(_:didAuthorizePayment:handler:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}