{"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-apple-pay\/s15BitwiseCopyableP","doc:\/\/com.stripe.stripe-apple-pay\/SQ","doc:\/\/com.stripe.stripe-apple-pay\/SH","doc:\/\/com.stripe.stripe-apple-pay\/s8SendableP"],"title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentStatus"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentstatus"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext"]]},"metadata":{"symbolKind":"enum","externalID":"s:14StripeApplePay08STPAppleC7ContextC13PaymentStatusO","navigatorTitle":[{"kind":"identifier","text":"PaymentStatus"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentStatus","kind":"identifier"}],"role":"symbol","modules":[{"name":"StripeApplePay"}],"title":"STPApplePayContext.PaymentStatus","roleHeading":"Enumeration"},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus\/error","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus\/success","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus\/userCancellation"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus\/Equatable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"An enum representing the status of a payment requested from the user."}],"identifier":{"url":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-apple-pay/s15BitwiseCopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/PaymentStatus/userCancellation":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus\/userCancellation","abstract":[{"type":"text","text":"The user cancelled the payment (for example, by hitting “cancel” in the Apple Pay dialog)."}],"url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentstatus\/usercancellation","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userCancellation","kind":"identifier"}],"role":"symbol","title":"STPApplePayContext.PaymentStatus.userCancellation"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/PaymentStatus/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus\/Equatable-Implementations","abstract":[],"url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentstatus\/equatable-implementations","kind":"article","role":"collectionGroup","title":"Equatable Implementations"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/PaymentStatus":{"kind":"symbol","abstract":[{"type":"text","text":"An enum representing the status of a payment requested from the user."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentStatus"}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus","title":"STPApplePayContext.PaymentStatus","navigatorTitle":[{"kind":"identifier","text":"PaymentStatus"}],"role":"symbol","type":"topic","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentstatus"},"doc://com.stripe.stripe-apple-pay/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/SH"},"doc://com.stripe.stripe-apple-pay/SQ":{"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay":{"kind":"symbol","title":"StripeApplePay","type":"topic","role":"collection","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","url":"\/documentation\/stripeapplepay","abstract":[{"type":"text","text":"StripeApplePay is a lightweight Apple Pay SDK intended for building App Clips or other size-constrained apps."}]},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/PaymentStatus/success":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentstatus\/success","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus\/success","abstract":[{"type":"text","text":"The payment succeeded."}],"title":"STPApplePayContext.PaymentStatus.success","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"}]},"doc://com.stripe.stripe-apple-pay/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/s8SendableP"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext":{"role":"symbol","title":"STPApplePayContext","url":"\/documentation\/stripeapplepay\/stpapplepaycontext","type":"topic","abstract":[{"text":"A helper class that implements Apple Pay.","type":"text"},{"text":" ","type":"text"},{"text":"Usage looks like this:","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPApplePayContext"}],"navigatorTitle":[{"kind":"identifier","text":"STPApplePayContext"}],"kind":"symbol"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/PaymentStatus/error":{"kind":"symbol","role":"symbol","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentstatus\/error","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"abstract":[{"text":"The payment failed due to an unforeseen error, such as the user’s Internet connection being offline.","type":"text"}],"title":"STPApplePayContext.PaymentStatus.error","type":"topic","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus\/error"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/title","value":"STPApplePayContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/fragments","value":[{"text":"STPApplePayContext","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/navigatorTitle","value":[{"text":"STPApplePayContext","kind":"identifier"}]}]}]}