{"metadata":{"role":"symbol","externalID":"c:@M@StripeApplePay@objc(cs)STPApplePayContext(im)paymentAuthorizationController:didSelectShippingContact:handler:","title":"paymentAuthorizationController(_:didSelectShippingContact:handler:)","navigatorTitle":[{"kind":"identifier","text":"paymentAuthorizationController:didSelectShippingContact:handler:"}],"symbolKind":"method","modules":[{"name":"StripeApplePay"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentAuthorizationController"},{"text":"(","kind":"text"},{"text":"PKPaymentAuthorizationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectShippingContact"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKContact","text":"PKContact"},{"text":", ","kind":"text"},{"text":"handler","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentRequestShippingContactUpdate","text":"PKPaymentRequestShippingContactUpdate"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"roleHeading":"Instance Method"},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationController(_:didSelectShippingContact:handler:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentAuthorizationController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController","text":"PKPaymentAuthorizationController"},{"text":", ","kind":"text"},{"text":"didSelectShippingContact","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"contact","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKContact","text":"PKContact","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"handler","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"text":"PKPaymentRequestShippingContactUpdate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentRequestShippingContactUpdate"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]}]}],"abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentauthorizationcontroller(_:didselectshippingcontact:handler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentauthorizationcontroller(_:didselectshippingcontact:handler:)"]}],"references":{"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay":{"title":"StripeApplePay","url":"\/documentation\/stripeapplepay","type":"topic","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","role":"collection","kind":"symbol","abstract":[{"text":"StripeApplePay is a lightweight Apple Pay SDK intended for building App Clips or other size-constrained apps.","type":"text"}]},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/paymentAuthorizationController(_:didSelectShippingContact:handler:)":{"navigatorTitle":[{"text":"paymentAuthorizationController:didSelectShippingContact:handler:","kind":"identifier"}],"type":"topic","role":"symbol","title":"paymentAuthorizationController(_:didSelectShippingContact:handler:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"paymentAuthorizationController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController","text":"PKPaymentAuthorizationController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSelectShippingContact"},{"kind":"text","text":": "},{"text":"PKContact","preciseIdentifier":"c:objc(cs)PKContact","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentRequestShippingContactUpdate","text":"PKPaymentRequestShippingContactUpdate"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"text":":nodoc:","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationController(_:didSelectShippingContact:handler:)","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentauthorizationcontroller(_:didselectshippingcontact:handler:)"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext":{"url":"\/documentation\/stripeapplepay\/stpapplepaycontext","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPApplePayContext","kind":"identifier"}],"kind":"symbol","title":"STPApplePayContext","abstract":[{"type":"text","text":"A helper class that implements Apple Pay."},{"type":"text","text":" "},{"text":"Usage looks like this:","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext","navigatorTitle":[{"text":"STPApplePayContext","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"paymentAuthorizationController:didSelectShippingContact:handler:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"paymentAuthorizationController:didSelectShippingContact:handler:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"paymentAuthorizationController:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController","text":"PKPaymentAuthorizationController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didSelectShippingContact:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PKContact","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKContact"},{"kind":"text","text":" *) "},{"text":"contact","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"handler:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKPaymentRequestShippingContactUpdate","text":"PKPaymentRequestShippingContactUpdate","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"paymentAuthorizationController:didSelectShippingContact:handler:","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1paymentAuthorizationController(_:didSelectShippingContact:handler:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentAuthorizationController:didSelectShippingContact:handler:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1paymentAuthorizationController(_:didSelectShippingContact:handler:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/title","value":"STPApplePayContext"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/fragments","value":[{"text":"STPApplePayContext","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/navigatorTitle","op":"replace","value":[{"text":"STPApplePayContext","kind":"identifier"}]}]}]}