{"identifier":{"url":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationControllerDidFinish(_:)","interfaceLanguage":"swift"},"abstract":[{"text":":nodoc:","type":"text"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext"]]},"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentAuthorizationControllerDidFinish"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKPaymentAuthorizationController","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController"},{"kind":"text","text":")"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"StripeApplePay"}],"externalID":"c:@M@StripeApplePay@objc(cs)STPApplePayContext(im)paymentAuthorizationControllerDidFinish:","navigatorTitle":[{"text":"paymentAuthorizationControllerDidFinish:","kind":"identifier"}],"title":"paymentAuthorizationControllerDidFinish(_:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentAuthorizationControllerDidFinish"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PKPaymentAuthorizationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentauthorizationcontrollerdidfinish(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentauthorizationcontrollerdidfinish(_:)"]}],"references":{"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay":{"title":"StripeApplePay","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","role":"collection","type":"topic","url":"\/documentation\/stripeapplepay","abstract":[{"type":"text","text":"StripeApplePay is a lightweight Apple Pay SDK intended for building App Clips or other size-constrained apps."}]},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPApplePayContext"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext","url":"\/documentation\/stripeapplepay\/stpapplepaycontext","navigatorTitle":[{"text":"STPApplePayContext","kind":"identifier"}],"title":"STPApplePayContext","role":"symbol","abstract":[{"type":"text","text":"A helper class that implements Apple Pay."},{"text":" ","type":"text"},{"text":"Usage looks like this:","type":"text"}]},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/paymentAuthorizationControllerDidFinish(_:)":{"navigatorTitle":[{"text":"paymentAuthorizationControllerDidFinish:","kind":"identifier"}],"url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentauthorizationcontrollerdidfinish(_:)","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationControllerDidFinish(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentAuthorizationControllerDidFinish","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PKPaymentAuthorizationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController"},{"text":")","kind":"text"}],"title":"paymentAuthorizationControllerDidFinish(_:)","abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"paymentAuthorizationControllerDidFinish:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"paymentAuthorizationControllerDidFinish:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"paymentAuthorizationControllerDidFinish:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController","text":"PKPaymentAuthorizationController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/title","value":"STPApplePayContext","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/fragments","op":"replace","value":[{"text":"STPApplePayContext","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/navigatorTitle","value":[{"kind":"identifier","text":"STPApplePayContext"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1paymentAuthorizationControllerDidFinish(_:)\/title","value":"paymentAuthorizationControllerDidFinish:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1paymentAuthorizationControllerDidFinish(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"paymentAuthorizationControllerDidFinish:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}