{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"StripeApplePay"}],"symbolKind":"method","title":"paymentAuthorizationController(_:didChangeCouponCode:handler:)","platforms":[{"deprecated":false,"name":"iOS","introducedAt":"15.0","beta":false,"unavailable":false},{"unavailable":false,"beta":false,"introducedAt":"15.0","deprecated":false,"name":"iPadOS"},{"introducedAt":"15.0","deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false}],"navigatorTitle":[{"text":"paymentAuthorizationController:didChangeCouponCode:handler:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@StripeApplePay@objc(cs)STPApplePayContext(im)paymentAuthorizationController:didChangeCouponCode:handler:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentAuthorizationController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController","text":"PKPaymentAuthorizationController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didChangeCouponCode"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"handler"},{"text":": (","kind":"text"},{"text":"PKPaymentRequestCouponCodeUpdate","preciseIdentifier":"c:objc(cs)PKPaymentRequestCouponCodeUpdate","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentAuthorizationController"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController","text":"PKPaymentAuthorizationController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didChangeCouponCode"},{"kind":"text","text":" "},{"text":"couponCode","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"handler"},{"text":" ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"PKPaymentRequestCouponCodeUpdate","preciseIdentifier":"c:objc(cs)PKPaymentRequestCouponCodeUpdate","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationController(_:didChangeCouponCode:handler:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext"]]},"abstract":[{"text":":nodoc:","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentauthorizationcontroller(_:didchangecouponcode:handler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentauthorizationcontroller(_:didchangecouponcode:handler:)"]}],"references":{"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext":{"navigatorTitle":[{"kind":"identifier","text":"STPApplePayContext"}],"type":"topic","url":"\/documentation\/stripeapplepay\/stpapplepaycontext","title":"STPApplePayContext","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext","abstract":[{"text":"A helper class that implements Apple Pay.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Usage looks like this:"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPApplePayContext"}],"role":"symbol"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay":{"role":"collection","title":"StripeApplePay","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"StripeApplePay is a lightweight Apple Pay SDK intended for building App Clips or other size-constrained apps."}],"url":"\/documentation\/stripeapplepay"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/paymentAuthorizationController(_:didChangeCouponCode:handler:)":{"title":"paymentAuthorizationController(_:didChangeCouponCode:handler:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentAuthorizationController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController","text":"PKPaymentAuthorizationController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didChangeCouponCode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"handler","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)PKPaymentRequestCouponCodeUpdate","text":"PKPaymentRequestCouponCodeUpdate","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"paymentAuthorizationController:didChangeCouponCode:handler:","kind":"identifier"}],"url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentauthorizationcontroller(_:didchangecouponcode:handler:)","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationController(_:didChangeCouponCode:handler:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":[{"deprecated":false,"name":"iOS","introducedAt":"15.0","beta":false,"unavailable":false},{"unavailable":false,"beta":false,"introducedAt":"15.0","deprecated":false,"name":"iPadOS"},{"introducedAt":"15.0","deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false}],"op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"paymentAuthorizationController:didChangeCouponCode:handler:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"paymentAuthorizationController:didChangeCouponCode:handler:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"paymentAuthorizationController:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController","text":"PKPaymentAuthorizationController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangeCouponCode:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"couponCode"},{"kind":"text","text":" "},{"text":"handler:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"PKPaymentRequestCouponCodeUpdate","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentRequestCouponCodeUpdate"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"STPApplePayContext","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/title"},{"value":[{"text":"STPApplePayContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/fragments"},{"value":[{"text":"STPApplePayContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1paymentAuthorizationController(_:didChangeCouponCode:handler:)\/title","value":"paymentAuthorizationController:didChangeCouponCode:handler:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1paymentAuthorizationController(_:didChangeCouponCode:handler:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"paymentAuthorizationController:didChangeCouponCode:handler:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}