{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(presentApplePayWithCompletion:) "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentApplePay"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPVoidBlock","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPVoidBlock","preciseIdentifier":"s:14StripeApplePay12STPVoidBlocka","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Called after the Apple Pay sheet is presented","type":"text"}]}],"name":"completion"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"aside","name":"Note","content":[{"type":"paragraph","inlineContent":[{"text":"This method should only be called once; create a new instance of STPApplePayContext every time you present Apple Pay.","type":"text"}]}],"style":"note"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/presentApplePay(completion:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext"]]},"abstract":[{"text":"Presents the Apple Pay sheet from the key window, starting the payment process.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/presentapplepay(completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/presentapplepay(completion:)"]}],"metadata":{"platforms":[],"modules":[{"name":"StripeApplePay"}],"externalID":"c:@M@StripeApplePay@objc(cs)STPApplePayContext(im)presentApplePayWithCompletion:","role":"symbol","title":"presentApplePay(completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"presentApplePay","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPVoidBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripeApplePay12STPVoidBlocka"},{"kind":"text","text":"?)"}],"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"presentApplePayWithCompletion:","kind":"identifier"}]},"kind":"symbol","references":{"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay":{"title":"StripeApplePay","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"StripeApplePay is a lightweight Apple Pay SDK intended for building App Clips or other size-constrained apps."}],"url":"\/documentation\/stripeapplepay"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/presentApplePay(completion:)":{"type":"topic","kind":"symbol","abstract":[{"text":"Presents the Apple Pay sheet from the key window, starting the payment process.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentApplePay"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripeApplePay12STPVoidBlocka","text":"STPVoidBlock"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"presentApplePayWithCompletion:"}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/presentApplePay(completion:)","role":"symbol","title":"presentApplePay(completion:)","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/presentapplepay(completion:)"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPVoidBlock":{"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPVoidBlock","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPVoidBlock","navigatorTitle":[{"text":"STPVoidBlock","kind":"identifier"}],"title":"STPVoidBlock","url":"\/documentation\/stripeapplepay\/stpvoidblock","abstract":[{"text":"An empty block, called with no arguments, returning nothing.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext":{"abstract":[{"type":"text","text":"A helper class that implements Apple Pay."},{"type":"text","text":" "},{"text":"Usage looks like this:","type":"text"}],"url":"\/documentation\/stripeapplepay\/stpapplepaycontext","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPApplePayContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPApplePayContext","kind":"identifier"}],"title":"STPApplePayContext","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"presentApplePayWithCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentApplePayWithCompletion:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"presentApplePayWithCompletion:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":" (^","kind":"text"},{"kind":"text","text":")()) "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":{"parameters":[{"name":"completion","content":[{"inlineContent":[{"text":"Called after the Apple Pay sheet is presented","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1presentApplePay(completion:)\/title","value":"presentApplePayWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1presentApplePay(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"presentApplePayWithCompletion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/title","value":"STPApplePayContext"},{"value":[{"kind":"identifier","text":"STPApplePayContext"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/navigatorTitle","value":[{"kind":"identifier","text":"STPApplePayContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}