{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationWindow"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController","kind":"typeIdentifier","text":"PKPaymentAuthorizationController"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIWindow","kind":"typeIdentifier","text":"UIWindow"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/presentationWindow(for:)"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":":nodoc:"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/presentationwindow(for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/presentationwindow(for:)"]}],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"presentationWindowForPaymentAuthorizationController:"}],"title":"presentationWindow(for:)","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"StripeApplePay"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationWindow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController","text":"PKPaymentAuthorizationController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@StripeApplePay@objc(cs)STPApplePayContext(im)presentationWindowForPaymentAuthorizationController:"},"references":{"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","role":"collection","url":"\/documentation\/stripeapplepay","abstract":[{"text":"StripeApplePay is a lightweight Apple Pay SDK intended for building App Clips or other size-constrained apps.","type":"text"}],"title":"StripeApplePay","type":"topic"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/presentationWindow(for:)":{"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationWindow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController","text":"PKPaymentAuthorizationController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"presentationWindow(for:)","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/presentationwindow(for:)","navigatorTitle":[{"text":"presentationWindowForPaymentAuthorizationController:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/presentationWindow(for:)","abstract":[{"type":"text","text":":nodoc:"}]},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext":{"navigatorTitle":[{"kind":"identifier","text":"STPApplePayContext"}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext","type":"topic","url":"\/documentation\/stripeapplepay\/stpapplepaycontext","abstract":[{"type":"text","text":"A helper class that implements Apple Pay."},{"type":"text","text":" "},{"type":"text","text":"Usage looks like this:"}],"title":"STPApplePayContext","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPApplePayContext"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"presentationWindowForPaymentAuthorizationController:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"presentationWindowForPaymentAuthorizationController:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"UIWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIWindow"},{"text":" *) ","kind":"text"},{"text":"presentationWindowForPaymentAuthorizationController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PKPaymentAuthorizationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1presentationWindow(for:)\/title","op":"replace","value":"presentationWindowForPaymentAuthorizationController:"},{"value":[{"text":"- ","kind":"text"},{"text":"presentationWindowForPaymentAuthorizationController:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1presentationWindow(for:)\/fragments","op":"replace"},{"value":"STPApplePayContext","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/title","op":"replace"},{"value":[{"text":"STPApplePayContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPApplePayContext"}],"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/navigatorTitle","op":"replace"}]}]}