{"metadata":{"title":"presentApplePay(from:completion:)","role":"symbol","externalID":"c:@M@StripeApplePay@objc(cs)STPApplePayContext(im)presentApplePayFromWindow:completion:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentApplePay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIWindow"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripeApplePay12STPVoidBlocka","text":"STPVoidBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"modules":[{"name":"StripeApplePay"}],"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"presentApplePayFromWindow:completion:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(presentApplePayFromWindow:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentApplePay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"window","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIWindow"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPVoidBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripeApplePay12STPVoidBlocka","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPVoidBlock"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The UIWindow to host the Apple Pay sheet"}]}],"name":"window"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Called after the Apple Pay sheet is presented","type":"text"}]}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"style":"note","type":"aside","name":"Note","content":[{"type":"paragraph","inlineContent":[{"text":"This method should only be called once; create a new instance of STPApplePayContext every time you present Apple Pay.","type":"text"}]}]}]}],"abstract":[{"text":"Presents the Apple Pay sheet from the specified window, starting the payment process.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/presentapplepay(from:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/presentapplepay(from:completion:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/presentApplePay(from:completion:)"},"kind":"symbol","sections":[],"references":{"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPVoidBlock":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPVoidBlock","abstract":[{"text":"An empty block, called with no arguments, returning nothing.","type":"text"}],"navigatorTitle":[{"text":"STPVoidBlock","kind":"identifier"}],"title":"STPVoidBlock","url":"\/documentation\/stripeapplepay\/stpvoidblock","kind":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPVoidBlock","kind":"identifier"}]},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext","abstract":[{"text":"A helper class that implements Apple Pay.","type":"text"},{"text":" ","type":"text"},{"text":"Usage looks like this:","type":"text"}],"navigatorTitle":[{"text":"STPApplePayContext","kind":"identifier"}],"title":"STPApplePayContext","url":"\/documentation\/stripeapplepay\/stpapplepaycontext","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPApplePayContext","kind":"identifier"}]},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay":{"title":"StripeApplePay","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","role":"collection","abstract":[{"text":"StripeApplePay is a lightweight Apple Pay SDK intended for building App Clips or other size-constrained apps.","type":"text"}],"type":"topic","url":"\/documentation\/stripeapplepay","kind":"symbol"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/presentApplePay(from:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentApplePay"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPVoidBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripeApplePay12STPVoidBlocka"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"presentApplePayFromWindow:completion:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/presentApplePay(from:completion:)","title":"presentApplePay(from:completion:)","role":"symbol","abstract":[{"text":"Presents the Apple Pay sheet from the specified window, starting the payment process.","type":"text"}],"kind":"symbol","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/presentapplepay(from:completion:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/platforms","op":"add","value":null},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"presentApplePayFromWindow:completion:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"presentApplePayFromWindow:completion:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"presentApplePayFromWindow:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIWindow","kind":"typeIdentifier","text":"UIWindow"},{"text":" *) ","kind":"text"},{"text":"window","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^)()) "},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"window","content":[{"inlineContent":[{"text":"The UIWindow to host the Apple Pay sheet","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"text":"Called after the Apple Pay sheet is presented","type":"text"}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"STPApplePayContext","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/fragments","value":[{"kind":"identifier","text":"STPApplePayContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/navigatorTitle","value":[{"kind":"identifier","text":"STPApplePayContext"}]},{"value":"presentApplePayFromWindow:completion:","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1presentApplePay(from:completion:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"presentApplePayFromWindow:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1presentApplePay(from:completion:)\/fragments","op":"replace"}]}]}