{"abstract":[{"type":"text","text":"The Stripe Identity iOS SDK makes it quick and easy to verify your user’s identity in your iOS app. We provide a prebuilt UI to collect your user’s ID documents, match photo ID with selfies, and validate ID numbers."}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripeidentity"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripeidentity"]}],"primaryContentSections":[{"content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"name":"Note","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"To get access to the Identity iOS SDK, visit the "},{"identifier":"https:\/\/dashboard.stripe.com\/settings\/identity","isActive":true,"type":"reference"},{"type":"text","text":" page and click "},{"type":"strong","inlineContent":[{"text":"Enable","type":"text"}]},{"type":"text","text":"."}],"type":"paragraph"}]},{"text":"Table of contents","anchor":"Table-of-contents","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"#Features","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"#Requirements","isActive":true}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"#Getting-started","isActive":true}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"#Integration"}]}]},{"content":[{"inlineContent":[{"identifier":"#Example","type":"reference","isActive":true}],"type":"paragraph"}]}]}]},{"content":[{"inlineContent":[{"identifier":"#Manual-linking","type":"reference","isActive":true}],"type":"paragraph"}]}]},{"text":"Features","level":2,"anchor":"Features","type":"heading"},{"type":"paragraph","inlineContent":[{"inlineContent":[{"text":"Simplified security","type":"text"}],"type":"strong"},{"text":": We’ve made it simple for you to securely collect your user’s personally identifiable information (PII) such as identity document images. Sensitive PII data is sent directly to Stripe Identity instead of passing through your server. For more information, see our ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/stripe.com\/docs\/security"},{"type":"text","text":"."}]},{"inlineContent":[{"type":"strong","inlineContent":[{"text":"Automatic document capture","type":"text"}]},{"type":"text","text":": We automatically capture images of the front and back of government-issued photo ID to ensure a clear and readable image."}],"type":"paragraph"},{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Selfie matching"}]},{"type":"text","text":": We capture photos of your user’s face and review it to confirm that the photo ID belongs to them. For more information, see our guide on "},{"identifier":"https:\/\/stripe.com\/docs\/identity\/selfie","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"inlineContent":[{"type":"text","text":"Identity information collection"}],"type":"strong"},{"text":": We collect name, date of birth, and government ID number to validate that it is real.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"inlineContent":[{"text":"Prebuilt UI","type":"text"}],"type":"strong"},{"type":"text","text":": We provide "},{"identifier":"https:\/\/stripe.dev\/stripe-ios\/stripe-identity\/Classes\/IdentityVerificationSheet.html","isActive":true,"type":"reference"},{"type":"text","text":", a prebuilt UI that combines all the steps required to collect ID documents, selfies, and ID numbers into a single sheet that displays on top of your app."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Automated verification"}],"type":"strong"},{"text":": Stripe Identity’s automated verification technology looks for patterns to help determine if an ID document is real or fake and uses distinctive physiological characteristics of faces to match your users’ selfies to photos on their ID document. Collected identity information is checked against a global set of databases to confirm that it exists. Learn more about the ","type":"text"},{"type":"reference","identifier":"https:\/\/stripe.com\/docs\/identity\/verification-checks","isActive":true},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"https:\/\/stripe.com\/docs\/identity\/access-verification-results"},{"text":", or our integration guide on ","type":"text"},{"identifier":"https:\/\/stripe.com\/docs\/identity\/handle-verification-outcomes","type":"reference","isActive":true},{"text":".","type":"text"}]},{"level":2,"anchor":"Requirements","text":"Requirements","type":"heading"},{"inlineContent":[{"text":"The Stripe Identity iOS SDK is compatible with apps targeting iOS 13.0 or above.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"If you intend to use this SDK with Stripe’s Identity service, you must not modify this SDK. Using a modified version of this SDK with Stripe’s Identity service, without Stripe’s written authorization, is a breach of your agreement with Stripe and may result in your Stripe account being shut down."}],"type":"paragraph"},{"type":"heading","level":2,"text":"Getting started","anchor":"Getting-started"},{"type":"heading","level":3,"text":"Integration","anchor":"Integration"},{"inlineContent":[{"text":"Get started with Stripe Identity’s ","type":"text"},{"type":"reference","identifier":"https:\/\/stripe.com\/docs\/identity\/verify-identity-documents?platform=ios","isActive":true},{"type":"text","text":" and "},{"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/24.24.1\/StripeIdentity\/..\/Example\/IdentityVerification%20Example","type":"reference","isActive":true},{"type":"text","text":", or "},{"type":"reference","identifier":"https:\/\/stripe.dev\/stripe-ios\/stripe-identity\/index.html","isActive":true},{"text":" for fine-grained documentation of all the classes and methods in the SDK.","type":"text"}],"type":"paragraph"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Identity SDK uses camera to scan documents and selfies, you’ll need to set "},{"code":"NSCameraUsageDescription","type":"codeVoice"},{"text":" in your application’s plist, and provide a reason for accessing the camera (e.g. “This app uses the camera to take a picture of your identity documents.”).","type":"text"}]}],"type":"aside","name":"Note"},{"text":"Example","level":3,"anchor":"Example","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"reference","overridingTitleInlineContent":[{"type":"text","text":"Identity Verification Example"}],"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/24.24.1\/StripeIdentity\/..\/Example\/IdentityVerification%20Example","isActive":true,"overridingTitle":"Identity Verification Example"},{"text":" – This example demonstrates how to capture your users’ ID documents on iOS and securely send them to Stripe Identity for identity verification.","type":"text"}]},{"level":2,"anchor":"Manual-linking","type":"heading","text":"Manual linking"},{"inlineContent":[{"text":"If you link the Stripe Identity library manually, use a version from our ","type":"text"},{"type":"reference","identifier":"https:\/\/github.com\/stripe\/stripe-ios\/releases","isActive":true},{"text":" page and make sure to embed ","type":"text"},{"type":"text","text":"all"},{"type":"text","text":" of the following frameworks:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"StripeIdentity.xcframework"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"StripeCore.xcframework"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"StripeCameraCore.xcframework"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"code":"StripeUICore.xcframework","type":"codeVoice"}],"type":"paragraph"}]}]}],"kind":"content"}],"metadata":{"modules":[{"name":"StripeIdentity"}],"roleHeading":"Framework","symbolKind":"module","role":"collection","title":"StripeIdentity","externalID":"StripeIdentity"},"hierarchy":{"paths":[[]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/IdentityVerificationSheet","doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/STPAPIClient","doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/STPAppInfo","doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/STPError","doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/StripeAPI"],"title":"Classes","anchor":"Classes"},{"identifiers":["doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/SafeEnumCodable","doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/SafeEnumDecodable","doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/UnknownFieldsCodable","doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/UnknownFieldsDecodable","doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/UnknownFieldsEncodable"],"generated":true,"anchor":"Protocols","title":"Protocols"},{"anchor":"Structures","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/FinancialConnectionsEvent","doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/NonEncodableParameters"],"title":"Structures"},{"identifiers":["doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/StripeCoreVersionNumber","doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/StripeCoreVersionString"],"title":"Variables","generated":true,"anchor":"Variables"},{"identifiers":["doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/IdentityVerificationSheetError","doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/STPCardErrorCode","doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/STPErrorCode"],"title":"Enumerations","anchor":"Enumerations","generated":true},{"title":"Extended Modules","identifiers":["doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/Foundation"],"generated":true,"anchor":"Extended-Modules"}],"references":{"https://github.com/stripe/stripe-ios/releases":{"titleInlineContent":[{"type":"text","text":"releases"}],"type":"link","url":"https:\/\/github.com\/stripe\/stripe-ios\/releases","title":"releases","identifier":"https:\/\/github.com\/stripe\/stripe-ios\/releases"},"doc://com.stripe.stripe-identity/documentation/StripeIdentity/StripeIdentityVersionString":{"url":"\/documentation\/stripeidentity\/stripeidentityversionstring","title":"StripeIdentityVersionString","role":"symbol","abstract":[{"text":"Project version string for StripeIdentity.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/StripeIdentityVersionString","type":"topic","fragments":[{"text":"StripeIdentityVersionString","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-identity/documentation/StripeIdentity/StripeIdentityVersionNumber":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/StripeIdentityVersionNumber","role":"symbol","abstract":[{"type":"text","text":"Project version number for StripeIdentity."}],"url":"\/documentation\/stripeidentity\/stripeidentityversionnumber","fragments":[{"kind":"identifier","text":"StripeIdentityVersionNumber"}],"title":"StripeIdentityVersionNumber"},"doc://com.stripe.stripe-identity/documentation/StripeIdentity/StripeCoreVersionString":{"identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/StripeCoreVersionString","url":"\/documentation\/stripeidentity\/stripecoreversionstring","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"StripeCoreVersionString","kind":"identifier"},{"kind":"text","text":": <<error type>>"}],"title":"StripeCoreVersionString","role":"symbol","kind":"symbol","abstract":[],"type":"topic"},"doc://com.stripe.stripe-identity/documentation/StripeIdentity/UnknownFieldsDecodable":{"kind":"symbol","url":"\/documentation\/stripeidentity\/unknownfieldsdecodable","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UnknownFieldsDecodable"}],"role":"symbol","type":"topic","title":"UnknownFieldsDecodable","identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/UnknownFieldsDecodable","navigatorTitle":[{"text":"UnknownFieldsDecodable","kind":"identifier"}],"abstract":[{"text":"A Decodable object that retains unknown fields.","type":"text"},{"type":"text","text":" "},{"type":"text","text":":nodoc:"}]},"doc://com.stripe.stripe-identity/documentation/StripeIdentity/SafeEnumDecodable":{"title":"SafeEnumDecodable","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SafeEnumDecodable"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/SafeEnumDecodable","url":"\/documentation\/stripeidentity\/safeenumdecodable","abstract":[{"text":"A Decodable enum that sets an “unparsable” case","type":"text"},{"type":"text","text":" "},{"type":"text","text":"instead of failing on values that are unknown to the SDK."},{"text":" ","type":"text"},{"type":"text","text":":nodoc:"}],"kind":"symbol","navigatorTitle":[{"text":"SafeEnumDecodable","kind":"identifier"}],"role":"symbol"},"https://stripe.com/docs/identity/verification-checks":{"titleInlineContent":[{"type":"text","text":"verification checks supported by Stripe Identity"}],"type":"link","url":"https:\/\/stripe.com\/docs\/identity\/verification-checks","title":"verification checks supported by Stripe Identity","identifier":"https:\/\/stripe.com\/docs\/identity\/verification-checks"},"doc://com.stripe.stripe-identity/documentation/StripeIdentity":{"identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity","title":"StripeIdentity","kind":"symbol","abstract":[{"type":"text","text":"The Stripe Identity iOS SDK makes it quick and easy to verify your user’s identity in your iOS app. We provide a prebuilt UI to collect your user’s ID documents, match photo ID with selfies, and validate ID numbers."}],"role":"collection","type":"topic","url":"\/documentation\/stripeidentity"},"https://dashboard.stripe.com/settings/identity":{"titleInlineContent":[{"type":"text","text":"Identity Settings"}],"type":"link","url":"https:\/\/dashboard.stripe.com\/settings\/identity","identifier":"https:\/\/dashboard.stripe.com\/settings\/identity","title":"Identity Settings"},"doc://com.stripe.stripe-identity/documentation/StripeIdentity/STPAppInfo":{"abstract":[{"type":"text","text":"Libraries wrapping the Stripe SDK should use this object to provide information about the"},{"text":" ","type":"text"},{"type":"text","text":"library, and set it in on "},{"type":"codeVoice","code":"STPAPIClient"},{"type":"text","text":"."}],"title":"STPAppInfo","role":"symbol","url":"\/documentation\/stripeidentity\/stpappinfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPAppInfo","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/STPAppInfo","navigatorTitle":[{"kind":"identifier","text":"STPAppInfo"}],"kind":"symbol"},"doc://com.stripe.stripe-identity/documentation/StripeIdentity/Foundation":{"kind":"symbol","title":"Foundation","abstract":[],"type":"topic","url":"\/documentation\/stripeidentity\/foundation","role":"collection","identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/Foundation"},"doc://com.stripe.stripe-identity/documentation/StripeIdentity/FinancialConnectionsEvent":{"title":"FinancialConnectionsEvent","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"FinancialConnectionsEvent","kind":"identifier"}],"url":"\/documentation\/stripeidentity\/financialconnectionsevent","identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/FinancialConnectionsEvent","type":"topic","navigatorTitle":[{"text":"FinancialConnectionsEvent","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-identity/documentation/StripeIdentity/IdentityVerificationSheet":{"abstract":[{"type":"text","text":"A drop-in class that presents a sheet for a user to verify their identity."},{"text":" ","type":"text"},{"type":"text","text":"This class is in beta; see https:\/\/stripe.com\/docs\/identity for access"}],"type":"topic","role":"symbol","url":"\/documentation\/stripeidentity\/identityverificationsheet","identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/IdentityVerificationSheet","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IdentityVerificationSheet","kind":"identifier"}],"kind":"symbol","title":"IdentityVerificationSheet","navigatorTitle":[{"text":"IdentityVerificationSheet","kind":"identifier"}]},"doc://com.stripe.stripe-identity/documentation/StripeIdentity/UnknownFieldsCodable":{"identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/UnknownFieldsCodable","url":"\/documentation\/stripeidentity\/unknownfieldscodable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnknownFieldsCodable"}],"navigatorTitle":[{"kind":"identifier","text":"UnknownFieldsCodable"}],"kind":"symbol","title":"UnknownFieldsCodable","abstract":[{"text":"A protocol that conforms to both UnknownFieldsEncodable and UnknownFieldsDecodable.","type":"text"},{"type":"text","text":" "},{"text":":nodoc:","type":"text"}],"type":"topic","role":"symbol"},"#Manual-linking":{"titleInlineContent":[{"type":"text","text":"Manual linking"}],"type":"link","url":"#Manual-linking","title":"Manual linking","identifier":"#Manual-linking"},"doc://com.stripe.stripe-identity/documentation/StripeIdentity/STPError":{"title":"STPError","abstract":[{"type":"text","text":"Top-level class for Stripe error constants."}],"kind":"symbol","navigatorTitle":[{"text":"STPError","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPError"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/STPError","type":"topic","url":"\/documentation\/stripeidentity\/stperror"},"doc://com.stripe.stripe-identity/documentation/StripeIdentity/STPErrorCode":{"url":"\/documentation\/stripeidentity\/stperrorcode","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/STPErrorCode","type":"topic","abstract":[{"text":"Possible error code values for NSErrors with the ","type":"text"},{"code":"StripeDomain","type":"codeVoice"},{"type":"text","text":" domain."}],"role":"symbol","title":"STPErrorCode","navigatorTitle":[{"kind":"identifier","text":"STPErrorCode"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPErrorCode","kind":"identifier"}]},"doc://com.stripe.stripe-identity/documentation/StripeIdentity/STPAPIClient":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/STPAPIClient","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"title":"STPAPIClient","url":"\/documentation\/stripeidentity\/stpapiclient","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPAPIClient","kind":"identifier"}],"abstract":[{"type":"text","text":"A client for making connections to the Stripe API."}]},"https://stripe.com/docs/identity/handle-verification-outcomes":{"titleInlineContent":[{"type":"text","text":"handling verification outcomes"}],"type":"link","url":"https:\/\/stripe.com\/docs\/identity\/handle-verification-outcomes","identifier":"https:\/\/stripe.com\/docs\/identity\/handle-verification-outcomes","title":"handling verification outcomes"},"doc://com.stripe.stripe-identity/documentation/StripeIdentity/UnknownFieldsEncodable":{"url":"\/documentation\/stripeidentity\/unknownfieldsencodable","navigatorTitle":[{"kind":"identifier","text":"UnknownFieldsEncodable"}],"abstract":[{"text":"An Encodable object that allows unknown fields to be set.","type":"text"},{"type":"text","text":" "},{"text":":nodoc:","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/UnknownFieldsEncodable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnknownFieldsEncodable"}],"title":"UnknownFieldsEncodable","kind":"symbol"},"https://github.com/stripe/stripe-ios/tree/24.24.1/StripeIdentity/../Example/IdentityVerification%20Example":{"titleInlineContent":[{"type":"text","text":"example project"}],"type":"link","url":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/24.24.1\/StripeIdentity\/..\/Example\/IdentityVerification%20Example","title":"example project","identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/24.24.1\/StripeIdentity\/..\/Example\/IdentityVerification%20Example"},"https://stripe.dev/stripe-ios/stripe-identity/Classes/IdentityVerificationSheet.html":{"titleInlineContent":[{"type":"codeVoice","code":"IdentityVerificationSheet"}],"type":"link","url":"https:\/\/stripe.dev\/stripe-ios\/stripe-identity\/Classes\/IdentityVerificationSheet.html","identifier":"https:\/\/stripe.dev\/stripe-ios\/stripe-identity\/Classes\/IdentityVerificationSheet.html","title":"IdentityVerificationSheet"},"doc://com.stripe.stripe-identity/documentation/StripeIdentity/StripeCoreVersionNumber":{"type":"topic","title":"StripeCoreVersionNumber","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/StripeCoreVersionNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"StripeCoreVersionNumber"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/stripeidentity\/stripecoreversionnumber","role":"symbol"},"https://stripe.dev/stripe-ios/stripe-identity/index.html":{"titleInlineContent":[{"type":"text","text":"📘 browse the SDK reference"}],"type":"link","url":"https:\/\/stripe.dev\/stripe-ios\/stripe-identity\/index.html","identifier":"https:\/\/stripe.dev\/stripe-ios\/stripe-identity\/index.html","title":"📘 browse the SDK reference"},"doc://com.stripe.stripe-identity/documentation/StripeIdentity/SafeEnumCodable":{"type":"topic","title":"SafeEnumCodable","navigatorTitle":[{"text":"SafeEnumCodable","kind":"identifier"}],"abstract":[{"type":"text","text":"A Codable enum that sets an “unparsable” case"},{"text":" ","type":"text"},{"type":"text","text":"instead of failing on values that are unknown to the SDK."},{"type":"text","text":" "},{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/SafeEnumCodable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SafeEnumCodable"}],"kind":"symbol","url":"\/documentation\/stripeidentity\/safeenumcodable","role":"symbol"},"https://stripe.com/docs/identity/verify-identity-documents?platform=ios":{"titleInlineContent":[{"type":"text","text":"📚 iOS integration guide"}],"type":"link","url":"https:\/\/stripe.com\/docs\/identity\/verify-identity-documents?platform=ios","title":"📚 iOS integration guide","identifier":"https:\/\/stripe.com\/docs\/identity\/verify-identity-documents?platform=ios"},"doc://com.stripe.stripe-identity/documentation/StripeIdentity/StripeAPI":{"identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/StripeAPI","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StripeAPI"}],"navigatorTitle":[{"text":"StripeAPI","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripeidentity\/stripeapi","abstract":[{"text":"A top-level class that imports the rest of the Stripe SDK.","type":"text"}],"title":"StripeAPI","role":"symbol","kind":"symbol"},"#Features":{"titleInlineContent":[{"type":"text","text":"Features"}],"type":"link","url":"#Features","identifier":"#Features","title":"Features"},"#Requirements":{"titleInlineContent":[{"type":"text","text":"Requirements"}],"type":"link","url":"#Requirements","identifier":"#Requirements","title":"Requirements"},"https://stripe.com/docs/security":{"titleInlineContent":[{"type":"text","text":"integration security guide"}],"type":"link","url":"https:\/\/stripe.com\/docs\/security","title":"integration security guide","identifier":"https:\/\/stripe.com\/docs\/security"},"doc://com.stripe.stripe-identity/documentation/StripeIdentity/NonEncodableParameters":{"role":"symbol","type":"topic","title":"NonEncodableParameters","abstract":[{"text":"This should not be used directly.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Use the "},{"code":"additionalParameters","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"allResponseFields","type":"codeVoice"},{"text":" accessors instead.","type":"text"},{"text":" ","type":"text"},{"text":":nodoc:","type":"text"}],"url":"\/documentation\/stripeidentity\/nonencodableparameters","identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/NonEncodableParameters","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NonEncodableParameters"}],"navigatorTitle":[{"text":"NonEncodableParameters","kind":"identifier"}]},"#Example":{"identifier":"#Example","title":"Example","type":"link","url":"#Example","titleInlineContent":[{"text":"Example","type":"text"}]},"doc://com.stripe.stripe-identity/documentation/StripeIdentity/IdentityVerificationSheetError":{"identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/IdentityVerificationSheetError","navigatorTitle":[{"kind":"identifier","text":"IdentityVerificationSheetError"}],"title":"IdentityVerificationSheetError","abstract":[{"text":"Errors specific to the ","type":"text"},{"type":"codeVoice","code":"IdentityVerificationSheet"},{"type":"text","text":"."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IdentityVerificationSheetError"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/stripeidentity\/identityverificationsheeterror"},"#Integration":{"title":"Integration","identifier":"#Integration","titleInlineContent":[{"text":"Integration","type":"text"}],"url":"#Integration","type":"link"},"https://stripe.com/docs/identity/access-verification-results":{"title":"accessing verification results","identifier":"https:\/\/stripe.com\/docs\/identity\/access-verification-results","titleInlineContent":[{"text":"accessing verification results","type":"text"}],"url":"https:\/\/stripe.com\/docs\/identity\/access-verification-results","type":"link"},"#Getting-started":{"identifier":"#Getting-started","title":"Getting started","type":"link","url":"#Getting-started","titleInlineContent":[{"type":"text","text":"Getting started"}]},"doc://com.stripe.stripe-identity/documentation/StripeIdentity/STPCardErrorCode":{"abstract":[{"text":"Possible string values you may receive when there was an error tokenizing a card.","type":"text"}],"title":"STPCardErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCardErrorCode"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardErrorCode"}],"url":"\/documentation\/stripeidentity\/stpcarderrorcode","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/STPCardErrorCode"},"https://stripe.com/docs/identity/selfie":{"identifier":"https:\/\/stripe.com\/docs\/identity\/selfie","title":"adding selfie checks","type":"link","url":"https:\/\/stripe.com\/docs\/identity\/selfie","titleInlineContent":[{"type":"text","text":"adding selfie checks"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"title":"Variables","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/StripeIdentityVersionNumber","doc:\/\/com.stripe.stripe-identity\/documentation\/StripeIdentity\/StripeIdentityVersionString"],"anchor":"Variables"}]},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null}]}]}