//
//  STPConfirmKlarnaOptions.swift
//  StripePayments
//
//  Created by George Birch on 8/4/26.
//  Copyright © 2026 Stripe, Inc. All rights reserved.
//

import Foundation

/// Klarna options to pass to `STPConfirmPaymentMethodOptions`.
@_spi(KlarnaSDKPrivatePreview)
public class STPConfirmKlarnaOptions: NSObject {

    /// A token generated by the Klarna SDK for a pre-purchase interaction.
    @objc public var interoperabilityToken: String?

    /// A token generated by the Klarna SDK after successful payment authorization.
    @objc public var partnerConfirmationToken: String?

    /// :nodoc:
    @objc public var additionalAPIParameters: [AnyHashable: Any] = [:]

    /// Initializes Klarna payment method options.
    /// - Parameters:
    ///   - interoperabilityToken: A token generated by the Klarna SDK for a pre-purchase interaction.
    ///   - partnerConfirmationToken: A token generated by the Klarna SDK after successful payment authorization.
    @objc public init(
        interoperabilityToken: String? = nil,
        partnerConfirmationToken: String? = nil
    ) {
        self.interoperabilityToken = interoperabilityToken
        self.partnerConfirmationToken = partnerConfirmationToken
        super.init()
    }
}

// MARK: - STPFormEncodable
extension STPConfirmKlarnaOptions: STPFormEncodable {
    @objc
    public class func propertyNamesToFormFieldNamesMapping() -> [String: String] {
        return [
            NSStringFromSelector(#selector(getter: interoperabilityToken)): "interoperability_token",
            NSStringFromSelector(#selector(getter: partnerConfirmationToken)): "partner_confirmation_token",
        ]
    }

    @objc
    public class func rootObjectName() -> String? {
        return "klarna"
    }
}
