{"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canceled"}],"title":"STPSetupIntentStatus.canceled","symbolKind":"case","externalID":"c:@M@StripePayments@E@STPSetupIntentStatus@STPSetupIntentStatusCanceled","modules":[{"name":"StripePayments"}],"roleHeading":"Case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentStatusCanceled"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/canceled"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus"]]},"abstract":[{"type":"text","text":"This SetupIntent was canceled and cannot be changed."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canceled","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stpsetupintentstatus\/canceled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsetupintentstatus\/canceled"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus/canceled":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canceled","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/canceled","kind":"symbol","abstract":[{"text":"This SetupIntent was canceled and cannot be changed.","type":"text"}],"navigatorTitle":[{"text":"STPSetupIntentStatusCanceled","kind":"identifier"}],"title":"STPSetupIntentStatus.canceled","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentstatus\/canceled"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus":{"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentStatus"}],"title":"STPSetupIntentStatus","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus","abstract":[{"type":"text","text":"Status types for an STPSetupIntent"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentstatus","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntentStatus"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPSetupIntentStatusCanceled","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPSetupIntentStatusCanceled","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPSetupIntentStatusCanceled","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPSetupIntentStatusCanceled","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1canceled\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPSetupIntentStatusCanceled"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1canceled\/fragments"},{"op":"replace","value":"STPSetupIntentStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPSetupIntentStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPSetupIntentStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}