{"variants":[{"paths":["\/documentation\/stripepayments\/stpsetupintentstatus\/processing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsetupintentstatus\/processing"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Stripe is processing this SetupIntent","type":"text"}],"kind":"symbol","metadata":{"symbolKind":"case","role":"symbol","title":"STPSetupIntentStatus.processing","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processing","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPSetupIntentStatus@STPSetupIntentStatusProcessing","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentStatusProcessing"}]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processing","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/processing","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus":{"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentStatus"}],"kind":"symbol","type":"topic","title":"STPSetupIntentStatus","abstract":[{"text":"Status types for an STPSetupIntent","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntentStatus"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus","url":"\/documentation\/stripepayments\/stpsetupintentstatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus/processing":{"navigatorTitle":[{"text":"STPSetupIntentStatusProcessing","kind":"identifier"}],"type":"topic","title":"STPSetupIntentStatus.processing","abstract":[{"type":"text","text":"Stripe is processing this SetupIntent"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processing","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/processing","url":"\/documentation\/stripepayments\/stpsetupintentstatus\/processing"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPSetupIntentStatusProcessing","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPSetupIntentStatusProcessing","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"STPSetupIntentStatusProcessing","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPSetupIntentStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/title"},{"op":"replace","value":[{"text":"STPSetupIntentStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/fragments"},{"op":"replace","value":[{"text":"STPSetupIntentStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/navigatorTitle"},{"op":"replace","value":"STPSetupIntentStatusProcessing","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1processing\/title"},{"op":"replace","value":[{"text":"STPSetupIntentStatusProcessing","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1processing\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}