{"metadata":{"title":"STPSetupIntentStatus.requiresPaymentMethod","modules":[{"name":"StripePayments"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresPaymentMethod"}],"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentStatusRequiresPaymentMethod"}],"symbolKind":"case","externalID":"c:@M@StripePayments@E@STPSetupIntentStatus@STPSetupIntentStatusRequiresPaymentMethod","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsetupintentstatus\/requirespaymentmethod"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintentstatus\/requirespaymentmethod"]}],"kind":"symbol","abstract":[{"type":"text","text":"This SetupIntent requires a PaymentMethod"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/requiresPaymentMethod","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiresPaymentMethod"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus/requiresPaymentMethod":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"requiresPaymentMethod","kind":"identifier"}],"title":"STPSetupIntentStatus.requiresPaymentMethod","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/requiresPaymentMethod","url":"\/documentation\/stripepayments\/stpsetupintentstatus\/requirespaymentmethod","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPSetupIntentStatusRequiresPaymentMethod","kind":"identifier"}],"abstract":[{"type":"text","text":"This SetupIntent requires a PaymentMethod"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus":{"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentStatus"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus","type":"topic","url":"\/documentation\/stripepayments\/stpsetupintentstatus","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSetupIntentStatus"}],"abstract":[{"type":"text","text":"Status types for an STPSetupIntent"}],"kind":"symbol","title":"STPSetupIntentStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"STPSetupIntentStatusRequiresPaymentMethod","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentStatusRequiresPaymentMethod"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"STPSetupIntentStatusRequiresPaymentMethod","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"STPSetupIntentStatusRequiresPaymentMethod","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1requiresPaymentMethod\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPSetupIntentStatusRequiresPaymentMethod"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1requiresPaymentMethod\/fragments"},{"op":"replace","value":"STPSetupIntentStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/title"},{"op":"replace","value":[{"text":"STPSetupIntentStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/navigatorTitle","value":[{"kind":"identifier","text":"STPSetupIntentStatus"}],"op":"replace"}]}]}