{"variants":[{"paths":["\/documentation\/stripepayments\/stpsetupintentstatus\/requiresconfirmation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsetupintentstatus\/requiresconfirmation"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/requiresConfirmation","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiresConfirmation"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"requiresConfirmation","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPSetupIntentStatus@STPSetupIntentStatusRequiresConfirmation","navigatorTitle":[{"text":"STPSetupIntentStatusRequiresConfirmation","kind":"identifier"}],"roleHeading":"Case","role":"symbol","symbolKind":"case","title":"STPSetupIntentStatus.requiresConfirmation"},"abstract":[{"type":"text","text":"This SetupIntent needs to be confirmed"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus/requiresConfirmation":{"role":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentstatus\/requiresconfirmation","abstract":[{"type":"text","text":"This SetupIntent needs to be confirmed"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiresConfirmation"}],"title":"STPSetupIntentStatus.requiresConfirmation","type":"topic","navigatorTitle":[{"text":"STPSetupIntentStatusRequiresConfirmation","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/requiresConfirmation"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus":{"title":"STPSetupIntentStatus","kind":"symbol","abstract":[{"type":"text","text":"Status types for an STPSetupIntent"}],"type":"topic","url":"\/documentation\/stripepayments\/stpsetupintentstatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentStatus","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentStatus"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPSetupIntentStatusRequiresConfirmation"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"STPSetupIntentStatusRequiresConfirmation"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"STPSetupIntentStatusRequiresConfirmation","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"STPSetupIntentStatusRequiresConfirmation","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1requiresConfirmation\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPSetupIntentStatusRequiresConfirmation"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1requiresConfirmation\/fragments"},{"value":"STPSetupIntentStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/title","op":"replace"},{"value":[{"text":"STPSetupIntentStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/navigatorTitle","op":"replace","value":[{"text":"STPSetupIntentStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}