{"abstract":[{"type":"text","text":"The selected PaymentMethod requires additional authentication steps."},{"type":"text","text":" "},{"type":"text","text":"Additional actions found via the "},{"type":"codeVoice","code":"nextAction"},{"type":"text","text":" property of "},{"type":"codeVoice","code":"STPSetupIntent"}],"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/requiresAction","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresAction"}],"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentStatusRequiresAction"}],"externalID":"c:@M@StripePayments@E@STPSetupIntentStatus@STPSetupIntentStatusRequiresAction","roleHeading":"Case","title":"STPSetupIntentStatus.requiresAction"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresAction"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stpsetupintentstatus\/requiresaction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsetupintentstatus\/requiresaction"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentStatus","kind":"identifier"}],"navigatorTitle":[{"text":"STPSetupIntentStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"Status types for an STPSetupIntent"}],"title":"STPSetupIntentStatus","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentstatus","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus/requiresAction":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/requiresAction","url":"\/documentation\/stripepayments\/stpsetupintentstatus\/requiresaction","navigatorTitle":[{"text":"STPSetupIntentStatusRequiresAction","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"The selected PaymentMethod requires additional authentication steps.","type":"text"},{"text":" ","type":"text"},{"text":"Additional actions found via the ","type":"text"},{"code":"nextAction","type":"codeVoice"},{"text":" property of ","type":"text"},{"code":"STPSetupIntent","type":"codeVoice"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiresAction","kind":"identifier"}],"title":"STPSetupIntentStatus.requiresAction"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPSetupIntentStatusRequiresAction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentStatusRequiresAction"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPSetupIntentStatusRequiresAction"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/title","value":"STPSetupIntentStatus"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/navigatorTitle","value":[{"kind":"identifier","text":"STPSetupIntentStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1requiresAction\/title","value":"STPSetupIntentStatusRequiresAction","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1requiresAction\/fragments","value":[{"text":"STPSetupIntentStatusRequiresAction","kind":"identifier"}],"op":"replace"}]}]}