{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The SetupIntent has succeeded"}],"metadata":{"role":"symbol","roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPSetupIntentStatus@STPSetupIntentStatusSucceeded","title":"STPSetupIntentStatus.succeeded","navigatorTitle":[{"text":"STPSetupIntentStatusSucceeded","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"succeeded"}],"symbolKind":"case"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/succeeded","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"succeeded","kind":"identifier"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsetupintentstatus\/succeeded"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintentstatus\/succeeded"]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus/succeeded":{"navigatorTitle":[{"text":"STPSetupIntentStatusSucceeded","kind":"identifier"}],"abstract":[{"type":"text","text":"The SetupIntent has succeeded"}],"url":"\/documentation\/stripepayments\/stpsetupintentstatus\/succeeded","kind":"symbol","role":"symbol","title":"STPSetupIntentStatus.succeeded","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/succeeded","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"succeeded","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus":{"title":"STPSetupIntentStatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus","type":"topic","abstract":[{"type":"text","text":"Status types for an STPSetupIntent"}],"role":"symbol","navigatorTitle":[{"text":"STPSetupIntentStatus","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentStatus","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsetupintentstatus","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPSetupIntentStatusSucceeded","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPSetupIntentStatusSucceeded","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPSetupIntentStatusSucceeded","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPSetupIntentStatusSucceeded","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1succeeded\/title"},{"value":[{"kind":"identifier","text":"STPSetupIntentStatusSucceeded"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1succeeded\/fragments"},{"value":"STPSetupIntentStatus","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/title"},{"value":[{"kind":"identifier","text":"STPSetupIntentStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/fragments"},{"value":[{"kind":"identifier","text":"STPSetupIntentStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}