{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/clientAttributionMetadata","interfaceLanguage":"occ"},"sections":[],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"clientAttributionMetadata"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentParams(py)clientAttributionMetadata","title":"clientAttributionMetadata","fragments":[{"text":"clientAttributionMetadata","kind":"identifier"}],"role":"symbol","modules":[{"name":"StripePayments"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"text":"STPClientAttributionMetadata","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPClientAttributionMetadata","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"clientAttributionMetadata","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentparams\/clientattributionmetadata"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"text":"Contains metadata with identifiers for the session and information about the integration","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams","title":"STPPaymentIntentParams","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentparams","kind":"symbol","abstract":[{"text":"An object representing parameters used to confirm a PaymentIntent object.","type":"text"},{"text":" ","type":"text"},{"text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"That PaymentMethod or Source can either be:"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentParams","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/clientAttributionMetadata":{"fragments":[{"kind":"identifier","text":"clientAttributionMetadata"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/clientAttributionMetadata","title":"clientAttributionMetadata","url":"\/documentation\/stripepayments\/stppaymentintentparams\/clientattributionmetadata","kind":"symbol","type":"topic","abstract":[{"text":"Contains metadata with identifiers for the session and information about the integration","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/title","value":"STPPaymentIntentParams"},{"value":[{"kind":"identifier","text":"STPPaymentIntentParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/navigatorTitle","value":[{"text":"STPPaymentIntentParams","kind":"identifier"}]}]}]}