{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentparams\/init(clientsecret:paymentmethodtype:)"]},{"paths":["\/documentation\/stripepayments\/stppaymentintentparams\/init(clientsecret:paymentmethodtype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/init(clientSecret:paymentMethodType:)"},"metadata":{"title":"init(clientSecret:paymentMethodType:)","modules":[{"name":"StripePayments"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentMethodType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodType","text":"STPPaymentMethodType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithClientSecret:paymentMethodType:","kind":"identifier"}],"roleHeading":"Initializer","externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentParams(im)initWithClientSecret:paymentMethodType:","symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams"]]},"abstract":[{"text":"Initializes this ","type":"text"},{"code":"STPPaymentIntentParams","type":"codeVoice"},{"text":" with a ","type":"text"},{"type":"codeVoice","code":"clientSecret"},{"type":"text","text":" and "},{"code":"paymentMethodType","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"Use this initializer for PaymentIntents that already have a PaymentMethod attached.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"clientSecret"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"paymentMethodType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","text":"STPPaymentMethodType","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodType"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"clientSecret","content":[{"inlineContent":[{"text":"The client secret for this PaymentIntent","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The known type of the PaymentIntent’s attached PaymentMethod","type":"text"}]}],"name":"paymentMethodType"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/init(clientSecret:paymentMethodType:)":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentparams\/init(clientsecret:paymentmethodtype:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/init(clientSecret:paymentMethodType:)","abstract":[{"text":"Initializes this ","type":"text"},{"code":"STPPaymentIntentParams","type":"codeVoice"},{"text":" with a ","type":"text"},{"code":"clientSecret","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"paymentMethodType"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Use this initializer for PaymentIntents that already have a PaymentMethod attached."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithClientSecret:paymentMethodType:"}],"title":"init(clientSecret:paymentMethodType:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"paymentMethodType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPPaymentMethodType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodType"},{"kind":"text","text":")"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodType","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","title":"STPPaymentMethodType","abstract":[{"type":"text","text":"The type of the PaymentMethod."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentIntentParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentIntentParams","kind":"identifier"}],"type":"topic","title":"STPPaymentIntentParams","url":"\/documentation\/stripepayments\/stppaymentintentparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams","role":"symbol","abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"text":" ","type":"text"},{"type":"text","text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it."},{"text":" ","type":"text"},{"text":"That PaymentMethod or Source can either be:","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithClientSecret:paymentMethodType:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithClientSecret:paymentMethodType:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithClientSecret:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"clientSecret","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethodType:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","text":"STPPaymentMethodType","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"paymentMethodType"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"clientSecret","content":[{"inlineContent":[{"text":"The client secret for this PaymentIntent","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The known type of the PaymentIntent’s attached PaymentMethod","type":"text"}]}],"name":"paymentMethodType"}],"kind":"parameters"}},{"value":"initWithClientSecret:paymentMethodType:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1init(clientSecret:paymentMethodType:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1init(clientSecret:paymentMethodType:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithClientSecret:paymentMethodType:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title","op":"replace","value":"STPPaymentMethodType"},{"op":"replace","value":[{"text":"STPPaymentMethodType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle","value":[{"text":"STPPaymentMethodType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/title","value":"STPPaymentIntentParams"},{"value":[{"kind":"identifier","text":"STPPaymentIntentParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/fragments","op":"replace"},{"value":[{"text":"STPPaymentIntentParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/navigatorTitle","op":"replace"}]}]}