{"metadata":{"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentParams(py)mandateData","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"mandateData"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"mandateData","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateDataParams","text":"STPMandateDataParams","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","modules":[{"name":"StripePayments"}],"title":"mandateData"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mandateData","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateDataParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateDataParams","text":"STPMandateDataParams"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"aside","name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If this value is null, the SDK will set this to an internal value indicating that the mandate data should be inferred from the current context if it’s required for "},{"type":"codeVoice","code":"self.paymentMethodType"}]}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/mandateData"},"kind":"symbol","abstract":[{"text":"Details about the Mandate to create.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentparams\/mandatedata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentparams\/mandatedata"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams":{"url":"\/documentation\/stripepayments\/stppaymentintentparams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentParams","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentParams"}],"title":"STPPaymentIntentParams","abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"type":"text","text":" "},{"type":"text","text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it."},{"text":" ","type":"text"},{"text":"That PaymentMethod or Source can either be:","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateDataParams":{"abstract":[{"type":"text","text":"This object contains details about the Mandate to create. - seealso: https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-mandate_data"}],"url":"\/documentation\/stripepayments\/stpmandatedataparams","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateDataParams","navigatorTitle":[{"text":"STPMandateDataParams","kind":"identifier"}],"role":"symbol","title":"STPMandateDataParams","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPMandateDataParams","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/mandateData":{"abstract":[{"type":"text","text":"Details about the Mandate to create."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/mandateData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mandateData"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateDataParams","text":"STPMandateDataParams","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"mandateData","navigatorTitle":[{"text":"mandateData","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentparams\/mandatedata","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"mandateData","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mandateData"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateDataParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateDataParams","text":"STPMandateDataParams"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"mandateData"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/title","op":"replace","value":"STPPaymentIntentParams"},{"value":[{"text":"STPPaymentIntentParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/fragments"},{"value":[{"text":"STPPaymentIntentParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams\/title","value":"STPMandateDataParams"},{"value":[{"kind":"identifier","text":"STPMandateDataParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams\/fragments"},{"value":[{"kind":"identifier","text":"STPMandateDataParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams\/navigatorTitle","op":"replace"},{"op":"replace","value":"mandateData","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1mandateData\/title"},{"value":[{"text":"mandateData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1mandateData\/fragments"}]}]}