{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentparams\/paymentmethodid"]},{"paths":["\/documentation\/stripepayments\/stppaymentintentparams\/paymentmethodid"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/paymentMethodId","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams"]]},"metadata":{"title":"paymentMethodId","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentParams(py)paymentMethodId","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"paymentMethodId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"paymentMethodId","kind":"identifier"}]},"abstract":[{"text":"Provide an already created PaymentMethod’s id, and it will be used to confirm the PaymentIntent.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethodId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Alternative to "},{"type":"codeVoice","code":"paymentMethodParams"}]}],"style":"note"}],"kind":"content"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentIntentParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentIntentParams","kind":"identifier"}],"type":"topic","title":"STPPaymentIntentParams","url":"\/documentation\/stripepayments\/stppaymentintentparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams","role":"symbol","abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"text":" ","type":"text"},{"type":"text","text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it."},{"text":" ","type":"text"},{"text":"That PaymentMethod or Source can either be:","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/paymentMethodId":{"title":"paymentMethodId","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentparams\/paymentmethodid","abstract":[{"type":"text","text":"Provide an already created PaymentMethod’s id, and it will be used to confirm the PaymentIntent."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethodId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"paymentMethodId","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/paymentMethodId"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"paymentMethodId"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"paymentMethodId"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"paymentMethodId"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","value":"STPPaymentIntentParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/title"},{"value":[{"text":"STPPaymentIntentParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/navigatorTitle","value":[{"text":"STPPaymentIntentParams","kind":"identifier"}]},{"op":"replace","value":"paymentMethodId","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1paymentMethodId\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1paymentMethodId\/fragments","value":[{"text":"paymentMethodId","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}