{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/radarOptions","interfaceLanguage":"occ"},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"radarOptions","kind":"identifier"}],"navigatorTitle":[{"text":"radarOptions","kind":"identifier"}],"title":"radarOptions","externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentParams(py)radarOptions","modules":[{"name":"StripePayments"}],"role":"symbol"},"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentparams\/radaroptions"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"Radar options that may contain HCaptcha token","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPRadarOptions","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarOptions","text":"STPRadarOptions","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"radarOptions"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams":{"kind":"symbol","navigatorTitle":[{"text":"STPPaymentIntentParams","kind":"identifier"}],"abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"text":" ","type":"text"},{"type":"text","text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it."},{"text":" ","type":"text"},{"type":"text","text":"That PaymentMethod or Source can either be:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams","title":"STPPaymentIntentParams","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentParams"}],"url":"\/documentation\/stripepayments\/stppaymentintentparams","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRadarOptions":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarOptions","url":"\/documentation\/stripepayments\/stpradaroptions","abstract":[{"type":"text","text":"Values for STPRadarOptions"}],"type":"topic","kind":"symbol","role":"symbol","title":"STPRadarOptions","fragments":[{"kind":"identifier","text":"STPRadarOptions"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/radarOptions":{"title":"radarOptions","url":"\/documentation\/stripepayments\/stppaymentintentparams\/radaroptions","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/radarOptions","kind":"symbol","fragments":[{"text":"radarOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Radar options that may contain HCaptcha token"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPPaymentIntentParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/fragments","value":[{"text":"STPPaymentIntentParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/navigatorTitle","value":[{"text":"STPPaymentIntentParams","kind":"identifier"}]}]}]}