{"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/saveSourceToCustomer","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"saveSourceToCustomer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"abstract":[{"type":"codeVoice","code":"@YES"},{"type":"text","text":" to save this PaymentIntent’s Source to the associated Customer,"},{"text":" ","type":"text"},{"type":"text","text":"if the Source is not already attached."},{"type":"text","text":" "},{"text":"This should be a boolean NSNumber, so that it can be ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" "},{"text":"This property has been renamed to ","type":"text"},{"code":"savePaymentMethod","type":"codeVoice"},{"text":" and deprecated.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams"]]},"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentParams(py)saveSourceToCustomer","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"saveSourceToCustomer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","title":"saveSourceToCustomer","navigatorTitle":[{"text":"saveSourceToCustomer","kind":"identifier"}],"platforms":[]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentparams\/savesourcetocustomer"]},{"paths":["\/documentation\/stripepayments\/stppaymentintentparams\/savesourcetocustomer"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/saveSourceToCustomer":{"url":"\/documentation\/stripepayments\/stppaymentintentparams\/savesourcetocustomer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"saveSourceToCustomer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/saveSourceToCustomer","kind":"symbol","role":"symbol","abstract":[{"type":"codeVoice","code":"@YES"},{"text":" to save this PaymentIntent’s Source to the associated Customer,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"if the Source is not already attached."},{"type":"text","text":" "},{"text":"This should be a boolean NSNumber, so that it can be ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"This property has been renamed to "},{"code":"savePaymentMethod","type":"codeVoice"},{"text":" and deprecated.","type":"text"}],"title":"saveSourceToCustomer","navigatorTitle":[{"text":"saveSourceToCustomer","kind":"identifier"}],"deprecated":true},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentParams","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentParams"}],"abstract":[{"text":"An object representing parameters used to confirm a PaymentIntent object.","type":"text"},{"text":" ","type":"text"},{"text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"That PaymentMethod or Source can either be:"}],"type":"topic","title":"STPPaymentIntentParams","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"saveSourceToCustomer","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"saveSourceToCustomer","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"saveSourceToCustomer"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1saveSourceToCustomer\/title","value":"saveSourceToCustomer"},{"value":[{"kind":"identifier","text":"saveSourceToCustomer"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1saveSourceToCustomer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/title","value":"STPPaymentIntentParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/fragments","value":[{"text":"STPPaymentIntentParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentIntentParams","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}