{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/savePaymentMethod","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"savePaymentMethod","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentParams(py)savePaymentMethod","title":"savePaymentMethod","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"savePaymentMethod"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams"]]},"abstract":[{"type":"codeVoice","code":"@YES"},{"type":"text","text":" to save this PaymentIntent’s PaymentMethod or Source to the associated Customer,"},{"type":"text","text":" "},{"type":"text","text":"if the PaymentMethod\/Source is not already attached."},{"type":"text","text":" "},{"text":"This should be a boolean NSNumber, so that it can be ","type":"text"},{"code":"nil","type":"codeVoice"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentparams\/savepaymentmethod"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentparams\/savepaymentmethod"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"savePaymentMethod","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentparams","title":"STPPaymentIntentParams","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentParams"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentIntentParams","kind":"identifier"}],"abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"type":"text","text":" "},{"text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it.","type":"text"},{"type":"text","text":" "},{"text":"That PaymentMethod or Source can either be:","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/savePaymentMethod":{"url":"\/documentation\/stripepayments\/stppaymentintentparams\/savepaymentmethod","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"savePaymentMethod","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","abstract":[{"type":"codeVoice","code":"@YES"},{"type":"text","text":" to save this PaymentIntent’s PaymentMethod or Source to the associated Customer,"},{"type":"text","text":" "},{"type":"text","text":"if the PaymentMethod\/Source is not already attached."},{"text":" ","type":"text"},{"type":"text","text":"This should be a boolean NSNumber, so that it can be "},{"type":"codeVoice","code":"nil"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/savePaymentMethod","title":"savePaymentMethod","navigatorTitle":[{"text":"savePaymentMethod","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"savePaymentMethod"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"savePaymentMethod"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"savePaymentMethod"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/title","value":"STPPaymentIntentParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/fragments","value":[{"text":"STPPaymentIntentParams","kind":"identifier"}],"op":"replace"},{"value":"savePaymentMethod","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1savePaymentMethod\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1savePaymentMethod\/fragments","op":"replace","value":[{"kind":"identifier","text":"savePaymentMethod"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
