{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/setAsDefaultPM","interfaceLanguage":"occ"},"abstract":[{"text":"@YES","type":"text"},{"text":" to set this PaymentIntent’s PaymentMethod as the associated Customer’s default","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This should be a boolean NSNumber, so that it can be "},{"text":"nil","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentparams\/setasdefaultpm"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"setAsDefaultPM"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"property","fragments":[{"kind":"identifier","text":"setAsDefaultPM"}],"roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentParams(py)setAsDefaultPM","navigatorTitle":[{"kind":"identifier","text":"setAsDefaultPM"}],"title":"setAsDefaultPM"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/setAsDefaultPM":{"abstract":[{"type":"text","text":"@YES"},{"type":"text","text":" to set this PaymentIntent’s PaymentMethod as the associated Customer’s default"},{"type":"text","text":" "},{"type":"text","text":"This should be a boolean NSNumber, so that it can be "},{"text":"nil","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/setAsDefaultPM","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentparams\/setasdefaultpm","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"setAsDefaultPM"}],"title":"setAsDefaultPM"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams":{"type":"topic","abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"type":"text","text":" "},{"text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"That PaymentMethod or Source can either be:"}],"navigatorTitle":[{"text":"STPPaymentIntentParams","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentIntentParams"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams","title":"STPPaymentIntentParams","url":"\/documentation\/stripepayments\/stppaymentintentparams","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/title","op":"replace","value":"STPPaymentIntentParams"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentIntentParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/navigatorTitle"}]}]}