{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/setupFutureUsage-4tdvn","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"setupFutureUsage","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage","text":"STPPaymentIntentSetupFutureUsage","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams"]]},"kind":"symbol","abstract":[{"type":"text","text":"When provided, this property indicates how you intend to use the payment method that your customer provides after the current payment completes."},{"text":" ","type":"text"},{"text":"If applicable, additional authentication may be performed to comply with regional legislation or network rules required to enable the usage of the same payment method for additional payments.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"StripePayments"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setupFutureUsage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage","text":"STPPaymentIntentSetupFutureUsage","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"externalID":"s:14StripePayments22STPPaymentIntentParamsC16setupFutureUsageAA0cd5SetupgH0OSgvp","symbolKind":"property","role":"symbol","title":"setupFutureUsage","roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentparams\/setupfutureusage-4tdvn"]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentparams","abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"type":"text","text":" "},{"type":"text","text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it."},{"type":"text","text":" "},{"type":"text","text":"That PaymentMethod or Source can either be:"}],"kind":"symbol","navigatorTitle":[{"text":"STPPaymentIntentParams","kind":"identifier"}],"role":"symbol","title":"STPPaymentIntentParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentIntentParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"title":"STPPaymentIntentSetupFutureUsage","abstract":[{"text":"Indicates how you intend to use the payment method that your customer provides after the current payment completes.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If applicable, additional authentication may be performed to comply with regional legislation or network rules required to enable the usage of the same payment method for additional payments."}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsage"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/setupFutureUsage-4tdvn":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/setupFutureUsage-4tdvn","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupFutureUsage","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage","text":"STPPaymentIntentSetupFutureUsage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"setupFutureUsage","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentparams\/setupfutureusage-4tdvn","abstract":[{"text":"When provided, this property indicates how you intend to use the payment method that your customer provides after the current payment completes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If applicable, additional authentication may be performed to comply with regional legislation or network rules required to enable the usage of the same payment method for additional payments."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPPaymentIntentParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/title"},{"op":"replace","value":[{"text":"STPPaymentIntentParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/navigatorTitle","value":[{"text":"STPPaymentIntentParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/title","value":"STPPaymentIntentSetupFutureUsage","op":"replace"},{"value":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/navigatorTitle","value":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"op":"replace"}]}]}