{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams"]]},"metadata":{"title":"useStripeSDK","role":"symbol","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentParams(py)useStripeSDK","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useStripeSDK"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"useStripeSDK"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"A boolean number to indicate whether you intend to use the Stripe SDK’s functionality to handle any PaymentIntent next actions.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If set to false, STPPaymentIntent.nextAction will only ever contain a redirect url that can be opened in a webview or mobile browser."},{"text":" ","type":"text"},{"text":"When set to true, the nextAction may contain information that the Stripe SDK can use to perform native authentication within your","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"app."}],"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/useStripeSDK","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"useStripeSDK","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentparams\/usestripesdk"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentparams\/usestripesdk"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/useStripeSDK":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/useStripeSDK","url":"\/documentation\/stripepayments\/stppaymentintentparams\/usestripesdk","kind":"symbol","title":"useStripeSDK","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useStripeSDK","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"text":"A boolean number to indicate whether you intend to use the Stripe SDK’s functionality to handle any PaymentIntent next actions.","type":"text"},{"type":"text","text":" "},{"text":"If set to false, STPPaymentIntent.nextAction will only ever contain a redirect url that can be opened in a webview or mobile browser.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"When set to true, the nextAction may contain information that the Stripe SDK can use to perform native authentication within your"},{"text":" ","type":"text"},{"type":"text","text":"app."}],"navigatorTitle":[{"kind":"identifier","text":"useStripeSDK"}],"type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams":{"url":"\/documentation\/stripepayments\/stppaymentintentparams","role":"symbol","title":"STPPaymentIntentParams","navigatorTitle":[{"text":"STPPaymentIntentParams","kind":"identifier"}],"abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"text":" ","type":"text"},{"type":"text","text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it."},{"text":" ","type":"text"},{"text":"That PaymentMethod or Source can either be:","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentIntentParams"}],"type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"useStripeSDK","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"useStripeSDK"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" * "},{"text":"useStripeSDK","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"value":"useStripeSDK","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1useStripeSDK\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1useStripeSDK\/fragments","value":[{"text":"useStripeSDK","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/title","value":"STPPaymentIntentParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/fragments","value":[{"text":"STPPaymentIntentParams","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntentParams"}]}]}]}