{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionAlipayHandleRedirect","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionAlipayHandleRedirect\/STPAPIResponseDecodable-Implementations"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionAlipayHandleRedirect\/decodedObject(fromAPIResponse:)"},"abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"type":"text","text":" "},{"type":"text","text":"an "},{"type":"codeVoice","code":"NSDictionary"},{"text":") into an instance of the class.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodedObject"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":" "},{"text":"response","kind":"internalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The JSON dictionary that represents an object of this type","type":"text"}],"type":"paragraph"}],"name":"response"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The object represented by the JSON dictionary, or nil if the object","type":"text"},{"type":"text","text":" "},{"type":"text","text":"could not be decoded (i.e. if one of its "},{"type":"codeVoice","code":"requiredFields"},{"type":"text","text":" is nil)."}]}]}],"metadata":{"externalID":"c:@CM@StripePayments@objc(cs)STPIntentActionAlipayHandleRedirect(cm)decodedObjectFromAPIResponse:","roleHeading":"Type Method","title":"decodedObject(fromAPIResponse:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedObject"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"text":"?","kind":"text"}],"modules":[{"name":"StripePayments"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"role":"symbol","extendedModule":"StripePayments"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactionalipayhandleredirect\/decodedobject(fromapiresponse:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactionalipayhandleredirect\/decodedobject(fromapiresponse:)"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionAlipayHandleRedirect/decodedObject(fromAPIResponse:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"title":"decodedObject(fromAPIResponse:)","kind":"symbol","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentactionalipayhandleredirect\/decodedobject(fromapiresponse:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionAlipayHandleRedirect\/decodedObject(fromAPIResponse:)","abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"text":" ","type":"text"},{"type":"text","text":"an "},{"type":"codeVoice","code":"NSDictionary"},{"text":") into an instance of the class.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionAlipayHandleRedirect/STPAPIResponseDecodable-Implementations":{"role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionAlipayHandleRedirect\/STPAPIResponseDecodable-Implementations","title":"STPAPIResponseDecodable Implementations","url":"\/documentation\/stripepayments\/stpintentactionalipayhandleredirect\/stpapiresponsedecodable-implementations","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionAlipayHandleRedirect":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionAlipayHandleRedirect","navigatorTitle":[{"text":"STPIntentActionAlipayHandleRedirect","kind":"identifier"}],"title":"STPIntentActionAlipayHandleRedirect","url":"\/documentation\/stripepayments\/stpintentactionalipayhandleredirect","abstract":[{"text":"Contains instructions for authenticating a payment by redirecting your customer to Alipay App or website.","type":"text"},{"type":"text","text":" "},{"text":"You cannot directly instantiate an ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntentActionAlipayHandleRedirect"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPIntentActionAlipayHandleRedirect"}],"type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"decodedObjectFromAPIResponse:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"response"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionAlipayHandleRedirect~1decodedObject(fromAPIResponse:)\/title","value":"decodedObjectFromAPIResponse:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionAlipayHandleRedirect~1decodedObject(fromAPIResponse:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"op":"replace"},{"op":"replace","value":"STPIntentActionAlipayHandleRedirect","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionAlipayHandleRedirect\/title"},{"value":[{"kind":"identifier","text":"STPIntentActionAlipayHandleRedirect"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionAlipayHandleRedirect\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionAlipayHandleRedirect\/navigatorTitle","value":[{"text":"STPIntentActionAlipayHandleRedirect","kind":"identifier"}]}]}]}