{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"returnURL","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionAlipayHandleRedirect\/returnURL","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactionalipayhandleredirect\/returnurl"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactionalipayhandleredirect\/returnurl"]}],"abstract":[{"type":"text","text":"If the customer does not exit their browser while authenticating, they will be redirected to this specified URL after completion."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionAlipayHandleRedirect"]]},"metadata":{"symbolKind":"property","title":"returnURL","modules":[{"name":"StripePayments"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPIntentActionAlipayHandleRedirect(py)returnURL","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnURL"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"}],"navigatorTitle":[{"kind":"identifier","text":"returnURL"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","role":"collection","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionAlipayHandleRedirect/returnURL":{"title":"returnURL","abstract":[{"type":"text","text":"If the customer does not exit their browser while authenticating, they will be redirected to this specified URL after completion."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionAlipayHandleRedirect\/returnURL","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"}],"url":"\/documentation\/stripepayments\/stpintentactionalipayhandleredirect\/returnurl","navigatorTitle":[{"kind":"identifier","text":"returnURL"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionAlipayHandleRedirect":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionAlipayHandleRedirect","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to Alipay App or website."},{"type":"text","text":" "},{"text":"You cannot directly instantiate an ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntentActionAlipayHandleRedirect"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"STPIntentActionAlipayHandleRedirect","kind":"identifier"}],"title":"STPIntentActionAlipayHandleRedirect","url":"\/documentation\/stripepayments\/stpintentactionalipayhandleredirect","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionAlipayHandleRedirect","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"returnURL"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"returnURL","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"kind":"text","text":" * "},{"kind":"identifier","text":"returnURL"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionAlipayHandleRedirect~1returnURL\/title","op":"replace","value":"returnURL"},{"value":[{"text":"returnURL","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionAlipayHandleRedirect~1returnURL\/fragments","op":"replace"},{"value":"STPIntentActionAlipayHandleRedirect","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionAlipayHandleRedirect\/title"},{"value":[{"text":"STPIntentActionAlipayHandleRedirect","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionAlipayHandleRedirect\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
