{"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactionalipayhandleredirect\/stpapiresponsedecodable-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactionalipayhandleredirect\/stpapiresponsedecodable-implementations"]}],"sections":[],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionAlipayHandleRedirect"]]},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionAlipayHandleRedirect\/decodedObject(fromAPIResponse:)"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"STPAPIResponseDecodable Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"StripePayments"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionAlipayHandleRedirect\/STPAPIResponseDecodable-Implementations","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionAlipayHandleRedirect/decodedObject(fromAPIResponse:)":{"url":"\/documentation\/stripepayments\/stpintentactionalipayhandleredirect\/decodedobject(fromapiresponse:)","abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"type":"text","text":" "},{"type":"text","text":"an "},{"type":"codeVoice","code":"NSDictionary"},{"type":"text","text":") into an instance of the class."}],"role":"symbol","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"title":"decodedObject(fromAPIResponse:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionAlipayHandleRedirect\/decodedObject(fromAPIResponse:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionAlipayHandleRedirect":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionAlipayHandleRedirect","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPIntentActionAlipayHandleRedirect","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPIntentActionAlipayHandleRedirect"}],"title":"STPIntentActionAlipayHandleRedirect","url":"\/documentation\/stripepayments\/stpintentactionalipayhandleredirect","abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to Alipay App or website."},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"code":"STPPaymentIntentActionAlipayHandleRedirect","type":"codeVoice"},{"type":"text","text":"."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionAlipayHandleRedirect\/decodedObject(fromAPIResponse:)"],"generated":true}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionAlipayHandleRedirect~1decodedObject(fromAPIResponse:)\/title","op":"replace","value":"decodedObjectFromAPIResponse:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionAlipayHandleRedirect~1decodedObject(fromAPIResponse:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]},{"op":"replace","value":"STPIntentActionAlipayHandleRedirect","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionAlipayHandleRedirect\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionAlipayHandleRedirect\/fragments","value":[{"text":"STPIntentActionAlipayHandleRedirect","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionAlipayHandleRedirect\/navigatorTitle","op":"replace","value":[{"text":"STPIntentActionAlipayHandleRedirect","kind":"identifier"}]}]}]}