{"abstract":[{"type":"text","text":"Owner’s address."}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceowner\/address"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceowner\/address"]}],"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/address","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner"]]},"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPSourceOwner(py)address","modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","title":"address","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"address"},{"text":": ","kind":"text"},{"text":"STPAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"address","kind":"identifier"}],"role":"symbol","symbolKind":"property"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"address"},{"text":": ","kind":"text"},{"text":"STPAddress","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceOwner":{"url":"\/documentation\/stripepayments\/stpsourceowner","abstract":[{"text":"Information about a source’s owner.","type":"text"}],"title":"STPSourceOwner","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceOwner","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceOwner"}],"role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress":{"url":"\/documentation\/stripepayments\/stpaddress","title":"STPAddress","kind":"symbol","navigatorTitle":[{"text":"STPAddress","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAddress"}],"type":"topic","abstract":[{"text":"STPAddress Contains an address as represented by the Stripe API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","role":"collection","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceOwner/address":{"url":"\/documentation\/stripepayments\/stpsourceowner\/address","abstract":[{"type":"text","text":"Owner’s address."}],"title":"address","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"address","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/address","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"address"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"address","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"address"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"STPAddress","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"text":" * ","kind":"text"},{"text":"address","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"STPSourceOwner","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner\/fragments","op":"replace","value":[{"text":"STPSourceOwner","kind":"identifier"}]},{"value":"STPAddress","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/title","op":"replace"},{"op":"replace","value":[{"text":"STPAddress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1address\/title","op":"replace","value":"address"},{"op":"replace","value":[{"text":"address","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1address\/fragments"}]}]}
