{"abstract":[{"text":"Verified owner’s email address.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner"]]},"sections":[],"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPSourceOwner(py)verifiedEmail","title":"verifiedEmail","symbolKind":"property","navigatorTitle":[{"text":"verifiedEmail","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verifiedEmail"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/verifiedEmail","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceowner\/verifiedemail"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceowner\/verifiedemail"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verifiedEmail"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? { get }","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceOwner/verifiedEmail":{"abstract":[{"text":"Verified owner’s email address.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"verifiedEmail","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceowner\/verifiedemail","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"verifiedEmail","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/verifiedEmail","title":"verifiedEmail"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceOwner":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner","url":"\/documentation\/stripepayments\/stpsourceowner","kind":"symbol","abstract":[{"type":"text","text":"Information about a source’s owner."}],"title":"STPSourceOwner","role":"symbol","type":"topic","navigatorTitle":[{"text":"STPSourceOwner","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceOwner","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"verifiedEmail","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"verifiedEmail"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"verifiedEmail","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"verifiedEmail","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1verifiedEmail\/title"},{"value":[{"text":"verifiedEmail","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1verifiedEmail\/fragments","op":"replace"},{"op":"replace","value":"STPSourceOwner","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner\/fragments","value":[{"text":"STPSourceOwner","kind":"identifier"}]},{"op":"replace","value":[{"text":"STPSourceOwner","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}