{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"full"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpbillingaddressfields\/full"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpbillingaddressfields\/full"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/full","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Request the user’s full billing address"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"full"}],"title":"STPBillingAddressFields.full","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@Stripe@E@STPBillingAddressFields@STPBillingAddressFieldsFull","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"STPBillingAddressFieldsFull"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields/full":{"role":"symbol","title":"STPBillingAddressFields.full","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"full"}],"abstract":[{"type":"text","text":"Request the user’s full billing address"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/full","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBillingAddressFieldsFull"}],"url":"\/documentation\/stripe\/stpbillingaddressfields\/full"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields":{"role":"symbol","title":"STPBillingAddressFields","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBillingAddressFields"}],"abstract":[{"type":"text","text":"What set of billing address information you need to collect from your user."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBillingAddressFields"}],"url":"\/documentation\/stripe\/stpbillingaddressfields"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPBillingAddressFieldsFull"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPBillingAddressFieldsFull"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPBillingAddressFieldsFull"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields~1full\/title","value":"STPBillingAddressFieldsFull"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields~1full\/fragments","value":[{"kind":"identifier","text":"STPBillingAddressFieldsFull"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields\/title","value":"STPBillingAddressFields"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields\/fragments","value":[{"kind":"identifier","text":"STPBillingAddressFields"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}