{"sections":[],"kind":"symbol","metadata":{"symbolKind":"case","title":"STPBillingAddressFields.name","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"}],"role":"symbol","modules":[{"name":"Stripe"}],"externalID":"c:@M@Stripe@E@STPBillingAddressFields@STPBillingAddressFieldsName","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"STPBillingAddressFieldsName"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/name"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpbillingaddressfields\/name"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpbillingaddressfields\/name"]}],"abstract":[{"text":"Just request the user’s billing name","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields/name":{"abstract":[{"text":"Just request the user’s billing name","type":"text"}],"title":"STPBillingAddressFields.name","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/stripe\/stpbillingaddressfields\/name","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/name","kind":"symbol","navigatorTitle":[{"text":"STPBillingAddressFieldsName","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields":{"kind":"symbol","abstract":[{"text":"What set of billing address information you need to collect from your user.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPBillingAddressFields","kind":"identifier"}],"navigatorTitle":[{"text":"STPBillingAddressFields","kind":"identifier"}],"title":"STPBillingAddressFields","url":"\/documentation\/stripe\/stpbillingaddressfields","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPBillingAddressFieldsName","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPBillingAddressFieldsName"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPBillingAddressFieldsName"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPBillingAddressFieldsName","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields~1name\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields~1name\/fragments","op":"replace","value":[{"text":"STPBillingAddressFieldsName","kind":"identifier"}]},{"op":"replace","value":"STPBillingAddressFields","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields\/fragments","value":[{"text":"STPBillingAddressFields","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
