{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpbillingaddressfields\/none"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpbillingaddressfields\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/none","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"No billing address information"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"title":"STPBillingAddressFields.none","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@Stripe@E@STPBillingAddressFields@STPBillingAddressFieldsNone","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"STPBillingAddressFieldsNone"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields":{"role":"symbol","title":"STPBillingAddressFields","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBillingAddressFields"}],"abstract":[{"type":"text","text":"What set of billing address information you need to collect from your user."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBillingAddressFields"}],"url":"\/documentation\/stripe\/stpbillingaddressfields"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields/none":{"role":"symbol","title":"STPBillingAddressFields.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[{"type":"text","text":"No billing address information"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBillingAddressFieldsNone"}],"url":"\/documentation\/stripe\/stpbillingaddressfields\/none"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPBillingAddressFieldsNone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPBillingAddressFieldsNone"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPBillingAddressFieldsNone"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields\/title","value":"STPBillingAddressFields"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields\/fragments","value":[{"kind":"identifier","text":"STPBillingAddressFields"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields~1none\/title","value":"STPBillingAddressFieldsNone"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields~1none\/fragments","value":[{"kind":"identifier","text":"STPBillingAddressFieldsNone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
