{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpbillingaddressfields\/postalcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpbillingaddressfields\/postalcode"]}],"metadata":{"title":"STPBillingAddressFields.postalCode","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"postalCode"}],"navigatorTitle":[{"text":"STPBillingAddressFieldsPostalCode","kind":"identifier"}],"role":"symbol","externalID":"c:@M@Stripe@E@STPBillingAddressFields@STPBillingAddressFieldsPostalCode","symbolKind":"case","modules":[{"name":"Stripe"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/postalCode"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"postalCode","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields"]]},"abstract":[{"text":"Just request the user’s billing postal code","type":"text"}],"sections":[],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields":{"kind":"symbol","abstract":[{"text":"What set of billing address information you need to collect from your user.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPBillingAddressFields","kind":"identifier"}],"navigatorTitle":[{"text":"STPBillingAddressFields","kind":"identifier"}],"title":"STPBillingAddressFields","url":"\/documentation\/stripe\/stpbillingaddressfields","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields/postalCode":{"kind":"symbol","abstract":[{"type":"text","text":"Just request the user’s billing postal code"}],"title":"STPBillingAddressFields.postalCode","navigatorTitle":[{"kind":"identifier","text":"STPBillingAddressFieldsPostalCode"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"postalCode"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/postalCode","url":"\/documentation\/stripe\/stpbillingaddressfields\/postalcode","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"STPBillingAddressFieldsPostalCode"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"STPBillingAddressFieldsPostalCode","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPBillingAddressFieldsPostalCode","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields\/title","value":"STPBillingAddressFields"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields\/fragments","value":[{"kind":"identifier","text":"STPBillingAddressFields"}]},{"value":"STPBillingAddressFieldsPostalCode","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields~1postalCode\/title"},{"op":"replace","value":[{"text":"STPBillingAddressFieldsPostalCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields~1postalCode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
