{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"zip"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpbillingaddressfields\/zip"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpbillingaddressfields\/zip"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/zip","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Just request the user’s billing ZIP (synonym for STPBillingAddressFieldsZip)"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"STPBillingAddressFieldsZip"}],"role":"symbol","title":"STPBillingAddressFields.zip","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"zip"}],"symbolKind":"case","externalID":"c:@M@Stripe@E@STPBillingAddressFields@STPBillingAddressFieldsZip","modules":[{"name":"Stripe"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use STPBillingAddressFields.postalCode instead"}]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields":{"role":"symbol","title":"STPBillingAddressFields","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBillingAddressFields"}],"abstract":[{"type":"text","text":"What set of billing address information you need to collect from your user."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBillingAddressFields"}],"url":"\/documentation\/stripe\/stpbillingaddressfields"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields/zip":{"deprecated":true,"role":"symbol","title":"STPBillingAddressFields.zip","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"zip"}],"abstract":[{"type":"text","text":"Just request the user’s billing ZIP (synonym for STPBillingAddressFieldsZip)"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/zip","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBillingAddressFieldsZip"}],"url":"\/documentation\/stripe\/stpbillingaddressfields\/zip"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPBillingAddressFieldsZip"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPBillingAddressFieldsZip"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPBillingAddressFieldsZip"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields\/title","value":"STPBillingAddressFields"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields\/fragments","value":[{"kind":"identifier","text":"STPBillingAddressFields"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields~1zip\/title","value":"STPBillingAddressFieldsZip"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields~1zip\/fragments","value":[{"kind":"identifier","text":"STPBillingAddressFieldsZip"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}