{"metadata":{"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodAlipayParams(im)init","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipayParams\/init","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipayParams"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodalipayparams\/init"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAlipayParams/init":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipayParams\/init","title":"init","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodalipayparams\/init","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAlipayParams":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodalipayparams","title":"STPPaymentMethodAlipayParams","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodAlipayParams"}],"abstract":[{"type":"text","text":"An object representing parameters used to create an Alipay Payment Method."},{"text":" ","type":"text"},{"text":"There are currently no parameters to pass.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodAlipayParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipayParams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipayParams\/title","value":"STPPaymentMethodAlipayParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipayParams\/fragments","op":"replace","value":[{"text":"STPPaymentMethodAlipayParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipayParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodAlipayParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}