{"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodalipayparams\/propertynamestoformfieldnamesmapping()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodalipayparams\/propertynamestoformfieldnamesmapping()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipayParams\/propertyNamesToFormFieldNamesMapping()","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Method","navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"title":"propertyNamesToFormFieldNamesMapping()","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodAlipayParams(cm)propertyNamesToFormFieldNamesMapping","symbolKind":"method","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"},{"kind":"text","text":"() -> ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"modules":[{"name":"StripePayments"}]},"abstract":[{"type":"text","text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called "},{"type":"codeVoice","code":"expMonth"},{"type":"text","text":", but the Stripe API expects a field called "},{"type":"codeVoice","code":"exp_month"},{"text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipayParams"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAlipayParams/propertyNamesToFormFieldNamesMapping()":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipayParams\/propertyNamesToFormFieldNamesMapping()","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}],"title":"propertyNamesToFormFieldNamesMapping()","url":"\/documentation\/stripepayments\/stppaymentmethodalipayparams\/propertynamestoformfieldnamesmapping()","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called "},{"code":"expMonth","type":"codeVoice"},{"text":", but the Stripe API expects a field called ","type":"text"},{"type":"codeVoice","code":"exp_month"},{"type":"text","text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAlipayParams":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodAlipayParams"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodAlipayParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipayParams","title":"STPPaymentMethodAlipayParams","abstract":[{"type":"text","text":"An object representing parameters used to create an Alipay Payment Method."},{"type":"text","text":" "},{"text":"There are currently no parameters to pass.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodalipayparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"propertyNamesToFormFieldNamesMapping","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"propertyNamesToFormFieldNamesMapping","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipayParams~1propertyNamesToFormFieldNamesMapping()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipayParams~1propertyNamesToFormFieldNamesMapping()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipayParams\/title","value":"STPPaymentMethodAlipayParams","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipayParams\/fragments","value":[{"text":"STPPaymentMethodAlipayParams","kind":"identifier"}]},{"value":[{"text":"STPPaymentMethodAlipayParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipayParams\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}