{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/!=(_:_:)"],"title":"Operators","anchor":"Operators"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/Equatable-Implementations","interfaceLanguage":"swift"},"kind":"article","sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpcollectbankaccounterror\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"collectionGroup","modules":[{"name":"StripePayments"}],"title":"Equatable Implementations","roleHeading":"API Collection"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountError":{"url":"\/documentation\/stripepayments\/stpcollectbankaccounterror","abstract":[{"text":"Error codes generated by STPBankAccountCollector","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCollectBankAccountError","kind":"identifier"}],"navigatorTitle":[{"text":"STPCollectBankAccountError","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError","type":"topic","kind":"symbol","title":"STPCollectBankAccountError","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountError/!=(_:_:)":{"kind":"symbol","title":"!=(_:_:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/!=(_:_:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/stripepayments\/stpcollectbankaccounterror\/!=(_:_:)","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"value":"STPCollectBankAccountError","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError\/title","op":"replace"},{"value":[{"text":"STPCollectBankAccountError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPCollectBankAccountError"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}