{"abstract":[{"type":"text","text":"Error when using APIs that require the linking the StripeFinancialConnections SDK"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcollectbankaccounterror\/financialconnectionssdknotlinked"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcollectbankaccounterror\/financialconnectionssdknotlinked"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(STPCollectBankAccountErrorFinancialConnectionsSDKNotLinked) "},{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"financialConnectionsSDKNotLinked"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"metadata":{"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"STPCollectBankAccountErrorFinancialConnectionsSDKNotLinked"}],"externalID":"c:@M@StripePayments@E@STPCollectBankAccountError@STPCollectBankAccountErrorFinancialConnectionsSDKNotLinked","title":"STPCollectBankAccountError.financialConnectionsSDKNotLinked","modules":[{"name":"StripePayments"}],"symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"financialConnectionsSDKNotLinked"}]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/financialConnectionsSDKNotLinked","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountError":{"navigatorTitle":[{"kind":"identifier","text":"STPCollectBankAccountError"}],"title":"STPCollectBankAccountError","abstract":[{"type":"text","text":"Error codes generated by STPBankAccountCollector"}],"url":"\/documentation\/stripepayments\/stpcollectbankaccounterror","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCollectBankAccountError"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","kind":"symbol","title":"StripePayments","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountError/financialConnectionsSDKNotLinked":{"navigatorTitle":[{"text":"STPCollectBankAccountErrorFinancialConnectionsSDKNotLinked","kind":"identifier"}],"title":"STPCollectBankAccountError.financialConnectionsSDKNotLinked","abstract":[{"text":"Error when using APIs that require the linking the StripeFinancialConnections SDK","type":"text"}],"url":"\/documentation\/stripepayments\/stpcollectbankaccounterror\/financialconnectionssdknotlinked","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/financialConnectionsSDKNotLinked","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"financialConnectionsSDKNotLinked","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"STPCollectBankAccountErrorFinancialConnectionsSDKNotLinked"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPCollectBankAccountErrorFinancialConnectionsSDKNotLinked"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"STPCollectBankAccountErrorFinancialConnectionsSDKNotLinked","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError\/title","op":"replace","value":"STPCollectBankAccountError"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPCollectBankAccountError"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPCollectBankAccountError"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError~1financialConnectionsSDKNotLinked\/title","op":"replace","value":"STPCollectBankAccountErrorFinancialConnectionsSDKNotLinked"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError~1financialConnectionsSDKNotLinked\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPCollectBankAccountErrorFinancialConnectionsSDKNotLinked"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}