{"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/unexpectedError","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(STPCollectBankAccountErrorUnexpectedError) ","kind":"text"},{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unexpectedError","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unexpectedError","kind":"identifier"}],"role":"symbol","symbolKind":"case","roleHeading":"Case","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"STPCollectBankAccountErrorUnexpectedError"}],"externalID":"c:@M@StripePayments@E@STPCollectBankAccountError@STPCollectBankAccountErrorUnexpectedError","title":"STPCollectBankAccountError.unexpectedError"},"abstract":[{"type":"text","text":"Unexpected behavior in calling the API"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpcollectbankaccounterror\/unexpectederror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcollectbankaccounterror\/unexpectederror"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountError/unexpectedError":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/unexpectedError","kind":"symbol","role":"symbol","title":"STPCollectBankAccountError.unexpectedError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unexpectedError","kind":"identifier"}],"abstract":[{"type":"text","text":"Unexpected behavior in calling the API"}],"navigatorTitle":[{"text":"STPCollectBankAccountErrorUnexpectedError","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpcollectbankaccounterror\/unexpectederror"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountError":{"url":"\/documentation\/stripepayments\/stpcollectbankaccounterror","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Error codes generated by STPBankAccountCollector"}],"navigatorTitle":[{"text":"STPCollectBankAccountError","kind":"identifier"}],"title":"STPCollectBankAccountError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCollectBankAccountError","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPCollectBankAccountErrorUnexpectedError","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"STPCollectBankAccountErrorUnexpectedError","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"STPCollectBankAccountErrorUnexpectedError","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPCollectBankAccountErrorUnexpectedError","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError~1unexpectedError\/title","op":"replace"},{"value":[{"text":"STPCollectBankAccountErrorUnexpectedError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError~1unexpectedError\/fragments","op":"replace"},{"value":"STPCollectBankAccountError","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError\/title","op":"replace"},{"value":[{"text":"STPCollectBankAccountError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError\/fragments","op":"replace"},{"value":[{"text":"STPCollectBankAccountError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}