{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/confirmationMethod"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintent\/confirmationmethod"]},{"paths":["\/documentation\/stripepayments\/stppaymentintent\/confirmationmethod"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Confirmation method of this PaymentIntent"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmationMethod"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod","kind":"typeIdentifier","text":"STPPaymentIntentConfirmationMethod","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentConfirmationMethod"}],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"modules":[{"name":"StripePayments"}],"title":"confirmationMethod","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"confirmationMethod","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"confirmationMethod","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentIntentConfirmationMethod","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentConfirmationMethod"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntent(py)confirmationMethod","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmationMethod":{"title":"STPPaymentIntentConfirmationMethod","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentIntentConfirmationMethod"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentConfirmationMethod"}],"abstract":[{"type":"text","text":"Confirmation methods for a STPPaymentIntent"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod","url":"\/documentation\/stripepayments\/stppaymentintentconfirmationmethod","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntent"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntent"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","abstract":[{"type":"text","text":"A PaymentIntent tracks the process of collecting a payment from your customer."}],"url":"\/documentation\/stripepayments\/stppaymentintent","role":"symbol","title":"STPPaymentIntent"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/confirmationMethod":{"abstract":[{"text":"Confirmation method of this PaymentIntent","type":"text"}],"title":"confirmationMethod","role":"symbol","navigatorTitle":[{"text":"confirmationMethod","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/confirmationMethod","url":"\/documentation\/stripepayments\/stppaymentintent\/confirmationmethod","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"confirmationMethod","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentConfirmationMethod","kind":"typeIdentifier","text":"STPPaymentIntentConfirmationMethod"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"confirmationMethod","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"confirmationMethod"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentIntentConfirmationMethod","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentConfirmationMethod"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confirmationMethod"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod\/title","value":"STPPaymentIntentConfirmationMethod","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentConfirmationMethod"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod\/navigatorTitle","value":[{"text":"STPPaymentIntentConfirmationMethod","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title","value":"STPPaymentIntent","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments","value":[{"text":"STPPaymentIntent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle","value":[{"text":"STPPaymentIntent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1confirmationMethod\/title","value":"confirmationMethod","op":"replace"},{"value":[{"text":"confirmationMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1confirmationMethod\/fragments"}]}]}