{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextAction"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentAction","text":"STPIntentAction","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"If "},{"code":"status == .requiresAction","type":"codeVoice"},{"type":"text","text":", this"},{"type":"text","text":" "},{"text":"property contains the next action to take for this PaymentIntent.","type":"text"}],"metadata":{"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntent(py)nextAction","navigatorTitle":[{"kind":"identifier","text":"nextAction"}],"title":"nextAction","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPIntentAction","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentAction"},{"text":"?","kind":"text"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintent\/nextaction"]},{"paths":["\/documentation\/stripepayments\/stppaymentintent\/nextaction"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/nextAction"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPIntentAction","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Next action details for ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":" and "},{"type":"codeVoice","code":"STPSetupIntent"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"This is a container for the various types that are available.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Check the "},{"code":"type","type":"codeVoice"},{"type":"text","text":" to see which one it is, and then use the related"},{"text":" ","type":"text"},{"type":"text","text":"property for the details necessary to handle it."},{"type":"text","text":" "},{"text":"You cannot directly instantiate an ","type":"text"},{"type":"codeVoice","code":"STPIntentAction"},{"type":"text","text":"."}],"title":"STPIntentAction","navigatorTitle":[{"text":"STPIntentAction","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","url":"\/documentation\/stripepayments\/stpintentaction","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"type":"topic","abstract":[{"text":"A PaymentIntent tracks the process of collecting a payment from your customer.","type":"text"}],"navigatorTitle":[{"text":"STPPaymentIntent","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntent"}],"kind":"symbol","title":"STPPaymentIntent","url":"\/documentation\/stripepayments\/stppaymentintent"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/nextAction":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/nextAction","title":"nextAction","abstract":[{"type":"text","text":"If "},{"type":"codeVoice","code":"status == .requiresAction"},{"text":", this","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"property contains the next action to take for this PaymentIntent."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextAction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPIntentAction","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentAction","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nextAction"}],"url":"\/documentation\/stripepayments\/stppaymentintent\/nextaction"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"nextAction"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"nextAction"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentAction","text":"STPIntentAction","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"nextAction","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/title","value":"STPIntentAction"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/fragments","value":[{"text":"STPIntentAction","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/navigatorTitle","op":"replace","value":[{"text":"STPIntentAction","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title","value":"STPPaymentIntent"},{"value":[{"kind":"identifier","text":"STPPaymentIntent"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle","value":[{"text":"STPPaymentIntent","kind":"identifier"}]},{"value":"nextAction","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1nextAction\/title"},{"value":[{"kind":"identifier","text":"nextAction"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1nextAction\/fragments","op":"replace"}]}]}