{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextSourceAction"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentAction","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","text":"STPIntentAction"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"abstract":[{"text":"If ","type":"text"},{"code":"status == STPPaymentIntentStatusRequiresAction","type":"codeVoice"},{"type":"text","text":", this"},{"type":"text","text":" "},{"type":"text","text":"property contains the next source action to take for this PaymentIntent."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/nextSourceAction"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use nextAction instead"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintent\/nextsourceaction"]},{"paths":["\/documentation\/stripepayments\/stppaymentintent\/nextsourceaction"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","platforms":[],"externalID":"c:@CM@StripePayments@objc(cs)STPPaymentIntent(py)nextSourceAction","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"nextSourceAction","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentAction","text":"STPIntentAction","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"nextSourceAction","modules":[{"name":"StripePayments"}],"extendedModule":"StripePayments","navigatorTitle":[{"kind":"identifier","text":"nextSourceAction"}],"role":"symbol"},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction":{"url":"\/documentation\/stripepayments\/stpintentaction","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPIntentAction","kind":"identifier"}],"navigatorTitle":[{"text":"STPIntentAction","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","abstract":[{"type":"text","text":"Next action details for "},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":" and "},{"code":"STPSetupIntent","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"This is a container for the various types that are available.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Check the "},{"code":"type","type":"codeVoice"},{"type":"text","text":" to see which one it is, and then use the related"},{"type":"text","text":" "},{"text":"property for the details necessary to handle it.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"You cannot directly instantiate an "},{"code":"STPIntentAction","type":"codeVoice"},{"text":".","type":"text"}],"title":"STPIntentAction","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/nextSourceAction":{"type":"topic","kind":"symbol","role":"symbol","deprecated":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nextSourceAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentAction","text":"STPIntentAction"},{"text":"?","kind":"text"}],"abstract":[{"text":"If ","type":"text"},{"type":"codeVoice","code":"status == STPPaymentIntentStatusRequiresAction"},{"text":", this","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"property contains the next source action to take for this PaymentIntent."}],"title":"nextSourceAction","url":"\/documentation\/stripepayments\/stppaymentintent\/nextsourceaction","navigatorTitle":[{"kind":"identifier","text":"nextSourceAction"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/nextSourceAction"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"navigatorTitle":[{"text":"STPPaymentIntent","kind":"identifier"}],"title":"STPPaymentIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A PaymentIntent tracks the process of collecting a payment from your customer."}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentintent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentIntent"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":[],"op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"nextSourceAction","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"nextSourceAction"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentAction","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","text":"STPIntentAction"},{"text":" * ","kind":"text"},{"text":"nextSourceAction","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/title","value":"STPIntentAction","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/fragments","value":[{"kind":"identifier","text":"STPIntentAction"}]},{"op":"replace","value":[{"text":"STPIntentAction","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/navigatorTitle"},{"value":"nextSourceAction","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1nextSourceAction\/title"},{"value":[{"kind":"identifier","text":"nextSourceAction"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1nextSourceAction\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title","value":"STPPaymentIntent","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments","value":[{"text":"STPPaymentIntent","kind":"identifier"}]},{"value":[{"text":"STPPaymentIntent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle","op":"replace"}]}]}