{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"The list of payment method types (e.g. "},{"type":"codeVoice","code":"[NSNumber(value: STPPaymentMethodType.card.rawValue)]"},{"text":") that this PaymentIntent is allowed to use.","type":"text"}],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntent(py)paymentMethodTypes","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"paymentMethodTypes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]"}],"title":"paymentMethodTypes","navigatorTitle":[{"text":"paymentMethodTypes","kind":"identifier"}],"symbolKind":"property"},"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintent\/paymentmethodtypes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintent\/paymentmethodtypes"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/paymentMethodTypes"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"paymentMethodTypes","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/paymentMethodTypes":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/paymentMethodTypes","kind":"symbol","abstract":[{"text":"The list of payment method types (e.g. ","type":"text"},{"type":"codeVoice","code":"[NSNumber(value: STPPaymentMethodType.card.rawValue)]"},{"type":"text","text":") that this PaymentIntent is allowed to use."}],"title":"paymentMethodTypes","url":"\/documentation\/stripepayments\/stppaymentintent\/paymentmethodtypes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentMethodTypes"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"paymentMethodTypes","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"]","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","title":"STPPaymentIntent","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentIntent","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntent"}],"abstract":[{"type":"text","text":"A PaymentIntent tracks the process of collecting a payment from your customer."}],"url":"\/documentation\/stripepayments\/stppaymentintent","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"paymentMethodTypes","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"paymentMethodTypes"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"paymentMethodTypes"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1paymentMethodTypes\/title","value":"paymentMethodTypes","op":"replace"},{"value":[{"kind":"identifier","text":"paymentMethodTypes"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1paymentMethodTypes\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title","value":"STPPaymentIntent","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments","op":"replace","value":[{"text":"STPPaymentIntent","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
