{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shipping"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetails","kind":"typeIdentifier","text":"STPPaymentIntentShippingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetails"},{"kind":"text","text":"?"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntent(py)shipping","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shipping","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetails","text":"STPPaymentIntentShippingDetails","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"shipping","kind":"identifier"}],"title":"shipping","role":"symbol","modules":[{"name":"StripePayments"}]},"kind":"symbol","abstract":[{"text":"Shipping information for this PaymentIntent.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintent\/shipping"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintent\/shipping"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/shipping","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/shipping":{"abstract":[{"type":"text","text":"Shipping information for this PaymentIntent."}],"role":"symbol","kind":"symbol","title":"shipping","navigatorTitle":[{"kind":"identifier","text":"shipping"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shipping"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentIntentShippingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetails"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentintent\/shipping","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/shipping"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentShippingDetails":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetails","abstract":[{"type":"text","text":"Shipping information for a PaymentIntent"},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"type":"codeVoice","code":"STPPaymentIntentShippingDetails"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"You should only use one that is part of an existing "},{"type":"codeVoice","code":"STPPaymentMethod"},{"type":"text","text":" object."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentShippingDetails"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentShippingDetails"}],"title":"STPPaymentIntentShippingDetails","url":"\/documentation\/stripepayments\/stppaymentintentshippingdetails","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","kind":"symbol","title":"StripePayments","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"abstract":[{"type":"text","text":"A PaymentIntent tracks the process of collecting a payment from your customer."}],"role":"symbol","kind":"symbol","title":"STPPaymentIntent","navigatorTitle":[{"text":"STPPaymentIntent","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntent","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentintent","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"shipping"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"shipping"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPPaymentIntentShippingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetails","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"shipping","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1shipping\/title","op":"replace","value":"shipping"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1shipping\/fragments","op":"replace","value":[{"kind":"identifier","text":"shipping"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetails\/title","op":"replace","value":"STPPaymentIntentShippingDetails"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetails\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentShippingDetails"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetails\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentShippingDetails"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title","op":"replace","value":"STPPaymentIntent"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntent"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}