{"metadata":{"role":"symbol","title":"init(code:)","externalID":"c:@M@StripePayments@objc(cs)STPConfirmBLIKOptions(im)initWithCode:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"code","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCode:"}],"symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"StripePayments"}]},"kind":"symbol","abstract":[{"type":"text","text":"Initializes STPConfirmBLIKOptions"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"required"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"code","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"name":"code","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The 6-digit BLIK code that a customer has generated using their banking application."}]}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconfirmblikoptions\/init(code:)"]},{"paths":["\/documentation\/stripepayments\/stpconfirmblikoptions\/init(code:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions"]]},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions\/init(code:)","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmBLIKOptions":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPConfirmBLIKOptions"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmblikoptions","title":"STPConfirmBLIKOptions","role":"symbol","abstract":[{"text":"BLIK options to pass to `STPConfirmPaymentMethodOptions``","type":"text"}],"navigatorTitle":[{"text":"STPConfirmBLIKOptions","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmBLIKOptions/init(code:)":{"kind":"symbol","type":"topic","role":"symbol","title":"init(code:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions\/init(code:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"code","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"abstract":[{"text":"Initializes STPConfirmBLIKOptions","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCode:"}],"url":"\/documentation\/stripepayments\/stpconfirmblikoptions\/init(code:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithCode:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCode:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithCode:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"code","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":{"kind":"parameters","parameters":[{"name":"code","content":[{"type":"paragraph","inlineContent":[{"text":"The 6-digit BLIK code that a customer has generated using their banking application.","type":"text"}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":"STPConfirmBLIKOptions","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmBLIKOptions\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmBLIKOptions\/fragments","value":[{"text":"STPConfirmBLIKOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmBLIKOptions\/navigatorTitle","value":[{"text":"STPConfirmBLIKOptions","kind":"identifier"}]},{"value":"initWithCode:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmBLIKOptions~1init(code:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmBLIKOptions~1init(code:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithCode:","kind":"identifier"}],"op":"replace"}]}]}