{"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-apple-pay\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-apple-pay\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-apple-pay\/objc(pl)PKPaymentAuthorizationControllerDelegate","doc:\/\/com.stripe.stripe-apple-pay\/s7CVarArgP","doc:\/\/com.stripe.stripe-apple-pay\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-apple-pay\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-apple-pay\/SQ","doc:\/\/com.stripe.stripe-apple-pay\/SH"]}],"abstract":[{"text":"A helper class that implements Apple Pay.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Usage looks like this:"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext"]},{"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/init(paymentRequest:delegate:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/apiClient"]},{"identifiers":["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationController(_:didAuthorizePayment:handler:)","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationController(_:didChangeCouponCode:handler:)","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationController(_:didSelectShippingContact:handler:)","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationController(_:didSelectShippingMethod:handler:)","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationControllerDidFinish(_:)","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/presentApplePay(completion:)","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/presentApplePay(from:completion:)","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/presentApplePay(on:completion:)","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/presentationWindow(for:)","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/responds(to:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus"],"title":"Enumerations"}],"metadata":{"modules":[{"name":"StripeApplePay"}],"symbolKind":"class","navigatorTitle":[{"text":"STPApplePayContext","kind":"identifier"}],"externalID":"c:@M@StripeApplePay@objc(cs)STPApplePayContext","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPApplePayContext","kind":"identifier"}],"role":"symbol","title":"STPApplePayContext","roleHeading":"Class"},"identifier":{"url":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(STPApplePayContext) "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPApplePayContext"}],"languages":["swift"]}]},{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Initialize this class with a PKPaymentRequest describing the payment request (amount, line items, required shipping info, etc)"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Call presentApplePayOnViewController:completion: to present the Apple Pay sheet and begin the payment process","type":"text"},{"type":"text","text":" "},{"text":"3 (optional): If you need to respond to the user changing their shipping information\/shipping method, implement the optional delegate methods","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"When the user taps ‘Buy’, this class uses the PaymentIntent that you supply in the applePayContext:didCreatePaymentMethod:completion: delegate method to complete the payment","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"After payment completes\/errors and the sheet is dismissed, this class informs you in the applePayContext:didCompleteWithStatus: delegate method"}],"type":"paragraph"}]}]},{"style":"note","type":"aside","name":"See Also","content":[{"type":"paragraph","inlineContent":[{"text":"https:\/\/stripe.com\/docs\/apple-pay#native for a full guide","type":"text"}]}]},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"ApplePayExampleViewController for an example"}],"type":"paragraph"}],"style":"note","name":"See Also"}],"kind":"content"}],"references":{"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/paymentAuthorizationController(_:didAuthorizePayment:handler:)":{"kind":"symbol","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentauthorizationcontroller(_:didauthorizepayment:handler:)","abstract":[{"type":"text","text":":nodoc:"}],"title":"paymentAuthorizationController(_:didAuthorizePayment:handler:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentAuthorizationController:didAuthorizePayment:handler:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentAuthorizationController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController","text":"PKPaymentAuthorizationController"},{"text":", ","kind":"text"},{"text":"didAuthorizePayment","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKPayment","text":"PKPayment","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"handler"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationResult","text":"PKPaymentAuthorizationResult","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationController(_:didAuthorizePayment:handler:)"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/presentApplePay(from:completion:)":{"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/presentApplePay(from:completion:)","navigatorTitle":[{"text":"presentApplePayFromWindow:completion:","kind":"identifier"}],"url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/presentapplepay(from:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"presentApplePay","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIWindow","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIWindow"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14StripeApplePay12STPVoidBlocka","text":"STPVoidBlock","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"kind":"symbol","abstract":[{"type":"text","text":"Presents the Apple Pay sheet from the specified window, starting the payment process."}],"type":"topic","title":"presentApplePay(from:completion:)"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/presentationWindow(for:)":{"title":"presentationWindow(for:)","abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/presentationWindow(for:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationWindow"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController","text":"PKPaymentAuthorizationController"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIWindow","text":"UIWindow","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/presentationwindow(for:)","navigatorTitle":[{"kind":"identifier","text":"presentationWindowForPaymentAuthorizationController:"}]},"doc://com.stripe.stripe-apple-pay/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-apple-pay/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/responds(to:)":{"type":"topic","abstract":[{"text":":nodoc:","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"respondsToSelector:"}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/responds(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"responds","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV","kind":"typeIdentifier"},{"kind":"text","text":"!) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"responds(to:)","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/responds(to:)"},"doc://com.stripe.stripe-apple-pay/objc(pl)PKPaymentAuthorizationControllerDelegate":{"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/objc(pl)PKPaymentAuthorizationControllerDelegate","type":"unresolvable","title":"PKPaymentAuthorizationControllerDelegate"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/apiClient":{"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/apiClient","navigatorTitle":[{"text":"apiClient","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"apiClient","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","text":"STPAPIClient"}],"abstract":[{"text":"The API Client to use to make requests.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"code":"STPAPIClient.shared","type":"codeVoice"}],"kind":"symbol","title":"apiClient","type":"topic","role":"symbol","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/apiclient"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/PaymentStatus":{"url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentstatus","abstract":[{"text":"An enum representing the status of a payment requested from the user.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus","title":"STPApplePayContext.PaymentStatus","navigatorTitle":[{"kind":"identifier","text":"PaymentStatus"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PaymentStatus"}],"kind":"symbol"},"doc://com.stripe.stripe-apple-pay/SH":{"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-apple-pay/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/presentApplePay(on:completion:)":{"deprecated":false,"title":"presentApplePay(on:completion:)","abstract":[{"type":"text","text":"Presents the Apple Pay sheet from the specified view controller, starting the payment process."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/presentApplePay(on:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentApplePay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"STPVoidBlock","preciseIdentifier":"s:14StripeApplePay12STPVoidBlocka","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/presentapplepay(on:completion:)","navigatorTitle":[{"text":"presentApplePayOnViewController:completion:","kind":"identifier"}]},"doc://com.stripe.stripe-apple-pay/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/paymentAuthorizationControllerDidFinish(_:)":{"title":"paymentAuthorizationControllerDidFinish(_:)","abstract":[{"text":":nodoc:","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationControllerDidFinish(_:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"paymentAuthorizationControllerDidFinish","kind":"identifier"},{"kind":"text","text":"("},{"text":"PKPaymentAuthorizationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"paymentAuthorizationControllerDidFinish:","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentauthorizationcontrollerdidfinish(_:)"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/paymentAuthorizationController(_:didSelectShippingContact:handler:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentAuthorizationController"},{"kind":"text","text":"("},{"text":"PKPaymentAuthorizationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectShippingContact"},{"text":": ","kind":"text"},{"text":"PKContact","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKContact"},{"kind":"text","text":", "},{"text":"handler","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"PKPaymentRequestShippingContactUpdate","preciseIdentifier":"c:objc(cs)PKPaymentRequestShippingContactUpdate"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"title":"paymentAuthorizationController(_:didSelectShippingContact:handler:)","kind":"symbol","navigatorTitle":[{"text":"paymentAuthorizationController:didSelectShippingContact:handler:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationController(_:didSelectShippingContact:handler:)","abstract":[{"text":":nodoc:","type":"text"}],"type":"topic","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentauthorizationcontroller(_:didselectshippingcontact:handler:)"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/paymentAuthorizationController(_:didChangeCouponCode:handler:)":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationController(_:didChangeCouponCode:handler:)","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentauthorizationcontroller(_:didchangecouponcode:handler:)","title":"paymentAuthorizationController(_:didChangeCouponCode:handler:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentAuthorizationController"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController","text":"PKPaymentAuthorizationController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didChangeCouponCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"handler","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentRequestCouponCodeUpdate","text":"PKPaymentRequestCouponCodeUpdate"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"paymentAuthorizationController:didChangeCouponCode:handler:","kind":"identifier"}],"abstract":[{"text":":nodoc:","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/paymentAuthorizationController(_:didSelectShippingMethod:handler:)":{"title":"paymentAuthorizationController(_:didSelectShippingMethod:handler:)","abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationController(_:didSelectShippingMethod:handler:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentAuthorizationController"},{"text":"(","kind":"text"},{"text":"PKPaymentAuthorizationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationController"},{"text":", ","kind":"text"},{"text":"didSelectShippingMethod","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PKShippingMethod","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKShippingMethod"},{"text":", ","kind":"text"},{"text":"handler","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentRequestShippingMethodUpdate","text":"PKPaymentRequestShippingMethodUpdate"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentauthorizationcontroller(_:didselectshippingmethod:handler:)","navigatorTitle":[{"text":"paymentAuthorizationController:didSelectShippingMethod:handler:","kind":"identifier"}]},"doc://com.stripe.stripe-apple-pay/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/objc(cs)NSObject","title":"NSObject"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext":{"abstract":[{"type":"text","text":"A helper class that implements Apple Pay."},{"type":"text","text":" "},{"text":"Usage looks like this:","type":"text"}],"type":"topic","navigatorTitle":[{"text":"STPApplePayContext","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripeapplepay\/stpapplepaycontext","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPApplePayContext"}],"title":"STPApplePayContext","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay":{"url":"\/documentation\/stripeapplepay","type":"topic","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","abstract":[{"text":"StripeApplePay is a lightweight Apple Pay SDK intended for building App Clips or other size-constrained apps.","type":"text"}],"kind":"symbol","role":"collection","title":"StripeApplePay"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/init(paymentRequest:delegate:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"paymentRequest","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PKPaymentRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPaymentRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"text":"_stpinternal_STPApplePayContextDelegateBase","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripeApplePay@objc(pl)_stpinternal_STPApplePayContextDelegateBase"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPaymentRequest:delegate:"}],"kind":"symbol","type":"topic","title":"init(paymentRequest:delegate:)","role":"symbol","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/init(paymentrequest:delegate:)","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/init(paymentRequest:delegate:)","abstract":[{"text":"Initializes this class.","type":"text"}]},"doc://com.stripe.stripe-apple-pay/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/presentApplePay(completion:)":{"title":"presentApplePay(completion:)","deprecated":false,"navigatorTitle":[{"kind":"identifier","text":"presentApplePayWithCompletion:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentApplePay"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPVoidBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripeApplePay12STPVoidBlocka"},{"kind":"text","text":"?)"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/presentapplepay(completion:)","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/presentApplePay(completion:)","abstract":[{"type":"text","text":"Presents the Apple Pay sheet from the key window, starting the payment process."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"STPApplePayContext","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPApplePayContext","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPApplePayContext"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/apiClient"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/init(paymentRequest:delegate:)","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationController(_:didAuthorizePayment:handler:)","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationController(_:didChangeCouponCode:handler:)","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationController(_:didSelectShippingContact:handler:)","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationController(_:didSelectShippingMethod:handler:)","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/paymentAuthorizationControllerDidFinish(_:)","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/presentApplePay(completion:)","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/presentApplePay(from:completion:)","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/presentApplePay(on:completion:)","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/presentationWindow(for:)","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/responds(to:)"]}]},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-apple-pay\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-apple-pay\/objc(pl)PKPaymentAuthorizationControllerDelegate"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPApplePayContext"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"paymentAuthorizationController:didAuthorizePayment:handler:","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1paymentAuthorizationController(_:didAuthorizePayment:handler:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1paymentAuthorizationController(_:didAuthorizePayment:handler:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"paymentAuthorizationController:didAuthorizePayment:handler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1presentApplePay(from:completion:)\/title","value":"presentApplePayFromWindow:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1presentApplePay(from:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"presentApplePayFromWindow:completion:","kind":"identifier"}]},{"value":"presentationWindowForPaymentAuthorizationController:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1presentationWindow(for:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1presentationWindow(for:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationWindowForPaymentAuthorizationController:"}]},{"value":"respondsToSelector:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1responds(to:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"respondsToSelector:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1responds(to:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1apiClient\/title","value":"apiClient"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1apiClient\/fragments","op":"replace","value":[{"kind":"identifier","text":"apiClient"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1presentApplePay(on:completion:)\/title","value":"presentApplePayOnViewController:completion:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1presentApplePay(on:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"presentApplePayOnViewController:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1paymentAuthorizationControllerDidFinish(_:)\/title","value":"paymentAuthorizationControllerDidFinish:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"paymentAuthorizationControllerDidFinish:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1paymentAuthorizationControllerDidFinish(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1paymentAuthorizationController(_:didSelectShippingContact:handler:)\/title","op":"replace","value":"paymentAuthorizationController:didSelectShippingContact:handler:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1paymentAuthorizationController(_:didSelectShippingContact:handler:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"paymentAuthorizationController:didSelectShippingContact:handler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1paymentAuthorizationController(_:didChangeCouponCode:handler:)\/title","value":"paymentAuthorizationController:didChangeCouponCode:handler:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1paymentAuthorizationController(_:didChangeCouponCode:handler:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"paymentAuthorizationController:didChangeCouponCode:handler:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1paymentAuthorizationController(_:didSelectShippingMethod:handler:)\/title","value":"paymentAuthorizationController:didSelectShippingMethod:handler:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1paymentAuthorizationController(_:didSelectShippingMethod:handler:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"paymentAuthorizationController:didSelectShippingMethod:handler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/title","value":"STPApplePayContext"},{"value":[{"kind":"identifier","text":"STPApplePayContext"}],"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1init(paymentRequest:delegate:)\/title","op":"replace","value":"initWithPaymentRequest:delegate:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1init(paymentRequest:delegate:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPaymentRequest:delegate:"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1presentApplePay(completion:)\/title","value":"presentApplePayWithCompletion:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1presentApplePay(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"presentApplePayWithCompletion:","kind":"identifier"}]}]}]}
