{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionKonbiniDisplayDetails\/expiresAt","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiresAt"},{"kind":"text","text":": "},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPIntentActionKonbiniDisplayDetails(py)expiresAt","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"title":"expiresAt","navigatorTitle":[{"text":"expiresAt","kind":"identifier"}]},"abstract":[{"type":"text","text":"The date at which the pending Konbini payment expires."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expiresAt","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactionkonbinidisplaydetails\/expiresat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpintentactionkonbinidisplaydetails\/expiresat"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionKonbiniDisplayDetails"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionKonbiniDisplayDetails/expiresAt":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionKonbiniDisplayDetails\/expiresAt","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"expiresAt","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"title":"expiresAt","abstract":[{"text":"The date at which the pending Konbini payment expires.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpintentactionkonbinidisplaydetails\/expiresat","navigatorTitle":[{"text":"expiresAt","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionKonbiniDisplayDetails":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionKonbiniDisplayDetails","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentactionkonbinidisplaydetails","role":"symbol","navigatorTitle":[{"text":"STPIntentActionKonbiniDisplayDetails","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionKonbiniDisplayDetails","abstract":[{"type":"text","text":"Contains Konbini details necessary for the customer to complete the payment."}],"kind":"symbol","title":"STPIntentActionKonbiniDisplayDetails","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"expiresAt","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"expiresAt","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"text":" * ","kind":"text"},{"text":"expiresAt","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionKonbiniDisplayDetails~1expiresAt\/title","value":"expiresAt"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionKonbiniDisplayDetails~1expiresAt\/fragments","value":[{"text":"expiresAt","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"STPIntentActionKonbiniDisplayDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionKonbiniDisplayDetails\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionKonbiniDisplayDetails\/fragments","value":[{"kind":"identifier","text":"STPIntentActionKonbiniDisplayDetails"}],"op":"replace"},{"value":[{"kind":"identifier","text":"STPIntentActionKonbiniDisplayDetails"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionKonbiniDisplayDetails\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}