{"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType\/delivery","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripe\/stpshippingtype\/delivery"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpshippingtype\/delivery"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType"]]},"abstract":[{"type":"text","text":"Delivering the purchase by the seller."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"delivery","kind":"identifier"}],"externalID":"c:@M@Stripe@E@STPShippingType@STPShippingTypeDelivery","modules":[{"name":"Stripe"}],"roleHeading":"Case","symbolKind":"case","title":"STPShippingType.delivery","navigatorTitle":[{"text":"STPShippingTypeDelivery","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"delivery","kind":"identifier"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingType":{"url":"\/documentation\/stripe\/stpshippingtype","abstract":[{"type":"text","text":"These values control the labels used in the shipping info collection form."}],"role":"symbol","title":"STPShippingType","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingType"}],"navigatorTitle":[{"text":"STPShippingType","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingType/delivery":{"navigatorTitle":[{"text":"STPShippingTypeDelivery","kind":"identifier"}],"title":"STPShippingType.delivery","type":"topic","abstract":[{"text":"Delivering the purchase by the seller.","type":"text"}],"url":"\/documentation\/stripe\/stpshippingtype\/delivery","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"delivery","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType\/delivery","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"STPShippingTypeDelivery"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPShippingTypeDelivery"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"STPShippingTypeDelivery"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"STPShippingType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingType\/title"},{"value":[{"kind":"identifier","text":"STPShippingType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingType\/fragments","op":"replace"},{"value":"STPShippingTypeDelivery","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingType~1delivery\/title","op":"replace"},{"value":[{"text":"STPShippingTypeDelivery","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingType~1delivery\/fragments"}]}]}
