{"metadata":{"roleHeading":"Case","symbolKind":"case","externalID":"c:@M@Stripe@E@STPShippingType@STPShippingTypeShipping","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shipping"}],"navigatorTitle":[{"text":"STPShippingTypeShipping","kind":"identifier"}],"role":"symbol","modules":[{"name":"Stripe"}],"title":"STPShippingType.shipping"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"shipping"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Shipping the purchase to the provided address using a third-party"},{"type":"text","text":" "},{"text":"shipping company.","type":"text"}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType\/shipping","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpshippingtype\/shipping"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpshippingtype\/shipping"]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingType":{"title":"STPShippingType","abstract":[{"text":"These values control the labels used in the shipping info collection form.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"STPShippingType","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingType"}],"url":"\/documentation\/stripe\/stpshippingtype","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingType/shipping":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shipping"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType\/shipping","url":"\/documentation\/stripe\/stpshippingtype\/shipping","abstract":[{"text":"Shipping the purchase to the provided address using a third-party","type":"text"},{"type":"text","text":" "},{"type":"text","text":"shipping company."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPShippingTypeShipping"}],"kind":"symbol","title":"STPShippingType.shipping"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"STPShippingTypeShipping","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPShippingTypeShipping","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPShippingTypeShipping"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPShippingType","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingType\/title","op":"replace"},{"op":"replace","value":[{"text":"STPShippingType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingType\/fragments"},{"value":"STPShippingTypeShipping","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingType~1shipping\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingType~1shipping\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPShippingTypeShipping"}]}]}]}
