{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddressViewControllerDidCancel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"addressViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController","text":"STPShippingAddressViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"addressViewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the view controller that has been cancelled"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpshippingaddressviewcontrollerdelegate\/shippingaddressviewcontrollerdidcancel(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpshippingaddressviewcontrollerdelegate\/shippingaddressviewcontrollerdidcancel(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate\/shippingAddressViewControllerDidCancel(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the user cancels entering a shipping address. You should dismiss (or pop) the view controller at this point."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"shippingAddressViewControllerDidCancel:"}],"role":"symbol","title":"shippingAddressViewControllerDidCancel(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddressViewControllerDidCancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPShippingAddressViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@Stripe@objc(pl)STPShippingAddressViewControllerDelegate(im)shippingAddressViewControllerDidCancel:","required":true,"modules":[{"name":"Stripe"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewControllerDelegate":{"role":"symbol","title":"STPShippingAddressViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingAddressViewControllerDelegate"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPShippingAddressViewControllerDelegate"},{"type":"text","text":" is notified when an "},{"type":"codeVoice","code":"STPShippingAddressViewController"},{"type":"text","text":" receives an address, completes with an address, or is cancelled."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPShippingAddressViewControllerDelegate"}],"url":"\/documentation\/stripe\/stpshippingaddressviewcontrollerdelegate"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewControllerDelegate/shippingAddressViewControllerDidCancel(_:)":{"navigatorTitle":[{"kind":"identifier","text":"shippingAddressViewControllerDidCancel:"}],"role":"symbol","title":"shippingAddressViewControllerDidCancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddressViewControllerDidCancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPShippingAddressViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the user cancels entering a shipping address. You should dismiss (or pop) the view controller at this point."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate\/shippingAddressViewControllerDidCancel(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/stripe\/stpshippingaddressviewcontrollerdelegate\/shippingaddressviewcontrollerdidcancel(_:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController":{"role":"symbol","title":"STPShippingAddressViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingAddressViewController"}],"abstract":[{"type":"text","text":"This view controller contains a shipping address collection form. It renders a right bar button item that submits the form, so it must be shown inside a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":". Depending on your configuration’s shippingType, the view controller may present a shipping method selection form after the user enters an address."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPShippingAddressViewController"}],"url":"\/documentation\/stripe\/stpshippingaddressviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"shippingAddressViewControllerDidCancel:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shippingAddressViewControllerDidCancel:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"shippingAddressViewControllerDidCancel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController","text":"STPShippingAddressViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"addressViewController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate\/title","value":"STPShippingAddressViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"STPShippingAddressViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate~1shippingAddressViewControllerDidCancel(_:)\/title","value":"shippingAddressViewControllerDidCancel:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate~1shippingAddressViewControllerDidCancel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shippingAddressViewControllerDidCancel:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/title","value":"STPShippingAddressViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/fragments","value":[{"kind":"identifier","text":"STPShippingAddressViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
