{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"This is called when the user enters a shipping address and taps next. You"},{"text":" ","type":"text"},{"text":"should validate the address and determine what shipping methods are available,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and call the "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" block when finished. If an error occurrs, call"},{"type":"text","text":" "},{"text":"the ","type":"text"},{"code":"completion","type":"codeVoice"},{"text":" block with the error. Otherwise, call the ","type":"text"},{"type":"codeVoice","code":"completion"},{"type":"text","text":" "},{"text":"block with a nil error and an array of available shipping methods. If you don’t","type":"text"},{"type":"text","text":" "},{"type":"text","text":"need to collect a shipping method, you may pass an empty array or nil."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate\/shippingAddressViewController(_:didEnter:completion:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpshippingaddressviewcontrollerdelegate\/shippingaddressviewcontroller(_:didenter:completion:)"]},{"paths":["\/documentation\/stripe\/stpshippingaddressviewcontrollerdelegate\/shippingaddressviewcontroller(_:didenter:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"required":true,"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@Stripe@objc(pl)STPShippingAddressViewControllerDelegate(im)shippingAddressViewController:didEnterAddress:completion:","title":"shippingAddressViewController(_:didEnter:completion:)","symbolKind":"method","navigatorTitle":[{"text":"shippingAddressViewController:didEnterAddress:completion:","kind":"identifier"}],"modules":[{"name":"Stripe"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddressViewController"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController","text":"STPShippingAddressViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEnter"},{"text":": ","kind":"text"},{"text":"STPAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:6Stripe33STPShippingMethodsCompletionBlocka","kind":"typeIdentifier","text":"STPShippingMethodsCompletionBlock"},{"kind":"text","text":")"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(shippingAddressViewController:didEnterAddress:completion:) "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"shippingAddressViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"addressViewController"},{"text":": ","kind":"text"},{"text":"STPShippingAddressViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController"},{"text":", ","kind":"text"},{"text":"didEnter","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"address"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","text":"STPAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingMethodsCompletionBlock","text":"STPShippingMethodsCompletionBlock","preciseIdentifier":"s:6Stripe33STPShippingMethodsCompletionBlocka"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"the view controller where the address was entered","type":"text"}]}],"name":"addressViewController"},{"name":"address","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the address that was entered. - seealso: STPAddress"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"call this callback when you’re done validating the address and determining available shipping methods.","type":"text"}]}]}]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController":{"url":"\/documentation\/stripe\/stpshippingaddressviewcontroller","title":"STPShippingAddressViewController","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPShippingAddressViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This view controller contains a shipping address collection form. It renders a right bar button item that submits the form, so it must be shown inside a ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":". Depending on your configuration’s shippingType, the view controller may present a shipping method selection form after the user enters an address."}],"navigatorTitle":[{"text":"STPShippingAddressViewController","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddress":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddress"}],"navigatorTitle":[{"text":"STPAddress","kind":"identifier"}],"url":"\/documentation\/stripe\/stpaddress","role":"symbol","title":"STPAddress","type":"topic","abstract":[{"text":"STPAddress Contains an address as represented by the Stripe API.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingMethodsCompletionBlock":{"role":"symbol","url":"\/documentation\/stripe\/stpshippingmethodscompletionblock","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingMethodsCompletionBlock","title":"STPShippingMethodsCompletionBlock","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"STPShippingMethodsCompletionBlock","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A callback to be run with a validation result and shipping methods for a"},{"type":"text","text":" "},{"type":"text","text":"shipping address."}],"navigatorTitle":[{"text":"STPShippingMethodsCompletionBlock","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewControllerDelegate/shippingAddressViewController(_:didEnter:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shippingAddressViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController","text":"STPShippingAddressViewController"},{"text":", ","kind":"text"},{"text":"didEnter","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"STPShippingMethodsCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:6Stripe33STPShippingMethodsCompletionBlocka"},{"text":")","kind":"text"}],"title":"shippingAddressViewController(_:didEnter:completion:)","required":true,"navigatorTitle":[{"text":"shippingAddressViewController:didEnterAddress:completion:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This is called when the user enters a shipping address and taps next. You","type":"text"},{"type":"text","text":" "},{"text":"should validate the address and determine what shipping methods are available,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and call the "},{"type":"codeVoice","code":"completion"},{"text":" block when finished. If an error occurrs, call","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" block with the error. Otherwise, call the "},{"code":"completion","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"block with a nil error and an array of available shipping methods. If you don’t"},{"text":" ","type":"text"},{"type":"text","text":"need to collect a shipping method, you may pass an empty array or nil."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate\/shippingAddressViewController(_:didEnter:completion:)","type":"topic","role":"symbol","url":"\/documentation\/stripe\/stpshippingaddressviewcontrollerdelegate\/shippingaddressviewcontroller(_:didenter:completion:)"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewControllerDelegate":{"role":"symbol","title":"STPShippingAddressViewControllerDelegate","type":"topic","kind":"symbol","url":"\/documentation\/stripe\/stpshippingaddressviewcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPShippingAddressViewControllerDelegate"}],"navigatorTitle":[{"text":"STPShippingAddressViewControllerDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"An "},{"code":"STPShippingAddressViewControllerDelegate","type":"codeVoice"},{"text":" is notified when an ","type":"text"},{"code":"STPShippingAddressViewController","type":"codeVoice"},{"type":"text","text":" receives an address, completes with an address, or is cancelled."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"shippingAddressViewController:didEnterAddress:completion:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shippingAddressViewController:didEnterAddress:completion:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"shippingAddressViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController","text":"STPShippingAddressViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"addressViewController"},{"kind":"text","text":" "},{"text":"didEnterAddress:","kind":"identifier"},{"kind":"text","text":"("},{"text":"STPAddress","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"address"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#$@M@Stripe@E@STPShippingStatus#*$objc(cs)NSError#*Q$objc(cs)NSArray#*$objc(cs)PKShippingMethod)","text":"void (^)(enum STPShippingStatus, NSError *, NSArray<PKShippingMethod *> *, PKShippingMethod *)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"STPShippingAddressViewController","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/fragments","value":[{"text":"STPShippingAddressViewController","kind":"identifier"}]},{"op":"replace","value":"shippingAddressViewController:didEnterAddress:completion:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate~1shippingAddressViewController(_:didEnter:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"shippingAddressViewController:didEnterAddress:completion:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate~1shippingAddressViewController(_:didEnter:completion:)\/fragments"},{"op":"replace","value":"STPShippingAddressViewControllerDelegate","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate\/fragments","value":[{"text":"STPShippingAddressViewControllerDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
