{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(shippingAddressViewController:didFinishWithAddress:shippingMethod:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shippingAddressViewController"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"addressViewController"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController","text":"STPShippingAddressViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFinishWith"},{"text":" ","kind":"text"},{"text":"address","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress"},{"kind":"text","text":", "},{"text":"shippingMethod","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"method"},{"text":": ","kind":"text"},{"text":"PKShippingMethod","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKShippingMethod"},{"kind":"text","text":"?)"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the view controller where the address was entered"}]}],"name":"addressViewController"},{"name":"address","content":[{"inlineContent":[{"text":"the address that was entered. - seealso: STPAddress","type":"text"}],"type":"paragraph"}]},{"name":"method","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the shipping method that was selected."}]}]}],"kind":"parameters"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate"]]},"abstract":[{"text":"This is called when the user selects a shipping method. If no shipping methods are given, or if the shipping type doesn’t require a shipping method, this will be called after the user has a shipping address and your validation has succeeded. After updating your app with the user’s shipping info, you should dismiss (or pop) the view controller. Note that if ","type":"text"},{"code":"shippingMethod","type":"codeVoice"},{"text":" is non-nil, there will be an additional shipping methods view controller on the navigation controller’s stack.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpshippingaddressviewcontrollerdelegate\/shippingaddressviewcontroller(_:didfinishwith:shippingmethod:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpshippingaddressviewcontrollerdelegate\/shippingaddressviewcontroller(_:didfinishwith:shippingmethod:)"]}],"metadata":{"title":"shippingAddressViewController(_:didFinishWith:shippingMethod:)","externalID":"c:@M@Stripe@objc(pl)STPShippingAddressViewControllerDelegate(im)shippingAddressViewController:didFinishWithAddress:shippingMethod:","navigatorTitle":[{"kind":"identifier","text":"shippingAddressViewController:didFinishWithAddress:shippingMethod:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddressViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPShippingAddressViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController"},{"text":", ","kind":"text"},{"text":"didFinishWith","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shippingMethod","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)PKShippingMethod","text":"PKShippingMethod","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"Stripe"}],"symbolKind":"method","role":"symbol","required":true},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate\/shippingAddressViewController(_:didFinishWith:shippingMethod:)","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewControllerDelegate/shippingAddressViewController(_:didFinishWith:shippingMethod:)":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate\/shippingAddressViewController(_:didFinishWith:shippingMethod:)","url":"\/documentation\/stripe\/stpshippingaddressviewcontrollerdelegate\/shippingaddressviewcontroller(_:didfinishwith:shippingmethod:)","kind":"symbol","required":true,"title":"shippingAddressViewController(_:didFinishWith:shippingMethod:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"shippingAddressViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController","text":"STPShippingAddressViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFinishWith","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shippingMethod"},{"text":": ","kind":"text"},{"text":"PKShippingMethod","preciseIdentifier":"c:objc(cs)PKShippingMethod","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"shippingAddressViewController:didFinishWithAddress:shippingMethod:","kind":"identifier"}],"abstract":[{"type":"text","text":"This is called when the user selects a shipping method. If no shipping methods are given, or if the shipping type doesn’t require a shipping method, this will be called after the user has a shipping address and your validation has succeeded. After updating your app with the user’s shipping info, you should dismiss (or pop) the view controller. Note that if "},{"type":"codeVoice","code":"shippingMethod"},{"text":" is non-nil, there will be an additional shipping methods view controller on the navigation controller’s stack.","type":"text"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddress":{"kind":"symbol","navigatorTitle":[{"text":"STPAddress","kind":"identifier"}],"abstract":[{"type":"text","text":"STPAddress Contains an address as represented by the Stripe API."}],"type":"topic","title":"STPAddress","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","url":"\/documentation\/stripe\/stpaddress","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPAddress","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewControllerDelegate":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPShippingAddressViewControllerDelegate"}],"title":"STPShippingAddressViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingAddressViewControllerDelegate"}],"kind":"symbol","role":"symbol","abstract":[{"text":"An ","type":"text"},{"code":"STPShippingAddressViewControllerDelegate","type":"codeVoice"},{"text":" is notified when an ","type":"text"},{"code":"STPShippingAddressViewController","type":"codeVoice"},{"type":"text","text":" receives an address, completes with an address, or is cancelled."}],"url":"\/documentation\/stripe\/stpshippingaddressviewcontrollerdelegate","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPShippingAddressViewController"}],"type":"topic","abstract":[{"text":"This view controller contains a shipping address collection form. It renders a right bar button item that submits the form, so it must be shown inside a ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":". Depending on your configuration’s shippingType, the view controller may present a shipping method selection form after the user enters an address."}],"title":"STPShippingAddressViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController","url":"\/documentation\/stripe\/stpshippingaddressviewcontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPShippingAddressViewController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"shippingAddressViewController:didFinishWithAddress:shippingMethod:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shippingAddressViewController:didFinishWithAddress:shippingMethod:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"shippingAddressViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController","text":"STPShippingAddressViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController"},{"text":" *) ","kind":"text"},{"text":"addressViewController","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didFinishWithAddress:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress"},{"kind":"text","text":" *) "},{"text":"address","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"shippingMethod:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)PKShippingMethod","text":"PKShippingMethod","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"method","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate~1shippingAddressViewController(_:didFinishWith:shippingMethod:)\/title","value":"shippingAddressViewController:didFinishWithAddress:shippingMethod:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"shippingAddressViewController:didFinishWithAddress:shippingMethod:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate~1shippingAddressViewController(_:didFinishWith:shippingMethod:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate\/title","value":"STPShippingAddressViewControllerDelegate"},{"value":[{"kind":"identifier","text":"STPShippingAddressViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate\/fragments"},{"value":"STPShippingAddressViewController","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/title"},{"value":[{"kind":"identifier","text":"STPShippingAddressViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
