{"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/image","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A small (32 x 20 points) logo image representing the payment method. For"},{"type":"text","text":" "},{"text":"example, the Visa logo for a Visa card, or the Apple Pay logo.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpapplepaypaymentoption\/image"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpapplepaypaymentoption\/image"]}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"image"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"}],"externalID":"c:@M@Stripe@objc(cs)STPApplePayPaymentOption(py)image","modules":[{"name":"Stripe"}],"roleHeading":"Instance Property","symbolKind":"property","title":"image","navigatorTitle":[{"text":"image","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayPaymentOption/image":{"url":"\/documentation\/stripe\/stpapplepaypaymentoption\/image","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"}],"abstract":[{"type":"text","text":"A small (32 x 20 points) logo image representing the payment method. For"},{"type":"text","text":" "},{"text":"example, the Visa logo for a Visa card, or the Apple Pay logo.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/image","kind":"symbol","title":"image","navigatorTitle":[{"text":"image","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayPaymentOption":{"navigatorTitle":[{"kind":"identifier","text":"STPApplePayPaymentOption"}],"title":"STPApplePayPaymentOption","type":"topic","abstract":[{"type":"text","text":"An empty class representing that the user wishes to pay via Apple Pay. This can"},{"type":"text","text":" "},{"text":"be checked on an ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"text":", e.g:","type":"text"}],"url":"\/documentation\/stripe\/stpapplepaypaymentoption","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPApplePayPaymentOption"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"image","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"image"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"image","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption~1image\/title","op":"replace","value":"image"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption~1image\/fragments","value":[{"text":"image","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption\/title","value":"STPApplePayPaymentOption","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption\/fragments","value":[{"kind":"identifier","text":"STPApplePayPaymentOption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
