{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"object"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}]}],"metadata":{"modules":[{"name":"Stripe"}],"title":"isEqual(_:)","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@Stripe@objc(cs)STPApplePayPaymentOption(im)isEqual:","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/isEqual(_:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":":nodoc:"}],"variants":[{"paths":["\/documentation\/stripe\/stpapplepaypaymentoption\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpapplepaypaymentoption\/isequal(_:)"]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayPaymentOption/isEqual(_:)":{"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"title":"isEqual(_:)","type":"topic","url":"\/documentation\/stripe\/stpapplepaypaymentoption\/isequal(_:)","abstract":[{"type":"text","text":":nodoc:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/isEqual(_:)","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayPaymentOption":{"navigatorTitle":[{"kind":"identifier","text":"STPApplePayPaymentOption"}],"title":"STPApplePayPaymentOption","type":"topic","abstract":[{"type":"text","text":"An empty class representing that the user wishes to pay via Apple Pay. This can"},{"type":"text","text":" "},{"text":"be checked on an ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"text":", e.g:","type":"text"}],"url":"\/documentation\/stripe\/stpapplepaypaymentoption","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPApplePayPaymentOption"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"isEqual:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"isEqual:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"isEqual:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption~1isEqual(_:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption~1isEqual(_:)\/fragments"},{"value":"STPApplePayPaymentOption","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption\/title","op":"replace"},{"value":[{"text":"STPApplePayPaymentOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
