{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isReusable"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"text":"Describes whether this payment option may be used multiple times. If it is not reusable,","type":"text"},{"type":"text","text":" "},{"text":"the payment method must be discarded after use.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@Stripe@objc(cs)STPApplePayPaymentOption(py)isReusable","title":"isReusable","modules":[{"name":"Stripe"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"isReusable"}],"symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isReusable"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpapplepaypaymentoption\/isreusable"]},{"paths":["\/documentation\/stripe\/stpapplepaypaymentoption\/isreusable"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/isReusable","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayPaymentOption/isReusable":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes whether this payment option may be used multiple times. If it is not reusable,"},{"type":"text","text":" "},{"type":"text","text":"the payment method must be discarded after use."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/isReusable","role":"symbol","title":"isReusable","url":"\/documentation\/stripe\/stpapplepaypaymentoption\/isreusable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isReusable","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isReusable"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayPaymentOption":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPApplePayPaymentOption","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPApplePayPaymentOption"}],"url":"\/documentation\/stripe\/stpapplepaypaymentoption","type":"topic","title":"STPApplePayPaymentOption","kind":"symbol","role":"symbol","abstract":[{"text":"An empty class representing that the user wishes to pay via Apple Pay. This can","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"be checked on an "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":", e.g:","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"isReusable"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isReusable"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isReusable"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"isReusable","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption~1isReusable\/title","op":"replace"},{"value":[{"text":"isReusable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption~1isReusable\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption\/title","value":"STPApplePayPaymentOption"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPApplePayPaymentOption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
