{"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/label","interfaceLanguage":"swift"},"abstract":[{"text":"A string describing the payment method, such as “Apple Pay” or “Visa 4242”.","type":"text"}],"metadata":{"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@Stripe@objc(cs)STPApplePayPaymentOption(py)label","modules":[{"name":"Stripe"}],"symbolKind":"property","title":"label","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"label","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"label","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"label"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/stripe\/stpapplepaypaymentoption\/label"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpapplepaypaymentoption\/label"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayPaymentOption/label":{"url":"\/documentation\/stripe\/stpapplepaypaymentoption\/label","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"label"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"A string describing the payment method, such as “Apple Pay” or “Visa 4242”."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/label","kind":"symbol","title":"label","navigatorTitle":[{"kind":"identifier","text":"label"}],"role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayPaymentOption":{"navigatorTitle":[{"kind":"identifier","text":"STPApplePayPaymentOption"}],"title":"STPApplePayPaymentOption","type":"topic","abstract":[{"type":"text","text":"An empty class representing that the user wishes to pay via Apple Pay. This can"},{"type":"text","text":" "},{"text":"be checked on an ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"text":", e.g:","type":"text"}],"url":"\/documentation\/stripe\/stpapplepaypaymentoption","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPApplePayPaymentOption"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"label"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"label","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"label"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"label","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption~1label\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption~1label\/fragments","op":"replace","value":[{"text":"label","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption\/title","op":"replace","value":"STPApplePayPaymentOption"},{"value":[{"kind":"identifier","text":"STPApplePayPaymentOption"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption\/fragments","op":"replace"}]}]}
