{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand"]]},"abstract":[{"type":"text","text":"AmBank"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/ambank"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/ambank"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/ambank","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"symbol","externalID":"c:@M@StripePayments@E@STPFPXBankBrand@STPFPXBankBrandAmbank","modules":[{"name":"StripePayments"}],"roleHeading":"Case","symbolKind":"case","title":"STPFPXBankBrand.ambank","navigatorTitle":[{"text":"STPFPXBankBrandAmbank","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ambank","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ambank","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/ambank":{"navigatorTitle":[{"text":"STPFPXBankBrandAmbank","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/ambank","title":"STPFPXBankBrand.ambank","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ambank","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpfpxbankbrand\/ambank","abstract":[{"text":"AmBank","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand":{"role":"symbol","title":"STPFPXBankBrand","abstract":[{"text":"The various bank brands available for FPX payments.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrand"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFPXBankBrand"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","type":"topic","url":"\/documentation\/stripepayments\/stpfpxbankbrand","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"STPFPXBankBrandAmbank","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPFPXBankBrandAmbank","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"STPFPXBankBrandAmbank","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1ambank\/title","value":"STPFPXBankBrandAmbank","op":"replace"},{"value":[{"kind":"identifier","text":"STPFPXBankBrandAmbank"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1ambank\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/title","value":"STPFPXBankBrand","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/fragments","value":[{"kind":"identifier","text":"STPFPXBankBrand"}]},{"value":[{"kind":"identifier","text":"STPFPXBankBrand"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}