{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/bankmuamalat"]},{"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/bankmuamalat"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/bankMuamalat"},"abstract":[{"type":"text","text":"Bank Muamalat"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"bankMuamalat","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"externalID":"c:@M@StripePayments@E@STPFPXBankBrand@STPFPXBankBrandBankMuamalat","roleHeading":"Case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrandBankMuamalat"}],"modules":[{"name":"StripePayments"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bankMuamalat","kind":"identifier"}],"title":"STPFPXBankBrand.bankMuamalat"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/bankMuamalat":{"url":"\/documentation\/stripepayments\/stpfpxbankbrand\/bankmuamalat","kind":"symbol","abstract":[{"type":"text","text":"Bank Muamalat"}],"type":"topic","title":"STPFPXBankBrand.bankMuamalat","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bankMuamalat"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/bankMuamalat","navigatorTitle":[{"text":"STPFPXBankBrandBankMuamalat","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPFPXBankBrand"}],"type":"topic","title":"STPFPXBankBrand","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","abstract":[{"text":"The various bank brands available for FPX payments.","type":"text"}],"navigatorTitle":[{"text":"STPFPXBankBrand","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpfpxbankbrand","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPFPXBankBrandBankMuamalat","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"STPFPXBankBrandBankMuamalat","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPFPXBankBrandBankMuamalat"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1bankMuamalat\/title","value":"STPFPXBankBrandBankMuamalat"},{"op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrandBankMuamalat"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1bankMuamalat\/fragments"},{"op":"replace","value":"STPFPXBankBrand","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/title"},{"value":[{"text":"STPFPXBankBrand","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/fragments"},{"value":[{"kind":"identifier","text":"STPFPXBankBrand"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/navigatorTitle"}]}]}