{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bankRakyat","kind":"identifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/bankRakyat","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Bank Rakyat"}],"metadata":{"role":"symbol","modules":[{"name":"StripePayments"}],"roleHeading":"Case","title":"STPFPXBankBrand.bankRakyat","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bankRakyat","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@StripePayments@E@STPFPXBankBrand@STPFPXBankBrandBankRakyat","navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrandBankRakyat"}]},"variants":[{"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/bankrakyat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/bankrakyat"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/bankRakyat":{"title":"STPFPXBankBrand.bankRakyat","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/bankRakyat","navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrandBankRakyat"}],"abstract":[{"type":"text","text":"Bank Rakyat"}],"url":"\/documentation\/stripepayments\/stpfpxbankbrand\/bankrakyat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bankRakyat"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","type":"topic","kind":"symbol","role":"symbol","title":"STPFPXBankBrand","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFPXBankBrand"}],"abstract":[{"type":"text","text":"The various bank brands available for FPX payments."}],"navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrand"}],"url":"\/documentation\/stripepayments\/stpfpxbankbrand"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPFPXBankBrandBankRakyat","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"STPFPXBankBrandBankRakyat","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"STPFPXBankBrandBankRakyat","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPFPXBankBrandBankRakyat","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1bankRakyat\/title","op":"replace"},{"value":[{"text":"STPFPXBankBrandBankRakyat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1bankRakyat\/fragments","op":"replace"},{"value":"STPFPXBankBrand","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/title","op":"replace"},{"value":[{"text":"STPFPXBankBrand","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/fragments","op":"replace"},{"value":[{"text":"STPFPXBankBrand","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/navigatorTitle","op":"replace"}]}]}