{"abstract":[{"text":"BSN","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/bsn"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/bsn"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPFPXBankBrand@STPFPXBankBrandBSN","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"BSN","kind":"identifier"}],"role":"symbol","modules":[{"name":"StripePayments"}],"symbolKind":"case","navigatorTitle":[{"text":"STPFPXBankBrandBSN","kind":"identifier"}],"title":"STPFPXBankBrand.BSN"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"BSN","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/BSN","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/BSN":{"kind":"symbol","navigatorTitle":[{"text":"STPFPXBankBrandBSN","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/BSN","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/bsn","abstract":[{"type":"text","text":"BSN"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"BSN","kind":"identifier"}],"title":"STPFPXBankBrand.BSN"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpfpxbankbrand","navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrand"}],"title":"STPFPXBankBrand","role":"symbol","abstract":[{"type":"text","text":"The various bank brands available for FPX payments."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPFPXBankBrand","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"STPFPXBankBrandBSN","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPFPXBankBrandBSN","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPFPXBankBrandBSN"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1BSN\/title","value":"STPFPXBankBrandBSN","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1BSN\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrandBSN"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/title","value":"STPFPXBankBrand"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/fragments","value":[{"kind":"identifier","text":"STPFPXBankBrand"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/navigatorTitle","value":[{"text":"STPFPXBankBrand","kind":"identifier"}]}]}]}