{"metadata":{"externalID":"c:@M@StripePayments@E@STPFPXBankBrand@STPFPXBankBrandCIMB","role":"symbol","title":"STPFPXBankBrand.CIMB","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CIMB"}],"symbolKind":"case","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrandCIMB"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand"]]},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/cimb"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/cimb"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"CIMB","kind":"identifier"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"CIMB Clicks"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/CIMB"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/CIMB":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/CIMB","kind":"symbol","abstract":[{"text":"CIMB Clicks","type":"text"}],"role":"symbol","title":"STPFPXBankBrand.CIMB","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/cimb","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CIMB"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrandCIMB"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPFPXBankBrand","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpfpxbankbrand","title":"STPFPXBankBrand","abstract":[{"type":"text","text":"The various bank brands available for FPX payments."}],"role":"symbol","navigatorTitle":[{"text":"STPFPXBankBrand","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPFPXBankBrandCIMB"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPFPXBankBrandCIMB","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPFPXBankBrandCIMB"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1CIMB\/title","value":"STPFPXBankBrandCIMB"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1CIMB\/fragments","value":[{"text":"STPFPXBankBrandCIMB","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/title","op":"replace","value":"STPFPXBankBrand"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/fragments","value":[{"text":"STPFPXBankBrand","kind":"identifier"}]},{"value":[{"text":"STPFPXBankBrand","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/navigatorTitle"}]}]}