{"sections":[],"metadata":{"title":"hashValue","roleHeading":"Instance Property","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@StripePayments@E@STPFPXBankBrand","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"modules":[{"relatedModules":["Swift"],"name":"StripePayments"}],"symbolKind":"property","extendedModule":"Swift","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"RawRepresentable.hashValue"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/hashValue","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/RawRepresentable-Implementations"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/hashValue":{"role":"symbol","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/hashValue","abstract":[],"url":"\/documentation\/stripepayments\/stpfpxbankbrand\/hashvalue","kind":"symbol","type":"topic","title":"hashValue"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/RawRepresentable-Implementations":{"kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/RawRepresentable-Implementations","type":"topic","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/rawrepresentable-implementations","abstract":[],"title":"RawRepresentable Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand":{"url":"\/documentation\/stripepayments\/stpfpxbankbrand","abstract":[{"text":"The various bank brands available for FPX payments.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","navigatorTitle":[{"text":"STPFPXBankBrand","kind":"identifier"}],"type":"topic","title":"STPFPXBankBrand","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPFPXBankBrand","kind":"identifier"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPFPXBankBrand","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/fragments","value":[{"kind":"identifier","text":"STPFPXBankBrand"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/navigatorTitle","value":[{"kind":"identifier","text":"STPFPXBankBrand"}],"op":"replace"}]}]}