{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/HSBC"},"abstract":[{"text":"HSBC BANK","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSBC"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","symbolKind":"case","title":"STPFPXBankBrand.HSBC","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPFPXBankBrandHSBC","kind":"identifier"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSBC"}],"externalID":"c:@M@StripePayments@E@STPFPXBankBrand@STPFPXBankBrandHSBC"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/hsbc"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/hsbc"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand"]]},"kind":"symbol","sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/HSBC":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSBC"}],"navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrandHSBC"}],"abstract":[{"text":"HSBC BANK","type":"text"}],"url":"\/documentation\/stripepayments\/stpfpxbankbrand\/hsbc","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/HSBC","title":"STPFPXBankBrand.HSBC","kind":"symbol","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","role":"symbol","abstract":[{"type":"text","text":"The various bank brands available for FPX payments."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFPXBankBrand"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrand"}],"url":"\/documentation\/stripepayments\/stpfpxbankbrand","title":"STPFPXBankBrand"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPFPXBankBrandHSBC"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPFPXBankBrandHSBC"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPFPXBankBrandHSBC","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1HSBC\/title","value":"STPFPXBankBrandHSBC"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1HSBC\/fragments","value":[{"text":"STPFPXBankBrandHSBC","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/title","value":"STPFPXBankBrand"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/fragments","value":[{"text":"STPFPXBankBrand","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/navigatorTitle","value":[{"kind":"identifier","text":"STPFPXBankBrand"}]}]}]}