{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"STPFPXBankBrand.maybank2U","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPFPXBankBrandMaybank2U","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maybank2U"}],"externalID":"c:@M@StripePayments@E@STPFPXBankBrand@STPFPXBankBrandMaybank2U","symbolKind":"case","roleHeading":"Case","role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/maybank2U","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/maybank2u"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/maybank2u"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maybank2U"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Maybank2U","type":"text"}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/maybank2U":{"type":"topic","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/maybank2u","kind":"symbol","navigatorTitle":[{"text":"STPFPXBankBrandMaybank2U","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maybank2U"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/maybank2U","abstract":[{"text":"Maybank2U","type":"text"}],"title":"STPFPXBankBrand.maybank2U"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand":{"title":"STPFPXBankBrand","abstract":[{"type":"text","text":"The various bank brands available for FPX payments."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFPXBankBrand"}],"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpfpxbankbrand","navigatorTitle":[{"text":"STPFPXBankBrand","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPFPXBankBrandMaybank2U","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrandMaybank2U"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPFPXBankBrandMaybank2U","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1maybank2U\/title","value":"STPFPXBankBrandMaybank2U","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1maybank2U\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrandMaybank2U"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/title","op":"replace","value":"STPFPXBankBrand"},{"value":[{"text":"STPFPXBankBrand","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/fragments"},{"value":[{"kind":"identifier","text":"STPFPXBankBrand"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/navigatorTitle"}]}]}