{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maybank2E"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/maybank2e"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/maybank2e"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/maybank2E","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Maybank2E"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maybank2E"}],"title":"STPFPXBankBrand.maybank2E","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@StripePayments@E@STPFPXBankBrand@STPFPXBankBrandMaybank2E","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrandMaybank2E"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/maybank2E":{"role":"symbol","title":"STPFPXBankBrand.maybank2E","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"maybank2E"}],"abstract":[{"type":"text","text":"Maybank2E"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/maybank2E","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrandMaybank2E"}],"url":"\/documentation\/stripepayments\/stpfpxbankbrand\/maybank2e"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand":{"role":"symbol","title":"STPFPXBankBrand","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFPXBankBrand"}],"abstract":[{"type":"text","text":"The various bank brands available for FPX payments."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrand"}],"url":"\/documentation\/stripepayments\/stpfpxbankbrand"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPFPXBankBrandMaybank2E"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPFPXBankBrandMaybank2E"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPFPXBankBrandMaybank2E"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1maybank2E\/title","value":"STPFPXBankBrandMaybank2E"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1maybank2E\/fragments","value":[{"kind":"identifier","text":"STPFPXBankBrandMaybank2E"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/title","value":"STPFPXBankBrand"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/fragments","value":[{"kind":"identifier","text":"STPFPXBankBrand"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}