{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ocbc"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/ocbc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/ocbc"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand"]]},"metadata":{"navigatorTitle":[{"text":"STPFPXBankBrandOcbc","kind":"identifier"}],"role":"symbol","roleHeading":"Case","title":"STPFPXBankBrand.ocbc","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ocbc"}],"symbolKind":"case","externalID":"c:@M@StripePayments@E@STPFPXBankBrand@STPFPXBankBrandOcbc"},"kind":"symbol","sections":[],"abstract":[{"text":"OCBC Bank","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/ocbc"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/ocbc":{"abstract":[{"type":"text","text":"OCBC Bank"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ocbc","kind":"identifier"}],"navigatorTitle":[{"text":"STPFPXBankBrandOcbc","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/ocbc","kind":"symbol","type":"topic","title":"STPFPXBankBrand.ocbc","role":"symbol","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/ocbc"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand":{"abstract":[{"type":"text","text":"The various bank brands available for FPX payments."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFPXBankBrand"}],"navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrand"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","kind":"symbol","type":"topic","title":"STPFPXBankBrand","role":"symbol","url":"\/documentation\/stripepayments\/stpfpxbankbrand"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPFPXBankBrandOcbc","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"STPFPXBankBrandOcbc"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"identifier","text":"STPFPXBankBrandOcbc"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPFPXBankBrandOcbc","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1ocbc\/title"},{"value":[{"kind":"identifier","text":"STPFPXBankBrandOcbc"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1ocbc\/fragments"},{"value":"STPFPXBankBrand","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/title"},{"value":[{"kind":"identifier","text":"STPFPXBankBrand"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/fragments"},{"value":[{"kind":"identifier","text":"STPFPXBankBrand"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}