{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/publicbank"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/publicbank"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/publicBank"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"publicBank"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand"]]},"abstract":[{"type":"text","text":"Public Bank"}],"metadata":{"title":"STPFPXBankBrand.publicBank","symbolKind":"case","roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPFPXBankBrand@STPFPXBankBrandPublicBank","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrandPublicBank"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"publicBank"}]},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand":{"role":"symbol","type":"topic","abstract":[{"text":"The various bank brands available for FPX payments.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFPXBankBrand","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpfpxbankbrand","title":"STPFPXBankBrand","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrand"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/publicBank":{"url":"\/documentation\/stripepayments\/stpfpxbankbrand\/publicbank","title":"STPFPXBankBrand.publicBank","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/publicBank","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"publicBank","kind":"identifier"}],"navigatorTitle":[{"text":"STPFPXBankBrandPublicBank","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Public Bank","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"STPFPXBankBrandPublicBank","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPFPXBankBrandPublicBank"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"STPFPXBankBrandPublicBank","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/title","value":"STPFPXBankBrand","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrand"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/navigatorTitle","op":"replace","value":[{"text":"STPFPXBankBrand","kind":"identifier"}]},{"op":"replace","value":"STPFPXBankBrandPublicBank","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1publicBank\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1publicBank\/fragments","value":[{"text":"STPFPXBankBrandPublicBank","kind":"identifier"}],"op":"replace"}]}]}