{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"RHB","kind":"identifier"}]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/RHB","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand"]]},"kind":"symbol","abstract":[{"text":"RHB Bank","type":"text"}],"metadata":{"navigatorTitle":[{"text":"STPFPXBankBrandRHB","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RHB"}],"externalID":"c:@M@StripePayments@E@STPFPXBankBrand@STPFPXBankBrandRHB","symbolKind":"case","roleHeading":"Case","modules":[{"name":"StripePayments"}],"role":"symbol","title":"STPFPXBankBrand.RHB"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/rhb"]},{"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/rhb"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPFPXBankBrand","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"STPFPXBankBrand","kind":"identifier"}],"title":"STPFPXBankBrand","abstract":[{"text":"The various bank brands available for FPX payments.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","url":"\/documentation\/stripepayments\/stpfpxbankbrand","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/RHB":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/RHB","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/rhb","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"RHB"}],"navigatorTitle":[{"text":"STPFPXBankBrandRHB","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","title":"STPFPXBankBrand.RHB","abstract":[{"text":"RHB Bank","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPFPXBankBrandRHB"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPFPXBankBrandRHB","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPFPXBankBrandRHB"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/title","value":"STPFPXBankBrand","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrand"}]},{"value":[{"text":"STPFPXBankBrand","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1RHB\/title","op":"replace","value":"STPFPXBankBrandRHB"},{"value":[{"kind":"identifier","text":"STPFPXBankBrandRHB"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1RHB\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}