{"sections":[],"abstract":[{"type":"text","text":"An unknown bank"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/unknown"},"variants":[{"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/unknown"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/unknown"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"title":"STPFPXBankBrand.unknown","roleHeading":"Case","navigatorTitle":[{"text":"STPFPXBankBrandUnknown","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPFPXBankBrand@STPFPXBankBrandUnknown","modules":[{"name":"StripePayments"}],"symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","title":"STPFPXBankBrand","abstract":[{"type":"text","text":"The various bank brands available for FPX payments."}],"url":"\/documentation\/stripepayments\/stpfpxbankbrand","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrand"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPFPXBankBrand"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/unknown":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/unknown","title":"STPFPXBankBrand.unknown","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"type":"topic","abstract":[{"type":"text","text":"An unknown bank"}],"navigatorTitle":[{"text":"STPFPXBankBrandUnknown","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpfpxbankbrand\/unknown"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPFPXBankBrandUnknown","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPFPXBankBrandUnknown","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPFPXBankBrandUnknown"}]}],"kind":"declarations"},"op":"replace"},{"value":"STPFPXBankBrand","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/fragments","value":[{"text":"STPFPXBankBrand","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1unknown\/title","op":"replace","value":"STPFPXBankBrandUnknown"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1unknown\/fragments","op":"replace","value":[{"text":"STPFPXBankBrandUnknown","kind":"identifier"}]}]}]}
