{"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/UOB","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/uob"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/uob"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"STPFPXBankBrandUOB","kind":"identifier"}],"title":"STPFPXBankBrand.UOB","externalID":"c:@M@StripePayments@E@STPFPXBankBrand@STPFPXBankBrandUOB","roleHeading":"Case","modules":[{"name":"StripePayments"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UOB","kind":"identifier"}],"role":"symbol"},"abstract":[{"text":"UOB Bank","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UOB","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/UOB":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/UOB","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/uob","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"UOB Bank"}],"title":"STPFPXBankBrand.UOB","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UOB"}],"navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrandUOB"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand":{"abstract":[{"text":"The various bank brands available for FPX payments.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFPXBankBrand","kind":"identifier"}],"navigatorTitle":[{"text":"STPFPXBankBrand","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpfpxbankbrand","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","title":"STPFPXBankBrand"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPFPXBankBrandUOB","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPFPXBankBrandUOB","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPFPXBankBrandUOB"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPFPXBankBrandUOB","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1UOB\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrandUOB"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1UOB\/fragments"},{"op":"replace","value":"STPFPXBankBrand","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/title"},{"op":"replace","value":[{"text":"STPFPXBankBrand","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrand"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}