{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams"]]},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/clientAttributionMetadata"},"abstract":[{"text":"Contains metadata with identifiers for the session and information about the integration","type":"text"}],"metadata":{"title":"clientAttributionMetadata","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams(py)clientAttributionMetadata","navigatorTitle":[{"text":"clientAttributionMetadata","kind":"identifier"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"clientAttributionMetadata"}]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"STPClientAttributionMetadata","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPClientAttributionMetadata"},{"kind":"text","text":" * "},{"kind":"identifier","text":"clientAttributionMetadata"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmparams\/clientattributionmetadata"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams":{"role":"symbol","title":"STPPaymentIntentConfirmParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams","navigatorTitle":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"abstract":[{"text":"An object representing parameters used to confirm a PaymentIntent object.","type":"text"},{"text":" ","type":"text"},{"text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it.","type":"text"},{"text":" ","type":"text"},{"text":"That PaymentMethod or Source can either be:","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/clientAttributionMetadata":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/clientattributionmetadata","type":"topic","role":"symbol","title":"clientAttributionMetadata","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/clientAttributionMetadata","abstract":[{"text":"Contains metadata with identifiers for the session and information about the integration","type":"text"}],"fragments":[{"text":"clientAttributionMetadata","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/title","value":"STPPaymentIntentConfirmParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}