{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mandateData"},{"kind":"text","text":": "},{"text":"STPMandateDataParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateDataParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateDataParams"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"style":"note","name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If this value is null, the SDK will set this to an internal value indicating that the mandate data should be inferred from the current context if it’s required for "},{"type":"codeVoice","code":"self.paymentMethodType"}]}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/mandateData","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams"]]},"abstract":[{"type":"text","text":"Details about the Mandate to create."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmparams\/mandatedata"]},{"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmparams\/mandatedata"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mandateData"},{"kind":"text","text":": "},{"text":"STPMandateDataParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateDataParams","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","modules":[{"name":"StripePayments"}],"title":"mandateData","roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams(py)mandateData","navigatorTitle":[{"kind":"identifier","text":"mandateData"}],"symbolKind":"property"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/mandateData":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mandateData","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateDataParams","text":"STPMandateDataParams"},{"kind":"text","text":"?"}],"url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/mandatedata","abstract":[{"text":"Details about the Mandate to create.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/mandateData","title":"mandateData","navigatorTitle":[{"text":"mandateData","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams":{"title":"STPPaymentIntentConfirmParams","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams","navigatorTitle":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"type":"text","text":" "},{"type":"text","text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it."},{"type":"text","text":" "},{"text":"That PaymentMethod or Source can either be:","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateDataParams":{"url":"\/documentation\/stripepayments\/stpmandatedataparams","kind":"symbol","type":"topic","abstract":[{"text":"This object contains details about the Mandate to create. - seealso: https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-mandate_data","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateDataParams","navigatorTitle":[{"kind":"identifier","text":"STPMandateDataParams"}],"role":"symbol","title":"STPMandateDataParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPMandateDataParams","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"mandateData","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"mandateData"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"text":"STPMandateDataParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateDataParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateDataParams"},{"kind":"text","text":" * "},{"text":"mandateData","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1mandateData\/title","value":"mandateData"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1mandateData\/fragments","value":[{"kind":"identifier","text":"mandateData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/title","value":"STPPaymentIntentConfirmParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/fragments","value":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams\/title","value":"STPMandateDataParams","op":"replace"},{"value":[{"text":"STPMandateDataParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams\/navigatorTitle","op":"replace","value":[{"text":"STPMandateDataParams","kind":"identifier"}]}]}]}