{"kind":"symbol","metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams(py)paymentMethodParams","symbolKind":"property","modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","role":"symbol","title":"paymentMethodParams","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethodParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"paymentMethodParams","kind":"identifier"}]},"abstract":[{"type":"text","text":"Provide a supported "},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"type":"text","text":" object, and Stripe will create a"},{"type":"text","text":" "},{"type":"text","text":"PaymentMethod during PaymentIntent confirmation."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethodParams","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"style":"note","type":"aside","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Alternative to "},{"type":"codeVoice","code":"paymentMethodId"}]}]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/paymentMethodParams","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmparams\/paymentmethodparams"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmparams\/paymentmethodparams"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams"]]},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/paymentMethodParams":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/paymentMethodParams","kind":"symbol","title":"paymentMethodParams","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethodParams","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/paymentmethodparams","navigatorTitle":[{"text":"paymentMethodParams","kind":"identifier"}],"abstract":[{"text":"Provide a supported ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"text":" object, and Stripe will create a","type":"text"},{"text":" ","type":"text"},{"text":"PaymentMethod during PaymentIntent confirmation.","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"title":"STPPaymentMethodParams","url":"\/documentation\/stripepayments\/stppaymentmethodparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","kind":"symbol","abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodParams"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}],"role":"symbol","abstract":[{"text":"An object representing parameters used to confirm a PaymentIntent object.","type":"text"},{"text":" ","type":"text"},{"text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it.","type":"text"},{"text":" ","type":"text"},{"text":"That PaymentMethod or Source can either be:","type":"text"}],"title":"STPPaymentIntentConfirmParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"paymentMethodParams","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"paymentMethodParams"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"paymentMethodParams","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"paymentMethodParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1paymentMethodParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1paymentMethodParams\/fragments","op":"replace","value":[{"text":"paymentMethodParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","op":"replace","value":"STPPaymentMethodParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","op":"replace","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/title","op":"replace","value":"STPPaymentIntentConfirmParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}]}]}]}