{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/radarOptions","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"STPRadarOptions","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarOptions","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPRadarOptions"},{"kind":"text","text":" * "},{"kind":"identifier","text":"radarOptions"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"kind":"symbol","metadata":{"modules":[{"name":"StripePayments"}],"fragments":[{"kind":"identifier","text":"radarOptions"}],"navigatorTitle":[{"kind":"identifier","text":"radarOptions"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams(py)radarOptions","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","title":"radarOptions"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmparams\/radaroptions"]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Radar options that may contain HCaptcha token"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRadarOptions":{"title":"STPRadarOptions","role":"symbol","url":"\/documentation\/stripepayments\/stpradaroptions","abstract":[{"type":"text","text":"Values for STPRadarOptions"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarOptions","kind":"symbol","type":"topic","fragments":[{"text":"STPRadarOptions","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams":{"role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams","navigatorTitle":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"type":"text","text":" "},{"type":"text","text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it."},{"type":"text","text":" "},{"text":"That PaymentMethod or Source can either be:","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams","title":"STPPaymentIntentConfirmParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/radarOptions":{"title":"radarOptions","fragments":[{"text":"radarOptions","kind":"identifier"}],"type":"topic","abstract":[{"text":"Radar options that may contain HCaptcha token","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/radarOptions","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/radaroptions","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"STPPaymentIntentConfirmParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}