{"kind":"symbol","metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"receiptEmail","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"receiptEmail","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams(py)receiptEmail","modules":[{"name":"StripePayments"}],"role":"symbol","navigatorTitle":[{"text":"receiptEmail","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/receiptEmail","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams"]]},"abstract":[{"type":"text","text":"Email address that the receipt for the resulting payment will be sent to."}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmparams\/receiptemail"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmparams\/receiptemail"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"receiptEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"type":"topic","title":"STPPaymentIntentConfirmParams","role":"symbol","abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"type":"text","text":" "},{"type":"text","text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it."},{"type":"text","text":" "},{"type":"text","text":"That PaymentMethod or Source can either be:"}],"navigatorTitle":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/receiptEmail":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"receiptEmail","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[{"text":"Email address that the receipt for the resulting payment will be sent to.","type":"text"}],"navigatorTitle":[{"text":"receiptEmail","kind":"identifier"}],"title":"receiptEmail","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/receiptEmail","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/receiptemail","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"receiptEmail"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"receiptEmail","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"receiptEmail"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/title","op":"replace","value":"STPPaymentIntentConfirmParams"},{"value":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/navigatorTitle"},{"value":"receiptEmail","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1receiptEmail\/title"},{"value":[{"kind":"identifier","text":"receiptEmail"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1receiptEmail\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}