{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams"]]},"abstract":[{"type":"text","text":"The URL to redirect your customer back to after they authenticate or cancel"},{"type":"text","text":" "},{"type":"text","text":"their payment on the payment method’s app or site."},{"type":"text","text":" "},{"type":"text","text":"This should probably be a URL that opens your iOS app."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmparams\/returnurl-1o0ia"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmparams\/returnurl-1o0ia"]}],"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"returnURL"}],"title":"returnURL","externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams(py)returnURL","roleHeading":"Instance Property"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/returnURL-1o0ia"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"returnURL","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams":{"type":"topic","kind":"symbol","abstract":[{"text":"An object representing parameters used to confirm a PaymentIntent object.","type":"text"},{"text":" ","type":"text"},{"text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it.","type":"text"},{"text":" ","type":"text"},{"text":"That PaymentMethod or Source can either be:","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}],"title":"STPPaymentIntentConfirmParams","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/returnURL-1o0ia":{"kind":"symbol","abstract":[{"type":"text","text":"The URL to redirect your customer back to after they authenticate or cancel"},{"type":"text","text":" "},{"type":"text","text":"their payment on the payment method’s app or site."},{"type":"text","text":" "},{"type":"text","text":"This should probably be a URL that opens your iOS app."}],"navigatorTitle":[{"kind":"identifier","text":"returnURL"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/returnURL-1o0ia","title":"returnURL","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/returnurl-1o0ia","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"returnURL","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"returnURL","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"returnURL","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPPaymentIntentConfirmParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/title"},{"value":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/navigatorTitle"},{"value":"returnURL","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1returnURL-1o0ia\/title"},{"value":[{"kind":"identifier","text":"returnURL"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1returnURL-1o0ia\/fragments"}]}]}