{"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Shipping information.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shipping"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetailsParams","text":"STPPaymentIntentShippingDetailsParams"},{"kind":"text","text":"?"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/shipping"},"metadata":{"role":"symbol","title":"shipping","navigatorTitle":[{"text":"shipping","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shipping"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetailsParams","kind":"typeIdentifier","text":"STPPaymentIntentShippingDetailsParams"},{"kind":"text","text":"?"}],"modules":[{"name":"StripePayments"}],"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams(py)shipping"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmparams\/shipping"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmparams\/shipping"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams":{"title":"STPPaymentIntentConfirmParams","abstract":[{"text":"An object representing parameters used to confirm a PaymentIntent object.","type":"text"},{"text":" ","type":"text"},{"text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it.","type":"text"},{"text":" ","type":"text"},{"text":"That PaymentMethod or Source can either be:","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/shipping":{"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/shipping","kind":"symbol","abstract":[{"type":"text","text":"Shipping information."}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shipping"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentIntentShippingDetailsParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetailsParams"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/shipping","title":"shipping","navigatorTitle":[{"kind":"identifier","text":"shipping"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentShippingDetailsParams":{"navigatorTitle":[{"text":"STPPaymentIntentShippingDetailsParams","kind":"identifier"}],"title":"STPPaymentIntentShippingDetailsParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentShippingDetailsParams","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsParams","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentshippingdetailsparams","abstract":[{"type":"text","text":"Shipping information for a PaymentIntent"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"shipping"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"shipping","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"STPPaymentIntentShippingDetailsParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetailsParams"},{"kind":"text","text":" * "},{"kind":"identifier","text":"shipping"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/title","op":"replace","value":"STPPaymentIntentConfirmParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/fragments","op":"replace","value":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1shipping\/title","op":"replace","value":"shipping"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1shipping\/fragments","op":"replace","value":[{"text":"shipping","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsParams\/title","op":"replace","value":"STPPaymentIntentShippingDetailsParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsParams\/fragments","op":"replace","value":[{"text":"STPPaymentIntentShippingDetailsParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsParams\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentShippingDetailsParams"}]}]}]}