{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"]}]},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Alternative to "},{"type":"codeVoice","code":"sourceParams"}]}],"style":"note","name":"Note"}],"kind":"content"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams"]]},"metadata":{"modules":[{"name":"StripePayments"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"sourceId"}],"roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams(py)sourceId","title":"sourceId","symbolKind":"property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Provide an already created Source’s id, and it will be used to confirm the PaymentIntent."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmparams\/sourceid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmparams\/sourceid"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/sourceId"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams":{"abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"type":"text","text":" "},{"type":"text","text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it."},{"type":"text","text":" "},{"type":"text","text":"That PaymentMethod or Source can either be:"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"title":"STPPaymentIntentConfirmParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/sourceId":{"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sourceId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"sourceId","kind":"identifier"}],"title":"sourceId","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/sourceid","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/sourceId","abstract":[{"type":"text","text":"Provide an already created Source’s id, and it will be used to confirm the PaymentIntent."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"sourceId","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"sourceId","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"sourceId","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/title","op":"replace","value":"STPPaymentIntentConfirmParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/fragments","op":"replace","value":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1sourceId\/title","op":"replace","value":"sourceId"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1sourceId\/fragments","op":"replace","value":[{"text":"sourceId","kind":"identifier"}]}]}]}