{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sourceParams"},{"text":": ","kind":"text"},{"text":"STPSourceParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"style":"note","type":"aside","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Alternative to "},{"code":"sourceId","type":"codeVoice"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmparams\/sourceparams"]},{"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmparams\/sourceparams"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams"]]},"kind":"symbol","abstract":[{"type":"text","text":"Provide a supported "},{"type":"codeVoice","code":"STPSourceParams"},{"type":"text","text":" object into here, and Stripe will create a Source"},{"type":"text","text":" "},{"text":"during PaymentIntent confirmation.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/sourceParams"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"sourceParams"}],"roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams(py)sourceParams","modules":[{"name":"StripePayments"}],"symbolKind":"property","title":"sourceParams","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sourceParams"},{"text":": ","kind":"text"},{"text":"STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"},{"text":"?","kind":"text"}]},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceParams","kind":"identifier"}],"abstract":[{"type":"text","text":"An object representing parameters used to create a Source object."}],"type":"topic","navigatorTitle":[{"text":"STPSourceParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","title":"STPSourceParams","url":"\/documentation\/stripepayments\/stpsourceparams","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/sourceParams":{"navigatorTitle":[{"text":"sourceParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/sourceparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/sourceParams","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sourceParams","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Provide a supported "},{"code":"STPSourceParams","type":"codeVoice"},{"text":" object into here, and Stripe will create a Source","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"during PaymentIntent confirmation."}],"title":"sourceParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams":{"url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams","title":"STPPaymentIntentConfirmParams","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"role":"symbol","abstract":[{"text":"An object representing parameters used to confirm a PaymentIntent object.","type":"text"},{"text":" ","type":"text"},{"text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it.","type":"text"},{"text":" ","type":"text"},{"text":"That PaymentMethod or Source can either be:","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"sourceParams"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"sourceParams","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","kind":"typeIdentifier","text":"STPSourceParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"sourceParams"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"STPSourceParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments","value":[{"text":"STPSourceParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPSourceParams"}]},{"op":"replace","value":"sourceParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1sourceParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1sourceParams\/fragments","value":[{"text":"sourceParams","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"STPPaymentIntentConfirmParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/title"},{"value":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}