{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewController"]]},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"text":"STPBankSelectionViewControllerDelegate","preciseIdentifier":"c:@M@Stripe@objc(pl)STPBankSelectionViewControllerDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"modules":[{"name":"Stripe"}],"externalID":"c:@M@Stripe@objc(cs)STPBankSelectionViewController(py)delegate","title":"delegate","roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewController\/delegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The view controller’s delegate. This must be set before showing the view controller in order for it to work properly. - seealso: STPBankSelectionViewControllerDelegate"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpbankselectionviewcontroller\/delegate"]},{"paths":["\/documentation\/stripe\/stpbankselectionviewcontroller\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@Stripe@objc(pl)STPBankSelectionViewControllerDelegate","kind":"typeIdentifier","text":"STPBankSelectionViewControllerDelegate","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewControllerDelegate"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionViewController/delegate":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@objc(pl)STPBankSelectionViewControllerDelegate","kind":"typeIdentifier","text":"STPBankSelectionViewControllerDelegate"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"type":"topic","title":"delegate","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewController\/delegate","abstract":[{"text":"The view controller’s delegate. This must be set before showing the view controller in order for it to work properly. - seealso: STPBankSelectionViewControllerDelegate","type":"text"}],"url":"\/documentation\/stripe\/stpbankselectionviewcontroller\/delegate","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionViewController":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankSelectionViewController","kind":"identifier"}],"title":"STPBankSelectionViewController","role":"symbol","kind":"symbol","abstract":[{"text":"This view controller displays a list of banks of the specified type, allowing the user to select one to pay from.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Once a bank is selected, it will return a PaymentMethodParams object, which you can use to confirm a PaymentIntent"},{"text":" ","type":"text"},{"text":"or inspect to obtain details about the selected bank.","type":"text"}],"url":"\/documentation\/stripe\/stpbankselectionviewcontroller","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBankSelectionViewController"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionViewControllerDelegate":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPBankSelectionViewControllerDelegate","kind":"identifier"}],"title":"STPBankSelectionViewControllerDelegate","type":"topic","abstract":[{"text":"An ","type":"text"},{"code":"STPBankSelectionViewControllerDelegate","type":"codeVoice"},{"text":" is notified when a user selects a bank.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripe\/stpbankselectionviewcontrollerdelegate","navigatorTitle":[{"kind":"identifier","text":"STPBankSelectionViewControllerDelegate"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"delegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"delegate","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"text":"id<STPBankSelectionViewControllerDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@Stripe@objc(pl)STPBankSelectionViewControllerDelegate"},{"kind":"text","text":" * "},{"text":"delegate","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewController~1delegate\/title","value":"delegate"},{"value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewController~1delegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewController\/title","value":"STPBankSelectionViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPBankSelectionViewController"}]},{"op":"replace","value":"STPBankSelectionViewControllerDelegate","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewControllerDelegate\/fragments","value":[{"text":"STPBankSelectionViewControllerDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
