{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"bankMethod","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@E@STPBankSelectionMethod","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod","text":"STPBankSelectionMethod"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","text":"STPPaymentConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"theme","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user will be presented with a list of banks for this payment method. STPBankSelectionMethodFPX is currently the only supported payment method."}]}],"name":"bankMethod"},{"name":"configuration","content":[{"inlineContent":[{"text":"The configuration to use. This determines the Stripe publishable key to use when querying metadata about the banks. - seealso: STPPaymentConfiguration","type":"text"}],"type":"paragraph"}]},{"name":"theme","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The theme to use to inform the view controller’s visual appearance. - seealso: STPTheme"}]}]}],"kind":"parameters"}],"metadata":{"navigatorTitle":[{"text":"initWithBankMethod:configuration:theme:","kind":"identifier"}],"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bankMethod","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPBankSelectionMethod","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@E@STPBankSelectionMethod"},{"kind":"text","text":", "},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"theme"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"},{"text":")","kind":"text"}],"title":"init(bankMethod:configuration:theme:)","modules":[{"name":"Stripe"}],"symbolKind":"init","externalID":"c:@M@Stripe@objc(cs)STPBankSelectionViewController(im)initWithBankMethod:configuration:theme:","role":"symbol"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Initializes a new "},{"code":"STPBankSelectionViewController","type":"codeVoice"},{"type":"text","text":" with the provided configuration and theme. Don’t forget to set the "},{"type":"codeVoice","code":"delegate"},{"text":" property after initialization.","type":"text"}],"variants":[{"paths":["\/documentation\/stripe\/stpbankselectionviewcontroller\/init(bankmethod:configuration:theme:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpbankselectionviewcontroller\/init(bankmethod:configuration:theme:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewController"]]},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewController\/init(bankMethod:configuration:theme:)","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionMethod":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPBankSelectionMethod","kind":"identifier"}],"abstract":[{"type":"text","text":"The payment methods supported by STPBankSelectionViewController."}],"title":"STPBankSelectionMethod","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod","url":"\/documentation\/stripe\/stpbankselectionmethod","navigatorTitle":[{"text":"STPBankSelectionMethod","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration":{"url":"\/documentation\/stripe\/stppaymentconfiguration","role":"symbol","navigatorTitle":[{"text":"STPPaymentConfiguration","kind":"identifier"}],"title":"STPPaymentConfiguration","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"text":"An ","type":"text"},{"code":"STPPaymentConfiguration","type":"codeVoice"},{"type":"text","text":" represents all the options you can set or change"},{"type":"text","text":" "},{"type":"text","text":"around a payment."},{"text":" ","type":"text"},{"type":"text","text":"You provide an "},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"text":" object to your ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"when making a charge. The configuration generally has settings that"},{"type":"text","text":" "},{"type":"text","text":"will not change from payment to payment and thus is reusable, while the context"},{"type":"text","text":" "},{"text":"is specific to a single particular payment instance.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionViewController/init(bankMethod:configuration:theme:)":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithBankMethod:configuration:theme:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Initializes a new ","type":"text"},{"type":"codeVoice","code":"STPBankSelectionViewController"},{"text":" with the provided configuration and theme. Don’t forget to set the ","type":"text"},{"type":"codeVoice","code":"delegate"},{"type":"text","text":" property after initialization."}],"url":"\/documentation\/stripe\/stpbankselectionviewcontroller\/init(bankmethod:configuration:theme:)","title":"init(bankMethod:configuration:theme:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewController\/init(bankMethod:configuration:theme:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bankMethod"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPBankSelectionMethod","preciseIdentifier":"c:@M@Stripe@E@STPBankSelectionMethod"},{"kind":"text","text":", "},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPPaymentConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"theme"},{"kind":"text","text":": "},{"text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionViewController":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankSelectionViewController","kind":"identifier"}],"title":"STPBankSelectionViewController","role":"symbol","kind":"symbol","abstract":[{"text":"This view controller displays a list of banks of the specified type, allowing the user to select one to pay from.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Once a bank is selected, it will return a PaymentMethodParams object, which you can use to confirm a PaymentIntent"},{"text":" ","type":"text"},{"text":"or inspect to obtain details about the selected bank.","type":"text"}],"url":"\/documentation\/stripe\/stpbankselectionviewcontroller","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBankSelectionViewController"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPTheme","kind":"identifier"}],"navigatorTitle":[{"text":"STPTheme","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/stripe\/stptheme","kind":"symbol","abstract":[{"text":"STPTheme objects can be used to visually style Stripe-provided UI. See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#theming for more information.","type":"text"}],"title":"STPTheme","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"initWithBankMethod:configuration:theme:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBankMethod:configuration:theme:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithBankMethod:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"STPBankSelectionMethod","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod","preciseIdentifier":"c:@M@Stripe@E@STPBankSelectionMethod"},{"kind":"text","text":") "},{"text":"bankMethod","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configuration:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","text":"STPPaymentConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configuration"},{"text":" ","kind":"text"},{"text":"theme:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","text":"STPTheme"},{"kind":"text","text":" *) "},{"text":"theme","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionMethod\/title","op":"replace","value":"STPBankSelectionMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionMethod\/fragments","value":[{"text":"STPBankSelectionMethod","kind":"identifier"}]},{"op":"replace","value":"STPPaymentConfiguration","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/fragments","value":[{"text":"STPPaymentConfiguration","kind":"identifier"}]},{"value":"initWithBankMethod:configuration:theme:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewController~1init(bankMethod:configuration:theme:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewController~1init(bankMethod:configuration:theme:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBankMethod:configuration:theme:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewController\/title","value":"STPBankSelectionViewController","op":"replace"},{"value":[{"text":"STPBankSelectionViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/title","op":"replace","value":"STPTheme"},{"value":[{"text":"STPTheme","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/fragments","op":"replace"}]}]}
