{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpbankselectionviewcontroller\/init(bankmethod:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpbankselectionviewcontroller\/init(bankmethod:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bankMethod"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@E@STPBankSelectionMethod","text":"STPBankSelectionMethod"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewController"]]},"sections":[],"abstract":[{"type":"text","text":"A convenience initializer; equivalent to calling "},{"code":"init( bankMethod:bankMethod configuration:STPPaymentConfiguration.shared theme:STPTheme.defaultTheme","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewController\/init(bankMethod:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"bankMethod","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@E@STPBankSelectionMethod","kind":"typeIdentifier","text":"STPBankSelectionMethod"},{"text":")","kind":"text"}],"modules":[{"name":"Stripe"}],"role":"symbol","navigatorTitle":[{"text":"initWithBankMethod:","kind":"identifier"}],"roleHeading":"Initializer","externalID":"c:@M@Stripe@objc(cs)STPBankSelectionViewController(im)initWithBankMethod:","symbolKind":"init","title":"init(bankMethod:)"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionViewController/init(bankMethod:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"bankMethod","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@E@STPBankSelectionMethod","text":"STPBankSelectionMethod","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/stripe\/stpbankselectionviewcontroller\/init(bankmethod:)","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewController\/init(bankMethod:)","title":"init(bankMethod:)","navigatorTitle":[{"kind":"identifier","text":"initWithBankMethod:"}],"kind":"symbol","abstract":[{"text":"A convenience initializer; equivalent to calling ","type":"text"},{"type":"codeVoice","code":"init( bankMethod:bankMethod configuration:STPPaymentConfiguration.shared theme:STPTheme.defaultTheme"},{"text":".","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionViewController":{"kind":"symbol","abstract":[{"type":"text","text":"This view controller displays a list of banks of the specified type, allowing the user to select one to pay from."},{"text":" ","type":"text"},{"text":"Once a bank is selected, it will return a PaymentMethodParams object, which you can use to confirm a PaymentIntent","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"or inspect to obtain details about the selected bank."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewController","url":"\/documentation\/stripe\/stpbankselectionviewcontroller","navigatorTitle":[{"kind":"identifier","text":"STPBankSelectionViewController"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankSelectionViewController","kind":"identifier"}],"title":"STPBankSelectionViewController"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionMethod":{"title":"STPBankSelectionMethod","abstract":[{"text":"The payment methods supported by STPBankSelectionViewController.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"STPBankSelectionMethod","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPBankSelectionMethod","kind":"identifier"}],"url":"\/documentation\/stripe\/stpbankselectionmethod","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithBankMethod:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBankMethod:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithBankMethod:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@E@STPBankSelectionMethod","text":"STPBankSelectionMethod"},{"kind":"text","text":") "},{"text":"bankMethod","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewController~1init(bankMethod:)\/title","value":"initWithBankMethod:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithBankMethod:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewController~1init(bankMethod:)\/fragments","op":"replace"},{"op":"replace","value":"STPBankSelectionViewController","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewController\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPBankSelectionViewController"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionMethod\/title","value":"STPBankSelectionMethod","op":"replace"},{"value":[{"text":"STPBankSelectionMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionMethod\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
