{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactionswishhandleredirect\/allresponsefields"]},{"paths":["\/documentation\/stripepayments\/stpintentactionswishhandleredirect\/allresponsefields"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"allResponseFields","modules":[{"name":"StripePayments"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPIntentActionSwishHandleRedirect(py)allResponseFields","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"allResponseFields"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionSwishHandleRedirect\/allResponseFields"},"abstract":[{"type":"text","text":":nodoc:"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allResponseFields"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionSwishHandleRedirect"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionSwishHandleRedirect":{"title":"STPIntentActionSwishHandleRedirect","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Contains instructions for redirecting to the Swish app."},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"code":"STPIntentActionSwishHandle","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/stripepayments\/stpintentactionswishhandleredirect","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPIntentActionSwishHandleRedirect"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionSwishHandleRedirect","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionSwishHandleRedirect"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionSwishHandleRedirect/allResponseFields":{"title":"allResponseFields","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"url":"\/documentation\/stripepayments\/stpintentactionswishhandleredirect\/allresponsefields","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allResponseFields"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionSwishHandleRedirect\/allResponseFields","navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"allResponseFields"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"allResponseFields","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"kind":"text","text":" * "},{"kind":"identifier","text":"allResponseFields"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionSwishHandleRedirect\/title","value":"STPIntentActionSwishHandleRedirect","op":"replace"},{"value":[{"kind":"identifier","text":"STPIntentActionSwishHandleRedirect"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionSwishHandleRedirect\/fragments","op":"replace"},{"op":"replace","value":"allResponseFields","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionSwishHandleRedirect~1allResponseFields\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionSwishHandleRedirect~1allResponseFields\/fragments","value":[{"kind":"identifier","text":"allResponseFields"}],"op":"replace"}]}]}
