{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionSwishHandleRedirect"]]},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionSwishHandleRedirect\/decodedObject(fromAPIResponse:)"],"generated":true,"title":"Type Methods","anchor":"Type-Methods"}],"kind":"article","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionSwishHandleRedirect\/STPAPIResponseDecodable-Implementations","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactionswishhandleredirect\/stpapiresponsedecodable-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactionswishhandleredirect\/stpapiresponsedecodable-implementations"]}],"metadata":{"role":"collectionGroup","title":"STPAPIResponseDecodable Implementations","modules":[{"name":"StripePayments"}],"roleHeading":"API Collection"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionSwishHandleRedirect":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionSwishHandleRedirect","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpintentactionswishhandleredirect","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionSwishHandleRedirect"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionSwishHandleRedirect"}],"abstract":[{"text":"Contains instructions for redirecting to the Swish app.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"code":"STPIntentActionSwishHandle","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","title":"STPIntentActionSwishHandleRedirect"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionSwishHandleRedirect/decodedObject(fromAPIResponse:)":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionSwishHandleRedirect\/decodedObject(fromAPIResponse:)","kind":"symbol","title":"decodedObject(fromAPIResponse:)","abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"type":"text","text":" "},{"type":"text","text":"an "},{"type":"codeVoice","code":"NSDictionary"},{"type":"text","text":") into an instance of the class."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"url":"\/documentation\/stripepayments\/stpintentactionswishhandleredirect\/decodedobject(fromapiresponse:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionSwishHandleRedirect\/decodedObject(fromAPIResponse:)"],"title":"Type Methods"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":"STPIntentActionSwishHandleRedirect","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionSwishHandleRedirect\/title","op":"replace"},{"value":[{"text":"STPIntentActionSwishHandleRedirect","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionSwishHandleRedirect\/fragments","op":"replace"},{"value":[{"text":"STPIntentActionSwishHandleRedirect","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionSwishHandleRedirect\/navigatorTitle","op":"replace"},{"value":"decodedObjectFromAPIResponse:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionSwishHandleRedirect~1decodedObject(fromAPIResponse:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionSwishHandleRedirect~1decodedObject(fromAPIResponse:)\/fragments","op":"replace"}]}]}