{"metadata":{"fragments":[{"text":"mandateData","kind":"identifier"}],"navigatorTitle":[{"text":"mandateData","kind":"identifier"}],"title":"mandateData","roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPConfirmationTokenParams(py)mandateData","symbolKind":"property","modules":[{"name":"StripePayments"}],"role":"symbol"},"kind":"symbol","abstract":[{"text":"Details about the Mandate to create.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconfirmationtokenparams\/mandatedata"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateDataParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateDataParams","text":"STPMandateDataParams","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"mandateData"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/mandateData"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateDataParams":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateDataParams","title":"STPMandateDataParams","navigatorTitle":[{"text":"STPMandateDataParams","kind":"identifier"}],"abstract":[{"text":"This object contains details about the Mandate to create. - seealso: https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-mandate_data","type":"text"}],"url":"\/documentation\/stripepayments\/stpmandatedataparams","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPMandateDataParams","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams":{"title":"STPConfirmationTokenParams","fragments":[{"kind":"identifier","text":"STPConfirmationTokenParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams","type":"topic","abstract":[{"text":"An object representing parameters used to create a ConfirmationToken object.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"seealso:"},{"type":"text","text":" "},{"type":"text","text":"https:\/\/stripe.com\/docs\/api\/confirmation_tokens"}],"role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmationtokenparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams/mandateData":{"abstract":[{"type":"text","text":"Details about the Mandate to create."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/mandateData","kind":"symbol","type":"topic","title":"mandateData","fragments":[{"kind":"identifier","text":"mandateData"}],"url":"\/documentation\/stripepayments\/stpconfirmationtokenparams\/mandatedata"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","title":"StripePayments"}},"variantOverrides":[{"patch":[{"value":"STPMandateDataParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPMandateDataParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPMandateDataParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}