{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Payment-method-specific configuration for this ConfirmationToken.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConfirmPaymentMethodOptions","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions","text":"STPConfirmPaymentMethodOptions"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"paymentMethodOptions"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconfirmationtokenparams\/paymentmethodoptions"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/paymentMethodOptions","interfaceLanguage":"occ"},"metadata":{"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","title":"paymentMethodOptions","navigatorTitle":[{"text":"paymentMethodOptions","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPConfirmationTokenParams(py)paymentMethodOptions","fragments":[{"kind":"identifier","text":"paymentMethodOptions"}],"modules":[{"name":"StripePayments"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams","kind":"symbol","fragments":[{"kind":"identifier","text":"STPConfirmationTokenParams"}],"type":"topic","url":"\/documentation\/stripepayments\/stpconfirmationtokenparams","abstract":[{"type":"text","text":"An object representing parameters used to create a ConfirmationToken object."},{"type":"text","text":" "},{"text":"seealso:","type":"text"},{"type":"text","text":" "},{"type":"text","text":"https:\/\/stripe.com\/docs\/api\/confirmation_tokens"}],"title":"STPConfirmationTokenParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams/paymentMethodOptions":{"title":"paymentMethodOptions","type":"topic","abstract":[{"type":"text","text":"Payment-method-specific configuration for this ConfirmationToken."}],"role":"symbol","url":"\/documentation\/stripepayments\/stpconfirmationtokenparams\/paymentmethodoptions","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/paymentMethodOptions","fragments":[{"kind":"identifier","text":"paymentMethodOptions"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmPaymentMethodOptions":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPConfirmPaymentMethodOptions"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions","title":"STPConfirmPaymentMethodOptions","role":"symbol","abstract":[{"text":"Options to update the associated PaymentMethod during PaymentIntent confirmation.","type":"text"}],"url":"\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/title","value":"STPConfirmPaymentMethodOptions"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/fragments","value":[{"kind":"identifier","text":"STPConfirmPaymentMethodOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/navigatorTitle","op":"replace","value":[{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}]}]}]}