{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"StripePayments"}],"fragments":[{"kind":"identifier","text":"setupFutureUsage"}],"navigatorTitle":[{"kind":"identifier","text":"setupFutureUsage"}],"role":"symbol","title":"setupFutureUsage","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPConfirmationTokenParams(py)setupFutureUsage"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconfirmationtokenparams\/setupfutureusage"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage","text":"STPPaymentIntentSetupFutureUsage","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupFutureUsage"},{"text":";","kind":"text"}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/setupFutureUsage"},"abstract":[{"type":"text","text":"Indicates that you intend to make future payments with the payment method collected during checkout."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams":{"fragments":[{"text":"STPConfirmationTokenParams","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpconfirmationtokenparams","abstract":[{"text":"An object representing parameters used to create a ConfirmationToken object.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"seealso:"},{"type":"text","text":" "},{"text":"https:\/\/stripe.com\/docs\/api\/confirmation_tokens","type":"text"}],"title":"STPConfirmationTokenParams","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams/setupFutureUsage":{"url":"\/documentation\/stripepayments\/stpconfirmationtokenparams\/setupfutureusage","fragments":[{"kind":"identifier","text":"setupFutureUsage"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/setupFutureUsage","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Indicates that you intend to make future payments with the payment method collected during checkout."}],"title":"setupFutureUsage"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsage"}],"title":"STPPaymentIntentSetupFutureUsage","url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"abstract":[{"text":"Indicates how you intend to use the payment method that your customer provides after the current payment completes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If applicable, additional authentication may be performed to comply with regional legislation or network rules required to enable the usage of the same payment method for additional payments."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/title","value":"STPPaymentIntentSetupFutureUsage"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsage"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/navigatorTitle","value":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"op":"replace"}]}]}