{"sections":[],"metadata":{"roleHeading":"Instance Property","title":"shipping","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPConfirmationTokenParams(py)shipping","navigatorTitle":[{"kind":"identifier","text":"shipping"}],"symbolKind":"property","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"identifier","text":"shipping"}]},"kind":"symbol","abstract":[{"type":"text","text":"Shipping information to include with the ConfirmationToken."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetailsParams","text":"STPPaymentIntentShippingDetailsParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsParams"},{"kind":"text","text":" * "},{"kind":"identifier","text":"shipping"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/stripepayments\/stpconfirmationtokenparams\/shipping"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/shipping","interfaceLanguage":"occ"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams":{"url":"\/documentation\/stripepayments\/stpconfirmationtokenparams","kind":"symbol","title":"STPConfirmationTokenParams","fragments":[{"kind":"identifier","text":"STPConfirmationTokenParams"}],"abstract":[{"type":"text","text":"An object representing parameters used to create a ConfirmationToken object."},{"type":"text","text":" "},{"type":"text","text":"seealso:"},{"type":"text","text":" "},{"type":"text","text":"https:\/\/stripe.com\/docs\/api\/confirmation_tokens"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams/shipping":{"kind":"symbol","abstract":[{"type":"text","text":"Shipping information to include with the ConfirmationToken."}],"role":"symbol","title":"shipping","fragments":[{"text":"shipping","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpconfirmationtokenparams\/shipping","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/shipping"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentShippingDetailsParams":{"url":"\/documentation\/stripepayments\/stppaymentintentshippingdetailsparams","kind":"symbol","title":"STPPaymentIntentShippingDetailsParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentShippingDetailsParams","kind":"identifier"}],"abstract":[{"type":"text","text":"Shipping information for a PaymentIntent"}],"navigatorTitle":[{"text":"STPPaymentIntentShippingDetailsParams","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsParams"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsParams\/title","value":"STPPaymentIntentShippingDetailsParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentShippingDetailsParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntentShippingDetailsParams"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}