{"metadata":{"title":"CustomStringConvertible Implementations","modules":[{"name":"StripePaymentsUI"}],"role":"collectionGroup","roleHeading":"API Collection"},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpcardformviewstyle\/customstringconvertible-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/CustomStringConvertible-Implementations","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/description"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle"]]},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewStyle":{"title":"STPCardFormViewStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPCardFormViewStyle","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpcardformviewstyle","type":"topic","abstract":[{"text":"Options for configuring the display of an ","type":"text"},{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":" instance."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardFormViewStyle"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewStyle/description":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/stripepaymentsui\/stpcardformviewstyle\/description","kind":"symbol","abstract":[],"title":"description"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"title":"StripePaymentsUI","type":"topic","url":"\/documentation\/stripepaymentsui","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/title","value":"STPCardFormViewStyle","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/fragments","value":[{"text":"STPCardFormViewStyle","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"STPCardFormViewStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/navigatorTitle"}]}]}