{"metadata":{"title":"Equatable Implementations","roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"StripePaymentsUI"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"title":"Operators","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/!=(_:_:)"],"anchor":"Operators"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/Equatable-Implementations"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle"]]},"sections":[],"kind":"article","variants":[{"paths":["\/documentation\/stripepaymentsui\/stpcardformviewstyle\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewStyle":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFormViewStyle"}],"navigatorTitle":[{"kind":"identifier","text":"STPCardFormViewStyle"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle","title":"STPCardFormViewStyle","abstract":[{"text":"Options for configuring the display of an ","type":"text"},{"code":"STPCardFormView","type":"codeVoice"},{"text":" instance.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepaymentsui\/stpcardformviewstyle"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","title":"StripePaymentsUI","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"type":"topic","role":"collection","url":"\/documentation\/stripepaymentsui","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewStyle/!=(_:_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"!=(_:_:)","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/!=(_:_:)","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/stripepaymentsui\/stpcardformviewstyle\/!=(_:_:)"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/title","op":"replace","value":"STPCardFormViewStyle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/fragments","op":"replace","value":[{"text":"STPCardFormViewStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/navigatorTitle","op":"replace","value":[{"text":"STPCardFormViewStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}