{"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"text":".","type":"text"}],"metadata":{"modules":[{"name":"StripePaymentsUI"}],"roleHeading":"Initializer","role":"symbol","externalID":"s:16StripePaymentsUI20STPCardFormViewStyleO8rawValueACSgSi_tcfc","symbolKind":"init","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/init(rawValue:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpcardformviewstyle\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"kind":"symbol","role":"collection","title":"StripePaymentsUI","url":"\/documentation\/stripepaymentsui","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewStyle/init(rawValue:)":{"abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/init(rawValue:)","title":"init(rawValue:)","url":"\/documentation\/stripepaymentsui\/stpcardformviewstyle\/init(rawvalue:)"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewStyle":{"navigatorTitle":[{"text":"STPCardFormViewStyle","kind":"identifier"}],"abstract":[{"text":"Options for configuring the display of an ","type":"text"},{"code":"STPCardFormView","type":"codeVoice"},{"text":" instance.","type":"text"}],"kind":"symbol","title":"STPCardFormViewStyle","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFormViewStyle"}],"url":"\/documentation\/stripepaymentsui\/stpcardformviewstyle","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/title","value":"STPCardFormViewStyle","op":"replace"},{"op":"replace","value":[{"text":"STPCardFormViewStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardFormViewStyle"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}