{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpcardformviewstyle\/standard"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stpcardformviewstyle\/standard"]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"STPCardFormViewStyleStandard","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standard","kind":"identifier"}],"symbolKind":"case","role":"symbol","roleHeading":"Case","title":"STPCardFormViewStyle.standard","modules":[{"name":"StripePaymentsUI"}],"externalID":"c:@M@StripePaymentsUI@E@STPCardFormViewStyle@STPCardFormViewStyleStandard"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/standard","interfaceLanguage":"swift"},"abstract":[{"text":"Draws the form in a rounded rect with full separators between","type":"text"},{"text":" ","type":"text"},{"text":"each input field.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standard","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewStyle/standard":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/standard","url":"\/documentation\/stripepaymentsui\/stpcardformviewstyle\/standard","abstract":[{"text":"Draws the form in a rounded rect with full separators between","type":"text"},{"text":" ","type":"text"},{"text":"each input field.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"standard"}],"title":"STPCardFormViewStyle.standard","navigatorTitle":[{"kind":"identifier","text":"STPCardFormViewStyleStandard"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"url":"\/documentation\/stripepaymentsui","role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","title":"StripePaymentsUI","type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewStyle":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardFormViewStyle","kind":"identifier"}],"url":"\/documentation\/stripepaymentsui\/stpcardformviewstyle","type":"topic","navigatorTitle":[{"text":"STPCardFormViewStyle","kind":"identifier"}],"abstract":[{"text":"Options for configuring the display of an ","type":"text"},{"type":"codeVoice","code":"STPCardFormView"},{"text":" instance.","type":"text"}],"title":"STPCardFormViewStyle"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"STPCardFormViewStyleStandard"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPCardFormViewStyleStandard","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"STPCardFormViewStyleStandard","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle~1standard\/title","op":"replace","value":"STPCardFormViewStyleStandard"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle~1standard\/fragments","value":[{"kind":"identifier","text":"STPCardFormViewStyleStandard"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/title","value":"STPCardFormViewStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/fragments","value":[{"kind":"identifier","text":"STPCardFormViewStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/navigatorTitle","value":[{"text":"STPCardFormViewStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}