//
//  MobileSession.swift
//  StripePaymentSheet
//
//  Generated by mobile-session-codegen. DO NOT EDIT.
//  contract revision: eae9b348c98cf67b (major 1)
//
//  Plain request/response structs. camelCase properties decode against
//  StripeCore's StripeJSONDecoder, which maps them to snake_case wire keys
//  automatically.
//

import Foundation
@_spi(STP) import StripeCore

@_spi(STP) public enum MobileSessionContractV1 {
    @_spi(STP) public static let contractRevision = "eae9b348c98cf67b"
    @_spi(STP) public static let contractMajor = 1
    @_spi(STP) public static let contractDigest = "eae9b348c98cf67b22e31322185f8ec64623e7d5d585cce083d844404d2a8a74"
    @_spi(STP) public static let generatorDigest = "0c88f2a5a9217e261d82cdad233e898a9612f8c6a4699685b5973f069cfb5d97"
    @_spi(STP) public static let mintCommit = "ddfcb9410dc5e7d81f9bcac242c9bfe153abc16d"
}

/// Serializable Apple Pay settings from PaymentSheet.Configuration.
@_spi(STP) public struct ApplePayConfigV1: Codable, Equatable {
    @_spi(STP) public var merchantCountryCode: String
    @_spi(STP) public var merchantId: String
    @_spi(STP) public var buttonType: String
    @_spi(STP) public var paymentSummaryItemsProvided: Bool
    @_spi(STP) public var paymentRequestHandlerProvided: Bool
    @_spi(STP) public var authorizationResultHandlerProvided: Bool
    @_spi(STP) public var shippingMethodUpdateHandlerProvided: Bool
    @_spi(STP) public var shippingContactUpdateHandlerProvided: Bool

    private enum CodingKeys: String, CodingKey {
        case merchantCountryCode = "merchant_country_code"
        case merchantId = "merchant_id"
        case buttonType = "button_type"
        case paymentSummaryItemsProvided = "payment_summary_items_provided"
        case paymentRequestHandlerProvided = "payment_request_handler_provided"
        case authorizationResultHandlerProvided = "authorization_result_handler_provided"
        case shippingMethodUpdateHandlerProvided = "shipping_method_update_handler_provided"
        case shippingContactUpdateHandlerProvided = "shipping_contact_update_handler_provided"
    }

    @_spi(STP) public init(
        merchantCountryCode: String,
        merchantId: String,
        buttonType: String = "plain",
        paymentSummaryItemsProvided: Bool = false,
        paymentRequestHandlerProvided: Bool = false,
        authorizationResultHandlerProvided: Bool = false,
        shippingMethodUpdateHandlerProvided: Bool = false,
        shippingContactUpdateHandlerProvided: Bool = false
    ) {
        self.merchantCountryCode = merchantCountryCode
        self.merchantId = merchantId
        self.buttonType = buttonType
        self.paymentSummaryItemsProvided = paymentSummaryItemsProvided
        self.paymentRequestHandlerProvided = paymentRequestHandlerProvided
        self.authorizationResultHandlerProvided = authorizationResultHandlerProvided
        self.shippingMethodUpdateHandlerProvided = shippingMethodUpdateHandlerProvided
        self.shippingContactUpdateHandlerProvided = shippingContactUpdateHandlerProvided
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.merchantCountryCode = try container.decode(
            String.self,
            forKey: .merchantCountryCode
        )
        self.merchantId = try container.decode(
            String.self,
            forKey: .merchantId
        )
        self.buttonType = try container.decodeIfPresent(
            String.self,
            forKey: .buttonType
        ) ?? "plain"
        self.paymentSummaryItemsProvided = try container.decodeIfPresent(
            Bool.self,
            forKey: .paymentSummaryItemsProvided
        ) ?? false
        self.paymentRequestHandlerProvided = try container.decodeIfPresent(
            Bool.self,
            forKey: .paymentRequestHandlerProvided
        ) ?? false
        self.authorizationResultHandlerProvided = try container.decodeIfPresent(
            Bool.self,
            forKey: .authorizationResultHandlerProvided
        ) ?? false
        self.shippingMethodUpdateHandlerProvided = try container.decodeIfPresent(
            Bool.self,
            forKey: .shippingMethodUpdateHandlerProvided
        ) ?? false
        self.shippingContactUpdateHandlerProvided = try container.decodeIfPresent(
            Bool.self,
            forKey: .shippingContactUpdateHandlerProvided
        ) ?? false
    }
}

/// Serializable Google Pay settings from PaymentSheet.Configuration.
@_spi(STP) public struct GooglePayConfigV1: Codable, Equatable {
    @_spi(STP) public var merchantCountryCode: String
    @_spi(STP) public var environment: String
    @_spi(STP) public var currencyCode: String?
    @_spi(STP) public var amountProvided: Bool
    @_spi(STP) public var labelProvided: Bool
    @_spi(STP) public var buttonType: String
    @_spi(STP) public var additionalEnabledNetworks: [String]

    private enum CodingKeys: String, CodingKey {
        case merchantCountryCode = "merchant_country_code"
        case environment = "environment"
        case currencyCode = "currency_code"
        case amountProvided = "amount_provided"
        case labelProvided = "label_provided"
        case buttonType = "button_type"
        case additionalEnabledNetworks = "additional_enabled_networks"
    }

    @_spi(STP) public init(
        merchantCountryCode: String,
        environment: String = "production",
        currencyCode: String? = nil,
        amountProvided: Bool = false,
        labelProvided: Bool = false,
        buttonType: String = "pay",
        additionalEnabledNetworks: [String] = []
    ) {
        self.merchantCountryCode = merchantCountryCode
        self.environment = environment
        self.currencyCode = currencyCode
        self.amountProvided = amountProvided
        self.labelProvided = labelProvided
        self.buttonType = buttonType
        self.additionalEnabledNetworks = additionalEnabledNetworks
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.merchantCountryCode = try container.decode(
            String.self,
            forKey: .merchantCountryCode
        )
        self.environment = try container.decodeIfPresent(
            String.self,
            forKey: .environment
        ) ?? "production"
        self.currencyCode = try container.decodeIfPresent(
            String.self,
            forKey: .currencyCode
        )
        self.amountProvided = try container.decodeIfPresent(
            Bool.self,
            forKey: .amountProvided
        ) ?? false
        self.labelProvided = try container.decodeIfPresent(
            Bool.self,
            forKey: .labelProvided
        ) ?? false
        self.buttonType = try container.decodeIfPresent(
            String.self,
            forKey: .buttonType
        ) ?? "pay"
        self.additionalEnabledNetworks = try container.decodeIfPresent(
            [String].self,
            forKey: .additionalEnabledNetworks
        ) ?? []
    }
}

/// Serializable Link settings from PaymentSheet.Configuration.
@_spi(STP) public struct LinkConfigV1: Codable, Equatable {
    @_spi(STP) public var display: String
    @_spi(STP) public var brand: String?
    @_spi(STP) public var disabledFundingSources: [String]
    @_spi(STP) public var collectMissingBillingDetailsForExistingPaymentMethods: Bool
    @_spi(STP) public var allowUserEmailEdits: Bool
    @_spi(STP) public var allowLogout: Bool

    private enum CodingKeys: String, CodingKey {
        case display = "display"
        case brand = "brand"
        case disabledFundingSources = "disabled_funding_sources"
        case collectMissingBillingDetailsForExistingPaymentMethods = "collect_missing_billing_details_for_existing_payment_methods"
        case allowUserEmailEdits = "allow_user_email_edits"
        case allowLogout = "allow_logout"
    }

    @_spi(STP) public init(
        display: String = "automatic",
        brand: String? = nil,
        disabledFundingSources: [String] = [],
        collectMissingBillingDetailsForExistingPaymentMethods: Bool = true,
        allowUserEmailEdits: Bool = true,
        allowLogout: Bool = true
    ) {
        self.display = display
        self.brand = brand
        self.disabledFundingSources = disabledFundingSources
        self.collectMissingBillingDetailsForExistingPaymentMethods = collectMissingBillingDetailsForExistingPaymentMethods
        self.allowUserEmailEdits = allowUserEmailEdits
        self.allowLogout = allowLogout
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.display = try container.decodeIfPresent(
            String.self,
            forKey: .display
        ) ?? "automatic"
        self.brand = try container.decodeIfPresent(
            String.self,
            forKey: .brand
        )
        self.disabledFundingSources = try container.decodeIfPresent(
            [String].self,
            forKey: .disabledFundingSources
        ) ?? []
        self.collectMissingBillingDetailsForExistingPaymentMethods = try container.decodeIfPresent(
            Bool.self,
            forKey: .collectMissingBillingDetailsForExistingPaymentMethods
        ) ?? true
        self.allowUserEmailEdits = try container.decodeIfPresent(
            Bool.self,
            forKey: .allowUserEmailEdits
        ) ?? true
        self.allowLogout = try container.decodeIfPresent(
            Bool.self,
            forKey: .allowLogout
        ) ?? true
    }
}

/// Data-minimized Shop Pay settings and handler capabilities.
@_spi(STP) public struct ShopPayConfigV1: Codable, Equatable {
    @_spi(STP) public var billingAddressRequired: Bool
    @_spi(STP) public var emailRequired: Bool
    @_spi(STP) public var shippingAddressRequired: Bool
    @_spi(STP) public var allowedShippingCountries: [String]
    @_spi(STP) public var lineItemsProvided: Bool
    @_spi(STP) public var shippingRatesProvided: Bool
    @_spi(STP) public var shippingMethodUpdateHandlerProvided: Bool
    @_spi(STP) public var shippingContactUpdateHandlerProvided: Bool

    private enum CodingKeys: String, CodingKey {
        case billingAddressRequired = "billing_address_required"
        case emailRequired = "email_required"
        case shippingAddressRequired = "shipping_address_required"
        case allowedShippingCountries = "allowed_shipping_countries"
        case lineItemsProvided = "line_items_provided"
        case shippingRatesProvided = "shipping_rates_provided"
        case shippingMethodUpdateHandlerProvided = "shipping_method_update_handler_provided"
        case shippingContactUpdateHandlerProvided = "shipping_contact_update_handler_provided"
    }

    @_spi(STP) public init(
        billingAddressRequired: Bool = true,
        emailRequired: Bool = true,
        shippingAddressRequired: Bool = false,
        allowedShippingCountries: [String] = [],
        lineItemsProvided: Bool = false,
        shippingRatesProvided: Bool = false,
        shippingMethodUpdateHandlerProvided: Bool = false,
        shippingContactUpdateHandlerProvided: Bool = false
    ) {
        self.billingAddressRequired = billingAddressRequired
        self.emailRequired = emailRequired
        self.shippingAddressRequired = shippingAddressRequired
        self.allowedShippingCountries = allowedShippingCountries
        self.lineItemsProvided = lineItemsProvided
        self.shippingRatesProvided = shippingRatesProvided
        self.shippingMethodUpdateHandlerProvided = shippingMethodUpdateHandlerProvided
        self.shippingContactUpdateHandlerProvided = shippingContactUpdateHandlerProvided
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.billingAddressRequired = try container.decodeIfPresent(
            Bool.self,
            forKey: .billingAddressRequired
        ) ?? true
        self.emailRequired = try container.decodeIfPresent(
            Bool.self,
            forKey: .emailRequired
        ) ?? true
        self.shippingAddressRequired = try container.decodeIfPresent(
            Bool.self,
            forKey: .shippingAddressRequired
        ) ?? false
        self.allowedShippingCountries = try container.decodeIfPresent(
            [String].self,
            forKey: .allowedShippingCountries
        ) ?? []
        self.lineItemsProvided = try container.decodeIfPresent(
            Bool.self,
            forKey: .lineItemsProvided
        ) ?? false
        self.shippingRatesProvided = try container.decodeIfPresent(
            Bool.self,
            forKey: .shippingRatesProvided
        ) ?? false
        self.shippingMethodUpdateHandlerProvided = try container.decodeIfPresent(
            Bool.self,
            forKey: .shippingMethodUpdateHandlerProvided
        ) ?? false
        self.shippingContactUpdateHandlerProvided = try container.decodeIfPresent(
            Bool.self,
            forKey: .shippingContactUpdateHandlerProvided
        ) ?? false
    }
}

/// Presence-only view of default billing details; values remain on-device.
@_spi(STP) public struct BillingDetailsPresenceV1: Codable, Equatable {
    @_spi(STP) public var name: Bool
    @_spi(STP) public var email: Bool
    @_spi(STP) public var phone: Bool
    @_spi(STP) public var address: Bool
    @_spi(STP) public var addressCity: Bool
    @_spi(STP) public var addressLine1: Bool
    @_spi(STP) public var addressLine2: Bool
    @_spi(STP) public var addressPostalCode: Bool
    @_spi(STP) public var addressState: Bool
    @_spi(STP) public var addressCountryCode: String?

    private enum CodingKeys: String, CodingKey {
        case name = "name"
        case email = "email"
        case phone = "phone"
        case address = "address"
        case addressCity = "address_city"
        case addressLine1 = "address_line1"
        case addressLine2 = "address_line2"
        case addressPostalCode = "address_postal_code"
        case addressState = "address_state"
        case addressCountryCode = "address_country_code"
    }

    @_spi(STP) public init(
        name: Bool = false,
        email: Bool = false,
        phone: Bool = false,
        address: Bool = false,
        addressCity: Bool = false,
        addressLine1: Bool = false,
        addressLine2: Bool = false,
        addressPostalCode: Bool = false,
        addressState: Bool = false,
        addressCountryCode: String? = nil
    ) {
        self.name = name
        self.email = email
        self.phone = phone
        self.address = address
        self.addressCity = addressCity
        self.addressLine1 = addressLine1
        self.addressLine2 = addressLine2
        self.addressPostalCode = addressPostalCode
        self.addressState = addressState
        self.addressCountryCode = addressCountryCode
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.name = try container.decodeIfPresent(
            Bool.self,
            forKey: .name
        ) ?? false
        self.email = try container.decodeIfPresent(
            Bool.self,
            forKey: .email
        ) ?? false
        self.phone = try container.decodeIfPresent(
            Bool.self,
            forKey: .phone
        ) ?? false
        self.address = try container.decodeIfPresent(
            Bool.self,
            forKey: .address
        ) ?? false
        self.addressCity = try container.decodeIfPresent(
            Bool.self,
            forKey: .addressCity
        ) ?? false
        self.addressLine1 = try container.decodeIfPresent(
            Bool.self,
            forKey: .addressLine1
        ) ?? false
        self.addressLine2 = try container.decodeIfPresent(
            Bool.self,
            forKey: .addressLine2
        ) ?? false
        self.addressPostalCode = try container.decodeIfPresent(
            Bool.self,
            forKey: .addressPostalCode
        ) ?? false
        self.addressState = try container.decodeIfPresent(
            Bool.self,
            forKey: .addressState
        ) ?? false
        self.addressCountryCode = try container.decodeIfPresent(
            String.self,
            forKey: .addressCountryCode
        )
    }
}

/// Non-sensitive custom payment-method behavior used for server-owned form selection.
@_spi(STP) public struct CustomPaymentMethodConfigV1: Codable, Equatable {
    @_spi(STP) public var id: String
    @_spi(STP) public var subtitleProvided: Bool
    @_spi(STP) public var disableBillingDetailCollection: Bool

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case subtitleProvided = "subtitle_provided"
        case disableBillingDetailCollection = "disable_billing_detail_collection"
    }

    @_spi(STP) public init(
        id: String,
        subtitleProvided: Bool = false,
        disableBillingDetailCollection: Bool = true
    ) {
        self.id = id
        self.subtitleProvided = subtitleProvided
        self.disableBillingDetailCollection = disableBillingDetailCollection
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(
            String.self,
            forKey: .id
        )
        self.subtitleProvided = try container.decodeIfPresent(
            Bool.self,
            forKey: .subtitleProvided
        ) ?? false
        self.disableBillingDetailCollection = try container.decodeIfPresent(
            Bool.self,
            forKey: .disableBillingDetailCollection
        ) ?? true
    }
}

/// Wallet surface visibility without platform UI objects.
@_spi(STP) public struct WalletButtonsConfigV1: Codable, Equatable {
    @_spi(STP) public var willDisplayExternally: Bool
    @_spi(STP) public var paymentElement: [String: String]
    @_spi(STP) public var walletButtonsView: [String: String]

    private enum CodingKeys: String, CodingKey {
        case willDisplayExternally = "will_display_externally"
        case paymentElement = "payment_element"
        case walletButtonsView = "wallet_buttons_view"
    }

    @_spi(STP) public init(
        willDisplayExternally: Bool = false,
        paymentElement: [String: String] = [:],
        walletButtonsView: [String: String] = [:]
    ) {
        self.willDisplayExternally = willDisplayExternally
        self.paymentElement = paymentElement
        self.walletButtonsView = walletButtonsView
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.willDisplayExternally = try container.decodeIfPresent(
            Bool.self,
            forKey: .willDisplayExternally
        ) ?? false
        self.paymentElement = try container.decodeIfPresent(
            [String: String].self,
            forKey: .paymentElement
        ) ?? [:]
        self.walletButtonsView = try container.decodeIfPresent(
            [String: String].self,
            forKey: .walletButtonsView
        ) ?? [:]
    }
}

/// Billing details collection behavior from PaymentSheet.Configuration.
@_spi(STP) public struct BillingDetailsCollectionConfigV1: Codable, Equatable {
    @_spi(STP) public var name: String
    @_spi(STP) public var phone: String
    @_spi(STP) public var email: String
    @_spi(STP) public var address: String
    @_spi(STP) public var attachDefaultsToPaymentMethod: Bool
    @_spi(STP) public var allowedCountries: [String]

    private enum CodingKeys: String, CodingKey {
        case name = "name"
        case phone = "phone"
        case email = "email"
        case address = "address"
        case attachDefaultsToPaymentMethod = "attach_defaults_to_payment_method"
        case allowedCountries = "allowed_countries"
    }

    @_spi(STP) public init(
        name: String = "automatic",
        phone: String = "automatic",
        email: String = "automatic",
        address: String = "automatic",
        attachDefaultsToPaymentMethod: Bool = false,
        allowedCountries: [String] = []
    ) {
        self.name = name
        self.phone = phone
        self.email = email
        self.address = address
        self.attachDefaultsToPaymentMethod = attachDefaultsToPaymentMethod
        self.allowedCountries = allowedCountries
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.name = try container.decodeIfPresent(
            String.self,
            forKey: .name
        ) ?? "automatic"
        self.phone = try container.decodeIfPresent(
            String.self,
            forKey: .phone
        ) ?? "automatic"
        self.email = try container.decodeIfPresent(
            String.self,
            forKey: .email
        ) ?? "automatic"
        self.address = try container.decodeIfPresent(
            String.self,
            forKey: .address
        ) ?? "automatic"
        self.attachDefaultsToPaymentMethod = try container.decodeIfPresent(
            Bool.self,
            forKey: .attachDefaultsToPaymentMethod
        ) ?? false
        self.allowedCountries = try container.decodeIfPresent(
            [String].self,
            forKey: .allowedCountries
        ) ?? []
    }
}

/// Card brand filtering behavior from PaymentSheet.Configuration.
@_spi(STP) public struct CardBrandAcceptanceV1: Codable, Equatable {
    @_spi(STP) public var filter: String
    @_spi(STP) public var brands: [String]

    private enum CodingKeys: String, CodingKey {
        case filter = "filter"
        case brands = "brands"
    }

    @_spi(STP) public init(
        filter: String = "all",
        brands: [String] = []
    ) {
        self.filter = filter
        self.brands = brands
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.filter = try container.decodeIfPresent(
            String.self,
            forKey: .filter
        ) ?? "all"
        self.brands = try container.decodeIfPresent(
            [String].self,
            forKey: .brands
        ) ?? []
    }
}

/// Serializable subset of PaymentSheet.Configuration sent up on load.
@_spi(STP) public struct PaymentSheetConfigV1: Codable, Equatable {
    @_spi(STP) public var merchantCountryCode: String?
    @_spi(STP) public var allowsDelayedPaymentMethods: Bool
    @_spi(STP) public var allowsPaymentMethodsRequiringShippingAddress: Bool
    @_spi(STP) public var applePay: ApplePayConfigV1?
    @_spi(STP) public var googlePay: GooglePayConfigV1?
    @_spi(STP) public var link: LinkConfigV1
    @_spi(STP) public var shopPay: ShopPayConfigV1?
    @_spi(STP) public var returnUrlProvided: Bool
    @_spi(STP) public var merchantDisplayNameProvided: Bool
    @_spi(STP) public var customerConfigured: Bool
    @_spi(STP) public var customerAccessType: String?
    @_spi(STP) public var customApiClient: Bool
    @_spi(STP) public var defaultBillingDetails: BillingDetailsPresenceV1
    @_spi(STP) public var shippingDetailsProvided: Bool
    @_spi(STP) public var savePaymentMethodOptInBehavior: String
    @_spi(STP) public var primaryButtonLabelProvided: Bool
    @_spi(STP) public var appearanceCustomized: Bool
    @_spi(STP) public var userInterfaceStyle: String
    @_spi(STP) public var preferredNetworks: [String]
    @_spi(STP) public var billingDetailsCollectionConfiguration: BillingDetailsCollectionConfigV1
    @_spi(STP) public var externalPaymentMethods: [String]
    @_spi(STP) public var customPaymentMethodIds: [String]
    @_spi(STP) public var customPaymentMethods: [CustomPaymentMethodConfigV1]
    @_spi(STP) public var externalPaymentMethodHandlerProvided: Bool
    @_spi(STP) public var customPaymentMethodHandlerProvided: Bool
    @_spi(STP) public var paymentMethodOrder: [String]
    @_spi(STP) public var paymentMethodLayout: String
    @_spi(STP) public var cardBrandAcceptance: CardBrandAcceptanceV1
    @_spi(STP) public var allowedCardFundingTypes: [String]
    @_spi(STP) public var termsDisplay: [String: String]
    @_spi(STP) public var allowsRemovalOfLastSavedPaymentMethod: Bool
    @_spi(STP) public var removeSavedPaymentMethodMessageProvided: Bool
    @_spi(STP) public var opensCardScannerAutomatically: Bool
    @_spi(STP) public var disableWalletPaymentMethodFiltering: Bool
    @_spi(STP) public var linkPaymentMethodsOnly: Bool
    @_spi(STP) public var walletButtons: WalletButtonsConfigV1
    @_spi(STP) public var googlePlacesApiKeyProvided: Bool
    @_spi(STP) public var userOverrideCountry: String?

    private enum CodingKeys: String, CodingKey {
        case merchantCountryCode = "merchant_country_code"
        case allowsDelayedPaymentMethods = "allows_delayed_payment_methods"
        case allowsPaymentMethodsRequiringShippingAddress = "allows_payment_methods_requiring_shipping_address"
        case applePay = "apple_pay"
        case googlePay = "google_pay"
        case link = "link"
        case shopPay = "shop_pay"
        case returnUrlProvided = "return_url_provided"
        case merchantDisplayNameProvided = "merchant_display_name_provided"
        case customerConfigured = "customer_configured"
        case customerAccessType = "customer_access_type"
        case customApiClient = "custom_api_client"
        case defaultBillingDetails = "default_billing_details"
        case shippingDetailsProvided = "shipping_details_provided"
        case savePaymentMethodOptInBehavior = "save_payment_method_opt_in_behavior"
        case primaryButtonLabelProvided = "primary_button_label_provided"
        case appearanceCustomized = "appearance_customized"
        case userInterfaceStyle = "user_interface_style"
        case preferredNetworks = "preferred_networks"
        case billingDetailsCollectionConfiguration = "billing_details_collection_configuration"
        case externalPaymentMethods = "external_payment_methods"
        case customPaymentMethodIds = "custom_payment_method_ids"
        case customPaymentMethods = "custom_payment_methods"
        case externalPaymentMethodHandlerProvided = "external_payment_method_handler_provided"
        case customPaymentMethodHandlerProvided = "custom_payment_method_handler_provided"
        case paymentMethodOrder = "payment_method_order"
        case paymentMethodLayout = "payment_method_layout"
        case cardBrandAcceptance = "card_brand_acceptance"
        case allowedCardFundingTypes = "allowed_card_funding_types"
        case termsDisplay = "terms_display"
        case allowsRemovalOfLastSavedPaymentMethod = "allows_removal_of_last_saved_payment_method"
        case removeSavedPaymentMethodMessageProvided = "remove_saved_payment_method_message_provided"
        case opensCardScannerAutomatically = "opens_card_scanner_automatically"
        case disableWalletPaymentMethodFiltering = "disable_wallet_payment_method_filtering"
        case linkPaymentMethodsOnly = "link_payment_methods_only"
        case walletButtons = "wallet_buttons"
        case googlePlacesApiKeyProvided = "google_places_api_key_provided"
        case userOverrideCountry = "user_override_country"
    }

    @_spi(STP) public init(
        merchantCountryCode: String? = nil,
        allowsDelayedPaymentMethods: Bool = false,
        allowsPaymentMethodsRequiringShippingAddress: Bool = false,
        applePay: ApplePayConfigV1? = nil,
        googlePay: GooglePayConfigV1? = nil,
        link: LinkConfigV1 = LinkConfigV1(),
        shopPay: ShopPayConfigV1? = nil,
        returnUrlProvided: Bool = false,
        merchantDisplayNameProvided: Bool = false,
        customerConfigured: Bool = false,
        customerAccessType: String? = nil,
        customApiClient: Bool = false,
        defaultBillingDetails: BillingDetailsPresenceV1 = BillingDetailsPresenceV1(),
        shippingDetailsProvided: Bool = false,
        savePaymentMethodOptInBehavior: String = "automatic",
        primaryButtonLabelProvided: Bool = false,
        appearanceCustomized: Bool = false,
        userInterfaceStyle: String = "automatic",
        preferredNetworks: [String] = [],
        billingDetailsCollectionConfiguration: BillingDetailsCollectionConfigV1 = BillingDetailsCollectionConfigV1(),
        externalPaymentMethods: [String] = [],
        customPaymentMethodIds: [String] = [],
        customPaymentMethods: [CustomPaymentMethodConfigV1] = [],
        externalPaymentMethodHandlerProvided: Bool = false,
        customPaymentMethodHandlerProvided: Bool = false,
        paymentMethodOrder: [String] = [],
        paymentMethodLayout: String = "automatic",
        cardBrandAcceptance: CardBrandAcceptanceV1 = CardBrandAcceptanceV1(),
        allowedCardFundingTypes: [String] = [],
        termsDisplay: [String: String] = [:],
        allowsRemovalOfLastSavedPaymentMethod: Bool = true,
        removeSavedPaymentMethodMessageProvided: Bool = false,
        opensCardScannerAutomatically: Bool = false,
        disableWalletPaymentMethodFiltering: Bool = false,
        linkPaymentMethodsOnly: Bool = false,
        walletButtons: WalletButtonsConfigV1 = WalletButtonsConfigV1(),
        googlePlacesApiKeyProvided: Bool = false,
        userOverrideCountry: String? = nil
    ) {
        self.merchantCountryCode = merchantCountryCode
        self.allowsDelayedPaymentMethods = allowsDelayedPaymentMethods
        self.allowsPaymentMethodsRequiringShippingAddress = allowsPaymentMethodsRequiringShippingAddress
        self.applePay = applePay
        self.googlePay = googlePay
        self.link = link
        self.shopPay = shopPay
        self.returnUrlProvided = returnUrlProvided
        self.merchantDisplayNameProvided = merchantDisplayNameProvided
        self.customerConfigured = customerConfigured
        self.customerAccessType = customerAccessType
        self.customApiClient = customApiClient
        self.defaultBillingDetails = defaultBillingDetails
        self.shippingDetailsProvided = shippingDetailsProvided
        self.savePaymentMethodOptInBehavior = savePaymentMethodOptInBehavior
        self.primaryButtonLabelProvided = primaryButtonLabelProvided
        self.appearanceCustomized = appearanceCustomized
        self.userInterfaceStyle = userInterfaceStyle
        self.preferredNetworks = preferredNetworks
        self.billingDetailsCollectionConfiguration = billingDetailsCollectionConfiguration
        self.externalPaymentMethods = externalPaymentMethods
        self.customPaymentMethodIds = customPaymentMethodIds
        self.customPaymentMethods = customPaymentMethods
        self.externalPaymentMethodHandlerProvided = externalPaymentMethodHandlerProvided
        self.customPaymentMethodHandlerProvided = customPaymentMethodHandlerProvided
        self.paymentMethodOrder = paymentMethodOrder
        self.paymentMethodLayout = paymentMethodLayout
        self.cardBrandAcceptance = cardBrandAcceptance
        self.allowedCardFundingTypes = allowedCardFundingTypes
        self.termsDisplay = termsDisplay
        self.allowsRemovalOfLastSavedPaymentMethod = allowsRemovalOfLastSavedPaymentMethod
        self.removeSavedPaymentMethodMessageProvided = removeSavedPaymentMethodMessageProvided
        self.opensCardScannerAutomatically = opensCardScannerAutomatically
        self.disableWalletPaymentMethodFiltering = disableWalletPaymentMethodFiltering
        self.linkPaymentMethodsOnly = linkPaymentMethodsOnly
        self.walletButtons = walletButtons
        self.googlePlacesApiKeyProvided = googlePlacesApiKeyProvided
        self.userOverrideCountry = userOverrideCountry
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.merchantCountryCode = try container.decodeIfPresent(
            String.self,
            forKey: .merchantCountryCode
        )
        self.allowsDelayedPaymentMethods = try container.decodeIfPresent(
            Bool.self,
            forKey: .allowsDelayedPaymentMethods
        ) ?? false
        self.allowsPaymentMethodsRequiringShippingAddress = try container.decodeIfPresent(
            Bool.self,
            forKey: .allowsPaymentMethodsRequiringShippingAddress
        ) ?? false
        self.applePay = try container.decodeIfPresent(
            ApplePayConfigV1.self,
            forKey: .applePay
        )
        self.googlePay = try container.decodeIfPresent(
            GooglePayConfigV1.self,
            forKey: .googlePay
        )
        self.link = try container.decodeIfPresent(
            LinkConfigV1.self,
            forKey: .link
        ) ?? LinkConfigV1()
        self.shopPay = try container.decodeIfPresent(
            ShopPayConfigV1.self,
            forKey: .shopPay
        )
        self.returnUrlProvided = try container.decodeIfPresent(
            Bool.self,
            forKey: .returnUrlProvided
        ) ?? false
        self.merchantDisplayNameProvided = try container.decodeIfPresent(
            Bool.self,
            forKey: .merchantDisplayNameProvided
        ) ?? false
        self.customerConfigured = try container.decodeIfPresent(
            Bool.self,
            forKey: .customerConfigured
        ) ?? false
        self.customerAccessType = try container.decodeIfPresent(
            String.self,
            forKey: .customerAccessType
        )
        self.customApiClient = try container.decodeIfPresent(
            Bool.self,
            forKey: .customApiClient
        ) ?? false
        self.defaultBillingDetails = try container.decodeIfPresent(
            BillingDetailsPresenceV1.self,
            forKey: .defaultBillingDetails
        ) ?? BillingDetailsPresenceV1()
        self.shippingDetailsProvided = try container.decodeIfPresent(
            Bool.self,
            forKey: .shippingDetailsProvided
        ) ?? false
        self.savePaymentMethodOptInBehavior = try container.decodeIfPresent(
            String.self,
            forKey: .savePaymentMethodOptInBehavior
        ) ?? "automatic"
        self.primaryButtonLabelProvided = try container.decodeIfPresent(
            Bool.self,
            forKey: .primaryButtonLabelProvided
        ) ?? false
        self.appearanceCustomized = try container.decodeIfPresent(
            Bool.self,
            forKey: .appearanceCustomized
        ) ?? false
        self.userInterfaceStyle = try container.decodeIfPresent(
            String.self,
            forKey: .userInterfaceStyle
        ) ?? "automatic"
        self.preferredNetworks = try container.decodeIfPresent(
            [String].self,
            forKey: .preferredNetworks
        ) ?? []
        self.billingDetailsCollectionConfiguration = try container.decodeIfPresent(
            BillingDetailsCollectionConfigV1.self,
            forKey: .billingDetailsCollectionConfiguration
        ) ?? BillingDetailsCollectionConfigV1()
        self.externalPaymentMethods = try container.decodeIfPresent(
            [String].self,
            forKey: .externalPaymentMethods
        ) ?? []
        self.customPaymentMethodIds = try container.decodeIfPresent(
            [String].self,
            forKey: .customPaymentMethodIds
        ) ?? []
        self.customPaymentMethods = try container.decodeIfPresent(
            [CustomPaymentMethodConfigV1].self,
            forKey: .customPaymentMethods
        ) ?? []
        self.externalPaymentMethodHandlerProvided = try container.decodeIfPresent(
            Bool.self,
            forKey: .externalPaymentMethodHandlerProvided
        ) ?? false
        self.customPaymentMethodHandlerProvided = try container.decodeIfPresent(
            Bool.self,
            forKey: .customPaymentMethodHandlerProvided
        ) ?? false
        self.paymentMethodOrder = try container.decodeIfPresent(
            [String].self,
            forKey: .paymentMethodOrder
        ) ?? []
        self.paymentMethodLayout = try container.decodeIfPresent(
            String.self,
            forKey: .paymentMethodLayout
        ) ?? "automatic"
        self.cardBrandAcceptance = try container.decodeIfPresent(
            CardBrandAcceptanceV1.self,
            forKey: .cardBrandAcceptance
        ) ?? CardBrandAcceptanceV1()
        self.allowedCardFundingTypes = try container.decodeIfPresent(
            [String].self,
            forKey: .allowedCardFundingTypes
        ) ?? []
        self.termsDisplay = try container.decodeIfPresent(
            [String: String].self,
            forKey: .termsDisplay
        ) ?? [:]
        self.allowsRemovalOfLastSavedPaymentMethod = try container.decodeIfPresent(
            Bool.self,
            forKey: .allowsRemovalOfLastSavedPaymentMethod
        ) ?? true
        self.removeSavedPaymentMethodMessageProvided = try container.decodeIfPresent(
            Bool.self,
            forKey: .removeSavedPaymentMethodMessageProvided
        ) ?? false
        self.opensCardScannerAutomatically = try container.decodeIfPresent(
            Bool.self,
            forKey: .opensCardScannerAutomatically
        ) ?? false
        self.disableWalletPaymentMethodFiltering = try container.decodeIfPresent(
            Bool.self,
            forKey: .disableWalletPaymentMethodFiltering
        ) ?? false
        self.linkPaymentMethodsOnly = try container.decodeIfPresent(
            Bool.self,
            forKey: .linkPaymentMethodsOnly
        ) ?? false
        self.walletButtons = try container.decodeIfPresent(
            WalletButtonsConfigV1.self,
            forKey: .walletButtons
        ) ?? WalletButtonsConfigV1()
        self.googlePlacesApiKeyProvided = try container.decodeIfPresent(
            Bool.self,
            forKey: .googlePlacesApiKeyProvided
        ) ?? false
        self.userOverrideCountry = try container.decodeIfPresent(
            String.self,
            forKey: .userOverrideCountry
        )
    }
}

/// Nested object on the elements/sessions response carrying mobile Payment Element data.
@_spi(STP) public struct MobilePaymentElementV1: UnknownFieldsCodable, Equatable {
    @_spi(STP) public var contract: ContractMetadataV1
    @_spi(STP) public var paymentMethodAvailability: PaymentMethodAvailabilityV1
    @_spi(STP) public var features: MobilePaymentElementFeaturesV1
    @_spi(STP) public var assets: MobilePaymentElementAssetsV1
    @_spi(STP) public var formSpecs: [PaymentMethodFormSpecV1]
    @_spi(STP) public var _allResponseFieldsStorage: NonEncodableParameters?
    @_spi(STP) public var _additionalParametersStorage: NonEncodableParameters?

    private enum CodingKeys: String, CodingKey {
        case contract = "contract"
        case paymentMethodAvailability = "payment_method_availability"
        case features = "features"
        case assets = "assets"
        case formSpecs = "form_specs"
    }

    @_spi(STP) public init(
        contract: ContractMetadataV1,
        paymentMethodAvailability: PaymentMethodAvailabilityV1,
        features: MobilePaymentElementFeaturesV1 = MobilePaymentElementFeaturesV1(),
        assets: MobilePaymentElementAssetsV1 = MobilePaymentElementAssetsV1(),
        formSpecs: [PaymentMethodFormSpecV1] = []
    ) {
        self.contract = contract
        self.paymentMethodAvailability = paymentMethodAvailability
        self.features = features
        self.assets = assets
        self.formSpecs = formSpecs
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.contract = try container.decode(
            ContractMetadataV1.self,
            forKey: .contract
        )
        self.paymentMethodAvailability = try container.decode(
            PaymentMethodAvailabilityV1.self,
            forKey: .paymentMethodAvailability
        )
        self.features = try container.decodeIfPresent(
            MobilePaymentElementFeaturesV1.self,
            forKey: .features
        ) ?? MobilePaymentElementFeaturesV1()
        self.assets = try container.decodeIfPresent(
            MobilePaymentElementAssetsV1.self,
            forKey: .assets
        ) ?? MobilePaymentElementAssetsV1()
        self.formSpecs = try container.decodeIfPresent(
            [PaymentMethodFormSpecV1].self,
            forKey: .formSpecs
        ) ?? []
        self._allResponseFieldsStorage = nil
        self._additionalParametersStorage = nil
    }

    public static func == (lhs: MobilePaymentElementV1, rhs: MobilePaymentElementV1) -> Bool {
        return lhs.contract == rhs.contract && lhs.paymentMethodAvailability == rhs.paymentMethodAvailability && lhs.features == rhs.features && lhs.assets == rhs.assets && lhs.formSpecs == rhs.formSpecs
    }
}

/// Contract family and exact server schema revision used for this response.
@_spi(STP) public struct ContractMetadataV1: Codable, Equatable {
    @_spi(STP) public var major: Int
    @_spi(STP) public var revision: String

    private enum CodingKeys: String, CodingKey {
        case major = "major"
        case revision = "revision"
    }

    @_spi(STP) public init(
        major: Int,
        revision: String
    ) {
        self.major = major
        self.revision = revision
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.major = try container.decode(
            Int.self,
            forKey: .major
        )
        self.revision = try container.decode(
            String.self,
            forKey: .revision
        )
    }

    public static func == (lhs: ContractMetadataV1, rhs: ContractMetadataV1) -> Bool {
        return lhs.major == rhs.major && lhs.revision == rhs.revision
    }
}

/// Availability envelope with an explicit decision for every payment method.
@_spi(STP) public struct PaymentMethodAvailabilityV1: Codable, Equatable {
    @_spi(STP) public var entries: [PaymentMethodAvailabilityEntryV1]

    private enum CodingKeys: String, CodingKey {
        case entries = "entries"
    }

    @_spi(STP) public init(entries: [PaymentMethodAvailabilityEntryV1] = []) {
        self.entries = entries
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.entries = try container.decodeIfPresent(
            [PaymentMethodAvailabilityEntryV1].self,
            forKey: .entries
        ) ?? []
    }

    public static func == (lhs: PaymentMethodAvailabilityV1, rhs: PaymentMethodAvailabilityV1) -> Bool {
        return lhs.entries == rhs.entries
    }
}

/// One server-owned payment-method availability decision.
@_spi(STP) public struct PaymentMethodAvailabilityEntryV1: Codable, Equatable {
    @_spi(STP) public var paymentMethodType: String
    @_spi(STP) public var available: Bool
    @_spi(STP) public var reason: String?

    private enum CodingKeys: String, CodingKey {
        case paymentMethodType = "payment_method_type"
        case available = "available"
        case reason = "reason"
    }

    @_spi(STP) public init(
        paymentMethodType: String,
        available: Bool,
        reason: String? = nil
    ) {
        self.paymentMethodType = paymentMethodType
        self.available = available
        self.reason = reason
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.paymentMethodType = try container.decode(
            String.self,
            forKey: .paymentMethodType
        )
        self.available = try container.decode(
            Bool.self,
            forKey: .available
        )
        self.reason = try container.decodeIfPresent(
            String.self,
            forKey: .reason
        )
    }

    public static func == (lhs: PaymentMethodAvailabilityEntryV1, rhs: PaymentMethodAvailabilityEntryV1) -> Bool {
        return lhs.paymentMethodType == rhs.paymentMethodType && lhs.available == rhs.available && lhs.reason == rhs.reason
    }
}

/// Server-owned feature decisions consumed directly by the mobile SDKs.
@_spi(STP) public struct MobilePaymentElementFeaturesV1: Codable, Equatable {
    @_spi(STP) public var financialConnectionsLite: String
    @_spi(STP) public var linkGlobalHoldbackLookup: Bool
    @_spi(STP) public var forceVerticalPaymentMethodLayout: Bool
    @_spi(STP) public var cardFundingFiltering: Bool

    private enum CodingKeys: String, CodingKey {
        case financialConnectionsLite = "financial_connections_lite"
        case linkGlobalHoldbackLookup = "link_global_holdback_lookup"
        case forceVerticalPaymentMethodLayout = "force_vertical_payment_method_layout"
        case cardFundingFiltering = "card_funding_filtering"
    }

    @_spi(STP) public init(
        financialConnectionsLite: String = "automatic",
        linkGlobalHoldbackLookup: Bool = true,
        forceVerticalPaymentMethodLayout: Bool = false,
        cardFundingFiltering: Bool = false
    ) {
        self.financialConnectionsLite = financialConnectionsLite
        self.linkGlobalHoldbackLookup = linkGlobalHoldbackLookup
        self.forceVerticalPaymentMethodLayout = forceVerticalPaymentMethodLayout
        self.cardFundingFiltering = cardFundingFiltering
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.financialConnectionsLite = try container.decodeIfPresent(
            String.self,
            forKey: .financialConnectionsLite
        ) ?? "automatic"
        self.linkGlobalHoldbackLookup = try container.decodeIfPresent(
            Bool.self,
            forKey: .linkGlobalHoldbackLookup
        ) ?? true
        self.forceVerticalPaymentMethodLayout = try container.decodeIfPresent(
            Bool.self,
            forKey: .forceVerticalPaymentMethodLayout
        ) ?? false
        self.cardFundingFiltering = try container.decodeIfPresent(
            Bool.self,
            forKey: .cardFundingFiltering
        ) ?? false
    }

    public static func == (lhs: MobilePaymentElementFeaturesV1, rhs: MobilePaymentElementFeaturesV1) -> Bool {
        return lhs.financialConnectionsLite == rhs.financialConnectionsLite && lhs.linkGlobalHoldbackLookup == rhs.linkGlobalHoldbackLookup && lhs.forceVerticalPaymentMethodLayout == rhs.forceVerticalPaymentMethodLayout && lhs.cardFundingFiltering == rhs.cardFundingFiltering
    }
}

/// Localized display data and approved selector icons for available payment methods.
@_spi(STP) public struct MobilePaymentElementAssetsV1: Codable, Equatable {
    @_spi(STP) public var paymentMethods: [PaymentMethodAssetV1]

    private enum CodingKeys: String, CodingKey {
        case paymentMethods = "payment_methods"
    }

    @_spi(STP) public init(paymentMethods: [PaymentMethodAssetV1] = []) {
        self.paymentMethods = paymentMethods
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.paymentMethods = try container.decodeIfPresent(
            [PaymentMethodAssetV1].self,
            forKey: .paymentMethods
        ) ?? []
    }

    public static func == (lhs: MobilePaymentElementAssetsV1, rhs: MobilePaymentElementAssetsV1) -> Bool {
        return lhs.paymentMethods == rhs.paymentMethods
    }
}

/// Localized display data for one payment method.
@_spi(STP) public struct PaymentMethodAssetV1: Codable, Equatable {
    @_spi(STP) public var paymentMethodType: String
    @_spi(STP) public var locale: String
    @_spi(STP) public var displayName: String
    @_spi(STP) public var selectorIcon: SelectorIconV1?

    private enum CodingKeys: String, CodingKey {
        case paymentMethodType = "payment_method_type"
        case locale = "locale"
        case displayName = "display_name"
        case selectorIcon = "selector_icon"
    }

    @_spi(STP) public init(
        paymentMethodType: String,
        locale: String = "en",
        displayName: String,
        selectorIcon: SelectorIconV1? = nil
    ) {
        self.paymentMethodType = paymentMethodType
        self.locale = locale
        self.displayName = displayName
        self.selectorIcon = selectorIcon
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.paymentMethodType = try container.decode(
            String.self,
            forKey: .paymentMethodType
        )
        self.locale = try container.decodeIfPresent(
            String.self,
            forKey: .locale
        ) ?? "en"
        self.displayName = try container.decode(
            String.self,
            forKey: .displayName
        )
        self.selectorIcon = try container.decodeIfPresent(
            SelectorIconV1.self,
            forKey: .selectorIcon
        )
    }

    public static func == (lhs: PaymentMethodAssetV1, rhs: PaymentMethodAssetV1) -> Bool {
        return lhs.paymentMethodType == rhs.paymentMethodType && lhs.locale == rhs.locale && lhs.displayName == rhs.displayName && lhs.selectorIcon == rhs.selectorIcon
    }
}

/// HTTPS selector icon URLs hosted on an approved Stripe-controlled origin.
@_spi(STP) public struct SelectorIconV1: Codable, Equatable {
    @_spi(STP) public var lightThemePng: String
    @_spi(STP) public var darkThemePng: String?

    private enum CodingKeys: String, CodingKey {
        case lightThemePng = "light_theme_png"
        case darkThemePng = "dark_theme_png"
    }

    @_spi(STP) public init(
        lightThemePng: String,
        darkThemePng: String? = nil
    ) {
        self.lightThemePng = lightThemePng
        self.darkThemePng = darkThemePng
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.lightThemePng = try container.decode(
            String.self,
            forKey: .lightThemePng
        )
        self.darkThemePng = try container.decodeIfPresent(
            String.self,
            forKey: .darkThemePng
        )
    }

    public static func == (lhs: SelectorIconV1, rhs: SelectorIconV1) -> Bool {
        return lhs.lightThemePng == rhs.lightThemePng && lhs.darkThemePng == rhs.darkThemePng
    }
}

/// Declarative native form definition for one available payment method.
@_spi(STP) public struct PaymentMethodFormSpecV1: Codable, Equatable {
    @_spi(STP) public var type: String
    @_spi(STP) public var paymentMethodCode: String?
    @_spi(STP) public var fields: [FormElementSpecV1]
    @_spi(STP) public var requiresFormScreen: Bool
    @_spi(STP) public var selectorIcon: SelectorIconV1?

    private enum CodingKeys: String, CodingKey {
        case type = "type"
        case paymentMethodCode = "payment_method_code"
        case fields = "fields"
        case requiresFormScreen = "requires_form_screen"
        case selectorIcon = "selector_icon"
    }

    @_spi(STP) public init(
        type: String,
        paymentMethodCode: String? = nil,
        fields: [FormElementSpecV1] = [],
        requiresFormScreen: Bool = false,
        selectorIcon: SelectorIconV1? = nil
    ) {
        self.type = type
        self.paymentMethodCode = paymentMethodCode
        self.fields = fields
        self.requiresFormScreen = requiresFormScreen
        self.selectorIcon = selectorIcon
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.type = try container.decode(
            String.self,
            forKey: .type
        )
        self.paymentMethodCode = try container.decodeIfPresent(
            String.self,
            forKey: .paymentMethodCode
        )
        self.fields = try container.decodeIfPresent(
            [FormElementSpecV1].self,
            forKey: .fields
        ) ?? []
        self.requiresFormScreen = try container.decodeIfPresent(
            Bool.self,
            forKey: .requiresFormScreen
        ) ?? false
        self.selectorIcon = try container.decodeIfPresent(
            SelectorIconV1.self,
            forKey: .selectorIcon
        )
    }

    public static func == (lhs: PaymentMethodFormSpecV1, rhs: PaymentMethodFormSpecV1) -> Bool {
        return lhs.type == rhs.type && lhs.paymentMethodCode == rhs.paymentMethodCode && lhs.fields == rhs.fields && lhs.requiresFormScreen == rhs.requiresFormScreen && lhs.selectorIcon == rhs.selectorIcon
    }
}

/// One closed dropdown option in a declarative form element.
@_spi(STP) public struct FormElementOptionV1: Codable, Equatable {
    @_spi(STP) public var displayText: String
    @_spi(STP) public var apiValue: String?

    private enum CodingKeys: String, CodingKey {
        case displayText = "display_text"
        case apiValue = "api_value"
    }

    @_spi(STP) public init(
        displayText: String,
        apiValue: String? = nil
    ) {
        self.displayText = displayText
        self.apiValue = apiValue
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.displayText = try container.decode(
            String.self,
            forKey: .displayText
        )
        self.apiValue = try container.decodeIfPresent(
            String.self,
            forKey: .apiValue
        )
    }

    public static func == (lhs: FormElementOptionV1, rhs: FormElementOptionV1) -> Bool {
        return lhs.displayText == rhs.displayText && lhs.apiValue == rhs.apiValue
    }
}

/// Closed declarative form element interpreted by native SDK rendering code.
@_spi(STP) public struct FormElementSpecV1: Codable, Equatable {
    @_spi(STP) public var type: String
    @_spi(STP) public var apiPath: String?
    @_spi(STP) public var translationId: String?
    @_spi(STP) public var items: [FormElementOptionV1]
    @_spi(STP) public var allowedCountryCodes: [String]?
    @_spi(STP) public var placeholderFor: String?
    @_spi(STP) public var component: String?
    @_spi(STP) public var subtitle: String?
    @_spi(STP) public var disableBillingDetailCollection: Bool?
    @_spi(STP) public var textKey: String?
    @_spi(STP) public var localizedTextTemplate: String?
    @_spi(STP) public var setupFutureUsageRequired: Bool?

    private enum CodingKeys: String, CodingKey {
        case type = "type"
        case apiPath = "api_path"
        case translationId = "translation_id"
        case items = "items"
        case allowedCountryCodes = "allowed_country_codes"
        case placeholderFor = "placeholder_for"
        case component = "component"
        case subtitle = "subtitle"
        case disableBillingDetailCollection = "disable_billing_detail_collection"
        case textKey = "text_key"
        case localizedTextTemplate = "localized_text_template"
        case setupFutureUsageRequired = "setup_future_usage_required"
    }

    @_spi(STP) public init(
        type: String,
        apiPath: String? = nil,
        translationId: String? = nil,
        items: [FormElementOptionV1] = [],
        allowedCountryCodes: [String]? = nil,
        placeholderFor: String? = nil,
        component: String? = nil,
        subtitle: String? = nil,
        disableBillingDetailCollection: Bool? = nil,
        textKey: String? = nil,
        localizedTextTemplate: String? = nil,
        setupFutureUsageRequired: Bool? = nil
    ) {
        self.type = type
        self.apiPath = apiPath
        self.translationId = translationId
        self.items = items
        self.allowedCountryCodes = allowedCountryCodes
        self.placeholderFor = placeholderFor
        self.component = component
        self.subtitle = subtitle
        self.disableBillingDetailCollection = disableBillingDetailCollection
        self.textKey = textKey
        self.localizedTextTemplate = localizedTextTemplate
        self.setupFutureUsageRequired = setupFutureUsageRequired
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.type = try container.decode(
            String.self,
            forKey: .type
        )
        self.apiPath = try container.decodeIfPresent(
            String.self,
            forKey: .apiPath
        )
        self.translationId = try container.decodeIfPresent(
            String.self,
            forKey: .translationId
        )
        self.items = try container.decodeIfPresent(
            [FormElementOptionV1].self,
            forKey: .items
        ) ?? []
        self.allowedCountryCodes = try container.decodeIfPresent(
            [String].self,
            forKey: .allowedCountryCodes
        )
        self.placeholderFor = try container.decodeIfPresent(
            String.self,
            forKey: .placeholderFor
        )
        self.component = try container.decodeIfPresent(
            String.self,
            forKey: .component
        )
        self.subtitle = try container.decodeIfPresent(
            String.self,
            forKey: .subtitle
        )
        self.disableBillingDetailCollection = try container.decodeIfPresent(
            Bool.self,
            forKey: .disableBillingDetailCollection
        )
        self.textKey = try container.decodeIfPresent(
            String.self,
            forKey: .textKey
        )
        self.localizedTextTemplate = try container.decodeIfPresent(
            String.self,
            forKey: .localizedTextTemplate
        )
        self.setupFutureUsageRequired = try container.decodeIfPresent(
            Bool.self,
            forKey: .setupFutureUsageRequired
        )
    }

    public static func == (lhs: FormElementSpecV1, rhs: FormElementSpecV1) -> Bool {
        return lhs.type == rhs.type && lhs.apiPath == rhs.apiPath && lhs.translationId == rhs.translationId && lhs.items == rhs.items && lhs.allowedCountryCodes == rhs.allowedCountryCodes && lhs.placeholderFor == rhs.placeholderFor && lhs.component == rhs.component && lhs.subtitle == rhs.subtitle && lhs.disableBillingDetailCollection == rhs.disableBillingDetailCollection && lhs.textKey == rhs.textKey && lhs.localizedTextTemplate == rhs.localizedTextTemplate && lhs.setupFutureUsageRequired == rhs.setupFutureUsageRequired
    }
}
