{"topicSections":[{"anchor":"Classes","title":"Classes","identifiers":["doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/CardImageVerificationSheet","doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/CardScanSheet","doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/STPAPIClient","doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/STPAppInfo","doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/STPError","doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/StripeAPI"],"generated":true},{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/SafeEnumCodable","doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/SafeEnumDecodable","doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/UnknownFieldsCodable","doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/UnknownFieldsDecodable","doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/UnknownFieldsEncodable"],"anchor":"Protocols","title":"Protocols"},{"generated":true,"title":"Structures","identifiers":["doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/FinancialConnectionsEvent","doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/NonEncodableParameters","doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/ScannedCard"],"anchor":"Structures"},{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/StripeCoreVersionNumber","doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/StripeCoreVersionString"],"title":"Variables","anchor":"Variables"},{"generated":true,"title":"Enumerations","identifiers":["doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/CancellationReason","doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/CardImageVerificationSheetResult","doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/CardScanSheetError","doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/CardScanSheetResult","doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/STPCardErrorCode","doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/STPErrorCode"],"anchor":"Enumerations"},{"title":"Extended Modules","identifiers":["doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/Foundation"],"anchor":"Extended-Modules","generated":true}],"hierarchy":{"paths":[[]]},"metadata":{"externalID":"StripeCardScan","roleHeading":"Framework","role":"collection","symbolKind":"module","modules":[{"name":"StripeCardScan"}],"title":"StripeCardScan"},"sections":[],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","anchor":"Overview","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"This library provides a user interface through which users can scan payment cards and extract information from them. It uses the Stripe Publishable Key to authenticate with Stripe services.","type":"text"}]},{"inlineContent":[{"text":"Note that this is a standalone SDK and, while compatible with, does not directly integrate with the ","type":"text"},{"type":"reference","identifier":"https:\/\/stripe.com\/docs\/api\/payment_intents","isActive":true},{"type":"text","text":" API nor with "},{"type":"reference","identifier":"https:\/\/stripe.com\/docs\/api\/errors#errors-payment_intent-next_action","isActive":true},{"text":".","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"This library can be used entirely outside of a Stripe integration and with other payment processing providers.","type":"text"}],"type":"paragraph"},{"type":"heading","text":"Requirements","level":2,"anchor":"Requirements"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"iOS 13.0 or higher","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Xcode 15 or higher"}],"type":"paragraph"}]}]},{"text":"Example","anchor":"Example","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"See the ","type":"text"},{"isActive":true,"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/master\/Example\/CardImageVerification%20Example","type":"reference"},{"text":" directory for an example application that you can try for yourself!","type":"text"}]},{"type":"heading","level":2,"anchor":"Installation","text":"Installation"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Cocoapod"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"pod install StripeCardScan"}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"SPM"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"In Xcode, select File > Add Packages… and enter https:\/\/github.com\/stripe\/stripe-ios-spm as the repository URL."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Select the latest version number from our releases page."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Add the "},{"type":"codeVoice","code":"StripeCardScan"},{"type":"text","text":" product to the target of your app."}],"type":"paragraph"}]}]}]}]},{"level":2,"anchor":"Integration","type":"heading","text":"Integration"},{"level":3,"type":"heading","text":"Credit Card OCR","anchor":"Credit-Card-OCR"},{"inlineContent":[{"text":"Add ","type":"text"},{"type":"codeVoice","code":"CardScanSheet"},{"text":" in your view controller where you want to invoke the credit card scanning flow.","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"Set up camera permissions","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The SDK uses the camera, so you’ll need to add an description of camera usage to your Info.plist file:"},{"type":"text","text":" "},{"type":"image","identifier":"https:\/\/gblobscdn.gitbook.com\/assets\/-MAfqrnL3d-uke0sAFsI\/sync\/573e3f05043e4d903189b5fb107d4b3565bdb11b.png?alt=media"},{"text":" ","type":"text"},{"type":"image","identifier":"https:\/\/gblobscdn.gitbook.com\/assets\/-MAfqrnL3d-uke0sAFsI\/sync\/0d7119d3cbe2f519e5e5c04b56fe43539e4435e1.png?alt=media"}]}]},{"content":[{"inlineContent":[{"text":"Alternatively, you can add this permission directly to your Info.plist file:","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"code":["<key>NSCameraUsageDescriptionkey>","<string>We need access to your camera to scan your cardstring>"],"syntax":null,"type":"codeListing"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Add ","type":"text"},{"code":"CardScanSheet","type":"codeVoice"},{"text":" in your app where you want to invoke the scan flow","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"Initialize "},{"type":"codeVoice","code":"CardScanSheet"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"When it’s time to invoke the scan flow, display the sheet with ","type":"text"},{"type":"codeVoice","code":"CardScanSheet.present()"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"When the verification flow is finished, the sheet will be dismissed and the completion block will be called with a ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/stripe.dev\/stripe-ios\/"}],"type":"paragraph"}]}]}]}],"type":"orderedList"},{"anchor":"Example-Implementation","text":"Example Implementation","level":3,"type":"heading"},{"code":["","import UIKit","import StripeCardScan","","class ViewController: UIViewController {","","    @IBAction func cardScanSheetButtonPressed() {","        let cardScanSheet = CardScanSheet()","","        cardScanSheet.present(from: self) { [weak self] result in","            switch result {","                case .completed(let scannedCard):","                \/*","                 * The user scanned a card. The result of the scan are detailed ","                 * in the `scannedCard` field of the result.","                 *\/","                print(\"scan success\")","            case .canceled:","                \/*","                * The scan was canceled by the user.","                *\/","                print(\"scan canceled\")","            case .failed(let error):","                 \/*","                 * The scan failed. The displayable error is","                 * included in the `localizedDescription`. ","                 *\/","                 print(\"scan failed: \\(error.localizedDescription)\")","            }","        }","    }","}"],"syntax":"swift","type":"codeListing"},{"level":2,"anchor":"Credit-Card-Verification","type":"heading","text":"Credit Card Verification"},{"type":"paragraph","inlineContent":[{"text":"🚧","type":"text"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripecardscan"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripecardscan"]}],"abstract":[{"type":"text","text":"This library provides support for the standalone Stripe CardScan product."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/StripeCardScanVersionNumber":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/StripeCardScanVersionNumber","type":"topic","url":"\/documentation\/stripecardscan\/stripecardscanversionnumber","title":"StripeCardScanVersionNumber","fragments":[{"text":"StripeCardScanVersionNumber","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Project version number for StripeCardScan."}]},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/FinancialConnectionsEvent":{"identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/FinancialConnectionsEvent","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FinancialConnectionsEvent"}],"kind":"symbol","navigatorTitle":[{"text":"FinancialConnectionsEvent","kind":"identifier"}],"type":"topic","title":"FinancialConnectionsEvent","url":"\/documentation\/stripecardscan\/financialconnectionsevent","role":"symbol","abstract":[]},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/STPError":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPError","kind":"identifier"}],"title":"STPError","kind":"symbol","navigatorTitle":[{"text":"STPError","kind":"identifier"}],"abstract":[{"type":"text","text":"Top-level class for Stripe error constants."}],"url":"\/documentation\/stripecardscan\/stperror","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/STPError"},"https://gblobscdn.gitbook.com/assets/-MAfqrnL3d-uke0sAFsI/sync/573e3f05043e4d903189b5fb107d4b3565bdb11b.png?alt=media":{"type":"image","alt":"info.plist camera permissions","variants":[{"traits":["1x","light"],"url":"https:\/\/gblobscdn.gitbook.com\/assets\/-MAfqrnL3d-uke0sAFsI\/sync\/573e3f05043e4d903189b5fb107d4b3565bdb11b.png?alt=media"}],"identifier":"https:\/\/gblobscdn.gitbook.com\/assets\/-MAfqrnL3d-uke0sAFsI\/sync\/573e3f05043e4d903189b5fb107d4b3565bdb11b.png?alt=media"},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/ScannedCard":{"type":"topic","title":"ScannedCard","kind":"symbol","abstract":[{"text":"An struct that contains the PAN of the scanned card during","type":"text"},{"type":"text","text":" "},{"text":"the card image verification flow","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/ScannedCard","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"ScannedCard","kind":"identifier"}],"navigatorTitle":[{"text":"ScannedCard","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripecardscan\/scannedcard"},"https://stripe.com/docs/api/payment_intents":{"type":"link","url":"https:\/\/stripe.com\/docs\/api\/payment_intents","titleInlineContent":[{"type":"text","text":"PaymentIntent"}],"identifier":"https:\/\/stripe.com\/docs\/api\/payment_intents","title":"PaymentIntent"},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/STPAPIClient":{"title":"STPAPIClient","type":"topic","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPAPIClient","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/STPAPIClient","url":"\/documentation\/stripecardscan\/stpapiclient","abstract":[{"text":"A client for making connections to the Stripe API.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/CardScanSheet":{"abstract":[{"type":"text","text":"A drop-in class that presents a sheet for a customer to scan their card"}],"url":"\/documentation\/stripecardscan\/cardscansheet","navigatorTitle":[{"text":"CardScanSheet","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CardScanSheet","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/CardScanSheet","role":"symbol","type":"topic","title":"CardScanSheet","kind":"symbol"},"https://gblobscdn.gitbook.com/assets/-MAfqrnL3d-uke0sAFsI/sync/0d7119d3cbe2f519e5e5c04b56fe43539e4435e1.png?alt=media":{"type":"image","alt":"camera permissions prompt","variants":[{"traits":["1x","light"],"url":"https:\/\/gblobscdn.gitbook.com\/assets\/-MAfqrnL3d-uke0sAFsI\/sync\/0d7119d3cbe2f519e5e5c04b56fe43539e4435e1.png?alt=media"}],"identifier":"https:\/\/gblobscdn.gitbook.com\/assets\/-MAfqrnL3d-uke0sAFsI\/sync\/0d7119d3cbe2f519e5e5c04b56fe43539e4435e1.png?alt=media"},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/NonEncodableParameters":{"type":"topic","role":"symbol","url":"\/documentation\/stripecardscan\/nonencodableparameters","identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/NonEncodableParameters","navigatorTitle":[{"kind":"identifier","text":"NonEncodableParameters"}],"abstract":[{"type":"text","text":"This should not be used directly."},{"text":" ","type":"text"},{"type":"text","text":"Use the "},{"code":"additionalParameters","type":"codeVoice"},{"type":"text","text":" and "},{"code":"allResponseFields","type":"codeVoice"},{"type":"text","text":" accessors instead."},{"type":"text","text":" "},{"type":"text","text":":nodoc:"}],"kind":"symbol","title":"NonEncodableParameters","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NonEncodableParameters"}]},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/StripeCoreVersionString":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/StripeCoreVersionString","type":"topic","url":"\/documentation\/stripecardscan\/stripecoreversionstring","abstract":[],"title":"StripeCoreVersionString","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StripeCoreVersionString"},{"kind":"text","text":": <<error type>>"}]},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/CardScanSheetError":{"type":"topic","abstract":[{"text":"Errors specific to the ","type":"text"},{"code":"CardImageVerificationSheet","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CardScanSheetError"}],"navigatorTitle":[{"kind":"identifier","text":"CardScanSheetError"}],"title":"CardScanSheetError","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/CardScanSheetError","url":"\/documentation\/stripecardscan\/cardscansheeterror"},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/UnknownFieldsDecodable":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/UnknownFieldsDecodable","url":"\/documentation\/stripecardscan\/unknownfieldsdecodable","navigatorTitle":[{"kind":"identifier","text":"UnknownFieldsDecodable"}],"title":"UnknownFieldsDecodable","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A Decodable object that retains unknown fields."},{"text":" ","type":"text"},{"text":":nodoc:","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UnknownFieldsDecodable"}]},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/StripeAPI":{"url":"\/documentation\/stripecardscan\/stripeapi","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"StripeAPI","kind":"identifier"}],"navigatorTitle":[{"text":"StripeAPI","kind":"identifier"}],"role":"symbol","title":"StripeAPI","abstract":[{"text":"A top-level class that imports the rest of the Stripe SDK.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/StripeAPI","type":"topic"},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/SafeEnumDecodable":{"role":"symbol","abstract":[{"type":"text","text":"A Decodable enum that sets an “unparsable” case"},{"type":"text","text":" "},{"type":"text","text":"instead of failing on values that are unknown to the SDK."},{"type":"text","text":" "},{"type":"text","text":":nodoc:"}],"url":"\/documentation\/stripecardscan\/safeenumdecodable","identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/SafeEnumDecodable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SafeEnumDecodable"}],"type":"topic","navigatorTitle":[{"text":"SafeEnumDecodable","kind":"identifier"}],"kind":"symbol","title":"SafeEnumDecodable"},"https://stripe.dev/stripe-ios/":{"type":"link","url":"https:\/\/stripe.dev\/stripe-ios\/","titleInlineContent":[{"type":"text","text":"Result"}],"identifier":"https:\/\/stripe.dev\/stripe-ios\/","title":"Result"},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/Foundation":{"url":"\/documentation\/stripecardscan\/foundation","identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/Foundation","abstract":[],"type":"topic","kind":"symbol","title":"Foundation","role":"collection"},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/STPCardErrorCode":{"url":"\/documentation\/stripecardscan\/stpcarderrorcode","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/STPCardErrorCode","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardErrorCode"}],"abstract":[{"type":"text","text":"Possible string values you may receive when there was an error tokenizing a card."}],"title":"STPCardErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardErrorCode","kind":"identifier"}],"type":"topic"},"https://stripe.com/docs/api/errors#errors-payment_intent-next_action":{"type":"link","url":"https:\/\/stripe.com\/docs\/api\/errors#errors-payment_intent-next_action","titleInlineContent":[{"type":"text","text":"next_action"}],"identifier":"https:\/\/stripe.com\/docs\/api\/errors#errors-payment_intent-next_action","title":"next_action"},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/CancellationReason":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/CancellationReason","url":"\/documentation\/stripecardscan\/cancellationreason","navigatorTitle":[{"kind":"identifier","text":"CancellationReason"}],"title":"CancellationReason","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CancellationReason"}],"abstract":[{"type":"text","text":"The reason of the user initiated scan cancellation"}],"kind":"symbol"},"https://github.com/stripe/stripe-ios/tree/master/Example/CardImageVerification%20Example":{"type":"link","url":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/master\/Example\/CardImageVerification%20Example","titleInlineContent":[{"type":"text","text":"CardImageVerification Example"}],"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/master\/Example\/CardImageVerification%20Example","title":"CardImageVerification Example"},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/CardImageVerificationSheetResult":{"identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/CardImageVerificationSheetResult","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CardImageVerificationSheetResult","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/stripecardscan\/cardimageverificationsheetresult","navigatorTitle":[{"kind":"identifier","text":"CardImageVerificationSheetResult"}],"abstract":[{"type":"text","text":"The result of an attempt to finish an card image verification flow"}],"title":"CardImageVerificationSheetResult"},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/CardScanSheetResult":{"abstract":[{"type":"text","text":"The result of an attempt to scan a card"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/CardScanSheetResult","type":"topic","title":"CardScanSheetResult","navigatorTitle":[{"text":"CardScanSheetResult","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CardScanSheetResult","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripecardscan\/cardscansheetresult"},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan":{"identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan","abstract":[{"text":"This library provides support for the standalone Stripe CardScan product.","type":"text"}],"kind":"symbol","role":"collection","title":"StripeCardScan","url":"\/documentation\/stripecardscan","type":"topic"},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/CardImageVerificationSheet":{"kind":"symbol","title":"CardImageVerificationSheet","navigatorTitle":[{"kind":"identifier","text":"CardImageVerificationSheet"}],"type":"topic","role":"symbol","abstract":[{"text":"A drop-in class that presents a sheet for a user to verify their credit card","type":"text"}],"url":"\/documentation\/stripecardscan\/cardimageverificationsheet","identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/CardImageVerificationSheet","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CardImageVerificationSheet"}]},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/StripeCoreVersionNumber":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/StripeCoreVersionNumber","type":"topic","url":"\/documentation\/stripecardscan\/stripecoreversionnumber","abstract":[],"title":"StripeCoreVersionNumber","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"StripeCoreVersionNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/STPErrorCode":{"navigatorTitle":[{"text":"STPErrorCode","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPErrorCode","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Possible error code values for NSErrors with the "},{"code":"StripeDomain","type":"codeVoice"},{"type":"text","text":" domain."}],"url":"\/documentation\/stripecardscan\/stperrorcode","title":"STPErrorCode","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/STPErrorCode"},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/STPAppInfo":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPAppInfo","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripecardscan\/stpappinfo","abstract":[{"type":"text","text":"Libraries wrapping the Stripe SDK should use this object to provide information about the"},{"text":" ","type":"text"},{"text":"library, and set it in on ","type":"text"},{"type":"codeVoice","code":"STPAPIClient"},{"text":".","type":"text"}],"title":"STPAppInfo","type":"topic","identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/STPAppInfo","role":"symbol","navigatorTitle":[{"text":"STPAppInfo","kind":"identifier"}]},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/UnknownFieldsEncodable":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnknownFieldsEncodable","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UnknownFieldsEncodable"}],"identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/UnknownFieldsEncodable","url":"\/documentation\/stripecardscan\/unknownfieldsencodable","title":"UnknownFieldsEncodable","kind":"symbol","type":"topic","abstract":[{"text":"An Encodable object that allows unknown fields to be set.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":":nodoc:"}]},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/SafeEnumCodable":{"navigatorTitle":[{"text":"SafeEnumCodable","kind":"identifier"}],"url":"\/documentation\/stripecardscan\/safeenumcodable","title":"SafeEnumCodable","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/SafeEnumCodable","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SafeEnumCodable","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A Codable enum that sets an “unparsable” case"},{"type":"text","text":" "},{"type":"text","text":"instead of failing on values that are unknown to the SDK."},{"type":"text","text":" "},{"type":"text","text":":nodoc:"}]},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/UnknownFieldsCodable":{"navigatorTitle":[{"kind":"identifier","text":"UnknownFieldsCodable"}],"abstract":[{"type":"text","text":"A protocol that conforms to both UnknownFieldsEncodable and UnknownFieldsDecodable."},{"text":" ","type":"text"},{"text":":nodoc:","type":"text"}],"url":"\/documentation\/stripecardscan\/unknownfieldscodable","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"UnknownFieldsCodable","kind":"identifier"}],"type":"topic","title":"UnknownFieldsCodable","identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/UnknownFieldsCodable","kind":"symbol"},"doc://com.stripe.stripe-card-scan/documentation/StripeCardScan/StripeCardScanVersionString":{"title":"StripeCardScanVersionString","kind":"symbol","fragments":[{"kind":"identifier","text":"StripeCardScanVersionString"}],"identifier":"doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/StripeCardScanVersionString","type":"topic","abstract":[{"text":"Project version string for StripeCardScan.","type":"text"}],"role":"symbol","url":"\/documentation\/stripecardscan\/stripecardscanversionstring"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/StripeCardScanVersionNumber","doc:\/\/com.stripe.stripe-card-scan\/documentation\/StripeCardScan\/StripeCardScanVersionString"],"generated":true,"anchor":"Variables"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}