{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/affirm"},"metadata":{"symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"STPPaymentMethodTypeAffirm","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"affirm","kind":"identifier"}],"role":"symbol","externalID":"c:@M@StripePayments@E@STPPaymentMethodType@STPPaymentMethodTypeAffirm","title":"STPPaymentMethodType.affirm","modules":[{"name":"StripePayments"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"affirm","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"]]},"kind":"symbol","abstract":[{"text":"An Affirm payment method","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/affirm"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/affirm"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"abstract":[{"text":"The type of the PaymentMethod.","type":"text"}],"title":"STPPaymentMethodType","url":"\/documentation\/stripepayments\/stppaymentmethodtype","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodType","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/affirm":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"affirm","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/affirm","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/affirm","abstract":[{"text":"An Affirm payment method","type":"text"}],"type":"topic","navigatorTitle":[{"text":"STPPaymentMethodTypeAffirm","kind":"identifier"}],"title":"STPPaymentMethodType.affirm"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPPaymentMethodTypeAffirm","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPPaymentMethodTypeAffirm","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"STPPaymentMethodTypeAffirm","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentMethodType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle"},{"op":"replace","value":"STPPaymentMethodTypeAffirm","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1affirm\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodTypeAffirm"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1affirm\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}