{"metadata":{"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPPaymentMethodTypeAfterpayClearpay","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"afterpayClearpay","kind":"identifier"}],"symbolKind":"case","title":"STPPaymentMethodType.afterpayClearpay","roleHeading":"Case","role":"symbol","externalID":"c:@M@StripePayments@E@STPPaymentMethodType@STPPaymentMethodTypeAfterpayClearpay"},"abstract":[{"type":"text","text":"An AfterpayClearpay payment method"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/afterpayClearpay"},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/afterpayclearpay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/afterpayclearpay"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"afterpayClearpay","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"abstract":[{"type":"text","text":"The type of the PaymentMethod."}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodType"}],"role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodtype","title":"STPPaymentMethodType"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/afterpayClearpay":{"kind":"symbol","title":"STPPaymentMethodType.afterpayClearpay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/afterpayClearpay","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeAfterpayClearpay"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"afterpayClearpay"}],"type":"topic","abstract":[{"text":"An AfterpayClearpay payment method","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/afterpayclearpay"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"STPPaymentMethodTypeAfterpayClearpay"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPPaymentMethodTypeAfterpayClearpay","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPPaymentMethodTypeAfterpayClearpay","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title","op":"replace","value":"STPPaymentMethodType"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodType"}],"op":"replace"},{"value":[{"text":"STPPaymentMethodType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1afterpayClearpay\/title","value":"STPPaymentMethodTypeAfterpayClearpay","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeAfterpayClearpay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1afterpayClearpay\/fragments"}]}]}