{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeAmazonPay"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"amazonPay","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPPaymentMethodType@STPPaymentMethodTypeAmazonPay","roleHeading":"Case","title":"STPPaymentMethodType.amazonPay","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"]]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"An AmazonPay payment method"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"amazonPay","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/amazonPay","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/amazonpay"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/amazonpay"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"url":"\/documentation\/stripepayments\/stppaymentmethodtype","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The type of the PaymentMethod."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodType","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","title":"STPPaymentMethodType","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/amazonPay":{"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/amazonpay","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"amazonPay","kind":"identifier"}],"title":"STPPaymentMethodType.amazonPay","role":"symbol","abstract":[{"text":"An AmazonPay payment method","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeAmazonPay"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/amazonPay","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"STPPaymentMethodTypeAmazonPay","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeAmazonPay","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPPaymentMethodTypeAmazonPay"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPPaymentMethodType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodType"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1amazonPay\/title","value":"STPPaymentMethodTypeAmazonPay"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1amazonPay\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodTypeAmazonPay"}]}]}]}