{"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/aubecsdebit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/aubecsdebit"]}],"kind":"symbol","abstract":[{"text":"An AU BECS Debit payment method.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"STPPaymentMethodType.AUBECSDebit","externalID":"c:@M@StripePayments@E@STPPaymentMethodType@STPPaymentMethodTypeAUBECSDebit","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeAUBECSDebit"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AUBECSDebit"}],"modules":[{"name":"StripePayments"}],"symbolKind":"case","role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/AUBECSDebit"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(STPPaymentMethodTypeAUBECSDebit) "},{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"AUBECSDebit","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodType"}],"abstract":[{"text":"The type of the PaymentMethod.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","title":"STPPaymentMethodType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodType"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/AUBECSDebit":{"abstract":[{"text":"An AU BECS Debit payment method.","type":"text"}],"title":"STPPaymentMethodType.AUBECSDebit","navigatorTitle":[{"text":"STPPaymentMethodTypeAUBECSDebit","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/AUBECSDebit","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/aubecsdebit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"AUBECSDebit"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"STPPaymentMethodTypeAUBECSDebit","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodTypeAUBECSDebit"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"STPPaymentMethodTypeAUBECSDebit","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title","op":"replace","value":"STPPaymentMethodType"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle","value":[{"text":"STPPaymentMethodType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1AUBECSDebit\/title","op":"replace","value":"STPPaymentMethodTypeAUBECSDebit"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1AUBECSDebit\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodTypeAUBECSDebit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}