{"abstract":[{"type":"text","text":"A Bacs Debit payment method."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"]]},"metadata":{"externalID":"c:@M@StripePayments@E@STPPaymentMethodType@STPPaymentMethodTypeBacsDebit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bacsDebit"}],"symbolKind":"case","role":"symbol","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeBacsDebit"}],"title":"STPPaymentMethodType.bacsDebit","roleHeading":"Case"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bacsDebit","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/bacsDebit"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/bacsdebit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/bacsdebit"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/bacsDebit":{"title":"STPPaymentMethodType.bacsDebit","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/bacsdebit","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/bacsDebit","type":"topic","kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodTypeBacsDebit","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bacsDebit","kind":"identifier"}],"abstract":[{"text":"A Bacs Debit payment method.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodType","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodtype","abstract":[{"type":"text","text":"The type of the PaymentMethod."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodType","kind":"identifier"}],"kind":"symbol","title":"STPPaymentMethodType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentMethodTypeBacsDebit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentMethodTypeBacsDebit","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPPaymentMethodTypeBacsDebit"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1bacsDebit\/title","value":"STPPaymentMethodTypeBacsDebit"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1bacsDebit\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodTypeBacsDebit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title","value":"STPPaymentMethodType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodType"}]}]}]}