{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/bancontact"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/bancontact"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/bancontact","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"A Bancontact payment method."}],"metadata":{"roleHeading":"Case","modules":[{"name":"StripePayments"}],"title":"STPPaymentMethodType.bancontact","navigatorTitle":[{"text":"STPPaymentMethodTypeBancontact","kind":"identifier"}],"role":"symbol","symbolKind":"case","externalID":"c:@M@StripePayments@E@STPPaymentMethodType@STPPaymentMethodTypeBancontact","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"bancontact","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bancontact","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/bancontact":{"abstract":[{"text":"A Bancontact payment method.","type":"text"}],"title":"STPPaymentMethodType.bancontact","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/bancontact","navigatorTitle":[{"text":"STPPaymentMethodTypeBancontact","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/bancontact","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"bancontact","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodType"}],"kind":"symbol","abstract":[{"type":"text","text":"The type of the PaymentMethod."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodtype","title":"STPPaymentMethodType","navigatorTitle":[{"text":"STPPaymentMethodType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentMethodTypeBancontact"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypeBancontact"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPPaymentMethodTypeBancontact"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPPaymentMethodTypeBancontact","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1bancontact\/title"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypeBancontact"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1bancontact\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title","value":"STPPaymentMethodType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodType"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodType"}]}]}]}