{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/billie","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/billie"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/billie"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"billie"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"A Billie payment method","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"]]},"metadata":{"title":"STPPaymentMethodType.billie","symbolKind":"case","role":"symbol","externalID":"c:@M@StripePayments@E@STPPaymentMethodType@STPPaymentMethodTypeBillie","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"billie","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodTypeBillie","kind":"identifier"}],"modules":[{"name":"StripePayments"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","title":"STPPaymentMethodType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype","type":"topic","abstract":[{"text":"The type of the PaymentMethod.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodType"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/billie":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/billie","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/billie","title":"STPPaymentMethodType.billie","kind":"symbol","abstract":[{"text":"A Billie payment method","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"billie","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"STPPaymentMethodTypeBillie","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"STPPaymentMethodTypeBillie","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"STPPaymentMethodTypeBillie","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"STPPaymentMethodTypeBillie","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title","op":"replace","value":"STPPaymentMethodType"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments","value":[{"text":"STPPaymentMethodType","kind":"identifier"}],"op":"replace"},{"value":[{"text":"STPPaymentMethodType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1billie\/title","value":"STPPaymentMethodTypeBillie"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1billie\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodTypeBillie"}]}]}]}