{"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/cardPresent","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"]]},"abstract":[{"type":"text","text":"A card present payment method."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cardPresent"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/cardpresent"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/cardpresent"]}],"metadata":{"symbolKind":"case","modules":[{"name":"StripePayments"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cardPresent"}],"roleHeading":"Case","title":"STPPaymentMethodType.cardPresent","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeCardPresent"}],"externalID":"c:@M@StripePayments@E@STPPaymentMethodType@STPPaymentMethodTypeCardPresent"},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"url":"\/documentation\/stripepayments\/stppaymentmethodtype","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The type of the PaymentMethod."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodType","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","title":"STPPaymentMethodType","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/cardPresent":{"title":"STPPaymentMethodType.cardPresent","abstract":[{"type":"text","text":"A card present payment method."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cardPresent"}],"navigatorTitle":[{"text":"STPPaymentMethodTypeCardPresent","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/cardpresent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/cardPresent","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"STPPaymentMethodTypeCardPresent","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodTypeCardPresent"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPPaymentMethodTypeCardPresent","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title","op":"replace","value":"STPPaymentMethodType"},{"op":"replace","value":[{"text":"STPPaymentMethodType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle"},{"value":"STPPaymentMethodTypeCardPresent","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1cardPresent\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1cardPresent\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodTypeCardPresent"}]}]}]}