{"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/card"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/card"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"card"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@StripePayments@E@STPPaymentMethodType@STPPaymentMethodTypeCard","title":"STPPaymentMethodType.card","roleHeading":"Case","symbolKind":"case","role":"symbol","modules":[{"name":"StripePayments"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"card"}],"navigatorTitle":[{"text":"STPPaymentMethodTypeCard","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A card payment method."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/card","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"url":"\/documentation\/stripepayments\/stppaymentmethodtype","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The type of the PaymentMethod."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodType","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","title":"STPPaymentMethodType","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/card":{"title":"STPPaymentMethodType.card","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/card","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"card","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeCard"}],"abstract":[{"text":"A card payment method.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/card"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"STPPaymentMethodTypeCard"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodTypeCard"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"STPPaymentMethodTypeCard","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title","value":"STPPaymentMethodType"},{"value":[{"text":"STPPaymentMethodType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle","value":[{"text":"STPPaymentMethodType","kind":"identifier"}],"op":"replace"},{"value":"STPPaymentMethodTypeCard","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1card\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1card\/fragments","value":[{"text":"STPPaymentMethodTypeCard","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}