{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/crypto"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/crypto"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"]]},"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPPaymentMethodType@STPPaymentMethodTypeCrypto","title":"STPPaymentMethodType.crypto","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"crypto"}],"role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"STPPaymentMethodTypeCrypto","kind":"identifier"}],"roleHeading":"Case"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"crypto","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/crypto","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"A Crypto payment method"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodType","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","url":"\/documentation\/stripepayments\/stppaymentmethodtype","role":"symbol","title":"STPPaymentMethodType","type":"topic","abstract":[{"text":"The type of the PaymentMethod.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/crypto":{"title":"STPPaymentMethodType.crypto","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"crypto","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/crypto","navigatorTitle":[{"text":"STPPaymentMethodTypeCrypto","kind":"identifier"}],"abstract":[{"type":"text","text":"A Crypto payment method"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/crypto","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPPaymentMethodTypeCrypto","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodTypeCrypto"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPPaymentMethodTypeCrypto"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"STPPaymentMethodType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments","value":[{"text":"STPPaymentMethodType","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle"},{"value":"STPPaymentMethodTypeCrypto","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1crypto\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeCrypto","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1crypto\/fragments","op":"replace"}]}]}