{"abstract":[{"text":"An EPS payment method.","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/eps"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/eps"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(STPPaymentMethodTypeEPS) ","kind":"text"},{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EPS","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"externalID":"c:@M@StripePayments@E@STPPaymentMethodType@STPPaymentMethodTypeEPS","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EPS","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"text":"STPPaymentMethodTypeEPS","kind":"identifier"}],"title":"STPPaymentMethodType.EPS","role":"symbol","modules":[{"name":"StripePayments"}]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/EPS","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/EPS":{"abstract":[{"text":"An EPS payment method.","type":"text"}],"role":"symbol","kind":"symbol","title":"STPPaymentMethodType.EPS","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeEPS"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"EPS"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/eps","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/EPS"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","kind":"symbol","title":"StripePayments","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"navigatorTitle":[{"text":"STPPaymentMethodType","kind":"identifier"}],"title":"STPPaymentMethodType","abstract":[{"text":"The type of the PaymentMethod.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentMethodTypeEPS"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentMethodTypeEPS","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"STPPaymentMethodTypeEPS","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1EPS\/title","value":"STPPaymentMethodTypeEPS"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1EPS\/fragments","value":[{"text":"STPPaymentMethodTypeEPS","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title","value":"STPPaymentMethodType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments","value":[{"text":"STPPaymentMethodType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle","value":[{"text":"STPPaymentMethodType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}