{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/instantdebits"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/instantdebits"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeInstantDebits"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPPaymentMethodType@STPPaymentMethodTypeInstantDebits","title":"STPPaymentMethodType.instantDebits","symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"instantDebits"}]},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/instantDebits","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instantDebits","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"]]},"kind":"symbol","abstract":[{"text":"A Instant Debits payment method","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/instantDebits":{"navigatorTitle":[{"text":"STPPaymentMethodTypeInstantDebits","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/instantDebits","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/instantdebits","kind":"symbol","title":"STPPaymentMethodType.instantDebits","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"instantDebits","kind":"identifier"}],"abstract":[{"text":"A Instant Debits payment method","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodType"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","abstract":[{"type":"text","text":"The type of the PaymentMethod."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodType"}],"title":"STPPaymentMethodType","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"STPPaymentMethodTypeInstantDebits"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodTypeInstantDebits"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"STPPaymentMethodTypeInstantDebits","kind":"identifier"}],"languages":["occ"]}]}},{"value":"STPPaymentMethodTypeInstantDebits","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1instantDebits\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1instantDebits\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodTypeInstantDebits"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title","value":"STPPaymentMethodType"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments","value":[{"text":"STPPaymentMethodType","kind":"identifier"}],"op":"replace"}]}]}
