{"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/paypay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/paypay"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"payPay","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"A PayPay payment method"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/payPay"},"sections":[],"metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypePayPay"}],"title":"STPPaymentMethodType.payPay","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"payPay"}],"role":"symbol","externalID":"c:@M@StripePayments@E@STPPaymentMethodType@STPPaymentMethodTypePayPay","modules":[{"name":"StripePayments"}],"roleHeading":"Case"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/payPay":{"abstract":[{"text":"A PayPay payment method","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/payPay","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypePayPay"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"payPay"}],"title":"STPPaymentMethodType.payPay","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/paypay"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodType"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype","abstract":[{"type":"text","text":"The type of the PaymentMethod."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodType"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","role":"symbol","title":"STPPaymentMethodType"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"STPPaymentMethodTypePayPay","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPPaymentMethodTypePayPay","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPPaymentMethodTypePayPay"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1payPay\/title","value":"STPPaymentMethodTypePayPay","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1payPay\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodTypePayPay"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title","value":"STPPaymentMethodType","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}