{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/paypal"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/paypal"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"payPal","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/payPal","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A PayPal payment method. :nodoc:"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"payPal","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodTypePayPal","kind":"identifier"}],"role":"symbol","modules":[{"name":"StripePayments"}],"roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPPaymentMethodType@STPPaymentMethodTypePayPal","symbolKind":"case","title":"STPPaymentMethodType.payPal"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/payPal":{"title":"STPPaymentMethodType.payPal","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"payPal","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodTypePayPal","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"A PayPal payment method. :nodoc:","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/payPal","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/paypal"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","kind":"symbol","abstract":[{"type":"text","text":"The type of the PaymentMethod."}],"role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodtype","title":"STPPaymentMethodType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodType"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodType"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"STPPaymentMethodTypePayPal"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodTypePayPal"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"STPPaymentMethodTypePayPal","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1payPal\/title","value":"STPPaymentMethodTypePayPal","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1payPal\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodTypePayPal"}],"op":"replace"},{"op":"replace","value":"STPPaymentMethodType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments","op":"replace","value":[{"text":"STPPaymentMethodType","kind":"identifier"}]},{"value":[{"text":"STPPaymentMethodType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}