{"sections":[],"abstract":[{"text":"A RevolutPay payment method","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"revolutPay","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/revolutpay"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/revolutpay"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/revolutPay"},"kind":"symbol","metadata":{"title":"STPPaymentMethodType.revolutPay","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeRevolutPay"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"revolutPay"}],"role":"symbol","externalID":"c:@M@StripePayments@E@STPPaymentMethodType@STPPaymentMethodTypeRevolutPay","symbolKind":"case"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/revolutPay":{"title":"STPPaymentMethodType.revolutPay","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/revolutPay","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeRevolutPay"}],"abstract":[{"type":"text","text":"A RevolutPay payment method"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"revolutPay","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/revolutpay"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"url":"\/documentation\/stripepayments\/stppaymentmethodtype","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodType","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPPaymentMethodType","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The type of the PaymentMethod."}],"title":"STPPaymentMethodType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"STPPaymentMethodTypeRevolutPay","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodTypeRevolutPay"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"STPPaymentMethodTypeRevolutPay","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1revolutPay\/title","value":"STPPaymentMethodTypeRevolutPay"},{"op":"replace","value":[{"text":"STPPaymentMethodTypeRevolutPay","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1revolutPay\/fragments"},{"value":"STPPaymentMethodType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodType"}],"op":"replace"},{"value":[{"text":"STPPaymentMethodType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle"}]}]}