{"abstract":[{"type":"text","text":"A UPI payment method."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UPI","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/upi"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/upi"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/UPI"},"metadata":{"symbolKind":"case","roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UPI"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPPaymentMethodType@STPPaymentMethodTypeUPI","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeUPI"}],"title":"STPPaymentMethodType.UPI"},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodType"}],"type":"topic","abstract":[{"text":"The type of the PaymentMethod.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype","title":"STPPaymentMethodType","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodType"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/UPI":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UPI","kind":"identifier"}],"abstract":[{"type":"text","text":"A UPI payment method."}],"navigatorTitle":[{"text":"STPPaymentMethodTypeUPI","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/UPI","title":"STPPaymentMethodType.UPI","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/upi","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentMethodTypeUPI"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentMethodTypeUPI","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"STPPaymentMethodTypeUPI"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentMethodType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1UPI\/title","value":"STPPaymentMethodTypeUPI"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1UPI\/fragments","value":[{"text":"STPPaymentMethodTypeUPI","kind":"identifier"}]}]}]}