{"metadata":{"role":"symbol","symbolKind":"case","externalID":"c:@M@StripePayments@E@STPPaymentMethodType@STPPaymentMethodTypeUSBankAccount","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"USBankAccount","kind":"identifier"}],"title":"STPPaymentMethodType.USBankAccount","navigatorTitle":[{"text":"STPPaymentMethodTypeUSBankAccount","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"StripePayments"}]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/usbankaccount"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/usbankaccount"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/USBankAccount","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"text":"A US Bank Account payment method (ACH)","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"USBankAccount"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodType"}],"abstract":[{"type":"text","text":"The type of the PaymentMethod."}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodtype","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodType","kind":"identifier"}],"title":"STPPaymentMethodType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/USBankAccount":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A US Bank Account payment method (ACH)"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"USBankAccount"}],"title":"STPPaymentMethodType.USBankAccount","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeUSBankAccount"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/USBankAccount","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/usbankaccount"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"STPPaymentMethodTypeUSBankAccount","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentMethodTypeUSBankAccount","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPPaymentMethodTypeUSBankAccount"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"STPPaymentMethodType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodType"}]},{"value":"STPPaymentMethodTypeUSBankAccount","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1USBankAccount\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1USBankAccount\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodTypeUSBankAccount"}]}]}]}