{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wero"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodTypeWero","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"title":"STPPaymentMethodType.wero","externalID":"c:@M@StripePayments@E@STPPaymentMethodType@STPPaymentMethodTypeWero","roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wero"}]},"kind":"symbol","abstract":[{"type":"text","text":"A Wero payment method"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/wero"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodtype\/wero"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/wero"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"navigatorTitle":[{"text":"STPPaymentMethodType","kind":"identifier"}],"title":"STPPaymentMethodType","abstract":[{"text":"The type of the PaymentMethod.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodType","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","kind":"symbol","title":"StripePayments","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/wero":{"abstract":[{"type":"text","text":"A Wero payment method"}],"role":"symbol","kind":"symbol","title":"STPPaymentMethodType.wero","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeWero"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wero"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/wero","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/wero"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPPaymentMethodTypeWero","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodTypeWero"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPPaymentMethodTypeWero"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentMethodType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle"},{"op":"replace","value":"STPPaymentMethodTypeWero","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1wero\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodTypeWero"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1wero\/fragments"}]}]}