{"abstract":[{"type":"text","text":":nodoc:"}],"metadata":{"modules":[{"name":"StripePaymentsUI"}],"navigatorTitle":[{"kind":"identifier","text":"becomeFirstResponder"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"becomeFirstResponder"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@StripePaymentsUI@objc(cs)STPFormView(im)becomeFirstResponder","title":"becomeFirstResponder()"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpformview\/becomefirstresponder()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsui\/stpformview\/becomefirstresponder()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/becomeFirstResponder()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"becomeFirstResponder","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"type":"topic","abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"role":"collection","title":"StripePaymentsUI","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","kind":"symbol","url":"\/documentation\/stripepaymentsui"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormView":{"navigatorTitle":[{"text":"STPFormView","kind":"identifier"}],"type":"topic","title":"STPFormView","url":"\/documentation\/stripepaymentsui\/stpformview","abstract":[{"type":"codeVoice","code":"STPFormView"},{"type":"text","text":" is a base class for the Stripe SDK’s form input UI. You should use one of the available subclasses"},{"type":"text","text":" "},{"type":"text","text":"("},{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":") rather than instantiating an "},{"type":"codeVoice","code":"STPFormView"},{"type":"text","text":" instance directly."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFormView","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormView/becomeFirstResponder()":{"type":"topic","kind":"symbol","abstract":[{"text":":nodoc:","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/becomeFirstResponder()","url":"\/documentation\/stripepaymentsui\/stpformview\/becomefirstresponder()","role":"symbol","title":"becomeFirstResponder()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"becomeFirstResponder"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"becomeFirstResponder"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"becomeFirstResponder","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"becomeFirstResponder"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"becomeFirstResponder","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView\/title","value":"STPFormView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView\/fragments","value":[{"kind":"identifier","text":"STPFormView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView\/navigatorTitle","value":[{"text":"STPFormView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView~1becomeFirstResponder()\/title","value":"becomeFirstResponder"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView~1becomeFirstResponder()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"becomeFirstResponder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}