{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView"]]},"metadata":{"externalID":"c:@M@StripePaymentsUI@objc(cs)STPFormView(py)isFirstResponder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFirstResponder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"symbolKind":"property","navigatorTitle":[{"text":"isFirstResponder","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","title":"isFirstResponder","modules":[{"name":"StripePaymentsUI"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/isFirstResponder"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpformview\/isfirstresponder"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stpformview\/isfirstresponder"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFirstResponder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":":nodoc:","type":"text"}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","title":"StripePaymentsUI","url":"\/documentation\/stripepaymentsui","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormView/isFirstResponder":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFirstResponder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isFirstResponder"}],"abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/isFirstResponder","url":"\/documentation\/stripepaymentsui\/stpformview\/isfirstresponder","title":"isFirstResponder"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormView":{"title":"STPFormView","kind":"symbol","abstract":[{"code":"STPFormView","type":"codeVoice"},{"type":"text","text":" is a base class for the Stripe SDK’s form input UI. You should use one of the available subclasses"},{"type":"text","text":" "},{"type":"text","text":"("},{"code":"STPCardFormView","type":"codeVoice"},{"type":"text","text":") rather than instantiating an "},{"code":"STPFormView","type":"codeVoice"},{"type":"text","text":" instance directly."}],"navigatorTitle":[{"text":"STPFormView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView","url":"\/documentation\/stripepaymentsui\/stpformview","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFormView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"isFirstResponder","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"isFirstResponder","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isFirstResponder","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"isFirstResponder","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView~1isFirstResponder\/title","op":"replace"},{"value":[{"text":"isFirstResponder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView~1isFirstResponder\/fragments","op":"replace"},{"value":"STPFormView","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPFormView"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPFormView"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}