{"abstract":[{"type":"text","text":":nodoc:"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/isUserInteractionEnabled","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpformview\/isuserinteractionenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stpformview\/isuserinteractionenabled"]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"StripePaymentsUI"}],"title":"isUserInteractionEnabled","externalID":"c:@M@StripePaymentsUI@objc(cs)STPFormView(py)userInteractionEnabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isUserInteractionEnabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"text":"userInteractionEnabled","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isUserInteractionEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormView":{"type":"topic","navigatorTitle":[{"text":"STPFormView","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView","kind":"symbol","title":"STPFormView","url":"\/documentation\/stripepaymentsui\/stpformview","abstract":[{"code":"STPFormView","type":"codeVoice"},{"type":"text","text":" is a base class for the Stripe SDK’s form input UI. You should use one of the available subclasses"},{"type":"text","text":" "},{"text":"(","type":"text"},{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":") rather than instantiating an "},{"code":"STPFormView","type":"codeVoice"},{"type":"text","text":" instance directly."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPFormView"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"url":"\/documentation\/stripepaymentsui","kind":"symbol","role":"collection","title":"StripePaymentsUI","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormView/isUserInteractionEnabled":{"abstract":[{"type":"text","text":":nodoc:"}],"navigatorTitle":[{"kind":"identifier","text":"userInteractionEnabled"}],"url":"\/documentation\/stripepaymentsui\/stpformview\/isuserinteractionenabled","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/isUserInteractionEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isUserInteractionEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","title":"isUserInteractionEnabled","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"userInteractionEnabled","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"userInteractionEnabled"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"getter","kind":"keyword"},{"kind":"text","text":"="},{"text":"isUserInteractionEnabled","kind":"identifier"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userInteractionEnabled"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView\/title","value":"STPFormView","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView\/fragments","op":"replace","value":[{"text":"STPFormView","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"STPFormView"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView\/navigatorTitle"},{"op":"replace","value":"userInteractionEnabled","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView~1isUserInteractionEnabled\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView~1isUserInteractionEnabled\/fragments","value":[{"text":"userInteractionEnabled","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}